### ISSUE TITLE
[BUG] Retrieving Blob metadata with Blob SDK v12 returns NULL when using listBlobsByHierarchy

### ISSUE THREAD

**Issue by srideviaishwariya** [Azure/azure-sdk-for-java#10179]
**Describe the bug**
I can successfully add Metadata to a Blob using the Storage Blob SDK v12. I can see in Azure Portal and in the Storage Explorer that the metadata has been added to my blob, but when I retrieve the blob with the SDK, the metadata is NULL.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
Create a new Blob with the SDK
Add Metadata to the new Blob
Retrieve the Blob and try to read the metadata using listBlobsByHierarchy

***Code Snippet***
`ListBlobsOptions options = new ListBlobsOptions().setDetails(new BlobListDetails().setRetrieveMetadata(true)); for (BlobItem blobItem : containerClient.listBlobsByHierarchy(directory,options,null)) {
blobItem.getMetadata().get("foo");
}`

**Expected behavior**
Since I have confirmed that the Metadata has been successfully saved, I should be able to retrieve it with the latest Blob SDK (v12).

**Screenshots**

**Setup (please complete the following information):**
OS: Windows 10
IDE : IntelliJ IDEA
Azure Storage Blob SDK v12

**Additional context**
similar to bug https://github.com/Azure/azure-sdk-for-java/issues/6342

**Comment by rickle-msft** [comment]
As a part of this call, can you either print out and share the names of the BlobItems you are receiving or alternatively check whether the isPrefix property is set to true? You are correctly passing the listing details to retrieve metadata. What I suspect is happening therefore is you are getting back some blobs and some prefixes in your hierarchical listing results. Because prefixes are just a logical construct and not an actual blob, there's no metadata on them and therefore nothing to retrieve.

**Comment by srideviaishwariya** [comment]
Thanks, the check for the prefix helped. 

 ListBlobsOptions options = new ListBlobsOptions().setDetails(new BlobListDetails().setRetrieveMetadata(true));
            for (BlobItem blobItem : containerClient.listBlobsByHierarchy(directory,options,null)) {
                lastBlob = blobItem;
                System.out.printf("\nDirectory = %s, prefix = %b",blobItem.getName(),blobItem.isPrefix());
                if(blobItem.getMetadata()!= null){
                    System.out.printf("\nmetadata = %s", blobItem.getMetadata().get("foo"));
                }
            }
