### ISSUE TITLE
[Tests] Test resources json to support all clouds in Azure stack

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#10380]
Allow test-resources.json in FR to support multiple azure cloud parameters to support multiple cloud endpoint suffixes.

**Comment by danieljurek** [comment]
This is to include the possibility of testing in Azure instances that aren't Azure Public Cloud (e.g. sovereign clouds, Azure Stack deployments). Basically we want to avoid hardcoding things like storage endpoint suffixes (`.core.windows.net`), authority hosts, etc. anywhere in our test code because we'll have to go back and make that configurable to support testing in clouds that aren't the default Azure public cloud. 

It'd be nice if we could validate against a bounded set of endpoint suffixes, authority hosts, etc. but an Azure Stack deployment means that these values can be basically anything.

**Comment by samvaity** [comment]
@danieljurek  - we recently changed form recognizer test configurations to return the SAS Url itslef,. We do not have the hardcoded `core.windows.net` endpoint suffix anymore.
Could you confirm if this would no longer be an issue in [FormRecognizer](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/formrecognizer/test-resources.json).

**Comment by danieljurek** [comment]
I haven't had a chance to try this in a sovereign cloud yet. However it looks like this is no longer a problem as long as things like URLs, hostnames, and hostname suffixes aren't hardcoded into a .java file. 

From peering through the code and this [PR](https://github.com/Azure/azure-sdk-for-java/pull/10640/files#diff-29e70846f4657bb6deb50675c80e4598) it looks like this is no longer a concern.
