### ISSUE TITLE
[FEATURE REQ]

### ISSUE THREAD

**Issue by RGarrett88** [Azure/azure-sdk-for-java#10695]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
BlobClient.Upload should not require the input stream length.

**Describe alternatives you've considered**
Copying the input stream to memory and then getting the length and then uploading the input stream.

**Additional context**
An input stream doesn't know it's length because it hasn't been read. Requiring a length defeats the purpose of supporting an input stream.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by joshfree** [comment]
@rickle-msft @gapra-msft could you please follow up?

/cc @alzimmermsft

**Comment by rickle-msft** [comment]
Hi, @RGarrett88. Thank you for making this request. The current guidance on uploading data for which you do not know the length is to open a BlobOuptuStream and copy your InputStream to this OutputStream. Generally the reason we need to know the length for an upload is because we need to set the content length header on the request. BlobOutputStream is offered specifically for this scenario, but it should be noted that it is able to do this by doing some internal buffering.

**Comment by rickle-msft** [comment]
I am going to close this issue as we have given the most up to date guidance for our sdk with no follow up.

Please feel free to reach back out if you need more support.
