### ISSUE TITLE
Add ability to deserialize other Content-Types

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#11194]
Currently, if the Content-Type is not application/xml, it will assume the Content-Type is JSON. The Service Bus APIs return "application/atom+xml", which is being incorrectly deserialized as JSON.

SerializerEncoding: https://azuresdkdocs.blob.core.windows.net/$web/java/azure-core/1.3.0-beta.1/com/azure/core/util/serializer/SerializerEncoding.html#fromHeaders-com.azure.core.http.HttpHeaders-

It would be nice to add a way to associate other content types with serializers and treat the HTTP requests and responses according to which ones can be handled.

**Comment by alzimmermsft** [comment]
This problem should be resolvable by enhancing the `Content-Type` to `SerializerEncoding` mapping. Instead of checking static values we should be a little be more flexible by parsing the `Content-Type` header. `application/atom+xml` is using the suffix definition defined in [RFC 3023](https://tools.ietf.org/html/rfc3023), and this should work for other suffix types that we see in AppConfig and other services.

**Comment by alzimmermsft** [comment]
Should be resolved by #11255
