### ISSUE TITLE
Text Analytics code samples not rendered correctly on preview docs site 

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#11199]
Text Analytics code samples not rendered correctly on here - https://review.docs.microsoft.com/en-us/java/api/com.azure.ai.textanalytics.util?view=azure-java-preview&branch=smoke-test

**Comment by scbedd** [comment]
Ok I found the issue. There was an out of band release tracked [here](https://dev.azure.com/azure-sdk/release/_queries/edit/476/?triage=true).

I was not aware of this release. Next time we just need to make certain that I'm aware that this update needs to happen via update of the linked item + assignation to my user. 

The reason that we're not rendering correctly is because we needed to bump the target version of the preview package. This has [been completed.](https://github.com/Azure/azure-docs-sdk-java/commit/b06536c0a412e337bb866b5d57b329b84e757e64) The updates will merge with the next docs release.

**Comment by scbedd** [comment]
[Confirmed](https://review.docs.microsoft.com/en-us/java/api/com.azure.ai.textanalytics?view=azure-java-preview&branch=smoke-test)
![image](https://user-images.githubusercontent.com/45376673/83073169-d4f03400-a024-11ea-8151-60fb6826bc0f.png)

Merging to prod [today.](https://github.com/Azure/azure-docs-sdk-java/pull/1023)
