### ISSUE TITLE
[QUERY] Issue with new send(Iterable<EventData>) API added in EventHub SDK

### ISSUE THREAD

**Issue by shubhambhattar** [Azure/azure-sdk-for-java#11304]
**Query/Question**
A few days ago I reported this Issue ([#10682](https://github.com/Azure/azure-sdk-for-java/issues/10682)) where wrong maximumSizeInBytes was provided when the `EventDataBatch` was created and remained idle for > 30 mins before sending it.

As part of this fix, I believe a new API was added where users can send an `Iterable<EventData>` and the SDK will handle batching it given that the total size of messages in the `Iterable<EventData>` fits in an `EventDataBatch`. Please note here that as per the documentation, if this constraint isn't statisfied and exception will be thrown to the client: https://azuresdkdocs.blob.core.windows.net/$web/java/azure-messaging-eventhubs/5.1.0/index.html. I've two queries on this:

- I can't find a way to use my own `CreateBatchOptions` and also use `send(Iterable<EventData>)` API. I know I can use `SendOptions` but that only has a subset of tweakable parameters that are provided in `CreateBatchOptions` (where I can also set my own `maximumBatchSize`). Is this intentional to not allow `CreateBatchOptions` in the new API?
- Making sure that the total size of messages in `Iterable<EventData>` is less than `maximumSizeInBytes` for the `EventDataBatch` is non-trivial. Even in my testing, I found that there's always an overhead of `15KB` for every batch we create, and also an overhead for every message be add to the `EventDataBatch` (which changes with number of messages and I found it to be around > 16 bytes). Doing this calculation before sending the data to SDK might not be so clean given that I had to extract these numbers (of overhead size) in my own testing. Isn't a cleaner way would be to take the `Iterable<EventData>` and create as many `EventDataBatch` (in SDK) as it takes to push the complete `Iterable` to EventHub?

***Why is this not a Bug or a feature Request?***
This is related to the new API and I am not sure if the assumptions taken are intentional or not.

**Setup (please complete the following information if applicable):**
 - Version of the Library used: `5.1.0`
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by srnagar** [comment]
> I can't find a way to use my own CreateBatchOptions and also use send(Iterable<EventData>) API. I know I can use SendOptions but that only has a subset of tweakable parameters that are provided in CreateBatchOptions (where I can also set my own maximumBatchSize). Is this intentional to not allow CreateBatchOptions in the new API?

The new `send()` API that accepts an iterable is a convenience API for sending a small collection of events that are known to fit within the max link size limit. The API does not provide option to control the batch size to keep it simple. For finer control on batch size, applications can use `createBatch()` with `CreateBatchOptions`.

> Making sure that the total size of messages in Iterable<EventData> is less than maximumSizeInBytes for the EventDataBatch is non-trivial. Even in my testing, I found that there's always an overhead of 15KB for every batch we create, and also an overhead for every message be add to the EventDataBatch (which changes with number of messages and I found it to be around > 16 bytes). Doing this calculation before sending the data to SDK might not be so clean given that I had to extract these numbers (of overhead size) in my own testing. Isn't a cleaner way would be to take the Iterable<EventData> and create as many EventDataBatch (in SDK) as it takes to push the complete Iterable to EventHub?

For this new `send()` API, [several options](https://gist.github.com/srnagar/8616fede4d53677201e0ba50512a70f9)  were considered before [settling on this API](https://github.com/Azure/azure-sdk/issues/1259). This API is intended to be used by applications that have a set of events that are known to be well within the max link size. For applications that require accurate batch size, `createBatch()` with `CreateBatchOptions` should be used to first create the batch and then call `send(EventDataBatch)`. 

Please let me know if you need additional details.

PS: This API was added as a new feature and is not part of the fix for  https://github.com/Azure/azure-sdk-for-java/issues/10682. The fix for this issue can be found in [this PR](https://github.com/Azure/azure-sdk-for-java/pull/10825).

**Comment by shubhambhattar** [comment]
Thanks for the info @srnagar . I didn't know that `send(List<EventData>)` is only supposed to be used in cases where users know it'll definitely fit in the batch size.
