### ISSUE TITLE
Cannot set tag on StorageAccounts

### ISSUE THREAD

**Issue by jkubrynski** [Azure/azure-sdk-for-java#1148]
`Azure.storageAccounts()` doesn't include `DefinitionWithTags` interface anywhere

**Comment by martinsawicki** [comment]
tags in Azure are set on individual objects, not collections.
If you have an existing storage account to set a tag on, one way to do that could be:
```java
Azure.storageAccounts().getByGroup("myResourceGroup", "myStorageAccouunt").update()
    .withTag("tagname", "tagvalue")
    .apply()
```
If you want to do that as part of creating the storage account, then tag setting is possible within the "creatable" stage of the fluent definition flow, since tags are optional:

```java
azure.storageAccounts().define("mystorageaccount")
    .withRegion(Region.US_WEST) // Required
    .withNewResourceGroup()
    .withTag("mytag", "myvalue")   // Optional
    .create();
```

**Comment by jkubrynski** [comment]
I can invoke `withTag` method during the update but there is not tag support on `define` level - `StorageAccount.WithCreate` inteface doesn't include it. I'm using 1.0.0-beta2

**Comment by martinsawicki** [comment]
hmm, odd, you're right, we must have missed it in beta2 and added for beta3 (i'm looking at the current master branch - which is what beta3 will be).
Beta3 is around the corner - maybe 2 more days. So Master is stable - it's basically your beta3 right now.

**Comment by jkubrynski** [comment]
Great - I'll use jitpack then :)

**Comment by martinsawicki** [comment]
closing, since this is fixed in beta3
