### ISSUE TITLE
CircuitBreaker in EventHub sdk consumer ?

### ISSUE THREAD

**Issue by kumarrajnumber** [Azure/azure-sdk-for-java#11555]
**Query/Question**
I would like to implement CircuitBreaker pattern in EventHub consumer. Does the current SKD supports this functionality implicitly ? For example, consumer consumes messages and sends data to external API, if the external API server is down, consumer has to stop consuming messages. Is there any Listener or Flag mechanism which indirectly informs the consumer to halt consuming messages until further notice (CircuitBreaker is CLOSED) . 

***Why is this not a Bug or a feature Request?***
This is a common scenario, i believe Azure development team would have thought about it and implemented it in SKD.

**Setup (please complete the following information if applicable):**
 - OS: Windows10
 - IDE : IntelliJ
 - Version of the Library used
```
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-eventhubs</artifactId>
            <version>2.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-eventhubs-eph</artifactId>
            <version>2.4.0</version>
        </dependency>
```

 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by srnagar** [comment]
@serkantkaraca or @JamesBirdsall - could you please provide any insights into how this can be accomplished in Event Hubs SDK 2.2.0?

**Comment by JamesBirdsall** [comment]
If you're using Event Processor Host, then don't return from onEvents until the downstream dependency is back and you are able to finish processing the batch. If you do return, then EPH will move on to the next batch for that partition and there's no way to prevent that. The only thing that can happen while waiting is that the owning host might lose the lease on the partition -- and since you haven't checkpointed yet, the new owning host will get the same batch of messages again, encounter the same problem with the downstream dependency, and go into the same wait state in your code.

**Comment by srnagar** [comment]
@kumarrajnumber Does this answer your question?

**Comment by kumarrajnumber** [comment]
Yes, thanks, please close this issue.
