### ISSUE TITLE
Scope Component Detection Report

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#11593]
Currently, it appears that the Component Detection report runs the entire repository, client, data, and management tracks, in every pipeline. The reason appears to be targeting the incorrect `pom.xml` when running the report. This inadvertently flags incorrect pipelines as having component violations.

**Comment by kurtzeborn** [comment]
Based on previous conversations we've had with the CG folks, this is by design.  One thing we could consider is to only run CG in our aggregate pipeline.  If this concern is about wanting to scope the runs to sections of the repo (eg. too much noise in the reports from track 1) we're pretty sure there's no way to scope it, we can ask again.  If the concern is because of time spent reanalyzing the repo with each pipeline, we haven't seen CG taking very long and in a few weeks (through @mitchdenny's work) we'll have clear data on which tasks our pipelines are spending time on and will know how much time is being wasted here and whether it's worth the time to refactor.

**Comment by alzimmermsft** [comment]
@kurtzeborn to me, others may differ, this issue is noise. It appears that Azure Pipelines will flag each pipeline with a component governance violation when generating reports. An example here is that we had a static file listing an older version of Netty which had a violation, but since each pipeline will run the entire repo all pipelines get marked with a governance violation. When sourcing the root issue to mitigate there is a lot of time spent triangulating which library caused the violation. Moving the run to a centralized pipeline will reduce the number of pipelines flag but the investigation will remain the same where it requires searching for the root cause libraries.

As for noise from track 1, yes there is some around the dependencies they are using.

**Comment by mitchdenny** [comment]
The aggregate pipelines concern me. One of the things that I am experiencing now is that in order to fix anything in the aggregate pipeline the entire repo has to build successfully which I am sad to say is not often the case, there are often tests/issues that block completely successful runs.

This is something that we need to sort out, but adding things to the aggregate pipeline right now probably means that they aren't going to run that often. The noise might actually be better.

**Comment by mitchdenny** [comment]
I'm going to look into this a bit more closely. I find it hard to believe that there isn't a way to scope the CG search for components...

**Comment by mitchdenny** [comment]
Looks like the detection code has been open sourced: https://github.com/microsoft/componentdetection

**Comment by mitchdenny** [comment]
OK ... it looks like the compontent detection task now supports setting a sourceScanPath:

https://github.com/microsoft/ComponentDetection/blob/352828a29642c4135bb1c07f6044e277a425661e/AzurePipelinesExtension/src/component-detection-tool.ts#L619

If we disabled automated injection by manually putting in the task into the Analyze job (and disabled everywhere else) it means that we would get a scan of dependencies specific to a particular service directory.

Each pipeline would probably detect components which are common across service libraries, but not necessarily the entire graph every time. Would that work?

**Comment by alzimmermsft** [comment]
@mitchdenny that sounds like an ideal solution. Does it also mean we no longer need to generate a CG manifest?

**Comment by alzimmermsft** [comment]
Closing this as component detection has gotten better at associating the flag POM and this is no longer a problem
