### ISSUE TITLE
Linting issues for @ServiceMethod

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#11651]
![image](https://user-images.githubusercontent.com/48036328/83463030-b376ba00-a421-11ea-8bfd-e5469e6010e2.png)
The linting is checking the naming pattern which does not always apply to client SDK.
Also the link needs to be fixed:
https://azure.github.io/azure-sdk/java_design.html#common-service-client-patterns

**Comment by FrailWords** [comment]
@joshfree @sima-zhu I would like to work on this.  Do you think this is the best newcomer task that I could work on to start with ? Thank you.

**Comment by FrailWords** [comment]
I just looked at the code - there are existing `suppressions` in the `checkstyle-suppressions.xml` file referencing this issue.

This issue can be fixed in two ways - either rename all the methods to follow the convention or leave the suppressions and just fix the link.

The methods are named like `upload..` and `merge..`, which seem more clear than if we replace the method name with say `add..` or `update..`.  

I'd just like the your opinion on the right fix for this - basically you mentioned that the checkstyle "does not always apply to client SDK".  Does this mean that we can create some annotation to override this for specific functions?

**Comment by PoojaAggarwal01** [comment]
@sima-zhu Is this issue resolved? 

I am a beginner looking to contribute to OSS. Can I pick this issue if this is not resolved yet?

**Comment by 2MuchC0ff33** [comment]
To resolve the linting issues for @ServiceMethod in Azure SDK for Java, you could try the following steps:

1. Review the linting rules and regulations that apply to the Azure SDK for Java to understand what naming conventions are expected.
2. Check if the @ServiceMethod naming pattern you use is compliant with the defined rules and regulations.
3. If the naming pattern you use is not compliant, could you update it to align with the expected way?
4. Could you test the updated code to make sure that the linting issues are resolved?

For more information and sources, you can refer to the following URLs:

- Azure SDK for Java official documentation: https://docs.microsoft.com/en-us/azure/java/
- Azure SDK for Java GitHub repository: https://github.com/Azure/azure-sdk-for-java
- Azure SDK for Java linting and coding conventions guidelines: https://github.com/Azure/azure-sdk-for-java/wiki/Coding-Conventions

**Comment by Harsha-creator** [comment]
Hi i am new to open source 
I think changing the method name from analyzeText to analyzeTextAsync would be better given the naming conventions,thereby solving the above issue.
Let me know what you think.
