### ISSUE TITLE
Additional Telemetry Metadata

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#11685]
We should look into adding additional telemetry data point such as using sync vs async APIs.

**Comment by JonathanGiles** [comment]
We should introduce a new HTTP policy in azure-core that we can use to create a HTTP header with key `x-ms-azsdk-telemetry`. The value in this header will be defined in conjunction with @kyle-patterson so that we can get insight into consumption of sync vs async, as well as any other useful properties. We will then need to retrofit this into existing libraries via the Context (in much the same way as what we do for tracing) so that the right data is placed into it and made available for the policy.
