### ISSUE TITLE
Software Engineering Process

### ISSUE THREAD

**Issue by cristinamartins** [Azure/azure-sdk-for-java#1169]
We are students from Faculty of Engineering of University of Porto and we have a course on Software Engineering in which we are requested to understand which software development process is used by the team working on this open source project. 

We think it must be an agile development process, but can someone tell us for sure? @martinsawicki 

Thank you very much!!

**Comment by martinsawicki** [comment]
Hello, 
I don't know if I can provide an academically satisfying answer here that would fit within some well known, officially recognized framework or such, as I don't think we can point to a specific textbook example or agile terminology to just say "we do this, that and that". So let me put it this way: we consider or process "agile" in spirit, but it's not scrum, nor any other rigid framework. 

What our team values in general is:
- flexibility over overplanning, 
- rough high-level targets over hourly workitem breakdowns
- a clear sense of high level customer-driven priorities and exit criteria, but with enough wiggle room for ad-hoc innovation when needed, and adjusting the schedule when necessary.

Our efforts behind the new Azure SDK for Java are still to a large degree experimental and exploratory in nature, but at the end of the day, we do also have real deliverables to deliver, on a real timeline. So we work in a way where we try to achieve a balance of both: unplanned innovative and exploratory work and planned/prioritized/deliverable-focused work. 

It's a balance which I don't know of a well defined step-by-step prescription for achieving, so I would describe our dev process as home-grown, flexible, self-adjusting, mixing some elements borrowed from various recognized agile frameworks (at least in spirit) but also tapping into our many years of project management experience, and its continually evolving first-hand knowledge of what works/what doesn't, regardless of what the textbooks say.

Some specific principles I can call out here that our team generally tries to follow include:
- customer feedback driven -- we try to be as responsive as we can to feedback (GitHub issues is the preferred channel)
- iterative/incremental development -- definitely an important pattern for us
- role blending  -- we wear various hats as needed, not just coding. Although we still have official titles and functions, the devs don't only do dev work and the PM doesn't only do PM work, I've always though the lines between these roles are blurry anyway, especially when working on developer-focued technologies, there is no point rigidly sticking to them.
- testing as part of dev work  -- we don't have a separate test org, we rely on our own automation tests as much as possible
- CI at the heart of our source code control -- we could always do more, but so far we have our PRs running through automation, checking for build breaks and checkstyle rule enforcement
- Peer code-reviews - no central "approver", folks review each other's PRs depending on availability and expertise.
- Relatively frequent public releases -- but not killing ourselves over that either, aiming for roughly bimonthly, so that our releases would have enough meat for customers to chew on to make them worthwhile, but also frequently enough to fix arising issues quickly to keep customers engaged, and keep a sharp eye on the always evolving priorities.

There are probably a few more patterns a one would identify in our day to day work that my list is missing here, but fwiw, I hope this helps.

Btw, MSFT has a *great* intern program (https://careers.microsoft.com/students/internships) :-)

**Comment by cristinamartins** [comment]
Thank you so much for the trouble of structuring such a good answer, it was very helpful!!

**Comment by cristinamartins** [comment]
Hello again!

Sorry to bother you again but we have another task for this course. This time we are studying Requirements Engineering and we are supposed to understand how this project deals with requirements elicitation. Do you rely mainly on issues to decide what features to implement? How do you decide whether to implement a new feature or not?

Thank you very much for your attention and we hope you can help us again :-) @martinsawicki

**Comment by martinsawicki** [comment]
GitHub Issues are actually only a small part of the requirements - those are mosty about bugs and such. Some issues entered by us are just our To-Dos to remember. For the most part though, the direction and priorities of the project are determined by a combination of:
- direct customer interactions (phone calls, meetings), which give us a better understanding of the higher-level customer scenarios and painpoints the APIs are intended to address
- our management's strategic guidance as far as business priorities go
- new feature/service availability in Azure
Hope this helps.

**Comment by cristinamartins** [comment]
Thank you, it helped a lot! However, we have been trying to make a list of requirements of the Azure SDK for Java. In terms of functional requirements, namely the capabilities of the software, we've listed the following:

- Create, delete, and update settings for resources like web sites, SQL databases, cloud services, scheduler job collections, virtual machines, and storage
- Start and stop web sites
- Back up databases to storage accounts
- Automate the creation of virtual machines

Are there more?

On the other hand, we are also supposed to list the non-functional requirements, the ones that act to constrain the solution (like particular conditions imposed to the system and not specific functionalities), but we are having some trouble finding them. Can you help us? @martinsawicki 

Sorry to take your time but you have been very helpful!
