### ISSUE TITLE
Cosmos Samples issues

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#12571]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos/src/samples/java/com/azure/cosmos/ChangeFeedProcessorCodeSnippet.java#L14):
![image](https://user-images.githubusercontent.com/64007802/85942441-ed24dd00-b95b-11ea-8533-8fda3bab4350.png)
Reason:
![image](https://user-images.githubusercontent.com/64007802/85942443-f31abe00-b95b-11ea-9def-00d0a64361de.png)
Suggestion:
Update the code:
`CosmosAsyncClient cosmosAsyncClient = new CosmosClientBuilder().buildAsyncClient();`
to:
` CosmosAsyncClient cosmosAsyncClient = new CosmosClientBuilder()
            .endpoint(TestConfigurations.HOST)
            .key(TestConfigurations.MASTER_KEY)
            .buildAsyncClient();`

**Comment by Melanie-Ma** [comment]
@jongio ， for notification.

**Comment by kushagraThapar** [comment]
@Melanie-Ma - these are not samples - but rather just the code snippets used in documentation. 
They are not designed to run, but just designed to tag in the code documentation. 
For samples, please refer to : https://github.com/Azure-Samples/azure-cosmos-java-sql-api-samples

**Comment by Melanie-Ma** [comment]
@kushagraThapar - I agree that the code snippets are used in documentation. However, I think that the code documentation also need right example for users ′ reference. Therefore, I think the issue need to be fixed.

**Comment by kushagraThapar** [comment]
@Melanie-Ma - For your #1 issue -> The reason we cannot use endpoints and keys in code snippets is because we cannot have real endpoints in the documentation. 
Also, the documentation only refers to the tagged code not the overall code - see below : 

![image](https://user-images.githubusercontent.com/14034156/86493388-3b542a80-bd26-11ea-9726-2b101837d9a9.png)

Regarding #2 -> @moderakh - please take a look at the analytical storage issue.

**Comment by jongio** [comment]
Howdy - Sample code should be copy and paste-able.  We aren't suggesting an actual endpoint, just code that will work if the user tries to use it.

@Melanie-Ma - Would be great to see a PR for your suggestions.  For the first issue.

Can you open another issue for the second issue you found so we can track that separately?

Thanks, 
Jon

@tzhanl

**Comment by kushagraThapar** [comment]
@jongio - I think the argument is incorrect here. At first place, this is not sample code, this is code snippet. 
Samples are here: https://github.com/Azure-Samples/azure-cosmos-java-sql-api-samples 

To treat code snippets as samples is incorrect in my opinion. Because the relative part of the code snippet that is present in the docs works correctly. 

We don't want users to look at these code snippets directly through source code, but rather through documentation. I think the directory structure is making it a wrong impression, because it says `samples`.

@srnagar  @alzimmermsft - thoughts ?

**Comment by Melanie-Ma** [comment]
@jongio -  I have opened another [issue ](https://github.com/Azure/azure-sdk-for-java/issues/12811)for the second issue. Please review.

**Comment by moderakh** [comment]
2 is not an issue in the SDK. you need to enable the feature on the service side before attempting to use it.
@srchi is the PM who can help on enabling analytical store in the account.
