### ISSUE TITLE
Exception while adding more eventProcessorClient instances and 2 instances reading same message of same partition

### ISSUE THREAD

**Issue by oceansv** [Azure/azure-sdk-for-java#13203]
1) Exception when adding up more consumer instances.
2) Two consumer  with same  consumer group running as 2 separate instances on same machine reading same message of same partition. (same message is read by both the instances )

Java 8 
dependencies getting used
  <dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-messaging-eventhubs</artifactId>
    <version>5.1.2</version>
    
    <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-messaging-eventhubs-checkpointstore-blob
            </artifactId>
            <version>1.1.2</version>
        </dependency>

I have a eventhub with 4 partition. I am producing messages continuously on the eventhub. and listening with EventProcessorClient.

Initially 1 instance is up and listening all the 4 partitions. In between i am starting the 2nd instance with same consumer group on the same machine. My expectation was partition will automatically get re balances and partition ownership will get distributed to 2 listeners (having same consumer group).
But i am facing 2 issues 

1) both instances are listening same messages of the same partition (contrast to 1 parition 1 consumer ownership).

2) getting below error and similar error continously.

Error occurred in partition processor for partition 3, com.azure.core.amqp.exception.AmqpException: New receiver 'nil' with higher epoch of '0' is created hence current receiver 'nil' with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:70cb6fce00000f030023f5515f0f1e63_G27_B21, SystemTracker:......:test~32766|$default, Timestamp:2020-07-15T15:19:19, errorContext[NAMESPACE: ......, PATH: test/ConsumerGroups/$default/Partitions/3, REFERENCE_ID: ......, LINK_CREDIT: 499].

**Comment by joshfree** [comment]
Thanks for reporting this issue @oceansv.  @conniey can you please take a look?

**Comment by srnagar** [comment]
1. Both instances will not be allowed to process the same partition. If one instance takes ownership of a partition, ownership will be revoked from the other instance by the service. There is a very small window of overlap before the service disconnects the link from one instance. 

2. This error occurs when the service disconnects a partition as another instance took ownership of that partition. 

It should eventually settle down to a stable ownership configuration with each instance owning 2 partitions. If this doesn't happen, please provide the complete logs for both instances.

**Comment by oceansv** [comment]
@srnagar 1) ) Are u saying during the ownership transfer period message can be read by 2 or more instances? 2) the error occuring are not to worry about if they are for a small time and goes off once partition transfer completes?

**Comment by srnagar** [comment]
@oceansv - When the ownership transfer happens from instance A to instance B, here's what happens:
- instance A would have read some events from the Event Hub service that are in its local queue waiting to be processed 
- instance B would request the ownership of the partition at which point the service disconnects the link from instance A and hands  it to instance B
- instance B starts processing the events from the last checkpoint that instance A had recorded which could be older than the events that are currently in its local queue
- so both instance A and instance B will now process the same events for a brief period until instance A clears out its local queue

Consumers are expected to be idempotent for this reason. See more documentation here - https://docs.microsoft.com/en-us/azure/event-hubs/event-processor-balance-partition-load#checkpointing

Also, regarding ordering, the ordering for a consumer instance is always guaranteed. A single consumer will never receive events out of order. Ordering does not guarantee exactly-once semantics which is why the ownership transfer or failure recovery would require idempotent consumers.

Regarding the error, this is expected when the transfer happens.

**Comment by oceansv** [comment]
@srnagar  Thanks for the clarification. Then it does not seems to be a issue.
