### ISSUE TITLE
Use consistent dependency management for Spring Boot starters

### ISSUE THREAD

**Issue by snicoll** [Azure/azure-sdk-for-java#13413]
I had created an issue in the previous repository that got closed, see https://github.com/microsoft/azure-spring-boot/issues/757 for a description.

Looking in the pom for `azure-spring-boot` I can see that [it has hardcoded dependencies](https://github.com/Azure/azure-sdk-for-java/blob/c88bd18edcd0e89dcaee46cba788760ef6c7bcda/sdk/spring/azure-spring-boot/pom.xml) for Spring Framework, Spring Boot, Spring Security and some third party whose  version is managed by a typical Spring Boot apps.

I don't understand how the issue is fixed. Have I missed something?

**Comment by chenrujun** [comment]
Hi, @snicoll .

In this repo, all dependencies are managed in a [config file](https://github.com/Azure/azure-sdk-for-java/blob/master/eng/versioning/external_dependencies.txt).

We have a [script](https://github.com/Azure/azure-sdk-for-java/blob/master/eng/versioning/update_versions.py) to set version for all pom file.

The `dependency version system` (including above `config file` and `script`) is designed by our `Engineering tool team` (@JimSuplizio ).

IMU, the main purpose of the `dependency version system`  are:
1. Make sure all the external dependency versions are synced in the whole repo. (Yes, `dependencyManagement` can also achieve this.)
2. All versions are managed by `Engineering tool team`, if some developer changed the `config file` in a PR, the `Engineering tool team` member will set as reviewer. (`dependencyManagement` can not achieve this, because developer may override the version in his own pom file)

(@JimSuplizio , correct me if my understanding is wrong.)


Here is my plan to keep the version synced with spring-boot:

Write a script to get all external dependency version list from [spring-boot-dependencies](https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/2.3.0.RELEASE/spring-boot-dependencies-2.3.0.RELEASE.pom), then sync all versions to the [config file](https://github.com/Azure/azure-sdk-for-java/blob/master/eng/versioning/external_dependencies.txt). When we update the spring-boot version, we run this script.


@JimSuplizio , what's your opinion?

(cc @saragluna , @jialindai , FYI.)

**Comment by snicoll** [comment]
Thanks for the explanation, this clarifies the intent.

> dependencyManagement can NOT achieve this, because developer may override the version in his own pom file.

I am not sure what you mean by that. I can import a BOM and override something if I want to. Or I can extend from `spring-boot-starter-parent` and override a property to change the version of a third party dependency. Hardocding the versions in each modules as you do doesn't prevent a user to override the version of a third party dependency. 

As for reviews (nice one btw!), you could achieve the same thing by having a bom and set the engineering tool team as a reviewer when the bom is changed. 

Speaking of bom and asking here as it is directly related, do we still have what used to be `azure-spring-boot-bom`? Thanks!

**Comment by chenrujun** [comment]
@snicoll ,
Thank you for the quick response.

> Hardocding the versions in each modules as you do doesn't prevent a user to override the version of a third party dependency.

`override the version of a third party dependency` in this repo is forbidden, and we have [script](https://github.com/Azure/azure-sdk-for-java/blob/master/eng/versioning/pom_file_version_scanner.ps1) to check that. If developer's module's version is not same with the config file, pipeline will failed in PR.

And that's the key point, `Engineering tool team` want `all version in this repo` under their control.

---

> do we still have what used to be azure-spring-boot-bom?

Yes, [here it is](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/boms/azure-spring-boot-bom/pom.xml).

**Comment by chenrujun** [comment]
@JimSuplizio 

BTW, if maven have the following 2 features, we can use them directly instead of checking version by script. Is that right?
1. https://issues.apache.org/jira/browse/MENFORCER-19
2. https://issues.apache.org/jira/browse/MENFORCER-65

**Comment by JimSuplizio** [comment]
@snicoll This is how [versions and versioning](https://github.com/Azure/azure-sdk-for-java/blob/master/CONTRIBUTING.md#versions-and-versioning) works within the azure-sdk-for-java repository. Versioning is centralized for the purpose of keeping the repository on consistent versions for the libraries built and released from the repository. A large part of why this was done was due to inconsistent versions which lead to dependency ordering issues. Unfortunately, Maven is not smart with some things. That being said the [azure-spring-boot-starters](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples) are all directly used by the azure-spring-boot-samples which do, parent from spring-boot-starter-parent and, outside of the starter's dependency version, use the the org.springframework.boot defined in the spring-boot-starter-parent's dependencyManagement section.

I'm happy to discuss this further with you but this isn't going to be changing within our repository.

**Comment by snicoll** [comment]
@JimSuplizio thanks for the additional context. This issue isn't a criticism of the mechanism you've put in place but rather a way for me to validate that Spring Boot's dependency management is consistently applied for the Spring integration in this repository. It is unclear if there is a process in place so that Spring-related artifacts are synced with what a typical Spring Boot app brings (i.e. Spring Boot's dependency management that's a key feature of the project). A comment above makes me think it isn't:

> Write a script to get all external dependency versions from spring-boot-dependencies, then sync all versions to the config file. When we update the spring-boot version in this repo, we run this script.

**Comment by chenrujun** [comment]
@snicoll , @JimSuplizio 

>Write a script to get all external dependency versions from spring-boot-dependencies, then sync all versions to the config file. When we update the spring-boot version in this repo, we run this script.

FYI: 
I plan to develop the script. 
And I'll reopen this issue to track the script development.
