### ISSUE TITLE
[Tables] Add more tests to validate update & upsert success / error scenarios

### ISSUE THREAD

**Issue by eboyd23** [Azure/azure-sdk-for-java#13680]
Validate that the update functionality works as expected / described in the comments below, and add more tests around update & upsert, and verify both the success and the error cases function as expected.

~When calling updateEntity without the etag, the behavior should merge/replace if the entity exists and throw and error if not and the etags do not have to match. Currently this part of the updateEntity() method uses getEntity() to verify the existence of a entity and throw an error if it does not exist. There is likely a better way to execute this behavior but I did not have time to figure it out.~

~Todo:~
~- Fix the updateEntity method (TableAsyncClient around line 311)~
~- updateEntity() does not have an overload updateEntity(TableEntity, ifUnchanged). This might be useful to a user and should be added if so.~

**Comment by bsiegel** [comment]
Update - this issue may be inaccurate, it doesn't seem like doing the `get` is required in order to get the operation to fail if the entity does not exist. The service returns 404 on any PUT or MERGE operation that includes an `If-Match` header if the entity with the given partition & row key doesn't exist.

However we may want to put better ergonomics around populating the eTag of the provided entity, right now the only way it works is if you do a getEntity and then re-use the returned object in future update calls.

Also we really need more tests around update / upsert, with varying combinations of merge mode + etag values. I found that the upsert operation was including an `If-Match` header mistakenly, meaning that it was actually doing an update operation. Will file an issue to track this.

**Comment by bsiegel** [comment]
Going to repurpose this issue to add more tests around update & upsert, and verify both the success and the error cases function as expected.
