### ISSUE TITLE
Subscription.listLocations should be renamed to listRegions

### ISSUE THREAD

**Issue by jianghaolu** [Azure/azure-sdk-for-java#1394]
and return `List<Region>`.

**Comment by martinsawicki** [comment]
Not quite. Regions and Locations are not just different names for the same thing in Azure - they represent different concepts. Unfortunately the REST API and the portal conflate the two, often using the word "location" to refer to what is really a "region", but the documentation is very clear about the distinction between a **region** and a **location**. As can be inferred from [this article](https://azure.microsoft.com/en-us/regions/), the _location_ represents a relatively specific location of a data center (the article lists the state or city name; the API includes its geographic coordinates), whereas the _region_ is an area in the world that that location is intended to primarily serve, referred to in a more general way, e.g. `USWest`.

The SDK's fluent API as designed is intentionally making that distinction: that's why the enum representing the list of "regions" is called `Region`, and APIs accepting that enum are called `withRegion()`.  This is the correct naming for what this does.

There is also an API call in the Azure REST surface called `listLocations()` -- its naming is also arguably correct, or at least useful, in the sense that it returns something different -- its individual results include the geographical coordinates of the data centers (`latitude()` and `longitude()`) accessible to a given subscription, so it is a list of locations, not so much regions, even though the list count is equal to the number of regions, not locations. A given location also contains the name of the region the data center at that location serves, so it is easy to look up the region from a location and vice versa.

Now, with this in mind, the issue as originally logged is worded incorrectly, but what it is motivated by is a valid need: the need to more easily convert from "location" to "region" back and forth.

So in beta5, new APIs have been added to address that need:
- `Subscription.getLocationByRegion(Region)`
- `Location.asRegion()`

Also, for greater ease of accessing the subscription associated with the instantiated `Azure` client, or listing other subscription IDs from it, the following are now exposed on the `Azure` object:
- `Azure.getCurrentSubscription()`
- `Azure.subscriptions()`

**Comment by martinsawicki** [comment]
shipped as described above in beta5
