### ISSUE TITLE
[BUG] - azure-keyvault-secrets-spring-boot-starter:2.3.3 depends on Spring Boot 2.3.2 rather than 2.3.3

### ISSUE THREAD

**Issue by paulnuk** [Azure/azure-sdk-for-java#14340]
**Describe the bug**

com.microsoft.azure:azure-keyvault-secrets-spring-boot-starter:2.3.3 depends on two spring boot projects, spring boot starter and spring boot starter validation. The versions of these dependencies should be 2.2.3, but they are actually 2.2.2 which is incorrect.

**To Reproduce**

Add the dependency to a Java project and the wrong spring boot dependencies are pulled in.

e.g. for gradle:

    implementation("com.microsoft.azure:azure-keyvault-secrets-spring-boot-starter:2.3.3")

***Code Snippet***

This pom inside the jar is incorrect, see attached

[pom.xml.txt](https://github.com/Azure/azure-sdk-for-java/files/5108901/pom.xml.txt)

**Expected behavior**

It should use the 2.3.3 dependencies

**Comment by zhoufenqin** [comment]
@paulnuk  Our azure spring boot starter version is not kept the same with the Spring Boot version. eg.  azure-keyvault-secrets-spring-boot-starter:2.3.4 may still related to Spring Boot 2.3.2, because we will release new features about azure-keyvault, but this features not directly related to Spring Boot version.

**Comment by zhoufenqin** [comment]
closing the issue
