### ISSUE TITLE
issue with list(filter,top) of resource group client

### ISSUE THREAD

**Issue by MSSedusch** [Azure/azure-sdk-for-java#1451]
Hi,

I am trying to retrieve 10 resource groups by calling 

`PagedList<ResourceGroupInner> result = ResourceManagementClientImpl.resourceGroups().list(null, 10)` 

which returns 10 elements. If I call result.size() it does not return 10 but instead calls loadAll() which downloads all available resource groups. Is this the intended behaviour?

loadAll() should honor the top query IMHO.

Thanks

**Comment by anuchandy** [comment]
@MSSedusch thanks for reporting this. 

It looks like a server side issue. When we list resource groups with $top, server returns a page with $top items but also a next link. I think nextLink should be present only if the value specified in the $top is greater than the default server defined page size, so that user can fetch items in a loop which exit when nextLink  is null, so he get exactly $top items.

I have reported this issue to resource provider team.

**Comment by martinsawicki** [comment]
service side issue reported - not actionable on the SDK side, so closing
