### ISSUE TITLE
Unable to create topic subscription with default rule

### ISSUE THREAD

**Issue by deejay220989** [Azure/azure-sdk-for-java#14572]
I'm trying to create new topic subscription with default rule using this:
https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.servicebus.management.managementclient.createsubscription?view=azure-java-legacy#com_microsoft_azure_servicebus_management_ManagementClient_createSubscription_SubscriptionDescription_RuleDescription_

The error I'm getting:
`Cannot create an abstract class
`
I'm using azure-servicebus 3.4.0.

Code sample:
```
SubscriptionDescription subscriptionDesc = new SubscriptionDescription(topicName, subName);
subscriptionDesc.setDefaultMessageTimeToLive(Duration.ofDays(14));
subscriptionDesc.setLockDuration(Duration.ofMinutes(5));
subscriptionDesc.setMaxDeliveryCount(20);
// Auto-forward messages to queue.
subscriptionDesc.setForwardTo(getServiceBusQueuePath(queueName));
// Set subscription as active
subscriptionDesc.setEntityStatus(EntityStatus.Active);

// Create default rule.
RuleDescription defaultRule = new RuleDescription("ContentRule", new SqlFilter("Content='abc'"));

// Connect to management client.
ConnectionStringBuilder connStrBuilder = new ConnectionStringBuilder(namespace, topicName, sharedAccessKeyName, sharedAccessKey);
ManagementClient mgmtClient = new ManagementClient(connStrBuilder);
// Create subscription to the metadata-events topic.
mgmtClient.createSubscription(subscriptionDesc, defaultRule);
mgmtClient.close();
```
 
It works if I just do this:
`mgmtClient.createSubscription(subscriptionDesc);`

Stack trace:
```
com.microsoft.azure.servicebus.primitives.ServiceBusException: Cannot create an abstract class. TrackingId:91b4c0b8-3388-412c-9e8a-7d1143d17198_G42, Topic:metadata-events, Timestamp:2020-08-28T05:02:51; Status code: 500
	at com.microsoft.azure.servicebus.management.ManagementClientAsync.validateHttpResponse(ManagementClientAsync.java:1127)
	at com.microsoft.azure.servicebus.management.ManagementClientAsync.lambda$sendManagementHttpRequestAsync$21(ManagementClientAsync.java:1055)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by joshfree** [comment]
Hi @deejay220989, someone from the `Mgmt` team will follow up on this github issue shortly.

/cc @yungezz

**Comment by yungezz** [comment]
hi @joshfree I think this is part of data plane operation of service bus management client, the `management` is not management client :) here's the source code matching namespace from error stacktrace: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/microsoft-azure-servicebus/src/main/java/com/microsoft/azure/servicebus/management/ManagementClientAsync.java.

Let me know if this is not the right library. I'll remove `Mgmt` for now.

**Comment by deejay220989** [comment]
What's the status of this issue?

**Comment by yungezz** [comment]
hi @joshfree could you pls help to route to right owner? thanks.

**Comment by axisc** [comment]
@deejay220989 

Thanks for raising this issue. We will investigate internally.

**Comment by hemanttanwar** [comment]
@axisc  Ashish , Following up on this, if we have update on why this issue happened ?

**Comment by yvgopal** [comment]
@deejay220989 I am investigating this issue. I haven't been able to reproduce this issue.
All I can tell you is the exception came from service bus service. Could you reproduce it again? If you can, please give us more info about your namespace like 
1. Namespace name - this tells us the clusters, SKU. 
2. Tracking Id and timestamp of the error,  that you can find in the exception message. TrackingId:91b4c0b8-3388-412c-9e8a-7d1143d17198_G42, Topic:metadata-events, Timestamp:2020-08-28T05:02:51; Status code: 500

**Comment by yvgopal** [comment]
I am closing it as I haven't heard from you. Even if it could be reproduced, it is most likely a service side issue.

**Comment by manishtulsiani** [comment]
@yvgopal , we also started facing this issue:

Caused by: com.microsoft.azure.servicebus.primitives.ServiceBusException: Cannot create an abstract class. TrackingId:7d965850-9b1d-4082-997d-c25fd81914ac_G0, SystemTracker:<service busnamspace>:Topic:<topic> Timestamp:2021-03-19T10:02:16; Status code: 500
	at com.microsoft.azure.servicebus.management.ManagementClientAsync.validateHttpResponse(ManagementClientAsync.java:1127)
	at com.microsoft.azure.servicebus.management.ManagementClientAsync.lambda$sendManagementHttpRequestAsync$21(ManagementClientAsync.java:1055)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

we are using service bus version client sdk: 3.6.0

**Comment by lchew7** [comment]
The root cause is a bug in the following JAR (it may not be specific to v2.7.2).  Please check if your application uses this library.

JAR name: xalan:serializer:jar:2.7.2
Namespace: com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.
Class name: org.apache.xalan.processor.TransformerFactoryImpl

This XSLT processing library mangles the XML that is sent by our SDK.  It strips out the namespace information on the Filter element:

Good Request that doesn't use Xalan:

<entry
xmlns=http://www.w3.org/2005/Atom>
<content type="application/xml">
<SubscriptionDescription
xmlns=http://schemas.microsoft.com/netservices/2010/10/servicebus/connect>
<LockDuration>PT5M</LockDuration>
.......
<DefaultRuleDescription>
**<Filter
xmlns:ns0=http://www.w3.org/2001/XMLSchema-instance ns0:type="SqlFilter">**
<SqlExpression>Content='abc'</SqlExpression>
</Filter>
</DefaultRuleDescription>
<Status>Active</Status>
</SubscriptionDescription>
</content>
</entry>
 

Bad Request that uses Xalan:

<entry
xmlns="http://www.w3.org/2005/Atom">
<content type="application/xml">
<SubscriptionDescription
xmlns="http://schemas.microsoft.com/netservices/2010/10/servicebus/connect">
<LockDuration>PT5M</LockDuration>
...
<DefaultRuleDescription>
**<Filter type="SqlFilter">
<SqlExpression>Content='abc'</SqlExpression>
</Filter>**
</DefaultRuleDescription>
</SubscriptionDescription>
</content>
</entry>

**Comment by rachelxj-ms** [comment]
@lchew7 
https://github.com/Azure/azure-sdk-for-java/blob/026664ea871586e681ab674e0332b6cc2352c655/sdk/servicebus/microsoft-azure-servicebus/src/main/java/com/microsoft/azure/servicebus/management/SubscriptionDescriptionSerializer.java#L123
        try {
            **TransformerFactory transformerFactory = TransformerFactory.newInstance();**
            Transformer transformer = transformerFactory.newTransformer();
            transformer.setOutputProperty("omit-xml-declaration", "yes");
            transformer.transform(new DOMSource(doc), new StreamResult(output));
        } catch (TransformerException var9) {
            throw new ServiceBusException(false, var9);
        }
javax.xml.transform.TransformerFactory#newInstance(), it'll use FactoryFinder to find an implementation of TransformerFactory, if there is no match, it will fall back to **"com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl"**

 public static TransformerFactory newInstance() throws TransformerFactoryConfigurationError {
        return (TransformerFactory)FactoryFinder.find(TransformerFactory.class, "com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl");
}
I read source code of javax.xml.transform.FactoryFinder, here are the steps how it finds an implementation of TransformerFactory. 
1. Is there system property named TransformerFactory.class.getName(), aka "javax.xml.transform.TransformerFactory", if yes, load the class specified in the property. If no, go to next. 
2. Does this file "%JAVA_HOME%\lib\jaxp.properties" exist? If yes, load the property file and find a property named as "javax.xml.transform.TransformerFactory", if found a match, load the class specified in the property. If no, go to next. 
3. Use class loader to find any class implements "javax.xml.transform.TransformerFactory", if found a match, load the class. If we import xalan, it'll load org.apache.xalan.processor.TransformerFactoryImpl. Otherwise it'll use "com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl".

For ServiceBus SDK, it must use "com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl" to avoid corruption of XML transformation.
There is another implementation of newInstance we can use to load specific class com.microsoft.azure.servicebus.management.SubscriptionDescriptionSerializer.
try {
            **TransformerFactory transformerFactory = TransformerFactory.newInstance("com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl", TransformerFactory.class.getClassLoader());**
            Transformer transformer = transformerFactory.newTransformer();
            transformer.setOutputProperty("omit-xml-declaration", "yes");
            transformer.transform(new DOMSource(doc), new StreamResult(output));
        } catch (TransformerException var9) {
            throw new ServiceBusException(false, var9);
        }

Right now, we have a workaround before we make any fix on SDK. 

String oldTransformerFactory = System.getProperty(TransformerFactory.class.getName());
        System.setProperty(TransformerFactory.class.getName(), "com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl");
        mgmtClient.createSubscription(subscriptionDesc, defaultRule);
        if (oldTransformerFactory != null) {
            System.setProperty(TransformerFactory.class.getName(), oldTransformerFactory);
        } else {
            System.clearProperty(TransformerFactory.class.getName());
        }

**Comment by lchew7** [comment]
Hey Rachel:

Interesting.  Great work!

A few comments with the proposed SDK fix:

1. It's not that we must use any specific library.  We can use any TransformerFactory provider.  It's that some providers are buggy (e.g., org.apache.xalan.processor.TransformerFactoryImpl).
2. TransformerFactory allows the user to specify different providers.  If we directly specify it in newInstance(), that would remove their ability to do so right?  For example, if a user set the system property "javax.xml.transform.TransformerFactory", it seems your fix would override/ignore that?

Ultimately, this is a client issue, and not a ServiceBus SDK issue.  They should not use this buggy library by either removing it from their dependencies, or by specifying a specific library as in your workaround solution (which is actually a proper solution).

**Comment by rachelxj-ms** [comment]
@lchew7 Well, my point is that if we specify it in newInstance() (called in com.microsoft.azure.servicebus.management.SubscriptionDescriptionSerializer), that'll only affect ServiceBus SDK to transform SubscriptionDescription into XML, it won't affect whatever providers user specifies in their application. We don't actually want other ability of different providers from SDK perspective.  
Anyway, workaround will work. :)
