### ISSUE TITLE
Missing Assign licence to User

### ISSUE THREAD

**Issue by dviru** [Azure/azure-sdk-for-java#1463]
Hi,

I am using this SDK for azure GraphAPI to create user.but i have some more requirement like assign/remove the licence for the user.I couldn't find how to assign/remove licence to user using this SDK. for more details

https://msdn.microsoft.com/Library/Azure/Ad/Graph/api/functions-and-actions#assignLicense

Is this SDK contains this functionality?

Regards,
Veerendra

**Comment by yugangw-msft** [comment]
[Swagger spec](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/graphrbac/data-plane/Microsoft.GraphRbac/stable/1.6/graphrbac.json) would need to be updated for this. Till that happens, this operation is not supported across SDKs. Note, this ask is not relevant to RABC which is what the GraphRBAC is mainly for

**Comment by baywet** [comment]
@ChenTanyi do you have any idea why the bot is pinging me on those issues? It seems to happen whenever the service attention tag is added. Thanks!

**Comment by ChenTanyi** [comment]
@baywet Yes, the bot will automatically ping the service team when the service attention tag is added.

The issue requests service to add swagger with `assignLicense` since the customer want to use this API in SDK. Thanks!

**Comment by baywet** [comment]
@ChenTanyi I'm not sure I should be on that list but rather API owners. Who should I reach out internally to review that list of "service team" members?

**Comment by ChenTanyi** [comment]
@baywet You can reach `Lily Ma <Jiayi.Ma@microsoft.com>` for the service member list.

Since issues which need service attention are not only the API requests, but also some service bugs, I think it may be better to reach a person for the whole services team than only API owners.
Could you ask the API owners to see this issue?

Meanwhile, I found a label `ARM - RBAC`, not sure if this team is for graphrbac API instead.
