### ISSUE TITLE
Try to reduce number of overloads in receiver methods.

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#14668]
From our Java API review, there is an overload explosion of settlement operations. Can we clean this up by passing some into an options class? For example, settlement options that takes a transaction context. For example, the `abandon` operation has 6 overloads, which is a lot. This makes the receiver client hard to figure out.

https://apiview.dev/Assemblies/Review/64f40be9988242c9a8facc8a20c5e9e7

**Comment by ramya-rao-a** [comment]
From offline discussions with @conniey:

Based on https://github.com/Azure/azure-sdk-for-net/issues/10852#issuecomment-679859788, we need to update the settlement methods to take the message instead of the lock token.

Once we have the message, we don't need the overloads that take the sessionId as the message would contain the messageId

That leaves us with the overloads that take the `propertiesToModify` and the transaction context which can go into an options bag.

This leaves  us with the below

```
abandon(ReceivedMessage)
abandon(ReceivedMessage, SettlementOptions)
```

But what about the dead letter method that already takes a `DeadLetterOptions`?
And the complete method that does not take `propertiesToModify`
Should we have `AbandonOptions`, `CompleteOptions` and `DeferOptions` separately?

cc @hemanttanwar, @YijunXieMS, @JonathanGiles
