### ISSUE TITLE
Reliable CosmosDB client connection configuration for Azure functions consumption plan

### ISSUE THREAD

**Issue by casper-79** [Azure/azure-sdk-for-java#14779]
**Query/Question**

We are building an analytics application for spiky workloads on Azure functions consumption plan. We use CosmosDB to store the state of each job, but when we use the default cosmos client configuration we see 95th percentile latencies of several seconds and a large number of "connection closed" exceptions from Cosmos DB. It appears that the default connection configuration is intended to be used by large always-on instances and we have been unable to find any documentation covering configuration for the consumption plan use case. In lack of documentation we have experimented with the settings and found a configuration that produces significantly better throughput and gives much fewer exceptions than with the defaults. Our query/question is for recommendations on an optimal client connection configuration for use with Azure functions on a consumption plan. We would also like feedback on the details of our performance tuning findings given below.

Further details: The workload on our system is a scheduled spike of jobs every hour, which we want to handle as quickly as possible. This implies lots of short lived consumption plan instances (100+) are spinning up at the same time and we found that the default cosmosDB client settings are simply not suitable for this scenario. We have done load testing experiments with the Java CosmosDB SDK 4.2.0 with different client configurations and followed best practices for performance optimization (eg. client is cached). Based on these experiments we have drawn the following conclusions:

• Direct connection is the way to go, since it can be tuned to deliver much better performance than gateway. Connection tuning is required to make it reliable, however. If we simply use the default configuration for direct connection we are flooded with thousands of the “connection closed” exception seen below.
• Limiting maxConnectionsPerEndpoint to 1 reduces the number of DB exceptions very significantly and does not appear to have any negative impact on performance
• Setting a low value for maxRequestsPerConnection lowers the latency of synchronous writes very significantly (At least an order of magnitude for the 95th percentile compared to default). If it goes too low, however, we start to see an increase in the number of DB exceptions. The optimal parameter appears to be a trade off between performance and the number of DB exceptions thrown. We have found 10 be a good compromise.
 • Performance varies significantly with different versions of the SDK. In our experiments 4.3.1 provides less than half the query throughput of 4.2.0 using the connection configuration seen below.

Highest throughput configuration:
```
DirectConnectionConfig directConnectionConfig = DirectConnectionConfig.getDefaultConfig();
directConnectionConfig.setMaxConnectionsPerEndpoint(1);
directConnectionConfig.setMaxRequestsPerConnection(10);
 
return new CosmosClientBuilder()
        .endpoint(environment.endpoint)
        .key(environment.primaryKey)
        .consistencyLevel(ConsistencyLevel.STRONG)
        .directMode(directConnectionConfig)
        .buildClient();
```

The connection closed exception we see thousands of with the default direct connection configuration:
```
Exception while executing function: Functions.JobPersister Result: Failure
Exception: IllegalStateException: RntbdServiceEndpoint({"id":3,"isClosed":true,"concurrentRequests":0,"remoteAddress":"cdb-ms-prod-westeurope1-fd20.documents.azure.com:14318","channelPool":{"remoteAddress":"cdb-ms-prod-westeurope1-fd20.documents.azure.com:14318","isClosed":false,"configuration":{"maxChannels":130,"maxRequestsPerChannel":30,"idleConnectionTimeout":0,"readDelayLimit":65000000000,"writeDelayLimit":10000000000},"state":{"channelsAcquired":0,"channelsAvailable":0,"requestQueueLength":0}}}) is closed
Stack: java.lang.reflect.InvocationTargetException
at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
at com.microsoft.azure.functions.worker.broker.JavaMethodExecutorImpl.execute(JavaMethodExecutorImpl.java:54)
```

***Why is this not a Bug or a feature Request?***
Although we do see exceptions, the cause of the exceptions seems to be related to configuration. 

**Setup (please complete the following information if applicable):**
Java Azure functions 3.0 on consumption plan
com.azure:azure-cosmos:4.2.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this github issue @casper-79.  An expert from the `Cosmos` SDK team will follow up shortly.

/cc @kushagraThapar

**Comment by casper-79** [comment]
@kushagraThapa Any update on this issue?

**Comment by kushagraThapar** [comment]
@casper-79 - I will look into this issue soon, will provide an update shortly, thanks.

**Comment by kushagraThapar** [comment]
@casper-79 - Thanks for the detailed explanation of your issue, here are my recommendations: 

1. Using DIRECT connection mode is the right way to go, since GATEWAY has its limitations (as it is a shared resources). 
2. `directConnectionConfig.setMaxRequestsPerConnection(10);` = 10 sounds good, as it is also the default value. 
3. `directConnectionConfig.setMaxConnectionsPerEndpoint(1);` = 1, this is limiting the number of connections per endpoint to only 1 which will affect your application in case of very high load, or if the endpoint goes down for any normal reasons (like upgrades / updates / bad node / unhealthy node, etc.). So setting this value to 1 will have some side effects in case of these corner cases. I would recommend having at least few connections per endpoint so when you hit these corner cases, your application is able to recover from unavailable endpoints. 

But if `maxConnectionsPerEndpoint` = 1 is working well for you in production, then stick with it for now, and you can update it if you see any issues.

**Comment by casper-79** [comment]
Thanks @kushagraThapar  

The thing is that it is not exactly working well in production. The configuration tweak is mildening the symptoms, but we are still seeing a boat load of exceptions that come with no usable explanation of cause. I had hoped you would be able to explain why the connection is constantly closed and why the change from default configuration is mildening the symptoms? We are not in production yet, but we need to get rid of this exception soon so we can go live ...

**Comment by kushagraThapar** [comment]
@casper-79  Let me explain the root cause of the exception you are seeing. 
The connections get dropped because the `idleEndpointTime` reaches and it close the connections. Also, we noticed that in the earlier v4 version of SDK, there were some issues with connections hanging which has been fixed in SDK version `4.5.0`. Please upgrade to the latest version. 

At this point I can suggest two options for you to take it forward: 
1. If you have fixed number of collections, then increase the `idleEndpointTimeout` to a bigger value - like 5 hours or 12 hours (default value is just 1 hour), which will ensure that connections are not dropped because of sparse workload that you have, and it will also ensure that you will not pay additional cost of creating and dropping connections every now and then. You will not see connections getting closed once you increase this value. 
2. If you have many collections (thousands), then you need to quickly close the connections and re-create them. In this case, you should rely on default settings, because they should only close the connections when the idleEndpointTimeout reaches (by default 1 hour), and you actually want to close the connections at that point, to not acquire big resources from your machine.

**Comment by casper-79** [comment]
Thanks @kushagraThapar

We had previously experimented with 4.3.1, which turned out to provide even more exceptions than with 4.2.0. However, I am happy to confirm that my preliminary testing confirms that this is indeed resolved by 4.5.0. So far the exceptions appear to have disappeared completely and our 99th percentile request times have dropped by more than a factor of 10. I am happy so far, but will keep the issue open until we have had time to do a more substantial load test ...

**Comment by kushagraThapar** [comment]
@casper-79 Thanks for the update, I am glad you are no longer seeing any issues, let me know once you have the full results.

**Comment by casper-79** [comment]
@kushagraThapar

I can confirm that everything works as it should with 4.5.0. Case closed.
