### ISSUE TITLE
[QUERY] Java API: ServiceBusReceiverAsyncClient receiveMessages() starting from sequence

### ISSUE THREAD

**Issue by wernerdaehn** [Azure/azure-sdk-for-java#14859]
**Query/Question**
How to call ServiceBusReceiverAsyncClient.receiveMessages() starting from a provided sequence number.

When using the ServiceBusReceiverAsyncClient there are batch and streaming operations.
* The batch version has a method peekMessageAt(long sequenceNumber) in order to move the receiver forward to that sequence number. All subsequent receive calls read messages after that sequenceNubmber. It is a seek()-like operation.
* For streams the receiveMessages() is used. But I can't see an option to control the startpoint here!? I would have expected either a receiveMessagesFrom(long sequenceNumber) or a method ServiceBusReceiverAsyncClient.seek(long sequenceNumber).receiveMessages()

The workaround to read all messages, read the metadata and skipping old messages seems overly expensive.

***Why is this not a Bug or a feature Request?***
Wanted to double check I am not missing anything. Feel free to convert it to an enhancement/bug per your discretion.

**Comment by joshfree** [comment]
Hi @wermerb thanks for filing this github issue.  Someone from the `Service Bus` team will follow up on your question, shortly.  @hemanttanwar can you please take a look?

**Comment by hemanttanwar** [comment]
@wernerdaehn Thank you for your question. You can use a `sequenceNumber` to peek a message but it would have no impact on `receiveMessages()` API.  The `receiveMessages()`   API always start from the first available message in the queue and every time client receive a message, client remove the message after processing using settlement API like `.complete(...)`. Once current message is removed from the queue, client will receive next available message.  
Because Queue is sequential message processing, you can not jump to another message using `sequenceNumber` in `receiveMessages()`  API.  The example in https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/README.md#examples  and https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-queues-topics-subscriptions#queues .

Please let us know if you need further assistance.  I will close this issue but please reopen if your questions is not answered.
