### ISSUE TITLE
[FEATURE REQ] Exclude some POMs from generated docs

### ISSUE THREAD

**Issue by nickzhums** [Azure/azure-sdk-for-java#14857]
Currently we scan every POM file in the service directory, for example, on **https://azure.github.io/azure-sdk-for-java/resourcemanager.html**

We can see that azure-resourcemanager-samples and azure-resourcemanager-tests are also shown on the list.

We would like to exclude those and don't auto-generate docs for certain jars

Thanks!

**Comment by weshaggard** [comment]
@scbedd when we start updating the doc indexing steps we should use the metadata reading code (https://github.com/Azure/azure-sdk-for-java/blob/master/eng/common/scripts/Package-Properties.ps1) that @chidozieononiwu  created and this should eliminate these from the list as those APIs only list things that are shipping in the ci.yml file as opposed to all the directories in the service folder.

**Comment by kurtzeborn** [comment]
@sima-zhu I think you already have a PR addressing what this issue is tracking.

CC: @scbedd

**Comment by sima-zhu** [comment]
@kurtzeborn Looking into this.
@chidozieononiwu is working on getting the right artifacts filtered out before upload to storage blobs. Will work with him to guarantee we take good care of java resource manger.

**Comment by sima-zhu** [comment]
Another way to achieve this is to skip github io step at artifact level

**Comment by weshaggard** [comment]
We cannot do this by skipping the github io step as the problem here is that some libraries aren't being built but are still showing up on the github.io index page. See https://github.com/Azure/azure-sdk-for-java/blob/master/eng/docgeneration/Generate-DocIndex.ps1#L36 when we build the list we just find all the directories and pom files, instead we should use the artifact list in the ci.yml file (which was my earlier comment) to filter the things we add to the index.

**Comment by sima-zhu** [comment]
The issue has been resolved by using blob storage as the truth of source whether to display the sdk artifact.
