### ISSUE TITLE
[QUERY] Batch complete

### ISSUE THREAD

**Issue by tomiasko** [Azure/azure-sdk-for-java#14905]
Is it possible to implement batch complete feature? When I receive batch of messages it seems to be a performance bottleneck that I cannot batch complete the messages. When I was searching for a solution i found that .NET library supports such a feature. Then I also found commented out method completeBatch inside IMessageReceiver. Are there any plans for implementing this feature?

**Comment by hemanttanwar** [comment]
@tomiasko Thank You for your query. Based on your Message, It seems like you are using this library https://mvnrepository.com/artifact/com.microsoft.azure/azure-servicebus . 

@yvgopal Please look into it. Is this feature available or on roadmap ?

**Comment by hemanttanwar** [comment]
@tomiasko Thank you for the query. And sorry for late response. We have considered this feature in past and there are many issues which could arise because of this. After considering many factors , we are not planning this feature at the moment.
Some of the issues we have considered are

1. Issues around if one of the lock is lost while completing batch of the messages.
2. On backend,  at amqp protocol level, we have to complete one message at a time.
3. any impact on resilience of the service.

I am adding @yvgopal  if I have missed out on any detail here.

Because of  above reasons, I will  be closing this issue.  Please let us know if you have any more comments.
