### ISSUE TITLE
Update target doc repo for Spring-Boot

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-java#15242]
Currently updates for `spring-*` packages are going to `Azure/azure-docs-sdk-java`.

This needs to be retarded to `MicrosoftDocs/azure-dev-docs`. 
Under [directory](https://github.com/MicrosoftDocs/azure-dev-docs/tree/master/articles/java/spring-framework): `articles/java/spring-framework`.

No CI updates for this package, only the readme updates.

**Comment by yiliuTo** [comment]
Thanks @scbedd , and the readmes to be relocated include:
- spring-integration-eventhubs,md
- spring-cloud-starter-azure-eventhubs.md
- spring-integration-storage-queue.md
- spring-cloud-azure-autoconfigure.md
- spring-cloud-azure-storage.md
- spring-starter-azure-cache.md
- spring-cloud-starter-azure-eventhubs-kafka.md
- spring-integration-servicebus.md
- spring-starter-azure-storage.md
- spring-cloud-starter-azure-servicebus.md
- spring-cloud-starter-azure-storage-queue.md
- spring-cloud-azure-servicebus-queue-stream-binder.md
- spring-cloud-azure-servicebus-stream-binder-core.md
- spring-cloud-azure-eventhubs-stream-binder.md
- spring-cloud-azure-context.md
- spring-cloud-azure-servicebus-topic-stream-binder.md
- azure-spring-boot-metrics-starter.md
- azure-servicebus-jms-spring-boot-starter.md
- azure-cosmosdb-spring-boot-starter.md
- azure-data-gremlin-spring-boot-starter.md
- azure-spring-boot-starter.md
- azure-active-directory-b2c-spring-boot-starter.md
- azure-spring-boot.md
- azure-keyvault-secrets-spring-boot-starter.md
- azure-active-directory-spring-boot-starter.md

Any problems about the target doc repo, please ping me. Thanks

**Comment by sima-zhu** [comment]
Taking a look.

Our current workflow is to update the azure-doc-sdk-java, create a PR and merge. Now we have to switch to the [repo](https://github.com/MicrosoftDocs/azure-dev-docs/tree/master/articles/java/spring-framework). If we want to automate within the pipeline, then we need to have configuration somewhere.

Proposals on configurations:
1. (Optimal) Have the configuration in ci.yml. 
1. Have regex to check the packages need to move. This is not that reliable if we do not have certain landmark.
Proposals on upload the readme file:
1. (Optimal)Have a new script like `update-docs-metadata` and using if switch on different config from ci.yml
1. Make changes on existing script `update-docs-metadata`. Very few thing we can share across.

All steps to achieve this:
1. Update the `update-docs-metadata` to retarget on new repo. Also, we do not have any adjustment like other package.
2. Remove all packages config from package.json.
3. Go to `MicrosoftDocs/azure-dev-docs` and update toc.yml manually.

**Comment by mitchdenny** [comment]
Question: Why is Azure Spring Boot different to our other packages in terms of documentation?

**Comment by sima-zhu** [comment]
> Question: Why is Azure Spring Boot different to our other packages in terms of documentation?

@mitchdenny Azure Spring Boot starter and cloud starter only contains the config code instead of API src code. [Example](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-cosmos)

The Doc.Ms has a step to fetch the API documentation from the maven source jar, which failed in this case. So spring team is trying to update readme only in Doc.Ms instead (No API doc as other repo).
E.g. https://review.docs.microsoft.com/en-us/java/api/overview/azure/spring-boot-starter-readme?view=azure-java-stable&branch=master

We currently support the automation process for updating their doc to our docs repo. However, they expect us to support both our docs repo and the repo in description.
Our docs repo: https://github.com/Azure/azure-docs-sdk-java
Another retarget repo: MicrosoftDocs/azure-dev-docs

**Comment by sima-zhu** [comment]
The task has been resolved. Will follow up with the task of adding configci instead of skip apc source code only.
