### ISSUE TITLE
ApplyAsync and CreateAsync should both return the same type

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-sdk-for-java#1572]
Right now ApplyAsync returns T while CreateAsync returns Indexable

**Comment by anuchandy** [comment]
We had some discussion about this - the idea was when applyAsync is invoked, it emit all updated and newly created resources. But implementing this requires dirty flag for the generated inners, so that when user call applyAsync on a top level resource, we should be able to identify the modified related resources and make api call to update them then emit it. Last time we decided to not do this because we wanted to keep generated inners state-less and thread safe.

**Comment by praries880** [comment]
@anuchandy @hovsepm can this issue be closed?
