### ISSUE TITLE
Non-public "setRequestTimeout" in "DirectConnectionConfig"

### ISSUE THREAD

**Issue by shirleyy0812** [Azure/azure-sdk-for-java#15733]
I have seen request timeout issue when calling [createDatabaseIfNotExists](https://github.com/Azure/azure-sdk-for-java/blob/475b50c0e884519e46babc95771ecc88accaf023/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/CosmosClient.java#L39) using `v4.2.0`. Looking through the code, the `requestTimeout` has [a default value of 5 seconds.](https://github.com/Azure/azure-sdk-for-java/blob/c548afc068451c8f24e503f24a369e7145091995/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/DirectConnectionConfig.java#L20) Since `setRequestTimeout` [is not a public method](https://github.com/Azure/azure-sdk-for-java/blob/c548afc068451c8f24e503f24a369e7145091995/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/DirectConnectionConfig.java#L217), we cannot change the value. 

A test on the same machine calling the same Cosmos account using `v4.0.0-preview.v2` shows it takes ~12 seconds for `createDatabaseIfNotExists` to return successful response. However, using this version means we cannot get any updates for new features or bug fixes.

I'm wondering what is the reason that `setRequestTimeout` is not public for `v4.0.0+` and is it possible to make is public or make the default value larger?

**Comment by joshfree** [comment]
Hi @shirleyy0812 thanks for posting this detailed question.  @kushagraThapar from the `Cosmos` SDK team will follow up

**Comment by kushagraThapar** [comment]
@shirleyy0812  - This change is intentional, as the requestTimeout you are talking about is strictly the timeout when request has reached the server and SDK is waiting for the response. 
Also, createDatabaseIfNotExists doesn't have the 5 second timeout, as that is a metadata call. For that we have default timeout of 60 seconds on HttpClient. 

Please upgrade to the latest version of azure-cosmos SDK - https://mvnrepository.com/artifact/com.azure/azure-cosmos
Create an issue if you are experiencing timeouts in your application with the latest version of the SDK.
