### ISSUE TITLE
CloudBlobClient should be able to use credentials from DefaultAzureCredential of azure identity

### ISSUE THREAD

**Issue by bloussou** [Azure/azure-sdk-for-java#15803]
**Problem**
In C# CloudBlobClient and CloudBlobContainerClient can be used with `Azure-identity` according to the [doc](https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-msi#net-code-example-create-a-block-blob). In java it is not possible to use it because only [StorageCredentials](https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.storage.blob.cloudblobclient.cloudblobclient?view=azure-java-legacy#com_microsoft_azure_storage_blob_CloudBlobClient_CloudBlobClient_final_StorageUri_StorageCredentials_) are supported.

**Solution**
I want to be able to use DefaultAzureCredential in the `azure-blob-storage` dependency to retrieve credentials and not only use the `Connection String`.

**Alternative found**
The only viable alternative I have found so far in java in the official documentation is to use Connection String.

**Additional context**
AWS and GCP are doing this and it avoid a lot of trouble dealing with credentials. `AmazonS3Client.builder().withCredentials` support the AwsCredentialChain and `StorageOptions.getDefaultInstance()` allows to get a `Storage` instance.

- [x] Description Added
- [x] Expected solution specified

**Comment by gapra-msft** [comment]
Hi @bloussou 

Thanks for reporting this issue. 

What version of the Java azure storage library are you using? From your terminology it sounds like you are using one of our older versions. 

The java azure-storage-blob library v12+ definitely does accept a DefaultAzureCredential  and can be used in conjunction with the azure-identity library.

**Comment by joshfree** [comment]
Hi @bloussou, from the documentation link you sent, it does appear that you're using an older version of the Azure Storage SDK for Java.  As @gapra-msft mentioned, if you upgrade to [version 12 of the Storage SDK](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/README.md), https://mvnrepository.com/artifact/com.azure/azure-storage-blob/12.0.0, you'll also be able to use `DefaultAzureCredential`.  Also any of the new Unified Azure SDK for Java will also work with `DefaultAzureCredential`.  You can tell these new Unified client libraries apart from the previous older version by the name starting with `com.azure` instead of `com.microsoft.azure`.

Please let us know if you need any additional info.

Thanks

**Comment by bloussou** [comment]
Hi @joshfree and @gapra-msft,
Thanks a lot for your quick answers. It helps me a lot and clarify the difference between `com.azure` and `com.microsoft.azure`. Maybe this [section](https://docs.microsoft.com/en-us/java/api/overview/azure/identity-readme?view=azure-java-stable#next-steps) of the doc should be updated in azure-identity. I will open a ticket.
Best
