### ISSUE TITLE
[BUG] Creating a BlobClientBuilder from an endpoint-url fails if the url has a port

### ISSUE THREAD

**Issue by RiederAlex** [Azure/azure-sdk-for-java#15827]
**Description**
Creating an BlobClient from an non-ip authority with a port is still detected as IpStyle and will therefore fail, as no `accountName` is set in the resulting BlobClient

```
String url = "https://xxxxx.blob.core.windows.net:443/....";
BlobClient blobClient = new BlobClientBuilder().endpoint(url).buildClient();
blobClient.uploadFromFile(file.getPath()); //Will fail, as no accountName set!
```
The actual bug is inside `ModelHelper.determineAuthorityIsIpStyle`, as it detects the IpStyle wrongly by simply checking for the existence of a port inside the URL.
Currently the workaround is to remove the port number from the URL.

**Expected behavior**
URLs with port can be used to create BlobClients

**Comment by RiederAlex** [comment]
@rickle-msft I'm using another MS Service called AppCenter, which provides me with an upload URL with the port already attached, so sadly also not a lot I can do about this on the other end.

**Comment by rickle-msft** [comment]
@RiederAlex Thank you for that information. Unfortunately the pattern of having a port attached to a url which uses a host name as in this case conflicts with a pattern we need to support for the emulator. Consequently our recommendation here needs to be that you strip the port number before passing in the url. This should hopefully be fairly manageable by using Java's URL type but you can let us know if you need any assistance there.

**Comment by RiederAlex** [comment]
@rickle-msft Ok I understand that and no worries, I can manage to strip the URL myself ;)
Thank you for your responses!

**Comment by mezpahlan** [comment]
Hi @rickle-msft there's another reason why I need to attach a port number. I use [MockWebserver](https://github.com/square/okhttp/tree/master/mockwebserver) to script server responses for testing purposes. I am unable to do this if I strip out the port. Here's how an example MockWebserver test would look like for some context:

1. Setup MockWebserver to listen to requests. It sets itself up to listen to `localhost` and a random port by default.
2. Configure your HTTP client to send requests to MockWebserver. A `BlobClient` configured with `OkHttpAsyncHttpClient` in this case.
3. Send request, exercising the logic of your app.
4. Capture and assert properties of the request in MockWebserver and send back canned responses for test purposes.

If I strip out the port, yes that works for the app but it makes testing really hard. In other words, how do I test my code whilst using a `BlobClient` without having to send real requests to real servers? I can do that nicely with MockWebserver but I am struggling with how to integrate that here.

**Comment by rickle-msft** [comment]
Hi, @mezpahlan. Two things:

The first is to use your existing workflow, but use IP-style endpoints. That is to say, your URL should be of the format: `https://127.0.0.1:<proxy port>/<account name>`. This does allow you to still attach a port number to your URL. 

To answer your broader question of how to test BlobClient without sending real requests, you could also consider using [Azurite](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite), which is a Storage emulator. You'll actually still have to use IpStyle URLs, but you might find some of the features of the emulator helpful, so I thought I'd mention it. 

Let me know if you have any more questions!

**Comment by mezpahlan** [comment]
Hi @rickle-msft thanks for the tips unfortunately I'm not able to get this to work. This is what I have at the moment:

I've configured a `BlobClient` like this:

```
BlobClientBuilder()
  .endpoint(workaroundAzureSdkForJava15827(httpUploadUrl)) // This strips the port as a workaround described in this issue
  .httpClient(okHttpAsyncHttpClientBuilder.build())
  .buildClient();
```

This lets me configure the BlobClient with OkHttp and thus use MockWebserver. I'm able to successfully send a request to MockWebserver and have it respond like this:

```
mockWebServer.enqueue(new MockResponse().setResponseCode(201)
  .setHeaders(Headers.of(
                "ETag", "0x8CB171BA9E94B0B",
                "Last-Modified", "1970-01-01T00:00:00",
                "Content-MD5", "sQqNsWTgdUEFt6mb5y4/5Q==",
                "x-ms-version-id", "1970-01-01T00:00:00"
            ))
  );
```

These are values taken from https://docs.microsoft.com/en-gb/rest/api/storageservices/put-blob#response.

This seems to make its way to `BlockBlobAsyncClient::uploadWithResponse` where it creates a `SimpleResponse`. After which it just hangs. After 60 seconds my test fails with `java.util.concurrent.ExecutionException: reactor.core.Exceptions$ReactiveException: java.net.SocketTimeoutException: timeout`

For some context the program I'm building using Java8 CompletableFutures so that I can compose various asynchronous tasks. I've set up the Blob upload to look like this:

```
 private CompletableFuture<UploadRequest> uploadSymbolsChunked(@Nonnull UploadRequest request, @Nonnull String symbolUploadUrl, @Nonnull File file) {       
final CompletableFuture<UploadRequest> future = new CompletableFuture<>();

        try {
            factory.createBlobUploadService(symbolUploadUrl).uploadFromFile(file.getPath(), true); // I never move past this point.
            future.complete(request);
        } catch (UncheckedIOException e) {
            future.completeExceptionally(exception);
        }
   return future;
}
```

Many thanks for the assistance and if you can suggest anything here that would be much appreciated.

**Comment by rickle-msft** [comment]
@mezpahlan Can you verify that the mockWebServer actually received the outgoing request and sent the response? That will tell us if there's still an issue in getting the request out the door or if something about the mocked response needs to change to allow the response to flow back upstream

**Comment by mezpahlan** [comment]
This is log from MockWebserver:

> Nov 10, 2020 5:07:23 PM okhttp3.internal.platform.Platform log
INFO: --> PUT http://localhost:60583/perry/casey/xiola
Nov 10, 2020 5:07:23 PM okhttp3.internal.platform.Platform log
INFO: x-ms-version: 2019-12-12
Nov 10, 2020 5:07:23 PM okhttp3.internal.platform.Platform log
INFO: User-Agent: azsdk-java-azure-storage-blob/12.8.0 (1.8.0_252; Linux; 5.4.0-52-generic)
Nov 10, 2020 5:07:23 PM okhttp3.internal.platform.Platform log
INFO: Content-Length: 41
Nov 10, 2020 5:07:23 PM okhttp3.internal.platform.Platform log
INFO: Date: Tue, 10 Nov 2020 17:07:23 GMT
Nov 10, 2020 5:07:23 PM okhttp3.internal.platform.Platform log
INFO: x-ms-client-request-id: 6a4ad2f3-1103-4b90-ba2d-543d5fd8945a
Nov 10, 2020 5:07:23 PM okhttp3.internal.platform.Platform log
INFO: Content-Type: application/octet-stream
Nov 10, 2020 5:07:23 PM okhttp3.internal.platform.Platform log
INFO: x-ms-blob-type: BlockBlob
Nov 10, 2020 5:07:23 PM okhttp3.internal.platform.Platform log
INFO: --> END PUT
Nov 10, 2020 5:07:23 PM okhttp3.internal.platform.Platform log
INFO: <-- 201 OK http://localhost:60583/perry/casey/xiola (3ms)
Nov 10, 2020 5:07:23 PM okhttp3.internal.platform.Platform log
INFO: ETag: 0x8CB171BA9E94B0B
Nov 10, 2020 5:07:23 PM okhttp3.internal.platform.Platform log
INFO: Last-Modified: 1970-01-01T00:00:00
Nov 10, 2020 5:07:23 PM okhttp3.internal.platform.Platform log
INFO: Content-MD5: sQqNsWTgdUEFt6mb5y4/5Q==
Nov 10, 2020 5:07:23 PM okhttp3.internal.platform.Platform log
INFO: x-ms-version-id: 1970-01-01T00:00:00
Nov 10, 2020 5:07:23 PM okhttp3.internal.platform.Platform log
INFO: <-- END HTTP

In my tests I configure a JUnit test rule that starts and stops MockWebserver automatically for each test method. Once the rule is running this is how I configure my tests to send to the running instance

```
@Rule
public MockWebServer mockWebServer = new MockWebServer();

...

@Test
public void testSomethingUsingMockWebserver() {
  // Given
  String urlForTesting = mockWebServer.url("perry/casey/xiola").toString();

  // When
  Result result = foo.doSomethingThatEventuallySendsARequestTo(urlForTesting);
 
  // Then
  assertThat(result).isAwesome();
}
```

**Comment by rickle-msft** [comment]
Ok. So it seems the server is successfully receiving and sending a request/response. So the first problem of properly constructing the URL is resolved. That means something is getting lost as the response returns to the client. Would you be able to crack open the blob dependency and set a breakpoint in common.policy.scrubEtagPolicy#scrubEtagHeader? This is the first piece of code that should get run on receiving a response, so if we can confirm this code is getting hit, then the client is indeed receiving the response. 

Alternatively, if you're more comfortable enabling logging in your tests, that could work as well

**Comment by mezpahlan** [comment]
I can confirm that `ScrubEtagPolicy::scrubETagHeader` is successfully being hit. For the test above there is effectively no _scrubbing_ being performed because there are no quote marks (") to remove - 0x8CB171BA9E94B0B. But that bit of the code is indeed being executed.

**Comment by rickle-msft** [comment]
Ok great. So we can confirm the client is actually getting the response. I somewhat suspect that there's probably an issue with the conversion to CompletableFutures. Are you able to run the test using the sync client or blocking directly on Reactor's Mono object rather than using Futures just to try diagnosing that?

**Comment by mezpahlan** [comment]
Yes, I think you're probably right about the conversion to CompletableFuture. I'm happy to give that a go but now you're stretching my knowledge.

1. Is there an OkHttpSyncHttpClientBuilder somewhere? I only see the Async one with the azure-core-http-okhttp artefact. If not how do I create one?
2. Same question with how to block on Reactor's Mono object. Apologies I'm more used to working with RxJava than Reactor and whilst some bits look similar a lot of it does not.

Many thanks for helping again :+1:

**Comment by rickle-msft** [comment]
No worries! My knowledge on Futures is similarly limited :). 

1. There's only an async builder for the http clients because the sync one uses that anyway. So you really just need to be building a sync blob client and using those apis directly rather than passing them to a completable future. 
2. Blocking should just be a `.block` call. 

Another option here is there's a [`toFuture`](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#toFuture--) method on Mono that I think you can use more safely to convert. That might also be worth a shot

**Comment by mezpahlan** [comment]
I tried a few of those options but no dice :cry: . 

I then started to look closer at the code in `OkHttpAsyncHttpClient::getBody` and noticed that the stream was never being closed. On a whim I started to google issues to do with empty bodies being returned from MockWebserver and came across this issue: https://github.com/square/okhttp/issues/6281#issuecomment-698667784. Whilst not totally the same I decided to try that workaround so now my MockWebserver response looks like this:

```
mockWebServer.enqueue(new MockResponse().setResponseCode(201)
  .setHeaders(Headers.of(
    "ETag", "0x8CB171BA9E94B0B",
    "Last-Modified", "1970-01-01T00:00:00",
    "Content-MD5", "sQqNsWTgdUEFt6mb5y4/5Q==",
    "x-ms-version-id", "1970-01-01T00:00:00"
  ))
  .setChunkedBody("", 1) // This line here is the workaround.
```
When I did that I started to notice this error from the Jackson deserialisation of the headers.
`Cannot construct instance of `com.azure.core.util.DateTimeRfc1123`, problem: Text '1970-01-01T00:00:00' could not be parsed at index 4`. So I changed this to `Thu, 01 Jan 1970 00:00:00 GMT` and reran the code.

Better.... but still we want more!

I then started to get null pointer exceptions in the mapper for `BlockBlobAsyncClient::uploadWithResponse(BlockBlobSimpleUploadOptions, Context)`. What this turned out to be was that I forgot to add the header `x-ms-request-server-encrypted`. What was interesting about this is that the exception said `null cannot be unboxed` (or something similar). It was a failure in trying to create a `BlockBlobItem`:

```
BlockBlobItem item = new BlockBlobItem(hd.getETag(), hd.getLastModified(), hd.getContentMD5(),
                    hd.isServerEncrypted(), hd.getEncryptionKeySha256(), hd.getEncryptionScope(),
                    hd.getVersionId());
```

Specifically `hd.isServerEncrypted()`. Now I know that my usecase is a very hacky one and I totally understand that we've veered wildly off course from the original issue here but I was expecting this to return `false` if the header was not present. _Maybe_ that's something to look at...... maybe.

Anyways, my MockWebserver response now looks like this:

```
mockWebServer.enqueue(new MockResponse().setResponseCode(201)
  .setHeaders(Headers.of(
    "ETag", "0x8CB171BA9E94B0B",
    "Last-Modified", "Thu, 01 Jan 1970 00:00:00 GMT",
    "Content-MD5", "sQqNsWTgdUEFt6mb5y4/5Q==",
    "x-ms-request-server-encrypted", "false",
    "x-ms-version-id", "Thu, 01 Jan 1970 00:00:00 GMT"
  ))
  .setChunkedBody("", 1)
```

And success! It works :smiley_cat: . For completeness, in the end I didn't have to change the way I create the `BlobClient` - I still use the `OkHttpAsyncClientBuilder`. I didn't need to modify any of the other CompletableFuture code (although I would love to get rid of it!!).

Many thanks again @rickle-msft, you've been fabulous!

**Comment by rickle-msft** [comment]
@mezpahlan Thank you so much for the thorough account of your debugging steps! I am sure they will be helpful for others trying to mock out the service! You certainly found some interesting details of this interaction, and I'd say your debugging was what was fabulous as you did pretty much everything yourself :)

Happy to see you're unblocked and let us know if we can be of further support!
