### ISSUE TITLE
Suggestion - consistency in upload operation for overwrite

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#16193]
We were using old microsoft SDK `azure-storage:5.5.0` and exploring latest SDK `azure-storage-blob:12.8.0` now as part of migration.

While exploring, i got to know inconsistence behaviour of upload operation in terms of overwrite. Please find below method details. By default - Some upload operations allowed to overrite blob, but some not.

As per user point of view, it should be consistence common behaviour for all upload opertions. Please suggest your opinion on this.

1. `upload(InputStream data, long length)`  - default **not allowed** to overwrite
2.  `uploadWithResponse(InputStream data, long length, ParallelTransferOptions parallelTransferOptions,
        BlobHttpHeaders headers, Map<String, String> metadata, AccessTier tier, BlobRequestConditions requestConditions,
        Duration timeout, Context context)` - default **allowed** to overwrite
3. `uploadFromFile(String filePath)`  --> default **not allowed** to overwrite
4. `uploadFromFileWithResponse(BlobUploadFromFileOptions options, Duration timeout, Context context) ` --> default **allowed** to overwrite

**Comment by gapra-msft** [comment]
Hi @abhikt48 

Thanks for your post. 

As per the service, the default behavior of upload is to overwrite existing data. Since this behavior is unsafe (and could cause customers to accidentally blow away their data), we made a decision to handle unsafe APIs in the following way

1. Min overload `upload(InputStream data, long length)` - safe for customers who don't want to use optional behavior.
2. Variation of min overload  `upload(InputStream data, long length, boolean overwrite)` - customers can specify whether or not they overwrite.
3. Max overload  `uploadWithResponse(...)` -  customers can specify whether or not they overwrite via BlobRequestConditions.setIfNoneMatch("*");

Our main goal was to provide safety to customers using the simplest APIs but also allow customers to specify their desired service behavior in the max optional overloads.
