### ISSUE TITLE
[QUERY] how can we encrypt entity with new Table SDK ?

### ISSUE THREAD

**Issue by abhikt48** [Azure/azure-sdk-for-java#16295]
We have encrypted entity with OLD sdks. Please find below sample code. 

DO we have any option to encrypt entity with new SDK `azure-data-tables:12.0.0-beta.2` ? If yes - could you please provide any samples.

**code with OLD SDK**
```
TableRequestOptions tableRequestOptions = new TableRequestOptions();
tableRequestOptions.setEncryptionPolicy(<##>);
tableRequestOptions.setEncryptionResolver(<##>);
cloudTable.execute(insert, tableRequestOptions, null);
```

**Comment by bsiegel** [comment]
Hi @abhikt48, we definitely intend to support entity encryption with the new Tables library. Based on our current velocity I anticipate we should be able to get this in for our initial GA release (12.0.0). I've captured your request as item #16316 - feel free to follow along with that issue to see progress.

**Comment by bsiegel** [comment]
I'm going to close this issue out for now, we're tracking the work to implement this feature in the issue linked above. Thank you so much for your request!

**Comment by rad-app** [comment]
Is there any update on this issue? In latest java SDK for Azure tables how the encryption/decryption of table entities is possible?

**Comment by MillerMatias** [comment]
@bsiegel Hi! Any updates on this? 

The Microsoft.WindowsAzure.Storage.Table is now marked as deprecated and we should use the Azure.Data.Tables but this new package does not support encryption of table entities like the deprecated package. Is support for table entity encryption/decryption now available in the Azure.Data.Tables package? It's been a while since its released.
