### ISSUE TITLE
[Tables] Add support for client-side encryption of table entities

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-java#16316]
We need to determine the best way to add this functionality to the Track 2 public API.

**Comment by abhikt48** [comment]
Hi @bsiegel  - Thanks for opening this ticket. Could you below use cases as well while providing feature fo encryption

1. Encrypt all entity
2. Encrypt partial entity (Only sensitive data)

**Comment by bsiegel** [comment]
Absolutely - the intention is for the new v12 library would be to cover the same use cases as the previous library, but with a more consistent and idiomatic API. Thank you so much for letting us know your requirements, it REALLY helps in planning and prioritizing feature work like this!

**Comment by rjoshi12** [comment]
Hi,
With latest java sdk for Azure Tables, can someone please provide the sample for encryption/decryption for table entities?
Thanks

**Comment by MillerMatias** [comment]
@bsiegel Hi! Any updates on this? 

The Microsoft.WindowsAzure.Storage.Table is now marked as deprecated and we should use the Azure.Data.Tables but this new package does not support encryption of table entities like the deprecated package. Is support for table entity encryption/decryption now available in the Azure.Data.Tables package? It's been a while since its released.

**Comment by jairmyree** [comment]
With support for this feature not planned, I will close out this issue.
