### ISSUE TITLE
[BUG] Byte array property not deserialized as byte array in Azure cStorage Table entities

### ISSUE THREAD

**Issue by gdurandrexel** [Azure/azure-sdk-for-java#16433]
When adding a byte array as a property of a TableEntity, it is serialized as a base64 string. But when deserialized, it is still a base64 string and not a byte array. I can also see that the odata type is not specified for this property. I suppose Edm.Binary in the response would be required to allow proper deserialization.

How I set the property:
```
val entity = TableEntity("1", datagram.timestamp.toEpochMilli().toString())
	.addProperty("type", datagram.type)
	.addProperty("sourceAddress", datagram.sourceAddress)
	.addProperty("destinationAddress", datagram.destinationAddress)
	.addProperty("rawData", datagram.rawData) // this is the byte array as kotlin.kotlin_builtins.ByteArray

createEntity(entity).awaitFirstOrNull()
```

The deserialized property, when listing table entities: https://ibb.co/c6MW0Ks
```
val client = this.tableServiceClient.getTableClient(tableName)
client.listEntities()
```
This happens whether I use `getTableClient()` or the `TableClientBuilder`.

- OS: Windows
- IDE : IntelliJ IDEA
- kotlin 1.4.10
- Vert.x 4.0.Beta3
- azure-data-tables-12.0.0-beta.2

**Comment by bsiegel** [comment]
Hi @gdurandrexel, I think I know what's going on here. The client automatically understands properties of type `byte[]` or `Byte[]` and will add the correct Edm.Binary type to the property. However it doesn't know about other binary types, such as e.g. `List<byte>` or Kotlin's `ByteArray`. I believe the reason that the object is still being serialized correctly to a Base64 string is because the Jackson serializer is able to handle a much wider range of input types than we currently cover in the code that adds the type tag annotations.

There are a couple things you could try - first, you could simply convert the type to a JVM `byte[]` before adding it to the properties. Another option would be to manually add the OData type tag:

```java
.addProperty("rawData@odata.type", "Edm.Binary")
```

Can you let me know if either or both of those workarounds solves the issue? In the meantime I will investigate how we can better support these types which are convertible to, but are not themselves, one of the know types for which we add type tags.

**Comment by bsiegel** [comment]
I've filed #16458 to investigate how we can make the scenario work for a broader set of types beyond the small set we define today.

**Comment by gdurandrexel** [comment]
Hi @bsiegel,

I made a mistake when reporting the bug: I ran the deserialization on data collected using `TableServiceClient.getTableClient(tableName)` which does not have the proper serializer, and thus did not set the odata type.
When collected with `TableClientBuilder()` the data type is properly set to Edm.Binary and deserialized as a byte array.

I think you can close the issue.
Sorry for the inconvenience.

**Comment by bsiegel** [comment]
Thanks for the info, that's helpful because I had been reading a bit about Kotlin and in fact it seems like `ByteArray` is essentially just an alias for the JVM  `byte[]` type. There are probably other types that we should support though, and/or we should make it easier for users to supply types that are convertible to the types we know about. I'll close this issue, but I think the one I filed above I will keep open to investigate how to make these two scenarios easier.
