### ISSUE TITLE
MSI Token provider does not work from AppServices -works from VMs.

### ISSUE THREAD

**Issue by giventocode** [Azure/azure-sdk-for-java#16923]
The current SDK 3.4, does not include [ManagedServiceIdentityTokenProvider](https://github.com/Azure/azure-service-bus-java/blob/650ee00905a68e03ffd69a0606064ed33180c2eb/azure-servicebus/src/main/java/com/microsoft/azure/servicebus/security/ManagedServiceIdentityTokenProvider.java) from the previous implementation. Instead, the SDK has the [ManagedIdentityTokenProvider](https://github.com/conniey/azure-sdk-for-java/blob/feature/session-receiver/sdk/servicebus/microsoft-azure-servicebus/src/main/java/com/microsoft/azure/servicebus/security/ManagedIdentityTokenProvider.java), which only works on VMs.

**Comment by yvgopal** [comment]
1. The name change was just a rename.
2. Functionality was changed to rely upon Azure Authentiction Library, instead of Service Bus SDK getting MSI tokens from a hardcoded URL. In the process, it looks like full functionality provided by the old way was not provided.

It is an oversight as we didn't test it outside of Azure VMs. But the new Service Bus SDK 'Azure-ServiceBus-Messaging' must be up to date with all authentication mechanisms. Please switch to the new SDK if you can.
