### ISSUE TITLE
Azure VM update changes the resource group name of the VM to all uppercase

### ISSUE THREAD

**Issue by esara** [Azure/azure-sdk-for-java#1708]
When changing the size of a VM using the java sdk:
        VirtualMachine vm = client.virtualMachines().getById(vmId);
        vm.update().withSize(sizeName).apply();

The VM object returned contains an UPPERCASE resource group name, because it gets the resource group name from:
https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/models/implementation/GroupableResourceImpl.java#L69

When this object is sent back with the withSize() method, the resource group name of the VM is unintentionally changed.
https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineImpl.java#L670

While I understand that the resource group names are case insensitive in Azure, the java sdk should be preserving the case.

**Comment by anuchandy** [comment]
SDK return the ids as it received from the service, the logic that extract resource group name from the id is [here](https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/ResourceId.java#L38) and [here](https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/ResourceId.java#L87), we are not changing the case of id here, we preserve the case.

**Comment by esara** [comment]
I understand that the SDK itself is not changing the case, but since the resourceId is converted to upppercase by the service and the vm.update sends it back as the same (even if the resourceId for the VM was originally mixed case), it inadvertently gets changed from its original case for each VM that is updated using the SDK. I suggest either one of two options to resolve this:

1) We either change the way we acquire the resourceId for the VM from the VM's resource information to maintain the case, when the VM is updated
2) Or we change the service, so that the resourceId is returned case-preserving and we can keep the SDK as it is (retrieve and update the resourceId from any place)

Endre

**Comment by anuchandy** [comment]
I can think of following two flows from the client side - 

1. VM created with `lower case` resource group name
2. A VM GET returns payload with `upper case` resource group name in the ID
3. VM PUT request payload contains ID with `upper case` resource group name
 
OR 

1. VM created with `lower case` resource group name
2. A VM GET returns payload with `lower case` resource group name in the ID
3. VM PUT request payload contains ID with `lower case` resource group name, but final response for PUT contains id with `upper case` resource group name.
 
In both cases for step3, SDK is not doing any special handling of the ID that changes the case, in fact as per ARM contract SDK is not suppose to change the ID, you can see here https://github.com/Azure/autorest-clientruntime-for-java/blob/master/azure-client-runtime/src/main/java/com/microsoft/azure/Resource.java that ID is not something SDK can set (there is no wither exposed due to contract).

Now regarding the options you suggested, Option 1 cannot be implemented in a consistent way because the vm can be updated from other clients (cli, portal, other sdks, raw API) as well. In this case java sdk has no idea what was the original case of the id.

This is something that should be handled in the service side. I would suggest  you opening azure ticket so that service team can prioritize and track this. I will also contact devs in compute team and make sure they are aware of the issue.

**Comment by anuchandy** [comment]
@ravbhatnagar (From ARM team) there are couple of customers reported similar issue. Is there a ARM guideline regarding casing of resource id?

**Comment by anuchandy** [comment]
//cc @ravbhatnagar 

Checked with the ARM team, their guideline for the RPs is "PR should preserve case and evaluate insensitively". @esara closing this as this is a service issue & I will let compute team know this. Please open a azure ticket https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request.

**Comment by anuchandy** [comment]
Keeping this open in case @esara has more comment

**Comment by esara** [comment]
Open a support ticket with Azure at
https://portal.azure.com/#resource/subscriptions/629bda66-cabf-4fae-90f2-f7ff29498bc6/providers/microsoft.support/supporttickets/117081716201872

**Comment by anuchandy** [comment]
@esara thanks. We communicated this to compute service team and they also opened an issue in their system. I will request them to link that issue with your support ticket.

**Comment by anuchandy** [comment]
Closing this as service team (CRP) is now tracking this in their system.
