### ISSUE TITLE
How launch multiple VMs

### ISSUE THREAD

**Issue by pditommaso** [Azure/azure-sdk-for-java#1726]
Newbie question: how to launch multiple VM instances? The doc seems suggesting to use a scale set, but that's overkill (also because I would like to spawn a different number of instances for different types, this means I should create many scale set .. ). 

Ideally it should be possible to request a certain number of instances given a VM name.

**Comment by martinsawicki** [comment]
for example see https://github.com/Azure/azure-sdk-for-java/blob/master/azure-samples/src/main/java/com/microsoft/azure/management/compute/samples/CreateVirtualMachinesInParallel.java

or others under https://github.com/Azure/azure-sdk-for-java/tree/master/azure-samples/src/main/java/com/microsoft/azure/management/compute/samples

The main idea is that you get to define each of your VMs separately (but don't call `.create()` on each of them as that will be too slow), put them all in a collection of "Creatables" instead (vmDefinitions), and then use `VirtualMachines.create(vmDefinitions)` to create them all in parallel. Dozens of arbitrary defined VMs can be created this way in about 2 minutes or less.

**Comment by pditommaso** [comment]
Thanks for your reply. Would the creation time remain in that range for a larger number of instances (let's say 100) ?

**Comment by martinsawicki** [comment]
The creation is done in parallel, so the time it takes should be independent of the number of VMs and only dependent on how long the longest of the individual VM creations happens to be. Usually, a given Linux VM takes about 90 sec to create on average, but this can vary somewhat randomly, and of course the more VMs that are being created, the higher the probability of running into a "bad apple" which for some random reason takes much longer, or fails altogether.

Also, eventually, since it is the client side SDK that is orchestrating and monitoring the creation of all those VMs under the hood, a problem that might be occasionally encountered is that the Azure service API may start throttling the calls to Azure if too many are happening within some short time period. But that is hard to predict and there are some mechanisms in the SDK which automatically slow things down when throttling is detected.

Btw - There is a test [here](https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-compute/src/test/java/com/microsoft/azure/management/compute/VirtualMachineRelatedResourcesDeletionTests.java#L55) which shows how the creation of many VMs in parallel could be achieved, including a graceful handling of failed VMs by deleting all the resources that were already created which are related to the failed VM.

**Comment by pditommaso** [comment]
Interesting, thanks for the detailed answer. More than quick launching I'm interested to understand if this is the proper way to spawn many instances programmatically and your answer seems to confirm that. I will try to make some tests following the examples you provided. Thanks.
