### ISSUE TITLE
Java - Detect API changes before they're released

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#17333]

**Comment by samvaity** [comment]
>API breaks
While Python does validation of new azure-core releases against older versions of released libraries that depend on it, we believe this is only necessary because we lack API static analysis tools for Python. For Java, .NET, and JS, we use RevApi, ApiCompat, and ExtractApi respectively to detect API breaking changes as they are introduced and block builds with them. So Python ensures backwards compatibility through validating that there are no breaks while Java, .NET, and JS do so through prevention of breaks. We believe both are acceptable approaches.


As a result of this discussion,  we’ll not pursue the back-compat testing investigations as part of MQ for Java.

cc: @kurtzeborn
