### ISSUE TITLE
cannot list web apps by resource group sometimes

### ISSUE THREAD

**Issue by juniwang** [Azure/azure-sdk-for-java#1762]
I have a web app(on Linux) `jw-webapp-linux-node-01` created and in resource group with a same name `jw-webapp-linux-node-01`. I can find it on azure port and azure cli. But I cannot get found it through java SDK. My azure sdk version is `1.1.0`.

Azure CLI:
![2017-06-15_1218](https://user-images.githubusercontent.com/8814383/27165207-f59befde-51c4-11e7-9f03-e6869085a2bf.png)

Debug window in IDEA
![2017-06-15_1219](https://user-images.githubusercontent.com/8814383/27165206-f594b354-51c4-11e7-8095-361a8cef987b.png)

But that is not always the case, since my another webapp `jw-webapp-linux-tomcat-04` CAN be listed through SDK. I cannot tell what's exactly different between the two webapps. Per my memory the only difference it the chosen docker image. One is built-in `NODE|4.5` and the another is a custom image from docker hub `junbowang/tomcat8-sshd:599`.

**Comment by jianghaolu** [comment]
Hi @juniwang ,

This is part of the issue that was being tracked - web app team changed the kind of linux web apps from “app” to “app;linux” and it broke us. 

At this moment, you can work around by calling
```java
azureClient.webApps().inner().listByResourceGroup(rgName);
```

**Comment by Eskibear** [comment]
Hi @jianghaolu ,
To list linux web apps, I've been using the above `azureClient.webApps().inner().list()`, and it returns a list of `SiteInner` instead of `WebApp`. It prevents me using some APIs like `WebApp.stop()`, and I don't know how to perform type cast  between them.
Currently my workaround method is:
```
WebApp app = azureClient.webApps().getById(siteInner.id());
```
It does return an instance of type `WebApp`, but has performance issue if I cast each of `SiteInner` instance in the list.

Is there any API can work now? Or when will you include linux web apps directly in `azureClient.webApps().list()` API?


p.s.
the `kind` of linux web apps has been `app,linux` for weeks, in case of unawareness.
