### ISSUE TITLE
[BUG] -  NullPointerException occurs in Save method when id is specified 

### ISSUE THREAD

**Issue by apescione** [Azure/azure-sdk-for-java#17724]
In case you want to set id for a new item and it is set to perform OptimisticLock on delete and update (@Version on _etag). 

The NullPointerException  occurs at the line https://github.com/Azure/azure-sdk-for-java/blob/255517749b4bc452ba55cebfc09190582706b8e7/sdk/cosmos/azure-spring-data-cosmos/src/main/java/com/azure/spring/data/cosmos/core/CosmosTemplate.java#L849

because it requires an "_etag" JsonNode valued that in case of insert it doesn't exist. If an empty value, instead of a null value is provided, everything works fine.

To reproduce it, it's  enough to set an "id" in a new POJO that has  @version on _etag attribute and save it.

```
 private void applyVersioning(Class<?> domainType,
                                 JsonNode jsonNode,
                                 CosmosItemRequestOptions options) {
        CosmosEntityInformation<?, ?> entityInformation = CosmosEntityInformation.getInstance(domainType);
        if (entityInformation.isVersioned()) {
            options.setIfMatchETag(jsonNode.get(Constants.ETAG_PROPERTY_DEFAULT_NAME).asText());
        }
    }
```

**Expected behavior**
The item is created a new _etag value is returned.

**Additional context**
I've not tested yet, but probably, the bug is present also on the reactive template

https://github.com/Azure/azure-sdk-for-java/blob/255517749b4bc452ba55cebfc09190582706b8e7/sdk/cosmos/azure-spring-data-cosmos/src/main/java/com/azure/spring/data/cosmos/core/ReactiveCosmosTemplate.java#L711

**Comment by kushagraThapar** [comment]
@mbhaskar - please take a look at this.

**Comment by Blackbaud-MikeLueders** [comment]
@kushagraThapar I don't know when this was fixed but it doesn't appear to currently be an issue.  `com.azure.spring.data.cosmos.core.CosmosTemplateIT#testUpsertNewDocument` tests this exact scenario by calling update directly on the CosmosTemplate.  Other tests like `com.azure.spring.data.cosmos.repository.integration.AuditableIT#testInsertShouldSetAuditableEntries` use the Repository rather than CosmosTemplate directly to insert @Version'd entities while setting their id.

I assume the NPE was coming from `jsonNode.get(Constants.ETAG_PROPERTY_DEFAULT_NAME)` but this is returning a NullNode instance.  

@apescione are you able to reproduce this with the current version of the library?  if you could reproduce with a simple project, that would be helpful.

**Comment by kushagraThapar** [comment]
I guess we can close this issue, as it has been fixed. @apescione - please close the issue if this is no longer happening.

**Comment by gpinolo** [comment]
The issue occour when domain type is annotated with @JsonInclude(JsonInclude.Include.NON_NULL)
