### ISSUE TITLE
[BUG] Get Certificate for specific version not return policy property

### ISSUE THREAD

**Issue by zhoufenqin** [Azure/azure-sdk-for-java#17747]
**Describe the bug**
When I use RestApi or com.microsoft.azure:azure-keyvault SDK to get a certificate with a specific version, then the policy property won't return, but if I request without a specific version, then the policy property will return, is it by design? But I don't get the description from the [document](https://docs.microsoft.com/en-us/rest/api/keyvault/getcertificate/getcertificate#certificatepolicy).
here is the RestApi result, SDK result is same.
![image](https://user-images.githubusercontent.com/8765864/99926964-7d861300-2d7e-11eb-9e59-e8c79685b5cf.png)
![image](https://user-images.githubusercontent.com/8765864/99926995-98588780-2d7e-11eb-9b9a-0b1e1ea8dd05.png)

***Exception or Stack Trace***
Return policy property when I get the specific version certification

the policy value in certificateBundle is null

***Code Snippet***
**To Reproduce**
    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure-keyvault</artifactId>
      <version>1.2.4</version>
    </dependency>
```
CertificateBundle certificateBundle = keyVaultClient
                .getCertificate(vaultBaseUrl, certificateName, certVersion);
            if (certificateBundle == null) {
                throw new CertificateException(String.format("Cannot find certificate, certificate name is %s, "
                    + "url is %s, please check if the certificate exists.", certificateName, vaultBaseUrl));
            }
```
**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - OS: windows 10
 - IDE : Intellij
 - com.microsoft.azure:azure-keyvault:1.2.4

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by zhoufenqin** [comment]
@g2vinay @vcolin7 Can you help to check the problem?

**Comment by vcolin7** [comment]
Hi @zhoufenqin, thanks for creating this issue, I will look into it :)

**Comment by zhoufenqin** [comment]
> Hi @zhoufenqin, thanks for creating this issue, I will look into it :)

Hi @vcolin7 thanks, Is it a bug? is so, we can temporarily solve the problem by getting the policy directly using ` keyVaultClient.getCertificatePolicy(vaultBaseUrl, certificateName)` in our project, because we need to fix it ASAP, when you fix it, we can upgrade the SDK

**Comment by vcolin7** [comment]
Hi again,

I want to preface this by suggesting you upgrade to the latest versions (Track 2) of our Azure Key Vault SDK offering:

- [Azure Key Vault Certificates](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-certificates)
- [Azure Key Vault Keys](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-keys)
- [Azure Key Vault Secrets](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-secrets)

We still support Track 1 SDKs but we have made a lot of improvements for Track 2 to provide for a better development experience, it's also is where most of our development happens.

Taking a look at the Track 2 Key Vault Certificates SDK, I found that the [`getCertificate`](https://github.com/Azure/azure-sdk-for-java/blob/f59534c27ee2339a4b66f41974ac9cc9783a9215/sdk/keyvault/azure-security-keyvault-certificates/src/main/java/com/azure/security/keyvault/certificates/CertificateClient.java#L195) operation returns a [`KeyVaultCertificateWithPolicy`](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/keyvault/azure-security-keyvault-certificates/src/main/java/com/azure/security/keyvault/certificates/models/KeyVaultCertificateWithPolicy.java), whereas the [`getCertificateVersion`](https://github.com/Azure/azure-sdk-for-java/blob/f59534c27ee2339a4b66f41974ac9cc9783a9215/sdk/keyvault/azure-security-keyvault-certificates/src/main/java/com/azure/security/keyvault/certificates/CertificateClient.java#L253) operation returns [`KeyVaultCertificate`](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/keyvault/azure-security-keyvault-certificates/src/main/java/com/azure/security/keyvault/certificates/models/KeyVaultCertificate.java). Adding this to what you found by directly calling the REST API makes me think this is the service's expected behavior.

Additionally, from what I can tell `getCertificatePolicy` in both the Track 1 and Track 2 SDKs will return the policy of the latest version of the certificate, because it does not accept a certificate version as an input, making it as effective as `getCertificate` for that matter.

Please correct me if I'm wrong @g2vinay, @heaths.

**Comment by zhoufenqin** [comment]
@vcolin7 Thank you for your response, so I think it's by design because the policy only relates to the latest version of the certificate. So when we get a certificate by version, it cannot return the latest version policy directly.

**Comment by heaths** [comment]
The policy basically represents the desired policy for the *next* certificate created. You can set a new policy then create a new certificate with that policy which would then be represented on the newly created (latest) certificate.

**Comment by zhoufenqin** [comment]
Hi @heaths, thank you for your response, I misunderstand the `policy` before, I see [the key vault certificate doc](https://docs.microsoft.com/en-us/rest/api/keyvault/) and doesn't find an API that will return the `subject`/`issue` info when I require a certificate by version.
Now I decode the `csr` to get the info I want.
If we do not support the function, I can close the issue

**Comment by heaths** [comment]
I'll let the service team comment (@RandalliLama @jlichwa) but given the policy describes what you want for the next certificate, I don't think there's value added to returning this with previous versions. It would also be a breaking change for clients that don't strictly adhere to JSON parsing rules (i.e. adding a property could be breaking if a client isn't expecting it and errs).

**Comment by sebansal** [comment]
Heath is right about policy.
For getting more info about the certificate, @zhoufenqin you may use `getcertificateversions`
That will return the thumbprint. 
https://docs.microsoft.com/en-us/rest/api/keyvault/getcertificateversions/getcertificateversions

For extracting information from cer file, you may need to use other mechanisms like openssl
