### ISSUE TITLE
[BUG] Azure Key Vault Secret client library SecretClient.getSecret call hangs if processed by more than 11 threads

### ISSUE THREAD

**Issue by usmansaleem** [Azure/azure-sdk-for-java#17894]
**Describe the bug**
`com.azure.security.keyvault.secrets.SecretClient.getSecret` hangs if processed by more than 11 threads in parallel.

***Exception or Stack Trace***
N/A

**To Reproduce**
Call `getSecret` from more than 11 threads. For simplicity, `list.parallelStream` can be used.

***Code Snippet***
~~~
package azure_keyvault_secret;

import com.azure.core.credential.TokenCredential;
import com.azure.identity.ClientSecretCredentialBuilder;
import com.azure.security.keyvault.secrets.SecretClient;
import com.azure.security.keyvault.secrets.SecretClientBuilder;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;

public class App {
    public static void main(String[] args) throws IOException {
        final String clientId = args[0];
        final String clientSecret = args[1];
        final String tenantId = args[2];
        final String vaultName = args[3];
        final String vaultUrl = String.format("https://%s.vault.azure.net", vaultName);
        // read secret names from a file
        final List<String> secretNames = Files.readAllLines(Path.of(args[4]));

        final TokenCredential tokenCredential =
                new ClientSecretCredentialBuilder()
                        .clientId(clientId)
                        .clientSecret(clientSecret)
                        .tenantId(tenantId)
                        .build();

        final SecretClient secretClient = new SecretClientBuilder()
                .vaultUrl(vaultUrl)
                .credential(tokenCredential)
                .buildClient();

        // 11 secrets are fetched without any issues, >= 12 makes app hang and no secret is returned...
        final int secretsToFetch = 11;
        final List<String> subList = secretNames.subList(0, secretsToFetch);
        System.out.printf("Fetching %d secrets ...", subList.size());

        final List<String> secrets = subList.parallelStream()
                .map(secretName -> secretClient.getSecret(secretName).getValue())
                .filter(Objects::nonNull)
                .collect(Collectors.toList());

        System.out.println("Secrets fetched:" + secrets.size());
    }
}
~~~

**Expected behavior**
getSecret should work for more than 11 threads in parallel. There shouldn't be a limit on how many times it can be called in parallel.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - IDE : IntelliJ 
 - Version of the Library used: 
~~~
    implementation 'com.azure:azure-security-keyvault-secrets:4.2.3'
    implementation 'com.azure:azure-identity:1.2.0'
~~~

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by vcolin7** [comment]
Let me preface this by explaining a bit about the authentication flow in the Azure Key Vault SDK: for any request to make to the service, we first make a naive unauthenticated call to obtain a challenge that will then be used in a subsequent authenticated call. This flow uses the **Azure Identity** library internally, which by default uses the common `ForkJoinPool` to obtain authentication details to add to calls.

`parallelStream` uses whichever `ForkJoinPool` it was created in and, in the case of the example you shared, uses the same pool as the Identity library.

Given all this, it is possible to have `parallelStream` use up all the available threads in the common pool, making first the initial unauthenticated requests and not leaving any available thread for the authentication flow to start at all. In my computer, for example, the limit to this is 8 threads since I only have 8 logical cores, so I was only able to get 7 secrets simultaneously but nothing more.

There is a few ways to get around this:

1. Change the thread pool Azure Identity will use by specifying which `ExecutorService` to use:

    ```java
    final TokenCredential tokenCredential =
        new ClientSecretCredentialBuilder()
            .clientId(clientId)
            .clientSecret(clientSecret)
            .tenantId(tenantId)
            .executorService(Executors.newCachedThreadPool()) // Here
            .build();
    ```

2. [Change the thread pool the parallel stream will use](https://stackoverflow.com/a/22269778/4967034). Although it appears this is not officially supported by the language[[1]](https://stackoverflow.com/a/52289102/4967034)[[2]](https://stackoverflow.com/a/36949448/4967034).

3. Use an async client. The Azure SDK async clients use [Project Reactor](https://projectreactor.io/), which uses its own thread pool. Here's a snippet showing how this could end up looking like:

    ```java
    AtomicInteger secretsCounter = new AtomicInteger();

    Flux.fromIterable(subList)
        .flatMap(secretAsyncClient::getSecret)
        .doOnNext(secret -> {
            System.out.println(secret.getName() + ":" + secret.getValue());
            secretsCounter.getAndIncrement();
        })
        .blockLast();

    System.out.println("Secrets fetched: " + secretsCounter);
    ```

All in all, I think the least disruptive and most stable solution is probably **number 1**.

I will be closing this issue for the time being but please feel free to re-open it if you found out that what I suggested was not sufficient or incorrect.

Finally, I want to give a quick shoutout to @srnagar for helping me debug this issue.

**Comment by usmansaleem** [comment]
@vcolin7 Thank you for the update, I'll modify our code as per suggested point # 1.

**Comment by darshan4545** [comment]
@usmansaleem  do you know how we can get this secrets from AKV to ConfigMap or Application YAML file !
