### ISSUE TITLE
Add support for checkAccess operation to AzureFileSystemProvider

### ISSUE THREAD

**Issue by pditommaso** [Azure/azure-sdk-for-java#17999]
**Is your feature request related to a problem? Please describe.**

The current `AzureFileSystemProfider` [NIO] does not support `checkAccess` operation, however it's quite important because it's used by the NIO API to check for a file existence. Currrently it just fails: 

```
java.lang.UnsupportedOperationException: null
	at com.azure.storage.blob.nio.AzureFileSystemProvider.checkAccess(AzureFileSystemProvider.java:801)
	at java.nio.file.Files.exists(Files.java:2385)
.. 
``` 

**Describe the solution you'd like**

To support this, it would be enough to use `readAttributes` operation. If attributes can be read => `true`, otherwise `false` 

**Describe alternatives you've considered**

Only alternative at this point is to branch this repo and patch directly.

**Additional context**

None

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

Version
- `com.azure:azure-storage-blob-nio:12.0.0-beta.2`

**Comment by rickle-msft** [comment]
Hi, @pditommaso Thanks for this request! We'd be happy to add support for this API; it just wasn't something we did before preview is all. 

I agree that a readAttributes call would be sufficient. Because of the complexity of how auth works with storage, we won't be able to actually validate read or write privileges specifically so much as ensure the existence of something at the destination that may be accessed. And from there we'll have to assume the customer configured the file system with sufficient privileges to read/write. I do think we should throw on execute, though, as it doesn't really make sense in the context of storage, but I am open to conversation there. 

If you are open to contributing the fix, I'd be happy to give some more details on how it might look in this code base, otherwise I'll work on getting this out soon.

**Comment by pditommaso** [comment]
Hi Rick, I've patched just like this 

```
    @Override
    public void checkAccess(Path path, AccessMode... accessModes) throws IOException {
        readAttributes(path, AzureBasicFileAttributes.class);
    }
```

Looks working in my tests. Don't think it's necessary to validate specific attributes, but I may miss something.
