### ISSUE TITLE
KnownLinuxVirtualMachineImage lists OpenSuSE Leap 42.1 but is not available anymore

### ISSUE THREAD

**Issue by tmonning** [Azure/azure-sdk-for-java#1800]
The enum in `com.microsoft.azure.management.compute.KnownLinuxVirtualMachineImage` shows the entry 
`OPENSUSE_LEAP_42_1("SUSE", "openSUSE-Leap", "42.1")`
but version 42.1 is not available anymore on Azure but rather 42.2. Creating a VM with the entry from the enum results in an error:

> The platform image 'SUSE:openSUSE-Leap:42.1:latest' is not available. Verify that all fields in the storage profile are correct.: The platform image 'SUSE:openSUSE-Leap:42.1:latest' is not available. Verify that all fields in the storage profile are correct.

**Comment by anuchandy** [comment]
https://github.com/Azure/azure-sdk-for-java/issues/1689

**Comment by anuchandy** [comment]
@martinsawicki should we remove this enum value as part of 1.2 release or 2.0?

**Comment by martinsawicki** [comment]
we should not break source code compat in 1.x - even if the underlying logic on the service side changes. If the service provider dropped support for this setting, can we just map it to something else that's a reasonable replacement for 1.x? And then remove in 2.0.
Also, perhaps the "42.1" part is too specific and we can make a new constant named in a way that is less version-dependent, so that users using it in the code don't have an expectation that it will point to 42.1 forever?  (and we can remap it in future to a different version)

**Comment by martinsawicki** [comment]
for 1.4, let's mark them as `@deprecated`
in 2., we'll clean up
