### ISSUE TITLE
[QUERY] Service Bus: How to free up a session earlier than 60s?

### ISSUE THREAD

**Issue by alewis001** [Azure/azure-sdk-for-java#18123]
**Query/Question**
Using the [Session based example](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ServiceBusSessionProcessorSample.java), a session appears to only free up after 60s allowing for messages on other sessions to be processed.

Can the 60s be shortened?

Can the session in the receiver be freed up on receipt of an "end" message as decided by the application?

***Why is this not a Bug or a feature Request?***
Apart from #18122 that I've raised, I would expect sessions to be freed up to process pending messages and free sessions to pick up messages on existing sessions regardless of duration between messages within a session.

There may be already a way to lower the timeout value and/or a mechanism for signalling that the session can be freed up that I haven't been able to find. Otherwise, this may become a feature request in order to access the Session from a received message to "free it" to process other sessions.

**Setup (please complete the following information if applicable):**
 - Version of the Library used: com.azure:azure-messaging-servicebus:7.0.0

**Comment by hemanttanwar** [comment]
@alewis001 

As of today we use 'AmqpRetryOptions.setTryTimeout()' for inactivity between messages. For example, If these is no message arrive with in this time, we will close the receiver and move on to next session.

The default value for this is 1 minute. You can change this in ServiceBusClientBuilder as shown below.

But keep in mind, We we are using this setting for other purpose also, for example when you call `sessionReceiver.acceptNextSession()` and If no session is available within this timeout, it completes with an error. So by changing this you are effecting other behavior also.

```java
        // Setting tryTimeout to 30 seconds
        ServiceBusProcessorClient processorClient = new ServiceBusClientBuilder()
            .connectionString("<< connection-string ")
            .retryOptions(new AmqpRetryOptions().setTryTimeout(Duration.ofSeconds(30)))
```
We have not exposed `inactivity between messages` as a separate parameter in our API. 

You can always process multiple session at once by specifying `.maxConcurrentSessions()` to greater than 1. This could be set in builder.

Your question "Can the session in the receiver be freed up on receipt of an "end" message as decided by the application?" : Conceptually The Client SDK do not know which message is "end" message. Because the back end is Queue/Topic, by definition it is an infinite stream of messages. If a message does not arrive in T second, It does not mean that it will not arrive ibn T+1 second. So SDK can not treat a specific message as "end"  message.

**Comment by alewis001** [comment]
Thank you for the explanation @hemanttanwar. We'll just set the maxConcurrentSessions sufficiently to account for this possible delay.

Sorry, I wasn't clear with my question "Can the session in the receiver be freed up on receipt of an "end" message as decided by the application?". To clarify, I meant is there a method that can be called by the application when processing a message that would tell the SDK to immediately free up the session once that message had been processed successfully. I couldn't find anything but I thought I'd ask just in case but you've already answered my question.

Thanks again.

**Comment by alewis001** [comment]
I'll close this as you've answered my questions. Thank you.
