### ISSUE TITLE
[BUG] Failure Modes are not documented in the API

### ISSUE THREAD

**Issue by clarkbreyman-yammer** [Azure/azure-sdk-for-java#18155]
**Describe the bug**
The JavaDoc does not include possible error responses for methods. 

For example, BlobClient.getProperties() does not mention what happens if the blob is not there. 

My personal opinion is that hiding possible errors from the method signature using RuntimeExceptions is a bad design as it makes it harder to robustly recover from these errors. To quote the [Oracle Java documentation:](https://docs.oracle.com/javase/tutorial/essential/exceptions/runtime.html) 

> Generally speaking, do not throw a RuntimeException or create a subclass of RuntimeException simply because you don't want to be bothered with specifying the exceptions your methods can throw ....If a client can reasonably be expected to recover from an exception, make it a checked exception. If a client cannot do anything to recover from the exception, make it an unchecked exception.

***Exception or Stack Trace***
not applicable

**To Reproduce**
read the Java Docs for BlobClient.getProperties.

***Code Snippet***
not applicable

**Expected behavior**
1 - Checked exceptions for recoverable failure modes AND
2 - Documentation in the JavaDoc of the possible failure modes, recoverable and unrecoverable.

**Screenshots**
not applicable

**Setup (please complete the following information):**
azure sdk java v 12

**Additional context**
not  applicable

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by rickle-msft** [comment]
@clarkbreyman-yammer Thank you for this feedback. I believe this decision was made because any api which hits the network can throw a BlobStorageException (in the case of blob storage... each service has its own exception type), and it seemed to clutter the API surface and user code to litter that everywhere. I'm not sure if there were other reasons. 

That said, this behavior is consistent across the Azure SDKs. With Storage in particular, we point to the REST API specs for each method which more clearly lay out the failure cases. Additionally, BlobErrorCode (and similar for other services) should provide a union of all failure cases for any given API. The REST docs do not call out common failure cases such as NotFound and auth failures because they are common to any distributed application, but those will still be present in BlobErrorCode. 

@JonathanGiles can speak more to the design guidelines, correct me if I'm wrong, and incorporate this feedback into our guidelines.

**Comment by JonathanGiles** [comment]
Rick is correct. The goal is to not overwhelm the user with a huge number of try / catch blocks. Our [design guidelines](https://azure.github.io/azure-sdk/java_introduction.html#exceptions) state that we should document all appropriate runtime exceptions as part of our JavaDoc, and I feel like this is the first hurdle we need to get better at clearing. I'm looking into any available tooling that can keep us more honest here.

**Comment by rickle-msft** [comment]
Thanks, Jonathan. I'll leave this issue open so Storage can track adding those parts to our docs

**Comment by clarkbreyman-yammer** [comment]
Thanks Jonathan. I've now read the design guidelines and, while I disagree with the choice to use unchecked exceptions I agree it is documented. Thank you both for the thoughtful responses. 

I know discussions around checked exceptions can result in more heat than light. I'm also familiar with the decisions in Kotlin, Scala and Clojure to eschew checked exceptions. Still, the Java team has documented what they feel is the idiomatic limits for unchecked exceptions and this decision seems to be non-idiomatic for Java. 

There is also a path that does not require discussing checked vs unchecked exceptions - not throwing exceptions at all and using a response object to report both success and failure cases. I was very disappointed that the WithResponse method variants would still throw exceptions for any non-2xx result. 

If the Java SDK team has any sort of RFC process or advisory board for changes, I'd love to get plugged in as a MSFT employee.
