### ISSUE TITLE
[BUG] com.azure.storage.common.Utility convertStreamToByteBuffer tries to reset/mark inputStreams that do not support it

### ISSUE THREAD

**Issue by alexander-riss** [Azure/azure-sdk-for-java#18178]
**Describe the bug**
Using any kind of input stream on the BlockBlobClient.upload(inputStream, size) call which does not support mark/reset causes this exception:

***Exception or Stack Trace***
java.lang.RuntimeException: java.io.IOException: reset not supported
	at com.azure.storage.common.Utility.lambda$convertStreamToByteBuffer$4(Utility.java:260)
	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:46)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:187)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1680)
		at 
		com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:110)
		at com.azure.storage.blob.specialized.BlockBlobClient.uploadWithResponse(BlockBlobClient.java:319)
		at com.azure.storage.blob.specialized.BlockBlobClient.uploadWithResponse(BlockBlobClient.java:286)
		at com.azure.storage.blob.specialized.BlockBlobClient.upload(BlockBlobClient.java:243)
		at com.azure.storage.blob.specialized.BlockBlobClient.upload(BlockBlobClient.java:215)
Caused by: java.io.IOException: reset not supported
	at <input stream that does not support mark / reset>
	at com.azure.storage.common.Utility.lambda$convertStreamToByteBuffer$4(Utility.java:258)
	... 9 common frames omitted

**To Reproduce**
Try to upload an inputStream that throws an exception on calling .reset() (and reports supportsMark() as false)

**Expected behavior**
This is a change in how the client behaved before - it should just not use mark/reset for this use case.

**Setup (please complete the following information):**
 - 12.9.0 azure-storage / 12.10.0-beta.1

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by rickle-msft** [comment]
Hi, @alexander-riss. Thanks for opening this issue! Our recommendation in this case is to wrap the inputStream in a BufferedInputStream so that marking is supported.

**Comment by alexander-riss** [comment]
@rickle-msft would it make sense for the library to do this kind of wrapping on its own if a stream reports markSupport as false? this is a breaking change which can only be detected at runtime - this might cause serious outages on clients upgrading their library

**Comment by rickle-msft** [comment]
@alexander-riss I believe there was a reason, but I'll need to confer with my team as I'm not remembering off the top of my head. What I can say in the meantime is that if you use BlobClient.upload instead of BlockBlobClient.upload, we do actually handle buffering for you so you don't need to do any wrapping or anything. In general, BlobClient is where we add these sorts of convenience features and BlockBlobClient is a pretty raw api. Let me know if switching methods is feasible and helps resolve the problem.

**Comment by alexander-riss** [comment]
the problem is that  we need to wrap the inputStream on our side since we receive it out of multiple sources - so this is breaking our workflow - for now we will remain on the non-broken version until this is addressed

**Comment by rickle-msft** [comment]
@alexander-riss The reason we don't want to add this by default in methods on BlockBlobClient is because some customers may already be performing their own buffering, so if we add buffering on top of that, we are wasting memory. The BlockBlobClient methods are meant to be very stripped down and leave responsibilities like this to the customer. Because of this, I don't think we are going to wrap in a BufferedInputStream by default.

Upload methods on BlobClient, though, will handle this for you

**Comment by alexander-riss** [comment]
@rickle-msft sorry i did not mean that the client should wrap the stream on its own - the client should only respect that if a stream reports back that it does not support resetting (like user uploads of streaming data), the client should not blindly assume it does and then fail doing so

**Comment by rickle-msft** [comment]
@alexander-riss Thank you for the clarification. A couple other questions. 

- Which method(s) are you talking about in your last comment? BlobClient.upload? Or the methods on BlockBlobClient?
- What is your ideal behavior if the client does not support resetting? To continue with the upload anyway or throw at a different point or with a different message?

Our current intention is to throw at some point if the stream does not support resetting, but what that experience looks like can be up for conversation

**Comment by alexander-riss** [comment]
We are using BlockBlobClient.upload(stream, size).
I would expect the client to use the stream as is (as it did in the previous version) and only throw an error if it e.g. hit a scenario where a resettable stream is required (e.g. for performing a retry of the upload on errors - which would simply be unsupported on non-resettable streams)

**Comment by rickle-msft** [comment]
@alexander-riss I talked about this with my team. We are reluctant to make this change to pushing the exception to the time of attempting a retry because we consider that a less safe option. Our concern is that some customers may not adequately test these scenarios, deploy to production, and then start seeing lots of exceptions in less stable networking environments. 

So I think for the time being we are going to continue to fail on non-markable streams up front, but if there are other ways that we can make the experience better for you or other avenues we can explore to address your concerns, I am happy to continue the conversation in that direction.

**Comment by alexander-riss** [comment]
would to be possible to expose an api which makes this more explicit? i think non-retryable streams make up most of our user provided content (streaming them from the user directly to the azure storage location without saving them to disk in between for obvious efficiency reasons for large files). 
I just want to repeat - this is how the api has worked  before - and you basically introduced the "breaking at runtime" feature already.

**Comment by rickle-msft** [comment]
A more explicit api in the sense that it lets you turn this off? 

I suspect that this made it through review because this fell into a category of trying to help protect data by ensuring retries are possible, but if you let me know the version you're trying to upgrade from, I'll lookup the exact change and see what happened. If there is something wrong about how we implemented it, I'll have to confer with our design board on what would be the policy in that case of how to handle amending what would be an accidental break.

**Comment by alexander-riss** [comment]
we are at version 12.6.1 of azure-storage-blob, this the last version to not break on non-resettable streams at runtime.

**Comment by rickle-msft** [comment]
Thank you for that information. [This](https://github.com/Azure/azure-sdk-for-java/commit/7dc9cf5b663ad38ad2a04ef781e2148e6efa9375) is the commit that changed this and it was evidently because of a bug that was causing empty data to be sent in cases of retrying. Because of that, I think this is an important change to keep in place

Can you describe a bit more about what you mean by an api that makes this more explicit?

**Comment by alexander-riss** [comment]
an api like "uploadVolatileStream(stream)" which allows for uploading non resettable streams would be fantastic - that could carry a javaDoc which meantions the limitations and could just throw an error on "repeatable" errors so the burden of retrying is left to the client (e.g. be sending the error upstream to the e.g. web-user which is actually able to retry the whole request)

**Comment by rickle-msft** [comment]
Thank you for those details and suggestions. Before we go too far into exploring adding a new api, one other option I don't think we fully explored in this thread is the use of BlobClient.upload. Rather than adding a new api, since there'd have to be a code change for that any way, would it be possible to use BlobClient.upload rather than BlockBlobClient.upload? The upload method on BlobClient should not try to reset your stream at all. That said, it does add some extra buffering. 

As a side note, I don't think I mentioned, but we do recognize the inconvenience this break in behavior causes you and we do apologize for that.

**Comment by rickle-msft** [comment]
@alexander-riss Were you able to try using this other upload method?

**Comment by alexander-riss** [comment]
@rickle-msft we use the client  we get from BlobContainerClientBuilder.buildClient() - is this  not supposed to return a blockBlobClient in higher versions?

**Comment by alexander-riss** [comment]
@rickle-msft - thank you for the guidance on switching to the plain BlobClient - we just finished this migration together with the version update to latest and so far it seems to work without any problems!
