### ISSUE TITLE
[QUERY]

### ISSUE THREAD

**Issue by rakhmvi** [Azure/azure-sdk-for-java#18335]
**Query/Question**
Hi, 
Our application runs on standalone server (later the app will be migrated to AZ). The application stores data in Azure Blob Storage. We have one storage account with multiple containers. Code below is used to connect to client:
`	public static BlobServiceClient getBlobServiceClient(String blobServiceEndpoint,String storageAccount,String sharedKey) {
		 return	new BlobServiceClientBuilder()
				.endpoint(blobServiceEndpoint)
				.credential(new StorageSharedKeyCredential(storageAccount, sharedKey))
				.buildClient();
	}`
then the app returns container client using `	public static  BlobContainerClient getBlobContainerClient(BlobServiceClient blobServiceClient,String containerName) {
		return  blobServiceClient.getBlobContainerClient(containerName);
	}`.
Now we need to restrict access to some containers using RBAC and Azure AD e.g.: 
- Group  A has access to container A, but has no access to Container B.
- Group  B has access to container B, but has no access to Container A.

Who can be a member of groups? How can I connect to BlobServiceClient using group member credentials? 

***Why is this not a Bug or a feature Request?***
Not a bug, need assistance.

**Setup (please complete the following information if applicable):**
 - OS: [win10]
 - IDE : [eclipse 4.17, openjdk 11]
 - azure SDK 12.9.

**Comment by rickle-msft** [comment]
Hi, @rakhmvi. Thank you for your question. I think when you are creating your BlobServiceClient, you will want to specify a TokenCredential object rather than a StorageSharedKeyCredential. There are a good number of implementations of TokenCredential in the identity package, at least one of which should be able to offer you RBAC. If you take a look through that package and still can't find what you're looking for, lmk.

**Comment by rakhmvi** [comment]
Hi @rickle-msft,
I've created two service principals and assigned them to Group A and B appropriately and a code frame below is used to init BlobServiceClient: 
`		TokenCredential tokenCredential = new ClientSecretCredentialBuilder()
				.clientId(clientId)
				.tenantId(tenantId)
				.clientSecret(clientSecret)
				.build();
		BlobServiceClient buildClient = new BlobServiceClientBuilder()
				.endpoint(blobServiceEndpoint)
				.credential(tokenCredential)
				.buildClient();`

However I hesitate that current solution is a best practice and ready for deliver into production.

**Comment by rickle-msft** [comment]
@rakhmvi Can you explain more about your concerns as to why this may not be best practice/production ready?

**Comment by brijesh-dobariya** [comment]
Hi @rickle-msft 

Me and @rakhmvi We are working on the same team, so lets continues further communication through me.

Actually, we are successfully achieved upload operation using by TokenCredential (RBAC service principal authentication), now here I have one question regarding RBAC authentication, can I achieve RBAC authentication through the Azure AD User? Can you plz guide me for same.

I have used below code for RBAC user authentication as an experiment instead of TokenCredential. 

UsernamePasswordCredential usernamePasswordCredential = new UsernamePasswordCredentialBuilder()
	.clientId(clientId)
	.username(username)
	.password(password)
	.build();

But, I have got many exceptions. I am not aware of this kind of authentication on azure, especially RBAC user authentication. Again RBAC service principal authentication is working fine through the TokenCredential but we want RBAC User/Group authentication.

Thanks in advance

**Comment by rickle-msft** [comment]
Hey! For questions on these credential types, I'm going to call in @g2vinay who works on the identity package and will be able to answer your questions more effectively.

**Comment by brijesh-dobariya** [comment]
Hello @rickle-msft , Thanks for your response. I am waiting here for your answer once you have done call with @g2vinay for same.

**Comment by brijesh-dobariya** [comment]
Hi @rickle-msft, Is there any update mate? Again, just recall you, I want container level RBAC authentication. One of the way is working fine which is the RBAC service principal but I want RBAC user/group authentication at the container level.

**Comment by g2vinay** [comment]
Hi @brijesh-dobariya 

To use UsernamePassword Credential, 2 FA needs to be disabled. It won't work if 2FA is enabled for the user.

There are other ways to use user credentials via Identity SDK. You can use InteractiveBrowserCredential and DeviceCodeCredential (both of them require interactive user authentication in a browser). 
Both of these credentials require an app registration in Azure Active Directory. The user credentials authorize these apps to act on their behalf.

To Utilize Device Code Credential:

## Devie Code Credential
### Enable applications for device code flow
In order to authenticate a user through device code flow, you need to go to Azure Active Directory on Azure Portal and find you app registration and enable the following 2 configurations:

![device code enable](https://raw.githubusercontent.com/wiki/Azure/azure-sdk-for-java/media/devicecode-enable.png)

This will let the application authenticate, but the application still doesn't have permission to log you into Active Directory, or access resources on your behalf. Open API Permissions, and enable Microsoft Graph, and the resources you want to access, e.g., Azure Service Management, Key Vault, etc:

![device code permissions](https://raw.githubusercontent.com/wiki/Azure/azure-sdk-for-java/media/devicecode-permissions.png)

Note that you also need to be the admin of your tenant to grant consent to your application when you login for the first time. Also note after 2018 your Active Directory may require your application to be multi-tenant. Select "Accounts in any organizational directory" under Authentication panel (where you enabled Device Code) to make your application a multi-tenant app.

### Code Example:
```java
    DeviceCodeCredential deviceCodeCredential = new DeviceCodeCredentialBuilder()
        .challengeConsumer(challenge -> {
            // lets user know of the challenge
            System.out.println(challenge.getMessage());
        })
        .clientId("Your-App-Client-Id")
        .build();

    // Azure SDK client builders accept the credential as a parameter
    SecretClient client = new SecretClientBuilder()
        .vaultUrl("https://{YOUR_VAULT_NAME}.vault.azure.net")
        .credential(deviceCodeCredential)
        .buildClient();
```

## Interactive Browser Credential
### Enable applications for interactive browser oauth 2 flow
You need to register an application in Azure Active Directory with permissions to login on behalf of a user to use InteractiveBrowserCredential. Follow all the steps above for device code flow to register your application to support logging you into Active Directory and access certain resources. Note the same limitations apply that an admin of your tenant must grant consent to your application before any user account can login.

You may notice in `InteractiveBrowserCredentialBuilder`, a `redirectUrl` is required, and you need to add the redirect URL on this page too:

![interactive redirect uri](https://raw.githubusercontent.com/wiki/Azure/azure-sdk-for-java/media/interactive-redirecturi.png)

### Code Example
```java
    InteractiveBrowserCredential interactiveBrowserCredential = new InteractiveBrowserCredentialBuilder()
        .clientId("<YOUR CLIENT ID>")
        .redirectUrl("http://localhost:8765"). //The registered redirect URL of the public client application 
        .build();

    // Azure SDK client builders accept the credential as a parameter
    SecretClient client = new SecretClientBuilder()
        .vaultUrl("https://{YOUR_VAULT_NAME}.vault.azure.net")
        .credential(interactiveBrowserCredential)
        .buildClient();
``` java

**Comment by brijesh-dobariya** [comment]
Hi @g2vinay Thanks for providing this kind of information. I have some question

Question 1: By using InteractiveBrowserCredential and DeviceCodeCredential, can I set permission or role in IAM of container level?

I just give you an idea about my java web application.

**Precondition:**
1. Was created azure storage account
2. Was created multiple container/blob in storage account (container_A and container_B)

Now,

**Case 1:** We are trying to upload file/blob on one **container_A** by using RBAC service principal (xyz_sp1) which is already give role assignment under **IAM container_A**
**Result:** Valid case and working file with RBAC service principal

**Case 2:** We are trying to upload file/blob on one **container_B** by using RBAC service principal (xyz_sp2) which is already give role assignment under **IAM container_B**
**Result:** Valid case and working file with RBAC service principal

But, Now

**Case 3:** We are trying to upload file/blob on one **container_A** by using RBAC service principal (xyz_sp2) which is not added under **IAM container_A** or vice versa.
**Result:** Authentication is failed because of xyz_sp2 service principal is not able to access container_A due to role assignment is not given.

Here,
1. container_A and container_B are name of the blob/container which is created under the single azure storage.
2. xyz_sp1 and xyz_sp2 are name of the service principal.
3. All three cases are valid with expected result because here we have used the RBAC service principal on container level.

So, can we achieved same cases by using RBAC AD user I mean If I have give role assignment to any AD user in IAM of container. Your above comment/answer is match this cases?

Again, In simple terms, We have achieved all the three cases by using RBAC service principal but we want achieved same cases by using RBAC AD User.

Thanks

**Comment by g2vinay** [comment]
Hi @brijesh-dobariya 

Yes, by using InteractiveBrowserCredential and DeviceCodeCredential, you can set permission or role in IAM of container level.
Just set it for the user instead of service principal.

Make sure, you follow the steps to use the Interactive Browser Credential mentioned above.
Let us know if you run into any issues.

**Comment by gapra-msft** [comment]
Looks like this thread has been answered, closing for now. @rakhmvi Please feel free to open another issue or reopen this issue if you hit any further problems, and we are happy to help
