### ISSUE TITLE
[BUG] Missing azure-spring-boot-starter-active-directory for the 3.x series beta releases

### ISSUE THREAD

**Issue by ogreface** [Azure/azure-sdk-for-java#18410]
**Describe the bug**
The docs (located here: https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-active-directory ) tell you to grab a 3.x series version of the SDK. However, while there are versions under com.azure.spring for the core / other starters, there is no version for the active-directory starter.

Your only option is 2.3.5 series library.

**To Reproduce**
Take a look at https://mvnrepository.com/artifact/com.microsoft.azure/azure-active-directory-spring-boot-starter

**Expected behavior**
Would hope for a beta release like the other starters.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X ] Bug Description Added
- [ X ] Repro Steps Added
- [ X ] Setup information Added

**Comment by yungezz** [comment]
hi @yiliuTo could you pls help to triage the spring issue? thanks

**Comment by yiliuTo** [comment]
Hi @ogreface , thanks for your reporting, our release of azure-active-directory-spring-boot-starter 3.0.0 has been done now, here is the [maven link](https://mvnrepository.com/artifact/com.azure.spring/azure-spring-boot-starter-active-directory). And we changed its group-id to `com.azure.spring`, so that's why you failed to find it through the original group-id, also, we will do the maven relocation for aad starter as soon as possible .

**Comment by ogreface** [comment]
Awesome, thank you!
