### ISSUE TITLE
[azure-storage-blob-nio] Support full configurable BlobEndpoint

### ISSUE THREAD

**Issue by hofficoffi** [Azure/azure-sdk-for-java#18564]
**Is your feature request related to a problem? Please describe.**
When i want to use docker azurite for local development, i cannot configure the BlobEndpoint to be http://127.0.0.1:10000/devstoreaccount1 as recommended by guides in setting up azurite

**Describe the solution you'd like**
As the BlobEndpoint configuration is available when directly using the BlobServiceClient, it should be possible for the azure-storage-blob-nio FileSystem configuration as well

**Comment by rickle-msft** [comment]
Hi, @hofficoffi. Thank you for opening this issue. I'll work on adding support for this feature soon.

**Comment by rickle-msft** [comment]
I think probably the best way to do this is to have a config option that accepts the endpoint and we just drop it in. Then customers can pass whatever they want. So one of the query parameters on the URI would be "?endpoint="http://127.0.0.1:10000/devstoraccount1". I think it's ok to put a query value in quotes like that. And then we just strip the quotes and put the whole value for the endpoint rather than parsing. 

@gapra-msft @alzimmermsft thoughts?
