### ISSUE TITLE
[BUG] Sample app use of duplicate attributes

### ISSUE THREAD

**Issue by xstof** [Azure/azure-sdk-for-java#18666]
**Query/Question**
The sample application uses both an annotation of `@EnableWebSecurity ` and `@EnableGlobalMethodSecurity`.  See the [sample here](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-webapp/src/main/java/com/azure/spring/sample/aad/security/AADOAuth2LoginSecurityConfig.java#L11).

According to Spring docs [here](https://docs.spring.io/spring-security/site/docs/4.0.4.RELEASE/reference/html/jc.html#hello-web-security-java-configuration) however it says: "The name of the `configureGlobal` method is not important. However, it is important to only configure `AuthenticationManagerBuilder` in a class annotated with either `@EnableWebSecurity`, `@EnableGlobalMethodSecurity`, or `@EnableGlobalAuthentication`. Doing otherwise has unpredictable results."

***Why is this not a Bug or a feature Request?***
Could this be potentially an error which needs correction to stay in line with Spring recommended practices?

**Setup (please complete the following information if applicable):**
 - OS: [e.g. iOS] Linux
 - IDE : [e.g. IntelliJ] Visual Studio Code
 - Version of the Library used: 3
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Thanks for filing this issue with the sample, @xstof.  @jialindai can you please follow up?

**Comment by saragluna** [comment]
@chenrujun could you please take a look at this?

**Comment by chenrujun** [comment]
Hi, @xstof .

Thank you for reaching out.

### Conclusion

In [the sample](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-webapp/src/main/java/com/azure/spring/sample/aad/security/AADOAuth2LoginSecurityConfig.java#L11), there is no problem to uses **@EnableWebSecurity** and **@EnableGlobalMethodSecurity** at the same time .

### Explanation

```
The name of the configureGlobal method is not important. However, it is important to only configure 
AuthenticationManagerBuilder in a class annotated with either @EnableWebSecurity, @EnableGlobalMethodSecurity, 
or @EnableGlobalAuthentication. Doing otherwise has unpredictable results.
```

1. `it is important to...` means `configure AuthenticationManagerBuilder` should in a class annotated with the 3 annotations.

1. `otherwise` means  `configure AuthenticationManagerBuilder` **NOT** in a class annotated with the 3 annotations, `otherwise` does not mean the 3 annotations appeared at the same time.
 
1. Actually, `@EnableGlobalMethodSecurity` is annotated by `@EnableGlobalAuthentication`, so it's valid to use `@EnableGlobalMethodSecurity` and `@EnableGlobalAuthentication` at the same time .

1. If we delete one of the 2 annotations, it will cause problem:

* If we delete `@EnableGlobalMethodSecurity`,  then [@PreAuthorize](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-webapp/src/main/java/com/azure/spring/sample/aad/controller/RoleController.java#L22) will not take effect.
* If we delete `@EnableWebSecurity`, the sample will lack some beans.

**Comment by yiliuTo** [comment]
Closing this issure because no response from the customer.
