### ISSUE TITLE
Samples Have Dependencies not Present in maven Repository[QUERY]

### ISSUE THREAD

**Issue by ianlikono** [Azure/azure-sdk-for-java#18749]
**Query/Question**
azure-spring-cloud-sample-eventhubs-binder sample have dependencies that have not been updated in mvn repository.

Specifically these are the dependencies:
- com.azure.spring:azure-spring-cloud-stream-binder-eventhubs has 2.1.0 while the latest in mvn is 2.0.0 [mvn repo](https://mvnrepository.com/artifact/com.azure.spring/azure-spring-cloud-stream-binder-eventhubs)
- com.azure.spring:azure-spring-cloud-storage has 2.1.0 while the latest in mvn repo is also 2.0.0 [mvn repo](https://mvnrepository.com/artifact/com.azure.spring/azure-spring-cloud-storage)
***Why is this not a Bug or a feature Request?***
Not sure if this is intentional and we are required to download the packages manually

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE: Eclipse
 - Version of the Library used: Latest sample here [pom.xml](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-samples/azure-spring-cloud-sample-eventhubs-binder/pom.xml)
 

If we need to download them from somewhere else could we have that in the README as well

**Comment by yiliuTo** [comment]
Hi @ianlikono , thanks for your reporting. This is because we started to release 2.1.0 of these two packages 3 days ago, so all the code in master branch is just the 2.1.0 version. However, due to some errors of our release pipeline, new packages haven't been published to Maven repository yet.

So if you want to test our 2.1.0 packages, you can clone the `master` branch and build it locally:
```
cd sdk\spring
mvn clean install -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -Dspotbugs.skip=true -Drevapi.skip=true -Djacoco.skip=true -DskipTests -Dparallel-test-playback -pl <package-list-you-want-to-build> -am
```
 Otherwise you can use 2.0.0 version.

**Comment by ianlikono** [comment]
Thanks for the clarification @yiliuTo

**Comment by saragluna** [comment]
Closing this issue now.
