### ISSUE TITLE
Azure Core Amqp Sample issue

### ISSUE THREAD

**Issue by Melanie-Ma** [Azure/azure-sdk-for-java#18806]
1. 
     Section [Link](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core-amqp/src/samples/java/com/azure/core/amqp/models/AmqpAnnotatedMessageJavaDocCodeSamples.java#L14):
![image](https://user-images.githubusercontent.com/64007802/105796264-715e4200-5fc9-11eb-859c-0c875f5453f7.png)
Reason:
AmqpAnnotatedMessage is null which caused NullPointException.

@jongio for notification

**Comment by hemanttanwar** [comment]
@Melanie-Ma I do not think we need to change anything here because all the sample which ends with `JavaDocCodeSamples` are just code snippet which are places in java doc. You will see `BEGIN:` and `END:` tag and the code with in these tag will placed in source code. The variable `amqpAnnotatedMessage` having null value is outside of these tags and will not be put in java doc like  [here](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/models/AmqpMessageBody.java#L23).

**Comment by Melanie-Ma** [comment]
@hemanttanwar - I  agree that the code snippets are used in  in java doc. However, I think that the code documentation also need right example for users ′ reference. Therefore, I think the issue need to be fixed. Please refer to the #12571
