### ISSUE TITLE
[Question] Why Blob Lease Status is Unlocked for Checkpoints and Ownership?

### ISSUE THREAD

**Issue by the-mod** [Azure/azure-sdk-for-java#19129]
**Query/Question**
I am able to spin up an EventProcessing Host using an Azure Storage Account to save checkpoints and sync Ownerships.
It is working fine so far.
But I figured out, all the blobs has Lease Status `unlocked` and  Lease State is `available` for both `ownership` and `checkpoints`.

The `Last modified` Tag is updated regularly.
So it seams it is working correctly with the blobs.
But if the blobs are not locked they are free for manipulation or deletion.

**Implemenation**
```java
EventProcessorClient processor = new EventProcessorClientBuilder() 
.connectionString(eventHubConnectionString) 
.consumerGroup(consumerGroupName) 
.checkpointStore(new BlobCheckpointStore(blobContainerClient)) 
.loadBalancingUpdateInterval(Duration.ofSeconds(5)) 
.partitionOwnershipExpirationInterval(Duration.ofSeconds(60)) 
.loadBalancingStrategy(LoadBalancingStrategy.GREEDY)
.processEventBatch(...) 
.processError(...) 
.processPartitionInitialization(...) 
.processPartitionClose(...) 
.buildEventProcessorClient();
```

**Setup**
 - Version of the Library used : `com.azure.azure-messaging-eventhubs.5.4.0` and `com.azure.azure-messaging-eventhubs-checkpointstore-blob:1.4.0`

**Comment by srnagar** [comment]
@the-mod The new `azure-messaging-eventhubs` library does not lease or lock blobs that track ownership and checkpoint. We use blob metadata and last modified time to determine active ownership of a partition. It is by design to keep the storage operations lightweight. These blobs are created, owned and maintained by the processor clients and shouldn't be used by any other applications/users.

However, there's no check to prevent someone from modifying/deleting these blobs. The processor client can auto-recover if ownership blobs are deleted. If checkpoint blobs are deleted, then the processor client will start consuming from the latest event position and can result in not consuming some events.

**Comment by the-mod** [comment]
@srnagar thx for the Information. I just wanted to clarify if it works as designed or if I did a misconfiguration. No further Questions from my side.
