### ISSUE TITLE
[QUERY] GoneException retry policy in case of writes

### ISSUE THREAD

**Issue by R0st0s** [Azure/azure-sdk-for-java#19514]
**Query/Question**
Write requests are not retried in case of 410 errors: https://github.com/Azure/azure-sdk-for-java/issues/15304.
Is this configurable? I'm using [com.azure.spring.data.cosmos.repository.CosmosRepository](https://github.com/Azure/azure-sdk-for-java/blob/5672b860b15aa32d1dd5b559f47c3cb1058f0166/sdk/cosmos/azure-spring-data-cosmos/src/main/java/com/azure/spring/data/cosmos/repository/CosmosRepository.java) from Spring Data Azure CosmosDB 3.1.0, the _save_ method should be idempotent in my understanding.

***Why is this not a Bug or a feature Request?***
I assume the behavior is correct and not all writes are non-idempotent, so I suppose it's not a bug that the request is not retried. It's not a feature request either because I don't know if it's already possible to configure the SDK to retry.

**Setup (please complete the following information if applicable):**
 - OS: Windows 10
 - IDE : IntelliJ
 - Version of the Library used:             azure-spring-data-cosmos 3.1.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Query Added
- [x ] Setup information Added

**Comment by kushagraThapar** [comment]
@R0st0s - Writes are not idempotent in cosmosdb, which I agree doesn't relates well with `save` operation in spring-data. However, since cosmosdb doesn't supports idempotent writes, the only way to fix this would be at your end. We highly recommend all customers to have retry logic in the writes. 
Cosmos Java SDK makes sure to retry writes internally only if it is sure that the write request has not reached the backend, that is failed on the wire. 
But any other scenario, we don't retry writes. 
We are working on something called as retriable writes, but it will take some time to bake and build. (sometime this semester), so for the time being, please have retry logic at your end on writes operations (`save` for spring-data). 
You can read more about it here - https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-java-sdk-v4-sql#retry-logic-

**Comment by R0st0s** [comment]
Thank you for the quick response, @kushagraThapar. When you're saying you are working on retriable writes, do you mean in the Java SDK? Or in the Spring data side, given that it's also in this repository?
Either way, we will implement the retry mechanism at our side until that.

**Comment by kushagraThapar** [comment]
@R0st0s - In the Java SDK. Spring Data will automatically get the benefits.

**Comment by R0st0s** [comment]
Thank you, closing the ticket.
