### ISSUE TITLE
How do I use prebuilt ID extraction models 

### ISSUE THREAD

**Issue by jjkuru-darkhorse** [Azure/azure-sdk-for-java#19574]
How do I get the prebuilt ID extraction models shown here with passport and driver's license?
https://azure.microsoft.com/en-us/services/cognitive-services/form-recognizer/#features

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b09706df-9b0b-6306-565c-6b625803aeb9
* Version Independent ID: ba8f04d0-448a-8224-1ec3-b7774ec0c889
* Content: [Azure Form Recognizer client library for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/ai-formrecognizer-readme?view=azure-java-stable#feedback)
* Content Source: [docs-ref-services/latest/ai-formrecognizer-readme.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/ai-formrecognizer-readme.md)
* Service: **formrecognizer**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by joshfree** [comment]
@samvaity could you please follow up on improving the docs?

**Comment by samvaity** [comment]
Hey @jjkuru-darkhorse, these features to extract document info for passport and ID model types should be incrementally available in the 3.1.0-beta.3 beta release for Form Recognizer client library. 
As the service just released these [features](https://docs.microsoft.com/en-us/azure/cognitive-services/form-recognizer/whats-new#march-2021), we are looking forward to get those out soon too.

**Comment by chandygithub** [comment]
Hi @samvaity I am using  azure sdk for java for the FormRecognizer,3.1.0-beta.4. I ran a Standalone java client. 
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/formrecognizer/azure-ai-formrecognizer/src/samples/java/com/azure/ai/formrecognizer/RecognizeInvoicesFromUrl.java
just used the FormRecognizer resource endpoint and Key,which i have created,in the above code  
Got Error
code":"401","message":"Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource."}.
Btwn the FormRecognizer resource endpoint is valid and works from https://fott-preview.azurewebsites.net/.
anything else?
