### ISSUE TITLE
Cannot specify tags on CosmosDBAccount

### ISSUE THREAD

**Issue by bguezzie** [Azure/azure-sdk-for-java#1970]
When either dealing with an existing `CosmosDBAccount` or a definition for a new account, there is no way to set or update tags.  In particular it would be handy to be able to specify the standard `provider` tag.

This means that any accounts we dynamically set up as a part of a solution cannot be attributed to our provider GUID in Azure billing.

I'm looking at version 1.3.0, if that helps.

[EDIT] I did find that I can add a tag once it's been created (via Update and Optionals).  Still, it would be nice to be able to provide the tag in the definition process for a new instance.

**Comment by martinsawicki** [comment]
@alvabandy accidentally missed from the definition?

**Comment by shurd** [comment]
Hi @bguezzie thank you for the inquiry. I do not know if something has changed since you raised the issue, but DatabaseAccount extends Resource, which provides the command [withTags](https://github.com/Azure/azure-sdk-for-java/blob/7397b5b6c40e57815c7e1c92197d3026415ff1df/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/models/Resource.java). Additionally, the control plane operations now appear in [azure-libraries-for-java](https://github.com/Azure/azure-libraries-for-java/tree/master/azure-mgmt-cosmosdb/src/main/java/com/microsoft/azure/management/cosmosdb). Using that SDK, I was able to create an account with tags using:

`CosmosDBAccount cosmosDBAccount = azure.cosmosDBAccounts().define("dbname")`
`                .withRegion(Region.US_EAST)`
`                .withNewResourceGroup("rg")`
`                .withKind(DatabaseAccountKind.GLOBAL_DOCUMENT_DB)`
`                .withWriteReplication(Region.US_WEST)`
`                .withReadReplication(Region.US_CENTRAL)`
`                .withTag("group", "value")`
`                .create();`

**Comment by shurd** [comment]
I am going to close this issue for now. You can re-open it if you still face problems setting tags.
