### ISSUE TITLE
Build pipeline cannot be rerun if APIView step fails

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-for-java#19788]
Rerun of build pipeline step fails in publish artifact step. Immediate fix is to reorder API view step to run before publish step and long term fix will be support retry for publish artifact step also.

**Comment by kurtzeborn** [comment]
@weshaggard and @scbedd investigated this a bit, and it appears the root cause is that the pipeline artifacts being uploaded to the same location.  They've fixed this for Python, but similar changes need to be made for the other languages.  While this was observed as a problem while running for ApiView, it appears to be a general problem independent of the checks ApiView is doing.
