### ISSUE TITLE
Support web-application and resource-server in one application.

### ISSUE THREAD

**Issue by blacelle** [Azure/azure-sdk-for-java#19816]
**Describe the bug**
We encounter difficulties while migrating from 

			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-spring-boot</artifactId>
			<version>2.3.5</version>

to

			<groupId>com.azure.spring</groupId>
			<artifactId>azure-spring-boot</artifactId>
			<version>3.2.0</version>

***Exception or Stack Trace***

```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.security.oauth2.client.userinfo.OAuth2UserService<?, ?>' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:351)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1171)
	at io.mitrust.backend.azuread.TestMinimalAzureAd.testGetGroups(TestMinimalAzureAd.java:32)
```

***Code Snippet***

```
@RunWith(SpringRunner.class)
@Import(AADWebAppConfiguration.class)
@TestPropertySource(properties = { "azure.activedirectory.client-id=" + "someClientId" })
public class TestMinimalAzureAd {
	private static final Logger LOGGER = LoggerFactory.getLogger(TestMinimalAzureAd.class);

	@Autowired
	ApplicationContext appContext;

	@Test
	public void testGetGroups() throws Exception {
		// see AADWebAppConfiguration
		LOGGER.info("Test done: {}", appContext.getBean(OAuth2UserService.class));
	}

}

```
while having in pom.xml the following dependencies:
```
		<dependency>
			<!-- Used to accept JWT from EndUsers -->
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-oauth2-resource-server</artifactId>
		</dependency>
```
**Expected behavior**
We expect AADOAuth2 to be run in parallel of our own oauth2 resource server (it is OK in 2.3.5).

**Additional context**
Our application has admin entrypoints protected by AAD tokens, and user entrypoints protected by custom JWT.

**Comment by chenrujun** [comment]
Hi, @blacelle 

Thank you for reaching out.

## Explain the exception

About `NoSuchBeanDefinitionException`. It's expected behavior. When added dependency `spring-security-oauth2-resource-server`,  `AADResourceServerConfiguration` will take effect instead of `AADWebAppConfiguration`.

## Scenario confirm

>We expect AADOAuth2 to be run in parallel of our own oauth2 resource server (it is OK in 2.3.5).

> Our application has admin entrypoints protected by AAD tokens, and user entrypoints protected by custom JWT.

Which scenario is your application? [web-application or resource-server](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-active-directory#key-concepts)? Please choose one scenario:

#### Scenario 1: web-application

1. `AADOAuth2` means login by Microsoft account.
2. `AAD tokens` means the id_token issued by AAD. 
3. You application support login by Microsoft account.
4. You are NOT using [AADAppRoleStatelessAuthenticationFilter](https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot_3.2.0/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-resource-server-by-filter-stateless/src/main/java/com/azure/spring/sample/aad/security/AADWebSecurityConfig.java#L20) or [AADAuthenticationFilter](https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot_3.2.0/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-resource-server-by-filter/src/main/java/com/azure/spring/sample/aad/security/WebSecurityConfig.java#L20) in your application.
5. "azure.activedirectory.user-group" is configured.

#### Scenario 2: resource-server

1. `AADOAuth2` means check the JWT token issued by AAD. 
2. `AAD tokens` means the access_token issued by AAD. 
3. Your application is just work as resource-server:  validate access_token, allow access if access_token is valid. Not support login.
4. You are using [AADAppRoleStatelessAuthenticationFilter](https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot_3.2.0/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-resource-server-by-filter-stateless/src/main/java/com/azure/spring/sample/aad/security/AADWebSecurityConfig.java#L20) or [AADAuthenticationFilter](https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot_3.2.0/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-resource-server-by-filter/src/main/java/com/azure/spring/sample/aad/security/WebSecurityConfig.java#L20) in your application.
5. "azure.activedirectory.user-group" is NOT configured.


## Questions about your own resource-server

How do you implement your own resource server? Do you implement in by [Minimal Configuration for JWTs](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2resourceserver-jwt-minimalconfiguration)?

Of course, it's better to provide a sample project to reproduce your problem.

**Comment by blacelle** [comment]
@chenrujun Our application is both a wen-application and a resource server.

**Comment by blacelle** [comment]
> How do you implement your own resource server?

Through the deprecated spring-security-oauth2 resource-server.

**Comment by chenrujun** [comment]
@blacelle 
> Our application is both a wen-application and a resource server.

So you are using `azure-spring-boot-starter-active-directory` to implement web-application, and using `spring-security-oauth2-resource-server` to implement resource-server?

I think it's not a valid to work as web-application and resource-server at the same time.

For example, when an user access an endpoint, if user is not logged in, resource-server will return `401`, but web-application will redirect to login page.  What's your application's behavior in this case?

**Comment by blacelle** [comment]
> So you are using azure-spring-boot-starter-active-directory to implement web-application, and using spring-security-oauth2-resource-server to implement resource-server?

Yes.

> I think it's not a valid to work as web-application and resource-server at the same time.

I works pretty well until given migration.

> For example, when an user access an endpoint, if user is not logged in, resource-server will return 401, but web-application will redirect to login page. What's your application's behavior in this case?

Each endpoint has a specific auth pattern. e.g. we protect `/admin/*` with AAD tokens and `/user/*` with our own resource-server oauth2 tokens: we want AAD security layer to behave like there was no resource-server in the same app. We workarounded part of issues regarding this migration by duplicating AAD classes, to remove the @ConditionOnMissingClass triggering on `spring-security-oauth2-resource-server`

**Comment by chenrujun** [comment]
@blacelle 

After version `3.0.0`, the `aad-starter` does not support web-app and -resource-server work in the same application.

Since you have the requirement, now I'm thinking about how to implement it.

**Comment by raniemi** [comment]
Hi @chenrujun, I just wanted to "bump"/vote this issue up since it's holding up a release for a customer.

**Comment by chenrujun** [comment]
Hi, @raniemi .
Thank you for your feedback.
Now I'm busy with other tasks, so it's milestone is still on August.
And PR is welcome.

**Comment by blacelle** [comment]
The official way to achieve this relies essentially on the following (new?) variable:

    azure.activedirectory.application-type: web_application_and_resource_server

**Comment by chenrujun** [comment]
> The official way to achieve this relies essentially on the following new variable:
> 
> ```
> azure.activedirectory.application-type: web_application_and_resource_server
> ```

@blacelle , thank you for your comment.

And here is related document: https://github.com/Azure/azure-sdk-for-java/tree/f599405caaf14e49dac005d238cf46db2407ea5a/sdk/spring/azure-spring-boot-starter-active-directory#web-application-and-resource-server-in-one-application
