### ISSUE TITLE
Azure java api vm.deallocateAsync() not deallocating the vms.

### ISSUE THREAD

**Issue by giridharkn** [Azure/azure-sdk-for-java#1986]
Hi,

I was trying to deallocate vm asynchronously using the vm.deallocateAsync() method. It is not at all deallocating the vms. Only the synchronous deallocate is working fine vm.deallocate(). 
Please help me to resolve the issue.

tried in 1.3 and 1.4 java sdk

Thanks and Regards
Giridhar K N

**Comment by anuchandy** [comment]
@giridharkn, `vm.deallocateAsync()` returns `Completable`, it represents the work (de-allocation) that is yet to be started not a work is progress. In-order to start the work consumer needs to subscribe to start. are you doing it?

**Comment by anuchandy** [comment]
to be more precise, the returned `Completable` is [cold](https://github.com/Froussios/Intro-To-RxJava/blob/master/Part%203%20-%20Taming%20the%20sequence/6.%20Hot%20and%20Cold%20observables.md#cold-observables)

**Comment by giridharkn** [comment]
@anuchandy  Yes it deallocated after subscribe. But still it works like blocking call. What i am expecting is to use as non blocking. It should return to me and deallocate in background. How to do this ?

**Comment by giridharkn** [comment]
@anuchandy  As mentioned in following issue, i had tried subscribeOn(Schedulers.io()). It's not deallocating the VM. Tried in both 1.3 and 1.4 java sdk. Please help me

https://github.com/Azure/azure-sdk-for-java/issues/1956

**Comment by giridharkn** [comment]
@anuchandy Please help me to run the deallocation task as async. Tried in both jars it behaving as blocking.

**Comment by anuchandy** [comment]
@giridharkn - deallocation is a long running operation, if we wanted to do some other operation in parallel with that, the correct way is - express the other operation as an Observable and merge that Observable with the Observable representing de-allocation [run both in io scheduler]. This means your application needs to build from bottom to top in reactive (async) way. This way we get notification when de allocation completes and can do something else that depends on the result of de-allocation.

If your application is not reactive from top to bottom and not interested in getting an event upon completion of de-allocation then easiest way is following code, which basically fire the de-allocate request over wire then timeout, because of that after 2 sec control should reach next line (`int i = 0`)

```java
        vm.deallocateAsync()
                .toObservable()
                .subscribeOn(Schedulers.io())
                .timeout(2, TimeUnit.SECONDS.SECONDS, rx.Observable.just(null))
                .toBlocking().last();

       int i = 0;
```

**Comment by giridharkn** [comment]
@anuchandy thanks a lot for the resolution :) working fine :)

**Comment by giridharkn** [comment]
@anuchandy yes my application is not interested in getting an event upon completion. This is fine for me.

**Comment by anuchandy** [comment]
@giridharkn nice, closing this issue then, feel free to re-open if you come across any issue.

**Comment by mayankkthr** [comment]
@anuchandy My application is not reactive. I want to use applyAsync while updating deployment. Can you please provide me code for it? I am not interested in getting notified after the update is complete.
