### ISSUE TITLE
[FEATURE REQ] mgmt, avoid customer calling API that retrieve service api-version automatically

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#19870]
I.e. the version of `getById` and `deleteById` without `api-version` parameter in `GenericResources`.

**Comment by xinyanmsft** [comment]
Currently if apiVersion is not passed in, GenericResources.checkExistenceById, getById and deleteById will default to use latest API version. Automatically use the latest API version may result in stability issues because latest API could carry over breaking changes, and there is no guarantee latest API version in one region is supported by a different ARM region (this could happen during resource provider deployment). Please deprecate the logic to get latest API version, and require caller to pass in API version explicitly.
