### ISSUE TITLE
Docs onboarding automation

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-java#20213]
In the `<lang> - docindex` pipeline: 

1. Add a script in eng/scripts/ that reads the language-specific package .csv file ([example](https://github.com/Azure/azure-sdk/blob/master/_data/releases/latest/java-packages.csv)) 
2. Generates the appropriate onboarding outputs (package.json, latest.csv, etc.) for the language
3. Opens a PR against the docs repo with the updated onboarding artifact.

**Comment by sima-zhu** [comment]
I have two pipelines setup for the task:
1. Update target CI.
Pipeline:https://dev.azure.com/azure-sdk/internal/_build?definitionId=2499
Branch:https://github.com/Azure/azure-sdk-for-java/tree/regen_package_json
2. Merge Job CI commit to live.
Pipeline:https://dev.azure.com/azure-sdk/internal/_build?definitionId=2577
Branch:https://github.com/Azure/azure-sdk-for-java/tree/merge_live

**Comment by sima-zhu** [comment]
**More cleanup scripts needed for the tasks.**

**We enabled the two pipeline for docs repo.**
We onboard with two functionalities:
1. We are able to sync with release csv, and have correct supersedes version for all packages.
2. We are able to make docs live everyday, instead of manually doing this weekly.
