### ISSUE TITLE
Make CosmosAsyncClient non final so mocking libraries can mock it's methods

### ISSUE THREAD

**Issue by silvercodemode** [Azure/azure-sdk-for-java#20365]
**Is your feature request related to a problem? Please describe.**
Recently on 2 separate projects I needed to write unit tests for code that uses CosmosAsyncClient and in order to mock it's methods I had to enable a flag in Mockito that allows mocking of final methods; the issue with this is that flag being enabled made it jdk dependent whether or not these tests would crash or not which caused much communication between teams about "this repos tests need to be ran with x jdk" and just adds an unneeded landmine to the development process. If CosmosAsyncClient (and the other user exposed methods) were non final it isn't necessary to enable any flags that (I presume) reach into jdk specific internals and cause erratic errors.

**Describe the solution you'd like**
Simply make all user exposed classes and methods non final so they can be mocked using Mockito (this will likely be how many java developers would like to unit test code calling these methods so I doubt this is super unique to me).

**Describe alternatives you've considered**
I could write a wrapper interface to the methods I am calling but it would be a very shoehorned not really abstract interface that just one for one uses the same methods of CosmosAsyncClient. This shouldn't be necessary because CosmosAsyncClient is very cosmos specific and it is unlikely any interface wrapping it could be implemented by anything else so it just makes more sense to not bother wrapping it at all and mock it with a mocking library which you can't (without enabling an option that caused issues) because it is final.

**Comment by joshfree** [comment]
@kushagraThapar could you please take a look

**Comment by kushagraThapar** [comment]
@MP7373 - Let me confirm that this scenario is not unique to you :) 
However, we intentionally make our classes final, as we don't want customers to extend those classes (whether intentionally or un-intentionally). You can still mock the final classes, using Mockito v2 framework : https://www.baeldung.com/mockito-final
cc @srnagar - as this is also part of the Azure SDK conventions.

**Comment by omarsmak** [comment]
@kushagraThapar the issue is, I don't even get the whole rational of making all classes package private or final, the end "users" here in this context are developers whom would have reason why they "need" to extend such classes. At some point, it makes the whole unit test a mocking hell or a wrapper hell to just for example a simple method, not to mention, I am not really fan of using complete mocking frameworks, I tend to prefer to override the methods and have my own control without the usage any mocking. 
At least introduce "interfaces" or "abstract" classes for clients and change the model objects to be public visible instead of private package constructors, e.g: `CosmosContainerResponse`? 
Seriously, after working intensively with Azure SDK for the last months to develop Azure components for Apache Camel, I find the whole "unit test" experience for Azure clients painful in comparison to AWS SDK where they have clear interfaces for the services clients. Example [Amazon S3 client](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3.java) and one of the models that being returned by the client [CompleteMultipartUploadRequest](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/CompleteMultipartUploadRequest.java)

**Comment by kushagraThapar** [comment]
@srnagar can you please provide some guidelines on this as it is not specific to cosmos, rather to all of our azure java SDKs.

**Comment by TheovanKraay** [comment]
@srnagar thoughts? Regardless, we'll consider some solutions during planning for next semester.

**Comment by srnagar** [comment]
@TheovanKraay @kushagraThapar We generally start out by making classes `final` but if we have good documentation and design to allow for inheritance, we can go ahead and make the class non-`final`. 

Consider reading this before removing `final`.
https://blogs.oracle.com/javamagazine/post/java-inheritance-design-document

While the intention of making classes `final` was to prevent extending types that are not ready/designed for inheritance, it also has the side effect of not being easily mockable. However, the [latest major version of mockito](https://www.infoq.com/news/2023/01/mockito-5/) supports mocking final classes out of the box. Hope that helps answer the question and Cosmos can validate the client design before making them non-final.

**Comment by kushagraThapar** [comment]
thanks @srnagar for the guidance, I agree with making classes not-final just for the sake of testing. 
@omarsmak hopefully that answers your question, if you still have any doubts or need help on how to test final classes, feel free to create another issue, thanks!
