### ISSUE TITLE
[FEATURE REQ] Java Service Bus SDK - Allow peeking of scheduled messages in a topic (consistent with .NET Core SDK)

### ISSUE THREAD

**Issue by sujitdmello** [Azure/azure-sdk-for-java#20510]
**Description**
Scheduled messages sit in a Topic until the scheduled time is current at which point, they move to the associated subscription. We have a need to peek these messages while they are still in the Topic. The use-case is to copy these messages to another namespace in the case of a disaster recovery scenario.

**Test Results**
The latest Java SDK for Service Bus (V7.2.0-beta.1) does not allow peeking these messages. Here is a snippet of code that I tried:
```Java
            ServiceBusReceiverClient receiverClient = new ServiceBusClientBuilder()
                    .connectionString(connectionString)
                    .receiver()
                    .topicName(topicName)
                    .buildClient();

            var o = receiverClient.peekMessage();
            System.out.println(o.getBody().toString());
```

This results in an error from the Builder:
```
topicName (sujittest) must have a subscriptionName associated with it.
```

**Expected Results**
Using the latest .NET Core SDK (V7.1.1) the following code was able to Peek the scheduled messages on the Topic:
```csharp
            ServiceBusClient client = new ServiceBusClient(connectionString);
            // Peek at topic for Scheduled messages
            Console.WriteLine("Peeking for scheduled messages:");
            var Receiver = client.CreateReceiver("sujittest");            
            ServiceBusReceivedMessage PeekedMessage = null;
            while ((PeekedMessage = Receiver.PeekMessageAsync().Result) != null)
            {
                // Only peek scheduled messages
                if (PeekedMessage.ScheduledEnqueueTime != null)
                    Console.WriteLine(PeekedMessage.ScheduledEnqueueTime + " - " + PeekedMessage.Body.ToString());
            }
```
The expectation is that the .NET Core and Java SDKs are consistent in behavior. 

**Alternatives Considered (also do not work)**
- Previous versions of the new Java SDK (V7.X.X)
- Older Java SDK (V3.6.1) *Edited - V3.6.2 works - allows browsing of Topics*
- Service Bus JMS SDK (V0.0.7)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by hemanttanwar** [comment]
@sujitdmello Just to clarify for the dotnet API you are using `client.CreateReceiver("sujittest"); ` According to API this must be a "queueName"  , here https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Client/ServiceBusClient.cs#L288

I understand it works for you, it it was not an  intentional feature.  

We in SDK team are going to discuss about this feature and how we want to support this.  Thank you for your query.

@joshfree

**Comment by sujitdmello** [comment]
Understood, but the ability to peek at messages in Topics is very useful. This feature (browsing of Topics) *does* work in the 'old' Java SDK for Service Bus - @yvgopal just fixed it in V3.6.2 https://github.com/Azure/azure-sdk-for-java/releases/tag/azure-servicebus_3.6.2

**Comment by hemanttanwar** [comment]
We understand that it a supported feature  in V3.x and we are going to consider this for discussion in our team. Your use case and query is important data point in our discussion.

**Comment by ramya-rao-a** [comment]
@ki1729 The reason the .NET code snippet shared by @sujitdmello above works is because the code assumes that a queue name has been passed. Can you try the Java code snippet shared by @sujitdmello and pass the topic name to `queueName()` instead of `topicName()` and see if you are able to peek into the topic?

If that can be done, then we can document that as a workaround until the service provides us with a dedicated endpoint to peek into scheduled messages

**Comment by ki1729** [comment]
@sujitdmello passing the topic name to queueName() when creating the client allows you to peek **scheduled (only)**  messages. Even though it is not intended usage. Please let us know if you have issues with using the workaround.
