### ISSUE TITLE
[QUERY]  blobClient.upload(inputStream, -1) not working

### ISSUE THREAD

**Issue by amzu-dev** [Azure/azure-sdk-for-java#20528]
**Query/Question**
I am trying to use blobClient.upload(inputStream, -1) as the file size is unknown and is streamed from a URL. 

I am getting the following error.

`2021-04-11 07:43:12,251Z [main] ERROR c.a.s.c.i.StorageImplUtils - The value of the parameter 'length' should be between 0 and 9223372036854775807.
Exception in thread "main" java.lang.IllegalArgumentException: The value of the parameter 'length' should be between 0 and 9223372036854775807.`

The document below says that if the length is unknown I can specify -1. 

https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.storage.blob.cloudblockblob.upload?view=azure-java-legacy#com_microsoft_azure_storage_blob_CloudBlockBlob_upload_final_InputStream_final_long_

but it looks like this is not working.

Can you please let me know how I could use the upload method to upload using inputstream of unknown size? 

**Setup (please complete the following information if applicable):**
 - OS: MacOS bigsur
 - IDE : IntelliJ Idea 2021
 - Library Version: implementation("com.azure:azure-storage-blob:12.10.2")
 - Language: Kotlin

**Comment by joshfree** [comment]
@gapra-msft PTAL

**Comment by jaschrep-msft** [comment]
You appear to be using the documentation for our legacy SDK. The SDK for v12 was completely rewritten with a completely different API surface. Notice the difference in class name between the docs and your code. [Here](https://docs.microsoft.com/en-us/java/api/com.azure.storage.blob.specialized.blockblobclient.upload?view=azure-java-stable) is the docs page for the method you are calling. Look into BlobClient instead of BlockBlobClient for methods that can handle streams of unknown length.

**Comment by amzu-dev** [comment]
Thank you

**Comment by gapra-msft** [comment]
Hi @amzu-dev 

Do you have any further questions regarding the upload API? If so, we are happy to help. If not, feel free to close this issue.

**Comment by amzu-dev** [comment]
Thank you. No further queries. Closing the issue.
