### ISSUE TITLE
How to retrieve public Ip address of VMSS instances

### ISSUE THREAD

**Issue by ying1i** [Azure/azure-sdk-for-java#2055]
After creating VMSS with public Ip, though cli az vmss list-instance-public-ips returns public ip addresses, I'm not sure how to retrieve it from Java SDK.

Azure.virtualMachineScaleSets().virtualInstances().list() does not have public ips populated
Azure.networkInterfaces().listByVirtualMachineScaleSet() returns id for public ip addresses
Azure.publicIpAddress().getById() returns null with the id retrieved from the previous step

**Comment by ying1i** [comment]
In case anybody would like to know, it is
Azure.publicIpAddress().inner()

**Comment by Neskz** [comment]
What is your code before. For me, it's impossible because public ip address is not associated to the VMSS. I didn't found a function which allows to associate public ip address and the VMSS. The unique possibility is ".withVirtualMachinePublicIP()". But i didnt found a function to obtain the public ip address of the VMSS.
