### ISSUE TITLE
[BUG] ServiceBus docs don't explain the difference between receiver & processor and why to use one over the other

### ISSUE THREAD

**Issue by jfurmankiewiczpros** [Azure/azure-sdk-for-java#20602]
**Describe the bug**

One doc says to use Recevier to receive messages:
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/servicebus/azure-messaging-servicebus#create-service-bus-clients-using-a-connection-string

other doc says to use a Processor:
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/servicebus/azure-messaging-servicebus#receive-messages

Migration guide says to use Processor as well
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/migration-guide.md#receiving-messages

But processor does NOT have an option for " Duration maxAutoLockRenewDuration", whereas receiver has. So Receiver seems more powerful.

No explanation as to which one to use when, they both seem to fulfill the same use case, but in different ways.

Not clear which one to use when migrating to the new SDK and what are the pros & cons of each.

**Comment by joshfree** [comment]
@hemanttanwar could you please take a look?

**Comment by hemanttanwar** [comment]
@jfurmankiewiczpros Thank  you for the query.
1. We have added  'processor : maxAutoLockRenewDuration()' in latest release '7.3.0-beta.1' .
2. When to use processor : We will add more details about in documentation. 'ServiceBusProcessorClient' This is a synchronous client with promise of reconnection even after exhausting all the retry. It gives you convenient features like auto complete and auto lock renew by default. The processor uses `ServiceBusReceiverAsyncClient` in background.   'ServiceBusProcessorClient' : You can think of this as convenience layer over receiver. 

3. If you want to use 'ServiceBusReceiverClient' instead of 'ServiceBusProcessorClient', that is fine too. 'ServiceBusReceiverClient' is have more API and it is lower level client. 

Hope this clarifies.

**Comment by hemanttanwar** [comment]
Closing this issue as we have added details in the readme.
