### ISSUE TITLE
How do I get the token via AAD starter?

### ISSUE THREAD

**Issue by einue** [Azure/azure-sdk-for-java#20980]
Can you please add the example request to get the Token for the example "Accessing a resource server"?

I get a token for client credentials. But finally I get a 401 with that token.

[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4b76f747-915d-ee17-02e6-daa22b57d733
* Version Independent ID: 98ce570a-f42f-68bb-aea4-a20b0f357c2a
* Content: [Azure AD Spring Boot Starter client library for Java](https://docs.microsoft.com/de-de/java/api/overview/azure/spring-boot-starter-active-directory-readme?view=azure-java-stable)
* Content Source: [docs-ref-services/latest/spring-boot-starter-active-directory-readme.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/spring-boot-starter-active-directory-readme.md)
* Service: **springbootspringboot**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by saragluna** [comment]
@einue could you please provide more details, like how you configure your application and which dependencies you added in your project?

**Comment by einue** [comment]
@saragluna sure.

I registered an App like described in this article https://github.com/Azure/azure-sdk-for-java/tree/azure-spring-boot-starter-active-directory_3.4.0/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-resource-server .


Furhtermore I added a secret for my app in azure portal.
I added the following scopes :

![image](https://user-images.githubusercontent.com/33625116/116249488-2a6d1d80-a76d-11eb-8ee3-371ff0577751.png)


Now I want to try make a get request of the homecontroller like
`@GetMapping("/test")
    @ResponseBody
    @PreAuthorize("hasAuthority('SCOPE_Api.Read')")
    public String test() {
        return "test";
    }`

At first I need the access-Token, right? 
I get an acess token via postman with the following settings:
![image](https://user-images.githubusercontent.com/33625116/116249970-9bacd080-a76d-11eb-87a2-0c0dd902c088.png)

Then I try to make a request to the endpoint test:

![image](https://user-images.githubusercontent.com/33625116/116250378-f6462c80-a76d-11eb-99a9-e5392cb742f9.png)


I also tried to add "Api.Read" for scope during getting the token.

**Comment by einue** [comment]
Hey I think I have the solution:

Requesting the Access token wit grant_type password works:

![image](https://user-images.githubusercontent.com/33625116/116302609-b13bed80-a7a1-11eb-9d50-f0a14203b04f.png)


Therefore I had to add "Api.Test" as delegated permission

**Comment by chenrujun** [comment]
Hi, @einue 

Thank you for reaching out.

---
> How do I get the token?

You can get the token by :
1. [auth code grant](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow)
2. [client-credential grant](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow)
3. [resource owner password credential grant](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc).
etc..

I suggest you to use [resource owner password credential grant](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc), it's the easiest way.

---
> Hey I think I have the solution:
> Requesting the Access token wit grant_type password works:

Then you are using [resource owner password credential grant](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc).

---
> Therefore I had to add "Api.Test" as delegated permission

If you are using [resource owner password credential grant](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc), then yes, you should add "Api.Test" as delegated permission.

You can use another client-id instead of use the client-id of the resource-server.

For example:

* `client-id` for `resource-server-aaa`: `aaaaaaaa-14a6-49ae-97bc-6eba6914391e`
* `client-id` used to get `access-token` for `resource-server-aaa`: `bbbbbbbb-14a6-49ae-97bc-6eba6914391e`

`bbbbbbbb-14a6-49ae-97bc-6eba6914391e` can be deleted after developing.

---
> Is there a way, to restrict the preauthorize by user-groups instead of scopes?

It is already support in [web-app](https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot-starter-active-directory_3.4.0/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-webapp/src/main/java/com/azure/spring/sample/aad/controller/RoleController.java#L15)

If you wan to group in resource-server, you should:
1. [Configuring groups optional claims](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims#configuring-groups-optional-claims)
2. Config your own `WebSecurityConfigurerAdapter` instead of using the [default one](https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot-starter-active-directory_3.4.0/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/aad/webapi/AADResourceServerWebSecurityConfigurerAdapter.java#L15-L20)

```
public class AADResourceServerWebSecurityConfigurerAdapter extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        // @formatter:off
        http.oauth2ResourceServer()
            .jwt()
            .jwtAuthenticationConverter(new AADJwtBearerTokenAuthenticationConverter("groups"));
        // @formatter:off
    }

}
```

Now I'm thinking about make it to be a configuration item, like this:
```
azure:
  activedirectory:
    resource-server:
      authorities-claim-name: group
      authority-prefix: ROLE_
      principal-claim-name: sub
```

**Comment by einue** [comment]
@chenrujun : thank you very much for your answer.

A separate tag in the configuration would be really great.

I have the following scenario:
I secure a spring-boot web application by the full oauth2-flow, also with client and secret.

In the same project I want to add a resource server with a new registered app in azure ad - so I have another clientId and clientSecret...

**Comment by chenrujun** [comment]
@einue 

> I secure a spring-boot web application by the full oauth2-flow, also with client and secret.
> In the same project I want to add a resource server with a new registered app in azure ad - so I have another clientId and clientSecret...

I think you are waiting this PR: https://github.com/Azure/azure-sdk-for-java/pull/20687

**Comment by einue** [comment]
@chenrujun  amazing, i hope you publish this in a stable version soon on maven central :)

**Comment by chenrujun** [comment]
Hi, @einue 

This issue is closed.
Let's track your requirement by these links:
1. https://github.com/Azure/azure-sdk-for-java/issues/21005
2. https://github.com/Azure/azure-sdk-for-java/pull/20687
