### ISSUE TITLE
[BUG] Connection reset by peer is not handled well by retry policy

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-java#21091]
We observe Connection reset by peer being propagated as an error in tests and reported by customers.
Looking for holistic solution for this problem in the core.

References:

Customer reported: https://github.com/Azure/azure-sdk-for-java/issues/21066

![image](https://user-images.githubusercontent.com/61715331/116720781-713b5d00-a991-11eb-8c8c-d10c771f72f5.png)

![image](https://user-images.githubusercontent.com/61715331/116719347-d1310400-a98f-11eb-8156-f5266e7b8e1c.png)

**Comment by somanshreddy** [comment]
@kasobol-msft A similar issue seen here #15215 

CC: @rickle-msft @alzimmermsft

**Comment by alzimmermsft** [comment]
Thanks for submitting this issue @kasobol-msft.

Just finished a rough investigation on this. It appears that when the expected response body of a request is `void`/`Void` the networking layer won't eagerly read the response body (as there isn't expected to be one). But, later in the call stack when converting the response headers, and body but there is none here, into the returned response there is an attempt to consume/fast-forward the response body. This is where the issue lies as doing this can result in a state when the remote closes/closed the connection triggering an exception to be thrown. Unfortunately, at this point the response has egressed past the retry policy, resulting in the exception being thrown to the caller instead of being captured and retried.

**Comment by kasobol-msft** [comment]
There seems to be few missing cases that we should cover:
- buffered upload
- download
- pageable operations

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=900469&view=ms.vss-test-web.build-test-results-tab&runId=19372912&resultId=103744&paneView=debug
![image](https://user-images.githubusercontent.com/61715331/118667492-eb008280-b7a8-11eb-882f-5be01c2a4dea.png)
![image](https://user-images.githubusercontent.com/61715331/118667543-f5228100-b7a8-11eb-8478-99b36fe76338.png)
![image](https://user-images.githubusercontent.com/61715331/118667603-023f7000-b7a9-11eb-9e33-f47f9ccee10f.png)

**Comment by kasobol-msft** [comment]
![image](https://user-images.githubusercontent.com/61715331/121382139-2b13da80-c8fb-11eb-9019-9aac22057783.png)
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=938985&view=ms.vss-test-web.build-test-results-tab&runId=20123708&resultId=101687&paneView=debug

**Comment by kasobol-msft** [comment]
Looks like there are still some gaps https://dev.azure.com/azure-sdk/internal/_build/results?buildId=954096&view=ms.vss-test-web.build-test-results-tab&runId=20421522&resultId=100738&paneView=debug

![image](https://user-images.githubusercontent.com/61715331/122599538-64e39000-d023-11eb-873a-fa903d720ab5.png)

**Comment by alzimmermsft** [comment]
@kasobol-msft, has this happened recently or has this issue been fixed by #22647

**Comment by kasobol-msft** [comment]
This has happened recently, most likely because we exhausted retry count. We should follow up with aggregated exception and logs from retry policy.

**Comment by alzimmermsft** [comment]
Closing as this hasn't been a reported issue for a while and if this is seen again a new issue should be opened.
