### ISSUE TITLE
Investigate Supporting GraalVM

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#21192]
Investigating having Azure SDKs offering support for GraalVM.

Investigation for GraalVM support:
- [ ] Add testing pipeline that runs on GraalVM.
   - [ ] Running on Linux pipeline is fine.
   - [ ] Copy common-stage template.
        - [ ] Create a new build pipeline off ci.yml.
	- [ ] Farm out test failures.
	- [ ] Optimisations to compile/runs.

**Comment by stliu** [comment]
what's the plan of this issue? is it on our roadmap? we're also considering to support sprint native

**Comment by benbp** [comment]
The azure pipelines ubuntu 20.04 images recently added Graal CE 21.1.0: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#graalvm

Assuming that's a workable version to use, then the infra side of things likely won't involve too much more than provisioning a new high mem pool.

**Comment by JonathanGiles** [comment]
@stliu Let's sync up - I've got a demo that I wanted to show the other week in our meeting that is Spring Native + Azure SDKs running as a native image. I would like to get the Azure Spring Boot Starters supported in my efforts too.

**Comment by JonathanGiles** [comment]
@benbp That version is the latest and what we are using for our development - so that is perfect for the ubuntu image. If we could get the same in Windows and MacOS, we're golden.

**Comment by joshfree** [comment]
Updating issue for tracking the EngSys part of GraalVM support with a target of ~November for having a pipeline we can run

**Comment by srnagar** [comment]
Related issue - https://github.com/Azure/azure-sdk-for-java/issues/21735

**Comment by benbp** [comment]
I talked with @conniey and @joshfree yesterday, summary:

Once I get some more info from the team on GraalVM environment setup, I'll plug the pieces in to a new pipeline definition (similar to how cosmos tests are forked off archetype-sdk-client). The thinking is the core JVM vs. GraalVM setup might be tedious to unwind from the main template, so while this is still in the experimentation phase, there's no need to generalize the pipeline.

After the new pipeline is set up with preliminary values changed, I'll hand it off back to the java team to iterate on getting it fully working. The target right now is just ubuntu20 support since that's the only agent image with GraalVM pre-installed so far.

We may or may not want to investigate artifact caching depending on how slow the dev loop is due to GraalVM pre-compile times.

**Comment by srnagar** [comment]
We had a sync up with Patrick on the requirements for running GraalVM builds and tests. 

@hallipr could you please update this with your findings on whether we can use 1ES pool with a custom image to run GraalVM pipelines?

**Comment by alzimmermsft** [comment]
Closing as this is tracked by #21735
