### ISSUE TITLE
[app] Configure attribute to access the user's name

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21587]

**Comment by chenrujun** [comment]
Closing this issue, because it's already implemented by [AADAuthenticationProperties#userNameAttribute](https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot-starter_3.4.0/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/autoconfigure/aad/AADAuthenticationProperties.java#L52)
