### ISSUE TITLE
[misc] Support conditional access

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21592]

**Comment by chenrujun** [comment]
Closing this issue, because this feature has already been implemented.

Refs: [AADConditionalAccessIT](https://github.com/Azure/azure-sdk-for-java/blob/azure-spring-boot-starter_3.4.0/sdk/spring/azure-spring-boot-test-aad/src/test/java/com/azure/test/aad/selenium/conditional/access/AADConditionalAccessIT.java#L39).
