### ISSUE TITLE
Apache camel support

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21608]
Apache Camel is another popular integration framework in java world

quote from @Ashish Chhabria 

Hi Sean, Jialin,

 

Do you (and team) own our contributions to the Apache Camel project? There is an opportunity to add the JMS starter for Azure Service Bus to Apache Camel as well.

camel-spring-boot/components-starter at master · apache/camel-spring-boot (github.com)

 

Some comparable starters are

Active MQ - camel-spring-boot/components-starter/camel-activemq-starter at master · apache/camel-spring-boot (github.com)

Rabbit MQ - camel-spring-boot/components-starter/camel-rabbitmq-starter at master · apache/camel-spring-boot (github.com)

 

The mechanics should be similar to what you did for the regular Spring Boot starter.

 

Do let me know if you own (or can own) this workstream.

**Comment by jialigit** [comment]
> Apache Camel is another popular integration framework in java world
> 
> quote from @Ashish Chhabria
> 
> Hi Sean, Jialin,
> 
> Do you (and team) own our contributions to the Apache Camel project? There is an opportunity to add the JMS starter for Azure Service Bus to Apache Camel as well.
> 
> camel-spring-boot/components-starter at master · apache/camel-spring-boot (github.com)
> 
> Some comparable starters are
> 
> Active MQ - camel-spring-boot/components-starter/camel-activemq-starter at master · apache/camel-spring-boot (github.com)
> 
> Rabbit MQ - camel-spring-boot/components-starter/camel-rabbitmq-starter at master · apache/camel-spring-boot (github.com)
> 
> The mechanics should be similar to what you did for the regular Spring Boot starter.
> 
> Do let me know if you own (or can own) this workstream.

As per camel-spring-boot/components-starter,  *camel-azure-servicebus-starter* and *camel-jms-starter* are provided.  So azure servicebus can now be integrated in camel both as 'non-jms' and 'jms' style.

 Regarding 'jms' integration, the camel-jms-starter is not specificlly implemented for servicebus specific purpose. That is to say, using this jms-starter, the configuration is not fully automatic.

So, a new camel servicebus-jms starter like may be needed, and this is to be considered. And as per this, another issue is about the servicebus jms support.  Now we have azure-servicebus-jms lib which utilizes JMS2.0 interface and one spring-cloud-azure-starter-servicebus-jms prepared. And one issue for enabling caching and pooling support is tracked with:
[issue-enable-caching and pooling](https://github.com/Azure/azure-sdk-for-java/issues/26072).

For now, this issue is closed for ease of concern.
