### ISSUE TITLE
Azure Storage ADLS gen2 

### ISSUE THREAD

**Issue by jselamy** [Azure/azure-sdk-for-java#22350]
Hi,

I'm experiencing a behaviour that wasn't present before. Ever since we've change the configuration of the Storage to use ADLS Gen2. Using the AppendBlobClient to append to existing blob storage. The UI displays a size 0KB next to the file. Perhaps when we do click in it to check the file is not empty right after, the size is not updated to the appropriate value.

Any clue ? if we're doing something wrong ?

Here's a snippet of the code

```
private void writeToBlob(Object item) throws Exception {
    String line = writer.writeValueAsString(item);
    try (ByteArrayInputStream dataStream = new ByteArrayInputStream(line.getBytes())) {
        client.appendBlock(dataStream, dataStream.available());
        log.debug("Appended to block the data -> {}", line);
    } catch (IOException e) {
        throw new RuntimeException(e);
    }
}
```

**Comment by rickle-msft** [comment]
Hi, @jselamy. Thank you for asking this question. 

I see you're making a call to append block. Since you're trying to use ADLS Gen 2, I wonder if you might be confusing the AppendBlobClient with the DataLakeFileClient. The latter also has an append method that is actually for use with ADLS Gen 2. Then any appends must be followed by a flush. Is there a reason why you're using the AppendBlobClient specifically?

**Comment by amishra-dev** [comment]
please let us know if you need further assistance.
