### ISSUE TITLE
[BUG] Some polled messages are moved to dead letter queue without errors being thrown

### ISSUE THREAD

**Issue by lordarcy** [Azure/azure-sdk-for-java#22423]
**Describe the bug**
I have an integration module that is using the azure-messaging-servicebus library version 7.1.0. We are using that library to poll a subscription exposed by Microsoft on the service bus. Occasionally some of the messages are posted by Microsoft but not received by Red Hat. When Microsoft engineers have examined the messages they have been moved to the dead letter queue after ten failed polling attempts. However, we don't see any indication that the message was polled by the library and there are no message in our log. We have the logging level set to WARN.

***Exception or Stack Trace***
There is no exception or log entry.

**To Reproduce**
Unfortunately this only happens occasionally so I don't have a consistent way to reproduce the problem.

***Code Snippet***

```java
LOGGER.info("MS Poller: Receive message ===>>>");
ServiceBusReceiverClient receiver = new ServiceBusClientBuilder()
    .connectionString(azureServiceBusConfig.azureBusConnectionString)
    .receiver()
    .topicName(azureServiceBusConfig.azureBusTopicName)
    .subscriptionName(azureServiceBusConfig.azureBusSubscriptionName)
    .buildClient();

LOGGER.info("MS Poller: Getting message...");
IterableStream<ServiceBusReceivedMessage> messages = receiver.receiveMessages(1, Duration.ofSeconds(1));
LOGGER.info(String.format("MS Poller: Retrieved messages = %b%n", messages.iterator().hasNext()));
ASBMessageResponse response = new ASBMessageResponse();

for (ServiceBusReceivedMessage message : messages) {
    LOGGER.info(String.format("MS Poller: Retrieved message = %s%n", message.toString()));
}

```

**Expected behavior**
If an error occurs while trying to poll a message or some other issue causes the message to not get properly polled then an exception should be thrown. At the very least there should be some log entries at ERROR level.

**Screenshots**

**Setup (please complete the following information):**
 - OS: RHEL 7.5
 - IDE: n/a
 - Library/Libraries: com.azure:azure-messaging-servicebus:7.1.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X ] Bug Description Added
- [? ] Repro Steps Added
- [X ] Setup information Added

**Comment by joshfree** [comment]
Hi @lordarcy, @YijunXieMS and @hemanttanwar will follow up with you shortly.

**Comment by YijunXieMS** [comment]
@lordarcy I'll look into this ASAP

**Comment by YijunXieMS** [comment]
Hi @lordarcy your code should receive only one message with the following code. 
```java
IterableStream messages = receiver.receiveMessages(1, Duration.ofSeconds(1));
```
From the existing information, I don't know why other messages are dead-lettered. 
Anyways, do you consider using the higer-level API `ServiceBusProcessorClient`? It receives indefinitely and recovers from network error. You just need to provide a callback function that handles messages.
BTW, could you upgrade to the latest version of SDK?

**Comment by lordarcy** [comment]
@YijunXieMS we are working on updating the library to the latest version but there were some dependencies brought in after March that are conflicting with our integration application. I will investigate using the ServiceBusProcessorClient but since that will require rearchitecting the application (which is currently stateless) I don't have an ETA for when/if that can be done.

Do you have any suggestions for logging that an be enabled to debug the process of retrieving messages? At the moment I don't get any indication of a processing errors and there is nothing showing up in the logs with the logging level set to warning.

**Comment by ramya-rao-a** [comment]
@lordarcy I took another look at your issue here. While moving to the ServiceBusProcessorClient has its benefits, mainly the fire and forget mechanism, auto lock renewal, auto complete feature, receiving indefinitely and recovering from failures, this move will not help with your problem with messages moving to the dead letter queue without the client telling you why.

Fortunately, dead lettered messages contain the reason as to why they were dead lettered. See [moving msgs to DLQ](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dead-letter-queues#moving-messages-to-the-dlq). The next time this happens to your application, we would recommend that you first check the dead letter reason on the message. See
- [ServiceBusReceivedMessage.getDeadLetterReason()](https://docs.microsoft.com/en-us/java/api/com.azure.messaging.servicebus.servicebusreceivedmessage.getdeadletterreason?view=azure-java-stable#com_azure_messaging_servicebus_ServiceBusReceivedMessage_getDeadLetterReason__)
- [ServiceBusReceivedMessage.getDeadLetterDescription()](https://docs.microsoft.com/en-us/java/api/com.azure.messaging.servicebus.servicebusreceivedmessage.getdeadlettererrordescription?view=azure-java-stable)

This reason should give you an idea of what is happening.

> Do you have any suggestions for logging that an be enabled to debug the process of retrieving messages? At the moment I don't get any indication of a processing errors and there is nothing showing up in the logs with the logging level set to warning.

Given that you were using receiveMessages() on the sync client, the typical try/catch should work for you to get the errors. @ki1729 Anything to add here?

**Comment by lordarcy** [comment]
I am waiting on a solution for https://github.com/Azure/azure-sdk-for-java/issues/22423 before merging this MR.
