### ISSUE TITLE
Cosmos oltp write - serialization options for fields with null values

### ISSUE THREAD

**Issue by vasanthprabhus** [Azure/azure-sdk-for-java#22828]
When i write a spark dataframe using cosmos oltp as below 

df.write.format("cosmos.oltp")
        .options(cfg)
        .mode("Append")
        .save()

fields with null values are getting written (happens with latest 2.12 cosmos oltp only, previously these fields were ignored)

would be better if we have a feature to turn on / off this feature, so that we dont write back fields with nulls onto cosmos db

**Comment by Inrixia** [comment]
+1 Using the spark connector now to write a dataframe to a cosmos container. Getting tons of null values being written when we want them to be undefined/not written. Looking into the SDK looks like there is no way to do this? 

Any update on this?

**Comment by FabianMeiswinkel** [comment]
A config option to change the default behavior exists. See https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3-1_2-12/docs/configuration-reference.md confi parameter spark.cosmos.serialization.inclusionMode - if you set it to NonNull, NonEmpty or NonDefault null values will not be persisted in Cosmos.

**Comment by Inrixia** [comment]
I attempted to use that config and received `The config property 'spark.cosmos.serialization.inclusion Mode' is invalid. No config setting with this name exists.`

An example of the code used:
```scala
sparkDataframe.write \
   .format("cosmos.oltp") \
   .options(**cfg) \
   .option("spark.cosmos.serialization.inclusionMode", "NonNull") \
   .mode("APPEND") \
   .save()
```

Does this config actually work or am I attempting to use it wrong?

**Comment by FabianMeiswinkel** [comment]
What version of the connector are you using? In 4.5.*  it definitely works. Also inclusionMode is one Word - but I assume the space was just a typo in the GitHub message.

**Comment by Inrixia** [comment]
Yes just a typo, and hmm using `azure_cosmos_spark_3_1_2_12_4_3_1.jar` which is the one referenced here: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3-1_2-12/docs/quick-start.md

Is there a newer version? Perhaps that quick-start guide needs to be updated.

**Comment by Inrixia** [comment]
Ah there is to! The quick-start should link to https://search.maven.org/search?q=g:com.azure.cosmos.spark

**Comment by FabianMeiswinkel** [comment]
Fair point - I have published a PR to fix the stale link in the quick-start.md file - and we will keep it referencing the latest version for next releases. Thanks for reporting it!
You can either install the latest jar by simply entering the Maven coordinates in Databricks "com.azure.cosmos.spark:azure-cosmos-spark_3-1_2-12:4.5.2" - or download it from here https://repo1.maven.org/maven2/com/azure/cosmos/spark/azure-cosmos-spark_3-1_2-12/4.5.2/azure-cosmos-spark_3-1_2-12-4.5.2.jar

Maven search is still lagging behind due to the immense upgrade volume caused by the log4j security issue which resulted in many jars being updated in the last couple of days
