### ISSUE TITLE
[FEATURE REQ] Service Bus Message Batch Consumption

### ISSUE THREAD

**Issue by michaelqi793** [Azure/azure-sdk-for-java#23040]
**Is your feature request related to a problem? Please describe.**

Currently, our project need consume service bus messages batch by batch not record by record,
So we firstly seek the help from ServiebusProcessorClient, but it only accepts a consumer that accepts Service Bus message one by one. 
Then we turn to ServiceBusReceiverAsyncClient. Then I code like this:
```
Flux<ServiceBusReceivedMessage>  msgs = serviceBusReceiverAsyncClient.receiveMessges();
msgs.buffer(batchSize).subscribe(new CoreSubscirber<List<ServiceBusMessageContext>>(){

...

  @Override
  public void onNext(List<ServiceBusMessageContext> serviceBusMessageContexts) {
          // my logic to consume the serviceBusMessageContexts
             
  }

...


});
```
This looks fine, but when i debug i find the FluxAutoLockRenew and FluxAutoComplete logic will be ended too early even before my logic begins. But what we want is these logics end after my logic ends. If the downstream logic, i.e. my logic succeeds, then autocomplete ends then autolockrenew ends.

Then I turn to ServiceBusReceiverClient, there is a method that returns serveral messages one time, So I code like this:
``` 
for( ;;){
            IterableStream<ServiceBusReceivedMessage> is = sy.receiveMessages(batchSize);
            List<ServiceBusReceivedMessageContext> li = is.stream().map(ServiceBusMessageContext::new).map(x -> new ServiceBusReceivedMessageContext(receiverClient, x)).collect(Collectors.toList());

            try {
                Thread.sleep(40 * 1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            for (ServiceBusReceivedMessageContext message : li) {
                sy.complete(message.getMessage());
            }

            // my logic to sconsume the list of ServiceBusReceivedMessageContext

 }
```
And the result is the same. Even before my logic begins the autocomplete and autolockrenew end. Please refer to #23039

**Describe the solution you'd like**

1 Can ServiceBusReceiverAsyncClient return a Flux<List<ServiceBusReceivedMessageContext>> and the parallel and the autocomplete and autolockrenew are encapsulated already there?
2 Can ServiceBusProcessorClient invoke the api above and accept an external Consumer<List< ServiceBusReceivedMessageContext >> like current Consumer<ServiceBusReceivedMessageContext>?
3 If i have to use the ServiceBusReceiverAsyncClient or ServiceBusReceiverClient to implement the batch-consuming, do i have a way to restart the client? Since isConnectionClosed of ServiceBusReceiverAsyncClient is not public.  Putting it in another way,  can i use ServiceBusReceiverAsyncClient like ServiceBusProcessorClient uses it but i'm outside the package.

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ yes] Description Added
- [ yes] Expected solution specified

**Comment by ki1729** [comment]
@michaelqi793 will look into the possibility of doing batch consumption

**Comment by anuchandy** [comment]
We recently identified that it is impossible to have AutoLockRenew and AutoComplete functionality when the reactor pipeline has buffering (batch) operators applied, as shown in the issue description. In light of this, we decided to deprecate these two APIs in the low-level receiver client (ServiceBusReceiverAsyncClient). Please see the issue here https://github.com/Azure/azure-sdk-for-java/issues/26084 and associated Gist. As documented, the responsibility of completion|renew is pushed down to the downstream, i.e. the user handler invokes the appropriate API for it.

The Flux returned by `ServiceBusReceiverAsyncClient` receive() API will emit an error if the error is retriable or retry is exhausted; the application can listen for such error emission. Upon error, the app can close the current client and open a new one, and do receive() on it.
