### ISSUE TITLE
[BUG] ConsumptionManager.usageDetails fails with deserialization exception when modern record is returned

### ISSUE THREAD

**Issue by denyshorman** [Azure/azure-sdk-for-java#23055]
Can't retrieve usage details for subscriptions that return modern records.
Snippet that reproduces the problem:

```xml
<dependency>
  <groupId>com.azure.resourcemanager</groupId>
  <artifactId>azure-resourcemanager-consumption</artifactId>
  <version>1.0.0-beta.1</version>
</dependency>
```

```java
ClientSecretCredential cred = new ClientSecretCredentialBuilder()
  .tenantId("[tenantId]")
  .clientId("[clientId]")
  .clientSecret("[clientSecret]")
  .build();

ConsumptionManager consumptionManager = ConsumptionManager.authenticate(cred, new AzureProfile(AzureEnvironment.AZURE));

String scope = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";

List<UsageDetail> usageDetails = consumptionManager.usageDetails().list(scope).stream().collect(Collectors.toList());
System.out.println(usageDetails.get(0).innerModel()); // can be either modern or legacy
```

`usageDetails` method can return 2 types of records:
 - `com.azure.resourcemanager.consumption.models.ModernUsageDetail`
 - `com.azure.resourcemanager.consumption.models.LegacyUsageDetail`

If some subscription returns `ModernUsageDetail` record, the code fails with deserialization exception: `Can't deserialize value of type java.lang.Boolean from String "1" for "properties.isAzureCreditEligible"`

**Comment by weidongxu-microsoft** [comment]
@denyshorman 
Is it possible for you to get the log of the response?
https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/resourcemanager#enabling-logging

From the description, it is service issue, as the response data is not correct. The `isAzureCreditEligible` field should be a boolean instead of a string
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/consumption/resource-manager/Microsoft.Consumption/stable/2019-10-01/consumption.json#L2042-L2046

**Comment by weidongxu-microsoft** [comment]
Not hear back from service.
