### ISSUE TITLE
[TEST] Smoke Test for Service Bus code samples are constantly failing

### ISSUE THREAD

**Issue by vcolin7** [Azure/azure-sdk-for-java#23315]
It looks like the smoke tests for Service Bus code samples have been failing for the [past month and a half](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1028531&view=logs&j=6d2c396a-8db4-5ace-4232-c5d41f60f5a1&t=81745624-11dd-57ea-85ed-afdac3b1fde7) (Microsoft internal link). It seems to be caused by some dependencies that cannot be resolved:

```bash
[INFO] ----------------< com.azure:azure-messaging-servicebus >----------------
[INFO] Building Microsoft Azure client library for Service Bus 7.4.0-beta.1
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.azure:azure-core:jar:1.19.0-beta.2 is missing, no dependency information available
[WARNING] The POM for com.azure:azure-core-test:jar:1.7.0-beta.1 is missing, no dependency information available
[WARNING] The POM for com.azure:azure-core:jar:1.19.0-alpha.20210802.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:08 min
[INFO] Finished at: 2021-08-02T20:22:28Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project azure-messaging-servicebus: Could not resolve dependencies for project com.azure:azure-messaging-servicebus:jar:7.4.0-beta.1: The following artifacts could not be resolved: com.azure:azure-core:jar:1.19.0-beta.2, com.azure:azure-core-test:jar:1.7.0-beta.1: Could not find artifact com.azure:azure-core:jar:1.19.0-beta.2 in ossrh (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]
```

**Comment by liukun-msft** [comment]
Hi @vcolin7
The related dependencies of service bus have been updated to a release version now. ([azure-messae-servicebus/pom.xml](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/pom.xml))

However, this issue will still happen in future when the azure-core/azure-core-test change to beta version. I can see you have [remove this part of smoke test](https://github.com/Azure/azure-sdk-for-java/pull/23362) in pipeline. Will you try to simply add them back or wait any improvement for dependencies resolution? 

One posibiltity solution may like maven build the total sdk project to resolve all the version in source code so that service bus code could always fetch the right version.

**Comment by vcolin7** [comment]
Hi @liukun-msft, looks like we can enable tests for the time being as we currently don't have any SDKs using an unreleased dependency. I have created an issue (#26751) to track the problem, as I think it will arise again at some point as you correctly pointed out. Maybe we can write something so we can determine if a build from source is required in these cases or maybe simply skip tests for libraries that use unreleased dependencies? Who should I talk to about smoke tests for Java @weshaggard?

**Comment by weshaggard** [comment]
For smoke-test stuff talk with @ckairen @benbp but for java specific stuff talk with @hallipr, between that set they should be able to help.
