### ISSUE TITLE
[BUG][Spring Data Cosmos] PartitionKey of type UUID broken since 3.7.0

### ISSUE THREAD

**Issue by witi83** [Azure/azure-sdk-for-java#23534]
**Describe the bug**
[This change](https://github.com/Azure/azure-sdk-for-java/pull/22483/files) broke the support for queries with PartitionKey of type UUID.

***Exception or Stack Trace***
````
java.lang.IllegalArgumentException: Unable to construct PartitionKeyInternal from objects array

        at com.azure.cosmos.implementation.routing.PartitionKeyInternal.fromObjectArray(PartitionKeyInternal.java:137)

        at com.azure.cosmos.implementation.routing.PartitionKeyInternal.fromObjectArray(PartitionKeyInternal.java:100)

        at com.azure.cosmos.models.PartitionKey.<init>(PartitionKey.java:31)

        at com.azure.spring.data.cosmos.core.CosmosTemplate.lambda$findItemsAsFlux$28(CosmosTemplate.java:860)
````

**To Reproduce**
```kotlin

data class User(
    val id: String,
    @PartitionKey val partitionKey: UUID
)

@Repository
interface UserRepository : CosmosRepository<User, String> {
    fun findByPartitionKey(partitionKey: UUID): Optional<User>
}
```

When you try to query it using ```repository.findByPartitionKey(UUID.randomUUID())``` you get the above mentioned exception.

**Additional information**
Please note that IDs of type UUID are [still not supported](https://github.com/Azure/azure-sdk-for-java/issues/16823) by azure-spring-data, which is really sad given the fact that UUIDs are handled as simple Strings in CosmosDB

**Comment by witi83** [comment]
@chenrujun any news?

**Comment by kushagraThapar** [comment]
@witi83  - UUID PartitionKey was never supported by spring data cosmos SDK. It is just that the error started surfacing since that PR supported partition key support for single partition queries in the above PR. 

UUID type is now supported for Id, I have introduced it here - https://github.com/Azure/azure-sdk-for-java/pull/24198
Support for UUID type for Partition Key is not supported through underlying azure-cosmos Java SDK. So spring data cosmos SDK cannot support it yet. 

Once the underlying azure-cosmos Java SDK supports UUID as partition key type, then spring-data-cosmos SDK can support it.

**Comment by witi83** [comment]
@kushagraThapar Thanks for the explanation. It makes sense to me!
