### ISSUE TITLE
[FEATURE REQ] Investigate whether we can deprecate azure-spring-boot-starter-active-directory-b2c.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#23545]
Investigate whether we can deprecate `azure-spring-boot-starter-active-directory-b2c`.

1, List all AAD B2C's features that spring-security can not provide.
2. Investigate if we can add these features in spring-security-repo.

[spring-security repo]: https://github.com/spring-projects/spring-security

**Comment by zhichengliu12581** [comment]
Currently, our azure-spring-boot-starter-active-directory-b2c provides the following functions:
As a WebApp:
We will help users choose the client to log in, logout and reset password etc.

As webapi:
1. We help users provide [trusted accessTokens from multiple issuers](https://github.com/Azure/azure-sdk-for-java/blob/a360bc4152ead0800153995812283552d40dc393/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/autoconfigure/b2c/AADB2CResourceServerAutoConfiguration.java#L73) (according to the information provided by users)
2. We helped users to add [verification of the audience](https://github.com/Azure/azure-sdk-for-java/blob/a360bc4152ead0800153995812283552d40dc393/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/autoconfigure/b2c/AADB2CResourceServerAutoConfiguration.java#L82-#L95) in the accessToken
3. Verification of the issuer in the accessToken obtained by the user (this is the same function as in the first point)

Common functions:
1.Help users configure the client (including [authentication_type](https://github.com/Azure/azure-sdk-for-java/blob/a360bc4152ead0800153995812283552d40dc393/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/autoconfigure/b2c/AADB2COAuth2ClientConfiguration.java#L70-#L84) and [client_credentials](https://github.com/Azure/azure-sdk-for-java/blob/a360bc4152ead0800153995812283552d40dc393/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/autoconfigure/b2c/AADB2COAuth2ClientConfiguration.java#L92-#L110) types).
2. We can obtain the information in scope and role at the same time for permission control ([Deprecated and instead by `AADJwtBearerTokenAuthenticationConverter`](https://github.com/Azure/azure-sdk-for-java/pull/23444))

When we use spring Security directly, the functions we have been able to provide are:
- When used as a webapi:
  1. Spring Security can [support multi Tenant](https://github.com/spring-projects/spring-security/pull/7733#issuecomment-567518233), similar to the [sample](https://github.com/spring-projects/spring-security-samples/tree/main/servlet/spring-boot/java/oauth2/resource-server/multi-tenancy) provided by spring:
  2. In the provision of multi Tenant, users can [customize the verification of audience](https://github.com/spring-projects/spring-security/issues/8334#issuecomment-609997301).
- When used as a webapp:
   1. Users can determine the default client through spring configuration
- When using common fucntions:
   1. Users can configure the information of each client by themselves
   2. If user wanner use the `Converter` in azure-spring-boot-starter-active-directory, they can add the dependency about aad. But we still need to add issue for spring security to see if we can set `AuthoritiesClaim` by properties. 

Summary:
We can Deprecated azure-spring-boot-starter-active-directory-b2c, because most of the functions are already supported by springSecurity, and users can also configure some of them by themselves.
