### ISSUE TITLE
Add Rule to Flag Creation of New ObjectMappers

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#23735]
Create a new Checkstyle rule that will flag `new ObjectMapper()`, and potentially similar code snippets, and trigger a Checkstyle warning. For the case of `ObjectMapper`, they are expensive to instantiate and doing so in a hot path could result in a large performance regression, additionally `ObjectMapper` is a very complex topic as the configuration in the mapper can greatly affect runtime behavior. Therefore, all instantiations of `ObjectMapper` should be reviewed, so flagging with a Checkstyle warning will make it clearer that its use should be reviewed.

**Comment by stliu** [comment]
I don't know checkstyle much, but I'm wondering if it supports check on this scenario:

Since at the core of spring it is a IoC container, usually create new instance manually is not considered a best practice, so I'm wondering if we can create a checkstyle rule and raise warn when it sees a `new` keyword from a non-configuration class (since configuration class is considered as a bean factory) -- class doesn't have `@AutoConfiguration` nor `@Configuration`


@alzimmermsft  any idea if this is doable?

**Comment by alzimmermsft** [comment]
> 

Just to clarify the question in my own words. Is the request to also flag properties with `@AutoConfiguration` and `@Configuration` that are `ObjectMapper`s?
