### ISSUE TITLE
JMS library issue

### ISSUE THREAD

**Issue by gothamliang** [Azure/azure-sdk-for-java#23810]
We made the load test and get such issues.

(1) the first one is about the Azure Service Bus JMS library, compare to the .NET component, we found there are significant performance gap.
(2) the connection will disconnect around every hour.

**Comment by joshfree** [comment]
Hi @gothamliang thanks for filing the issue.  We could use some more details in order to be able to help you further.

Could you please take a look at the issue template here: https://github.com/Azure/azure-sdk-for-java/tree/main/.github/ISSUE_TEMPLATE and provide the missing details (code sample, SDK version(s), etc)?

Thank you
