### ISSUE TITLE
the link to the Spring content is 404

### ISSUE THREAD

**Issue by cicorias** [Azure/azure-sdk-for-java#23947]
ON this page:
https://docs.microsoft.com/en-us/java/api/overview/azure/spring-cloud-stream-binder-eventhubs-readme

This link is provided for Spring but it's a 404

https://docs.microsoft.com/en-us/java/api/overview/azure/spring-cloud-stream-binder-eventhubs-readme

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da885aa0-2c2d-6344-4f15-304bbeb9db24
* Version Independent ID: 6590e484-b5fc-1135-3280-ebae04ceab3a
* Content: [Azure Event Hub libraries for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/eventhub?view=azure-java-stable)
* Content Source: [docs-ref-services/latest/eventhub.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/eventhub.md)
* Service: **event-hubs**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yiliuTo** [comment]
Hi @cicorias We deleted all of Azure Spring docs on the page of https://docs.microsoft.com/java/api/overview/azure/ because we want to keep one single source of the Azure Spring official documentations, which is https://docs.microsoft.com/azure/developer/java/spring-framework/. 

And for the library of `azure-spring-cloud-stream-binder-eventhubs`, you can refer to https://docs.microsoft.com/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub

**Comment by yiliuTo** [comment]
@cicorias Could you help to share in which page do you find this broken link? Thanks!

**Comment by cicorias** [comment]
the source link seems gone now.  I'll close for now.
