### ISSUE TITLE
[BUG] FeatureManager should refresh when feature flag is removed

### ISSUE THREAD

**Issue by HM-A** [Azure/azure-sdk-for-java#24041]
**Describe the bug**
Deleting a Feature Flag in the Azure Web Feature Manage does not create a RefreshEvent, so the connected Feature Manager in a service still uses the deleted Feature Flag.

**To Reproduce**

1. Create/Add a new Feature Flag 
2. Output all Feature Flags (see Code Snippet) -> all previously existing Feature Flags + the newly created one
3. Delete The newly created Feature Flag
4. wait a bit to rule out a Delay 
5. Output all Feature Flags (see Code Snippet) -> still all previously existing Feature Flags + the newly created one

At any point after this, if an existing Feature Flag gets changed or a new one added, the deleted Feature Flag will no longer be found by the Feature Manager. 

***Code Snippet***
The result of this call does not change when a Feature Flag is deleted.
`final Set<String> allFlags = featureManager.getAllFeatureNames();`

**Expected behavior**
When deleting a feature flag in the Azure Web Feature Manager, the connected feature Manager in a service should receive a RefreshEvent. Currently only adding a new Feature Flag or changing the state (e.g. enabled -> disabled, disabled -> enabled) creates a RefreshEvent and leads to an update of the feature Flags in the service.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Ubuntu 21.04 (ubuntu-latest)
 - IDE: IntelliJ IDEA 2021.1.3 Ultimate
 - Library/Libraries: com.microsoft.azure:spring-cloud-azure-feature-management-web:1.3.0
 - Java version: 11
 - App Server/Environment: Docker Pod in Azure environment, Azure Feature manager
 - Frameworks: Spring Boot 

**Additional context**
A Spring Boot Application in a Docker container that is hosted on Azure. The application uses com.microsoft.azure dependencies to connect to different Azure Services (relevant for this Bug -> App Configuration Feature Manager).

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@stliu could you please help route @HM-A's question

**Comment by mrm9084** [comment]
@HM-A this is a known issue with how all of the V1 libraries works. They use the revisions endpoint of App Configuration to check for changes, which doesn't work with deletes.

This should be fixed in all of the 2.1.0 version currently released, if you are able to move to those libraries.

I just want to note that the issue is with the spring-cloud-azure-appconfiguration-config-web library, not the feature flag one. The appconfiguraiton library loads the configurations/feature flags and does the refreshes, not the feature flag library.

If you are unable to upgrade you can trigger a refresh by using a sentinel key. An example would be
Key = /application/sentinel
Value = 0

And if you want to force a refresh you can just update the value of the key.

**Comment by HM-A** [comment]
@mrm9084 
Thank you for your answer. We will look into upgrading the libraries
