### ISSUE TITLE
Move to Java 9 Logging API

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#24295]
Remove dependency on SLF4J and use Java 9 logging APIs

**Comment by JonathanGiles** [comment]
My primary concern here is that SLF4J 2.x APIs have support for setting key/value pairs, and theoretically (because I haven't proven it works) this enables JSON structured logging output. My hope is to enable structured logging output for all of our client libraries, and so any move away from SLF4J should keep this in mind, even if we haven't yet enabled it there.

**Comment by JonathanGiles** [comment]
This issue is related to the issue to support [structured logging](https://github.com/Azure/azure-sdk-for-java/issues/24344).

**Comment by stliu** [comment]
does this mean SDK will drop jdk8?

**Comment by JonathanGiles** [comment]
@stliu No - these are just ideas for future changes. Nothing is being committed to here! :-)

**Comment by JonathanGiles** [comment]
@lmolkova Thinking back to your work on structured logging - did you use anything in slf4j that would prevent a move to the JDK 9 logger?

**Comment by lmolkova** [comment]
@JonathanGiles nope, I didn't use anything new from slf4j. I will also entertain the idea of fully structured login with OTel at some point. OTel defines over-the-wire format for logs with correlation and structure and works with AzMon, Splunk, and all the usual logs players with little-to-no setup. 

It'd mean implementing more pluggable logging impl while the default implementation can be JDK logger or stay at slf4j.
