### ISSUE TITLE
Make the BOM prominent on the Azure SDK Releases landing page

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#24437]
Tracking issue for making the azure-sdk-bom prominent in the Java section of the Azure SDK Release landing page: https://azure.github.io/azure-sdk/releases/latest/java.html

**Comment by pallavit** [comment]
I investigated this a bit. We now have the release notes for BOM on the landing page. however, this page does not have BOM docs. And adding docs for this library will not be straight forward. 

Since BOM is a special library we do not have any javadocs for it. The way readme.md becomes the landing page for doc,ms is that we have a special step in engsys that converts this readme to an overview page which then gets attached to the javadocs and these docs are then picked up by the doc.ms engine.  Since, BOM package do not have any javadocs this does not work for it.

Javadocs can't be generated for a package that does not have any sources (which BOM does not), so I am working with Daniel to see if there is a way to populate doc.ms with anything other than javadocs and see if we have any work-around here.

**Comment by JonathanGiles** [comment]
My thinking is to have a brand new 'getting started' section on docs.microsoft.com. I've briefly talked about this in the past, but under this section I would like docs detailing how to get started with Maven, Gradle, and GraalVM. These will all talk about the BOM as appropriate. 

I started mocking up some of this here: https://github.com/JonathanGiles/azure-sdk-setting-up-docs

**Comment by pallavit** [comment]
Getting started BOM section - https://gist.github.com/pallavit/aa1e3ff96c287828e5035bf6c632714e

**Comment by JonathanGiles** [comment]
Should we start integrating this documentation into the github repo I shared in the previous comment? That way we might get something close to complete that we can then put into docs.microsoft.com? There are still some gaps (e.g. graalvm, archetype), but we can start pulling things together...If you agree, perhaps lets set aside 30 minutes to sync up sometime this week?

**Comment by pallavit** [comment]
Closing this one, since we have a tracking bug for the blogpost, have incorporated BOM information in the getting-started documents and already added the azure-sdk-bom to the release landing page.
