### ISSUE TITLE
Update Azure App Service libraries for Java article

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-java#24786]
https://docs.microsoft.com/en-us/java/api/overview/azure/appservice?view=azure-java-stable

We already have Track2 article: Azure Resource Manager App Service client library for Java | Microsoft Docs
Do we update content, or just bring down this Track 1 article? Or do some search optimization?

**Comment by haolingdong-msft** [comment]
After discussed with @weidongxu-microsoft  and @nickzhums, we decided to update the Track1 article. Because using google search, the Track1 article comes as the top-hit result, and we don't have control on google's indexing, so it's better to update the Track1 article.
The pr is already merged. 
https://github.com/Azure/azure-docs-sdk-java/pull/2125
