### ISSUE TITLE
Update smoke tests to auto-generate dependency checks for all t2 SDKs

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-for-java#25184]
The goal for smoke tests is to catch and block on dependency issues before release.

- Delete the legacy smoke tests for each language (applies to net, python, java).
- Pull in all track 2 packages to a single project and install/compile (nightly versions, GA/beta versions).
- Run the project and instantiate clients from each package, where useful (for detecting lazy loaded runtime dependency issues).

**Comment by joshfree** [comment]
@pallavit could you drive this for our team?

**Comment by pallavit** [comment]
Absolutely!

**Comment by pallavit** [comment]
Given the goals of the work-item
1. Statically validate that the SDKs do not have any dependency conflicts.
2. Validate that the SDKs will work in the outside environment.

The work that was done as part of BOM validation\generation and the maven archetype recently released achieves both the above goals. With release pipeline validating the SDK dependencies before the package release and the way maven central works ensures that we do not rely on any internal dependencies.

Adding smoke tests that instantiates say clients\builder will not give any extra defense in depth because most of the conflicts on Java come from external dependencies like Jackson data-bind, netty etc that are not even exercised until we serialize\deserialize models, make http calls etc.

The current smoke tests are not exhaustive and have potential issues. Given all this I would like to remove smoke tests from Java repository for now. We should revisit this work-item in future when we have scenarios on which we would like to do defense in depth testing . Java team agrees with this sentiment. 

@benbp please let me know how would you like me to proceed here. Is there any dashboards etc that I need to update before I remove these smoke tests.

**Comment by weshaggard** [comment]
>Adding smoke tests that instantiates say clients\builder will not give any extra defense in depth

I'm not sure about this one I still think there is some potential for runtime failures that would be discovered this way that might not be found just from static analysis. 

From a goal perspective we want these tests to cover the basic scenario of how we would expect our customers to consume our libraries. This would mean we need to reference them all from a project, not bound to our engineering system, and have them execute some basic code. This will ensure both that our libraries can be used from a static dependency perspective as well as from a runtime perspective. 

@pallavit when we chatted, I thought we were going to use this smoke test infrastructure to test the BOM file, is that planning to happen as part of another effort now? Testing the BOM file from a runtime perspective seems like a worthwhile effort to me.

However, if we test the BOM we are really only testing the shipped GA versions and another bonus effort I was hoping to get was to verify our daily alpha builds as well but perhaps we can do that in a different way.

**Comment by pallavit** [comment]
> I'm not sure about this one I still think there is some potential for runtime failures that would be discovered this way that might not be found just from static analysis.
> @pallavit when we chatted, I thought we were going to use this smoke test infrastructure to test the BOM file, is that planning to happen as part of another effort now? Testing the BOM file from a runtime perspective seems like a worthwhile effort to me.

I completely agree that we should be testing our BOM. Instantiating clients\builders however is not going to give any coverage here. The only thing we will get from it is - does maven have the right package and could it be downloaded (none of the interesting pieces of interdependencies between SDK etc. will get tested via this) which is what we ideally want to test. Also, we will be testing libraries that have already been released. (which is a little late already). BOM validation has to be a dedicated test suite or per SDK test jars etc. but should they be part of smoke tests? BOM won't be generated until the 3rd week of the month. So, until then we would only be testing the old BOM that has already been released. If we run the smoke tests just before the BOM release they are not exactly smoke tests are they?

> However, if we test the BOM we are really only testing the shipped GA versions and another bonus effort I was hoping to get was to verify our daily alpha builds as well but perhaps we can do that in a different way.

Daily alpha builds will more often than not have conflicts in them due to the nature of Java releasing libraries every month at different timelines. So, I am not sure what advantage we get here either.

**Comment by weshaggard** [comment]
For the daily alpha builds I agree there might be some conflicts in some instances but we should come up with a strategy for making sure those work otherwise if they are always broken then what is the point of having them if folks cannot consume them.

**Comment by weshaggard** [comment]
For the BOM testing you are correct that we will be testing something that has already shipped but part of the point is to ensure that we can find issues quickly before our customers do so as long as we are doing the validation at the time of release of the BOM we should be covered. However there might still be some value it doing it more regularly to catch odd issues in the tooling or whatnot that might cause issue with an already released BOM.

> Instantiating clients\builders however is not going to give any coverage here. 

I would like to understand that a little more because I do think there is value. I will say one of the biggest challenges we had before our team was ensuring that our different libraries could be loaded and run in the same application so having some basic runtime tests seem like a good idea. I know that we have hit issues that didn't show up during static dependency analysis because Maven was able to resolve the graph but we hit them at runtime because the Java runtime ended up loading the first one it found which isn't necessarily the same one that was statically resolved. In other words, I believe there are differences between the maven dependency managed and the java runtime dependency management which would make doing runtime testing valuable.
