### ISSUE TITLE
Support for Cognitive Services Computer Vision Face API: LargePersonGroup etc.

### ISSUE THREAD

**Issue by polarapfel** [Azure/azure-sdk-for-java#2530]
Hi,

I noticed that the current implementation for Face API does not support LargePersonGroup and the other "large" versions of entities. Is this tracked as a missing feature?

thanks,

Tobias

**Comment by vhvb1989** [comment]
Hello @polarapfel 

I am sorry about you didn't get a sooner answer on this
Do you still need help? Let me know and I would be happy to assist.

Note: As part of repository cleaning effort, this issue will be closed by Sep 20 if no response is received from submitter and/or not further action is required.

**Comment by polarapfel** [comment]
Looking at the [API documentation for the stable branch](https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.cognitiveservices.vision.faceapi?view=azure-java-stable), there doesn't seem to be API methods in the Java CS Face API SDK for [LargePersonGroups](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/face/largepersongroup), so I guess my question still stands: will that be added to the SDK?

**Comment by vhvb1989** [comment]
@polarapfel , we are currently working on adding cognitive services to SDK
This will be ready later (this year).

I am going to tag this request so it can be reviewed and added into the feature planning (if not already).

Thank you

**Comment by polarapfel** [comment]
Awesome, thanks. Is this something a quick pull request would also solve if I chose to work on this? Just adding LargePersonGroup support is mostly copy&paste work, and adding the missing tests I guess.

**Comment by JonathanGiles** [comment]
@polarapfel Please feel free to submit a PR if you feel inclined - we always welcome contributions! The only thing I would note is to be careful not to do a PR on code that we autogenerate - otherwise it will be overwritten the next time the autogeneration occurs. If you look at the header text on the file, you can determine if it is autogenerated or not. If you have any questions, please ask in here about specific files and we can comment on them.
