### ISSUE TITLE
[BUG] NullPointerException in processMessage function prevents shutdown of application

### ISSUE THREAD

**Issue by steinrr** [Azure/azure-sdk-for-java#25709]
**Describe the bug**
I am creating a Spring Boot application that uses ServiceBusProcessorClient to receive messages from queue. Using ServiceBusClientBuilder with processMessage and processError handlers.

If a a NullPointerException in the processMessage handler function is thrown for some reason (or intentionally), it is no longer possible to "gracefully" shutdown the application - e.g. using ctrl-c. I am forced to kill the Java process.

***Exception or Stack Trace***
N/A

**To Reproduce**
Create a Spring bean that returns a ServiceBusProcessorClient instance. Define a processMessage and processError handler. In the processMessage handler function, do "throw new NullPointerException()". Observe that processError function is called. Try to stop the application using Ctrl-c. Observe that it is not possible to fully stop it. Kill the java-process using kill or system console.

***Code Snippet***
See above.

**Expected behavior**
The application should be possible to shutdown normally.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Mac OS
 - Library/Libraries: azure-messaging-servicebus 7.5.0
 - Java version: 11
 - App Server/Environment: Spring Boot (mvn spring-boot:run)
 - Frameworks: Sprint Boot 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
  
**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Bug Description Added
- [ x] Repro Steps Added
- [ x] Setup information Added

**Comment by haolingdong-msft** [comment]
Hi @steinrr 
I have successfully reproduced the issue. The issue is because by defining ServiceBusProcessorClient as bean and throws error in processMessage(), ctrl-c leads to calling processor.close() which stucks, so the program can't be killed gracefully.

I believe in production, ctrl-c to stop the application is not a good choice, a better behavior to recycle spring app when encountering exception is:

user app exception -> processor.close() -> bean cleanup

To unblock your issue and have better spring app recycling behavior, I would suggest to try below sample code. In the processMessage() to catch exceptions from business logic and call processor.close() (to init the closure of underlying clients). Then rethrow the exception for bean to run the destroy/shutdown phase for other cleanups.  This sample code is able to be killed gracefully.

Please let me know if this can resolve your issue.

```java
@Configuration
public class ServiceBusTestConfiguration {
    static String connectionString = "<connection-string>";
    static String queueName = "<queue-name>";

    ServiceBusProcessorClient processorClient = null;

    @Bean( initMethod = "start")
    public ServiceBusProcessorClient serviceBusProcessorClient() {
        processorClient = new ServiceBusClientBuilder()
                .connectionString(connectionString)
                .processor()
                .queueName(queueName)
                .processMessage((context) -> {
                    try {
                        System.out.println("process message");
                        throw new NullPointerException();
                    } catch (Exception e) {
                        processorClient.close();
                        e.printStackTrace();
                        throw e;
                    }
                })
                .processError((context) -> {
                    System.out.println("process error");
                })
                .buildProcessorClient();
        return processorClient;
    }
}
```

**Comment by steinrr** [comment]
Thanks for your investigation on this issue @haolingdong-msft!

We are now using a Azure Redis cache instead, but I will keep this in mind when using service bus again!
