### ISSUE TITLE
[BUG]azure-client-authentication 1.7.14 has json-smart dependency with known vulnerability

### ISSUE THREAD

**Issue by axhwk** [Azure/azure-sdk-for-java#25829]
**Describe the bug**
azure-client-authentication 1.7.14 has dependency to json-smart 2.4.2 with a known security vulnerability. 

***Exception or Stack Trace***
The relevant part of the dependency tree:

    com.microsoft.azure:azure-client-authentication:jar:1.7.14:compile
    +- com.microsoft.azure:adal4j:jar:1.6.7:compile
    |  \- com.nimbusds:oauth2-oidc-sdk:jar:9.4:compile
    |     +- com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile
    |     +- com.nimbusds:content-type:jar:2.1:compile
    |     +- net.minidev:json-smart:jar:2.4.2:compile (version selected from constraint [1.3.2,2.4.2])

Link to CVE stating that version 2.4.2 is vulnerable: https://nvd.nist.gov/vuln/detail/CVE-2021-31684

Please either check if this is exploitable or update to a newer version.

**Comment by joshfree** [comment]
@g2vinay could you please follow up and help route this `Track 1` / `com.microsoft.azure` issue as well as help @axhwk with pointers to migration guides for how to move forward to newer SDK versions

**Comment by g2vinay** [comment]
@axhwk
To unblock the current implementation on your end you can exclude the vulnerable dependency and pin to its latest version in your application pom file as follows:
```java
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-client-authentication</artifactId>
            <version>1.7.14</version>
            <exclusions>
                <exclusion>
                    <groupId>net.minidev</groupId>
                    <artifactId>json-smart</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>net.minidev</groupId>
            <artifactId>json-smart</artifactId>
            <version>2.4.7</version>
        </dependency>
```

**Further on our end, we are working towards resolving this issue as follows:**

1. The source of the issue is json-smart dependency being used in this flow: json-smart -> oauth2-oidc-sdk -> adal4j -> azure-client-authentication.

2. The latest version of oauth2-oidc-sdk has this issue as they depend on json-smart:2.4.7.

3. So, I've filed a [Github issue](https://github.com/AzureAD/azure-activedirectory-library-for-java/issues/310) for adal4j GitHub repo to upgrade their oauth2-oidc sdk to the latest version.

4. Once Step 3 is executed we will upgrade the adal4j in azure-client-authenticaiton library and do a patch release to fix this issue.



Further, to bring to your attention, you seem to be using Track 1 Azure SDKs.
Microsoft Azure has released Track 2 SDKs for various services including [Service Bus](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/servicebus/azure-messaging-servicebus), assuming that's the service you're using and [Azure Identity](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/identity) for AAD authentication.
These SDKs are designed to offer better UX, Performance, support and overall reliability. So for long term, I'd recommend to consider migrating to the Track 2 version of our Azure SDKs.
[Service Bus Migration Guide
](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/migration-guide.md)

**Comment by weidongxu-microsoft** [comment]
Vinay is right.

Another possible approach would be [dependency management](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#dependency-management)

**Comment by g2vinay** [comment]
Closing this issue as mitigation is posted above.
