### ISSUE TITLE
[FEATURE REQ] Add reactive batch upserts to CosmosAsyncContainer

### ISSUE THREAD

**Issue by segocago** [Azure/azure-sdk-for-java#26216]
**Is your feature request related to a problem? Please describe.**
It is not possible to reactively batch upsert documents through the CosmosAsyncContainer API atm.
DocumentBulkExecutor.importAll() method is the suggested method for bulk upsert operations that i saw in the [documents](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/bulk-executor-java) but it is not reactive. Therefore, reactive CosmosAsyncContainers users also have to deal with additional objects such as DocumentClient, BulkExecuter etc. to do batch operations.

**Describe the solution you'd like**
A similar method to importAll method of DocumentBulkExecutor could be added to CosmosAsyncContainer.

**Describe alternatives you've considered**
In order to achieve the batch upserts through the CosmosAsyncContainer, i have tried using CosmosAsyncContainer.executeBulkOperations() method. Even though this method sends the requests to the Cosmos in batches, upsert operations are executed individually (since it is bulk and not batch i assume).  As a result, the number of upsert requests in Cosmos rose from 60-100 (when DocumentBulkExecutor.importAll used)  to 25k-30k which lead to 429 - Too Many Requests responses from Cosmos.

CosmosAsyncContainer also has a executeCosmosBatch() method but this method requires items to have the same partition key which is not the case when unique identifier is also used for partition key.

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by FabianMeiswinkel** [comment]
HI @segocago - the CosmosAsyncContainer.executeBulkOperations is the API that can be used for bulk operations in the Java V4 SDK - https://github.com/Azure/azure-sdk-for-java/blob/4477d35375cb9a74865048de7ba5ea4f51b9b58a/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/CosmosAsyncContainer.java#L807-L871

The DocumentBulkExecutor was the API when using the sync Java V2 SDK.

The number of requests issued when using the bulk Api depends on different parameters (total request payload size, the 429-throttling rate etc.) and unlike with the DocumentBulkExecutor the micro batch size will be automatically modified based on the information above.

If you see now 25K-30K requests it would be good to know the total number of operations - the number of documents that bulk operations can handle together in a single request can be up to 100 documents per request, but if the documents are large or if there is heavy throttling each individual request will contain significantly fewer documents (possibly even just one).

This is expected and by design. If you still see unexpected behaviour or think that the chosen batch size is too small in your case please make sure to double check whether it also reproduces for the latest version (4.24.0) and let us know the account name, target database and container in a support request and we can take a look at what is causing the small batch size in your use case.
