### ISSUE TITLE
[QUERY] Accepting Messages without using deprecated classes

### ISSUE THREAD

**Issue by dvag-martin-anlauf** [Azure/azure-sdk-for-java#26557]
**Query/Question**
Hello, 
We use azure-spring-cloud-stream-binder-servicebus-queue version 2.12.0 to accept messages from an azure service bus. Our Code is structured according to the example in  https://docs.microsoft.com/de-de/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-with-service-bus . It works but uses the class _com.azure.spring.integration.core.api.Checkpointer_, which is deprecated.
Is there a documented way to accept messages without using deprecated classes? Links to documentation are welcome.

***Why is this not a Bug or a feature Request?***
It works, but using a deprecated class

**Setup (please complete the following information if applicable):**
 - OS: MacOS 12.0.1
 - IDE: IntelliJ
 - Library/Libraries: com.azure.spring:azure-spring-cloud-stream-binder-servicebus-queue:2.12.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ *] Query Added
- [ *] Setup information Added

**Comment by joshfree** [comment]
@yiliuTo could you please assist @dvag-martin-anlauf?

**Comment by yiliuTo** [comment]
@dvag-martin-anlauf , thanks for reporting this and we will update this doc soon. And as the javadoc of `com.azure.spring.integration.core.api.Checkpointer` says, you could replace it with `com.azure.spring.integration.core.api.Checkpointer`, for example, you could change the `consume` bean as the below one: 
   ```
    @Bean
    public Consumer<Message<String>> consume() {
        return message -> {
            Checkpointer checkpointer = (Checkpointer) message.getHeaders().get(CHECKPOINTER);
            LOGGER.info("New message received: '{}'", message.getPayload());
            checkpointer.success()
                    .doOnSuccess(s -> LOGGER.info("Message '{}' successfully checkpointed", message.getPayload()))
                    .doOnError(e -> LOGGER.error("Error found", e))
                    .subscribe();
        };
    }
   ```

**Comment by dvag-martin-anlauf** [comment]
Hi Yi,

thanks for your reply. I think you mean I should replace it with class com.azure.spring.**messaging**.core.checkpoint.Checkpointer. Thanks to your hint I found it in the documentation  ( https://azuresdkdocs.blob.core.windows.net/$web/java/azure-spring-integration-core/2.12.0/index.html?com/azure/spring/integration/core/api/Checkpointer.html ).

Which dependency exactly do I have to include to be able to use class com.azure.spring.messaging.core.checkpoint.Checkpointer for com.azure.spring:azure-spring-cloud-stream-binder-servicebus-queue:2.12.0?

**Comment by yiliuTo** [comment]
Hi @dvag-martin-anlauf , both of the classes `com.azure.spring.integration.core.api.reactor.Checkpointer` and `com.azure.spring.messaging.core.checkpoint.Checkpointer` are in package `com.azure.spring:azure-spring-integration-core`, and you don't need to include this package explicitly because it is also one of the dependencies of `azure-spring-cloud-stream-binder-servicebus-queue`
![image](https://user-images.githubusercontent.com/63028776/150248226-b4a0a14f-8768-4691-99d4-cc722951f244.png)

**Comment by yiliuTo** [comment]
Hi @dvag-martin-anlauf, sorry for the wrong information above, the deprecated class of `Checkpointer` cannot be replaced currently, this is due to that is a message header we put into the message, so replacement is not supported. We will update our javadoc to correct it.
And you could replace it in our 4.x version with the class of `com.azure.spring.messaging.checkpoint.Checkpointer`, for more details about migration to 4.x, you can refer to the [migration guide](https://microsoft.github.io/spring-cloud-azure/docs/4.0.0-beta.2/reference/html/index.html#migration-guide-for-4-0), [4.x reference doc](https://microsoft.github.io/spring-cloud-azure/docs/4.0.0-beta.2/reference/html/index.html#spring-cloud-stream-binder-for-azure-service-bus) and [samples](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0-beta.3/servicebus/spring-cloud-azure-stream-binder-servicebus)

**Comment by dvag-martin-anlauf** [comment]
Ok, thank you for the answers.
