### ISSUE TITLE
Upgrade azure-sdk version for Spring Cloud Azure 4.0

### ISSUE THREAD

**Issue by Netyyyy** [Azure/azure-sdk-for-java#27000]
We should upgrade the azure sdk version before the 4th beta of the Spring Cloud Azure 4.0, so we need to merge the main branch to 4.0 again.
- [ ] https://github.com/Azure/azure-sdk-for-java/pull/27496/
- [ ] Before 4.0 GA, need merge again:

**Comment by saragluna** [comment]
I just merged the main to 4.0 branch, https://github.com/Azure/azure-sdk-for-java/pull/27763. But since the PR to increment version for KV hasn't been merged, so we need to merge again before GA.
<img width="775" alt="image" src="https://user-images.githubusercontent.com/31124698/159217253-e362525b-6df4-4e46-8b87-b5f18700bfde.png">

**Comment by saragluna** [comment]
closed in https://github.com/Azure/azure-sdk-for-java/pull/27843
