### ISSUE TITLE
Question: createitem 

### ISSUE THREAD

**Issue by venkis** [Azure/azure-sdk-for-java#27239]
**Query/Question**
Looks like there is no option to exclude nulls when the object is serialized in CosmosDB when I send a Java object.
I'm thinking of eliminating nulls before calling createItem and pass the item as string or stream.
Is there a performance impact between sending a Java Object vs String vs Stream in createItem method.

***Why is this not a Bug or a feature Request?***
There seems to be feature requests already available to add serialization options to the Java SDK

**Setup (please complete the following information if applicable):**
``` 
<dependency>. 
    <groupId>com.azure</groupId>. 
    <artifactId>azure-cosmos</artifactId>. 
    <version>4.26.0</version>. 
</dependency>. 
```
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Query Added
- [ x] Setup information Added

**Comment by kushagraThapar** [comment]
@venkis - You can ignore null values using this annotation from jackson - 
`@JsonInclude(JsonInclude.Include.NON_NULL)` - more details here - https://www.baeldung.com/jackson-ignore-null-fields

Also, there should be no performance impact when using Java Object when sending the item for createItem API call.

**Comment by sconggit** [comment]
@kushagraThapar wish you could add this feature to the Java SDK. Using the annotation from Jackson means you have to convert and save the item as a string which isn't desired. We definitely need this feature because we have run into the situation with over a hundred of fields, most are null and we want to suppress those null fields.  I found .Net C# has this feature as an option on CosmosClient (https://stackoverflow.com/questions/25903302/removing-properties-with-null-values), we need to have this option for Java community, desperately.
