### ISSUE TITLE
[mgmt] [`azure-resourcemanager-sql`] Models for SQL resource manager are outdated

### ISSUE THREAD

**Issue by valfirst** [Azure/azure-sdk-for-java#27268]
**Is your feature request related to a problem? Please describe.**
Models for SQL resource manager were generated once on [Sep 25, 2020](https://github.com/Azure/azure-sdk-for-java/commits/main/sdk/resourcemanager/azure-resourcemanager-sql/src/main/java/com/azure/resourcemanager/sql/fluent/models).

The models have not been re-generated since those times, but they were updated, check: https://docs.microsoft.com/en-us/rest/api/sql/2021-08-01-preview/databases/get (e.g. search for `currentBackupStorageRedundancy` or `requestedBackupStorageRedundancy`)

**Describe the solution you'd like**
The models should be up to date with latest API changes.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by weidongxu-microsoft** [comment]
@valfirst 
SQL have huge breaking changes to the models and even APIs since last codegen (it was composite-v3 at a specific commit ID, even later composite-v3 breaks itself). Now the latest is composite-v5.
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/sql/resource-manager#tag-package-composite-v5

It is hard (or near impossible) to use composite-v5 without breaking changes to customer code. And this SDK forbid breaking changes https://azure.github.io/azure-sdk/java_introduction.html#versioning
Hence this leave us at an awkward position.

I've created a task to upgrade SQL, but do not expect anything soon.
https://github.com/Azure/azure-sdk-for-java/issues/27275

**Comment by valfirst** [comment]
@weidongxu-microsoft why not to increase major version number and release `3.x.x` version?

**Comment by weidongxu-microsoft** [comment]
@valfirst 

3.x would be a endeavor with similar scale. So far not a single lib in this repo underwent this.

> Breaking changes should happen rarely, if ever. Register your intent to do a breaking change with [adparch]. You’ll need to have a discussion with the language architect before approval.

**Comment by weidongxu-microsoft** [comment]
If you always like to use latest version of SQL, a local build SDK might be a better option.

I've made one here https://github.com/Azure/azure-sdk-for-java/pull/27479

You should be able to build and install it in `sdk/sql/azure-resourcemanager-sql`. And the SAMPLE.md should contains lots of usages.

**Comment by XiaofeiCao** [comment]
@valfirst [PR](https://github.com/Azure/azure-sdk-for-java/pull/31490) for sql api-version update. 
Breaking changes seem unavoidable since some resources(e.g. metrics) have been removed from swagger.

**Comment by XiaofeiCao** [comment]
@valfirst 2.23.0 has been released with sql api-version `2021-11`.
