### ISSUE TITLE
[BUG] Allow users to configure the max size for share file when using spring-cloud-azure-starter-storage-file-share

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#27278]
**Describe the bug**
The current max size 1024 is not supported to change, If it exceeds this size, the underline SDK interface will throw an exception.

Relate issue: 
- https://github.com/Azure/azure-sdk-for-java/issues/27230

***Exception or Stack Trace***
`Suppressed: com.azure.storage.file.share.models.ShareStorageException: Status code 416, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidRange</Code><Message>The range specified is invalid for the current size of the resource.
RequestId:97ec1c94-301a-005c-3f2e-29b1e1000000
`

**To Reproduce**
Save to the share file with data over 1024 size.

***Code Snippet***
https://github.com/Azure-Samples/azure-spring-boot-samples/tree/4cfe46d1aa5f26e32f216ab27d467b70a4053782/storage/spring-cloud-azure-starter-storage-file-share/storage-file-sample

**Expected behavior**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - IDE: [e.g. IntelliJ] Intellij idea
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]  com.azure.spring:spring-cloud-azure-starter-storage-file-share:4.0.0-beta.4
 - Java version: [e.g. 8] 11
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] spring boot 2.6.2

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by backwind1233** [comment]
For now, there are some limitations here.

because we are using spring resources to read and write.
![image](https://user-images.githubusercontent.com/4465723/155659447-d41c8bae-3885-4a38-925a-13292f288dcd.png)
in step 1, we create [shareFileClient ](https://github.com/Azure/azure-sdk-for-java/blob/59f875d454341b17618f097ca13c36c61877b57f/sdk/spring/spring-cloud-azure-core/src/main/java/com/azure/spring/core/resource/StorageFileResource.java#L220) and return OutputStream, but we have to give maxSize to create shareFileClient.

but the maxSize won't know until step 2.

**Comment by saragluna** [comment]
Close in favor of https://github.com/Azure/azure-sdk-for-java/issues/30120.
