### ISSUE TITLE
Why does the class NameValidator has disappeared since the legacy SDK?

### ISSUE THREAD

**Issue by samuelsayag** [Azure/azure-sdk-for-java#27401]
**Query/Question**

Why is the following class is in the legacy SDK but not in the latest one?

https://github.com/Azure/azure-storage-java/blob/legacy-master/microsoft-azure-storage/src/com/microsoft/azure/storage/NameValidator.java

It is quite practical and complete static code for validating resources format.

***Why is this not a Bug or a feature Request?***
It is just a request for information.

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - IDE: Vim
 - Library/Libraries: azure-storage 
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
Hi @samuelsayag someone from the storage team will follow up shortly.

@rickle-msft would it be possible to add this to the https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/storage/azure-storage-blob/migrationGuides and make the guides a bit more discoverable as well?

**Comment by rickle-msft** [comment]
@samuelsayag We can look into pulling this forward. I don't recall that there was a reason we intentionally did not add it; more that we had other priorities and hadn't gotten to it.

**Comment by rickle-msft** [comment]
@samuelsayag Apologies for the delay here. And I also must apologize because I was incorrect in my previous statement. After discussing with my team, it became clear that NameValidator was excluded from the new azure-storage-blob due to historical issues of it getting out-of-sync with the service. This becomes more important given the flexibility of azure-storage-blob to support multiple service versions. Unfortunately because of these concerns about the experience we can provide, we won't be able to accept this feature request. That said, we are happy to continue working with you to help improve your experience of the sdks if we can find an alternative solution.
