### ISSUE TITLE
Decoding multiple times a message raising SchemaParseException

### ISSUE THREAD

**Issue by ankursaini2006** [Azure/azure-sdk-for-java#27602]
Class : https://github.com/Azure/azure-sdk-for-java/blob/8f60b758143ce86e3c3e494ccba61676766ecb1e/sdk/schemaregistry/azure-data-schemaregistry-apacheavro/src/main/java/com/azure/data/schemaregistry/apacheavro/AvroSerializer.java#L165

Scenario: when AvroSerializer.decode() is called more than once for same message type, it is raising following exception since Schema.Paser keeps names already parsed.

```
org.apache.avro.SchemaParseException: Can't redefine: com.azure.data.schemaregistry.apacheavro.generatedtestsources.PlayingCard

	at org.apache.avro@1.10.1/org.apache.avro.Schema$Names.put(Schema.java:1542)
	at org.apache.avro@1.10.1/org.apache.avro.Schema$Names.add(Schema.java:1536)
	at org.apache.avro@1.10.1/org.apache.avro.Schema.parse(Schema.java:1655)
	at org.apache.avro@1.10.1/org.apache.avro.Schema$Parser.parse(Schema.java:1425)
	at org.apache.avro@1.10.1/org.apache.avro.Schema$Parser.parse(Schema.java:1413)
	at com.azure.data.schemaregistry.apacheavro/com.azure.data.schemaregistry.apacheavro.AvroSerializer.parseSchemaString(AvroSerializer.java:115)
	at com.azure.data.schemaregistry.apacheavro/com.azure.data.schemaregistry.apacheavro.AvroSerializer.decode(AvroSerializer.java:165)
```

Reproduction:

Edit AvroSerializerTest class for following test:

```
@Test
    public void encodesAndDecodesObject() {
        // Arrange
        final AvroSerializer registryUtils = new AvroSerializer(false, parser,
            encoderFactory, decoderFactory);

        final PlayingCard expected = PlayingCard.newBuilder()
            .setPlayingCardSuit(PlayingCardSuit.DIAMONDS)
            .setIsFaceCard(true)
            .setCardValue(13)
            .build();

        // Using the raw message encoder because the default card.getByteBuffer() uses BinaryMessageEncoder which adds
        // a header.
        final byte[] encoded = registryUtils.encode(expected);
        final byte[] schemaBytes = expected.getSchema().toString().getBytes(StandardCharsets.UTF_8);

        // Act
        final PlayingCard actual = registryUtils.decode(ByteBuffer.wrap(encoded), schemaBytes,
            TypeReference.createInstance(PlayingCard.class));

        **final PlayingCard thisWillBeFailed = registryUtils.decode(ByteBuffer.wrap(encoded), schemaBytes,
            TypeReference.createInstance(PlayingCard.class));**

        // Assert
        assertCardEquals(expected, actual);
    }
```

**Comment by joshfree** [comment]
@srnagar could you please take a look?

**Comment by srnagar** [comment]
@ankursaini2006 Could you please let us know what is the scenario where you would need to decode a named schema multiple times? Also, note that `AvroSerializer` is an internal type that is not for public use. The `decode` method is an implementation that shouldn't be called outside of this library. 

Regarding the change in unit test noted above, the exception is coming from the underlying Apache Avro package. This is working as expected and is according to the Avro spec where you cannot register named schemas multiple times. See [Avro spec](https://avro.apache.org/docs/1.9.2/spec.html#names) that states that the schema with the same name cannot be registered twice. 

Quoting the spec:
>  A schema or protocol may not contain multiple definitions of a fullname.

Given that the Apache Avro library doesn't allow parsing the named schema string multiple times, this exception is an expected behavior and isn't considered an issue that needs to be fixed. If you still have further questions regarding the unit test, please let us know.

**Comment by ankursaini2006** [comment]
@srnagar In our scenario, we are sending events from an application using avro serializer. When consuming these events, each event is being deserialised using spring bean SchemaRegistryApacheAvroSerializer. The first message is correctly deserialised since it is the first time Schema.Parser is called and names are created. While deserialising the second message the exception is raised since the both messages are received with same schemaId and Schema.Parser is static & keeps all the names in its state.

In the unit test, I tried to show the same scenario using same instance of AvroSerializer and decoding more than one message

**Comment by srnagar** [comment]
@ankursaini2006 thanks for clarifying that you are deserializing through SchemaRegistryApacheAvroSerializer. This type is public and shouldn't throw this error when multiple events with the same schema are deserialized. I have [created a PR](https://github.com/Azure/azure-sdk-for-java/pull/27688) to fix this bug and will be released in our next release cycle in April.
