### ISSUE TITLE
KeyVaultSecret does not get the full certificate (as originally uploaded). Missing CA Chain

### ISSUE THREAD

**Issue by kaioufcg** [Azure/azure-sdk-for-java#27629]
**Description**
After uploading a full PFX (cert, ca-chain, and private key) to azure keyvault, the certificate ca-chain is NOT included in the PFX when using java to retrieve certificate. If we use the original pfx, then the certificate chain is returned.

***Exception or Stack Trace***
N/A

**To Reproduce**

- Upload a full PFX (cert, ca chain, and private key) to Azure Keyvault using portal or powershell.
- Use documented instructions to download PFX via Java https://docs.microsoft.com/en-us/java/api/com.azure.security.keyvault.secrets.secretclient.getsecret?view=azure-java-stable
- Use Java to load the secret in the KeyStore Java and use the KeyStore methods to return the certificate chain

***Code Snippet***
`var fileInputStream = new ByteArrayInputStream(secretByteArray);`
`var keyStore = KeyStore.getInstance("JKS");`
`keyStore.load(fileInputStream, null);`
`var certchain = keystore.getCertificateChain(aliaz); // is null`

**Expected behavior**
Secret downloaded in keyvault should behave the same as pfx loaded.

**Screenshots**
![image](https://user-images.githubusercontent.com/1598224/157894664-95a8a5a2-f3d5-44cb-a178-1a836793bc59.png)

**Setup (please complete the following information):**
 - OS: Windows 10 PRO
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-security-keyvault-secrets:4.3.7
 - Java version: 15
 - Frameworks: Spring Boot

**Comment by vcolin7** [comment]
Hi @kaioufcg, although I think the Key Vault Secrets API was not designed to store PFX certificates (we offer a [Certificates API](https://docs.microsoft.com/en-us/azure/key-vault/certificates/tutorial-import-certificate?tabs=azure-portal) for just that), the value of a secret you save should not change at all between set and get operations. I tried to reproduce this myself with a PFX cert I created and saved as a secret in my own Key Vault and the contents were identical between the original value and what was retrieved via the `getSecret` operation. Here are some screenshots of the contents of a keystore containing the certificate read from a local file:

![image](https://user-images.githubusercontent.com/5799331/160768980-c0c0b3ad-43bc-4ea5-b4e4-e1599b6cd2b0.png)

and a keystore containing the certificate read from Azure Key Vault:

![image](https://user-images.githubusercontent.com/5799331/160769075-9167ca93-bfbd-4144-b91f-25776a48b551.png)

both taken in the same test run.

I also compared the string values and their corresponding byte array representations and they turned out to be identical. Here's the code that I used:

```java
// Load local certificate to keystore
Path certPath = Paths.get(myPfxCertPath);
byte[] certBytes = Files.readAllBytes(certPath);

// Encode the certificate to a URL-safe Base64 string
String certString = Base64.getEncoder().encodeToString(certBytes);

// Save the certificate's contents as a secret
secretClient.setSecret("myPfxCert", certString);

// Retrieve the secret
KeyVaultSecret retrievedCert = client.getSecret("myPfxCert");

// Compare the string originally set with the one obtained from Key Vault
String retrievedCertString = retrievedCert.getValue();
assertEquals(certString, retrievedCertString);

// Compare byte array representing the local certificate with the one obtained from Key Vault
byte[] retrievedCertBytes = Base64.getDecoder().decode(retrievedCertString);
assertArrayEquals(certBytes, retrievedCertBytes);

// Load the original local certificate into a keystore and get the certificate chain
InputStream inputStream = new ByteArrayInputStream(certBytes);
KeyStore keyStore = KeyStore.getInstance("JKS");
keyStore.load(inputStream, passwordCharArray);
Certificate[] certChain = keyStore.getCertificateChain("1");

// Load the retrieved certificate into a new keystore and get the certificate chain
InputStream retrievedInputStream = new ByteArrayInputStream(retrievedCertBytes);
KeyStore retrievedKeyStore = KeyStore.getInstance("JKS");
retrievedKeyStore.load(retrievedInputStream, passwordCharArray);
Certificate[] retrievedCertChain = retrievedKeyStore.getCertificateChain("1");

// Compare certificate chains' lengths
assertEquals(certChain.length, retrievedCertChain.length);
```

Is it possible you did not encode the certificate properly when originally saving it to Key Vault as a secret by using `Base64.getEncoder().encodeToString(certBytes)`?

**Comment by kaioufcg** [comment]
Hi @vcolin7, thanks for your attention. I'm running locally with my own certificates and it worked. Checking more, it doesn't appear to be the KEYVAULT API, i think it is at loading time of the KEYSTORE java, when I use the password as null. My PFX certificate has no password and did worked when I changed the value from null to empty when loading in the java keystore.

`keyStore.load(fileInputStream, null); --> keyStore.load(fileInputStream, "".toCharArray());`

Using the null value did not return an exception.

**Comment by vcolin7** [comment]
I see, thanks for letting us know. I'm glad you were able to make it work :)

I will be closing this issue for the time being but do not hesitate to reach out to us in case you find an issue with the Azure SDK for Java.
