### ISSUE TITLE
[FEATURE REQ] Add ability to manage rules with the ServiceBusReceiver

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-java#27711]
This existed in Track 1, and allowed users with only Listen claims to manage rules on the subscription that they had listen claims for. In Track 2, this can be done using the ServiceBusAdministrationClient, but it requires Manage claims.

.NET issue - https://github.com/Azure/azure-sdk-for-net/issues/25523
.NET PR - https://github.com/Azure/azure-sdk-for-net/pull/27346

**Comment by ZejiaJiang** [comment]
Hi @JoshLove-msft @jsquire I'm looking at this issue, after going through dotnet code, it feels like we just add a new client type `rule manager` to manage rules if user set `topice`, `subscription` and `connectionString` with `Listen` claims. Did I misunderstand?

**Comment by jsquire** [comment]
That was the approach that .NET took for modeling the API.   Since this functionality requires a dedicated set of AMQP links, it cannot be done directly via the Receiver's existing infrastructure and isolating that functionality in a dedicated type helps to manage that scope as well as logically group the related operations.

Personally, I'd like to see the pattern in Java align with the .NET API unless there's a good reason to deviate.

**Comment by ZejiaJiang** [comment]
Thank you @jsquire .I got it. And I'd like to make it clear. Actually the sender client or other client, they both use the dedicated set of AMQP links. What I mean above is we don't just add some new API to `ServiceBusReceiver`. My understanding is the rule manager use AMQP link to send operations to server just like sender and receiver, different from admin client using the HTTP.

**Comment by jsquire** [comment]
Correct; rule management here goes over a special set of AMQP links, not via the HTTP Atom service.
