### ISSUE TITLE
Azure blob storage - Android support

### ISSUE THREAD

**Issue by devzeze** [Azure/azure-sdk-for-java#27742]
### What SDK to use on Android?

I noticed the Android SDK is still referenced in the documentation https://github.com/Azure/azure-storage-java
But the last release was some years ago and it looks like SDK is not maintained anymore.

Are you supporting azure-storage for Android? And if yes what SDK should we use?

The Android SDK still works (implementation 'com.microsoft.azure.android:azure-storage-android:2.0.0@aar') but I am concerned about the future of this SDK and looks like is becoming a risk to rely on that.

I tried to use implementation 'com.azure:azure-storage-blob:12.14.4' and I got an exception:

java.lang.LinkageError: Package versions: jackson-annotations=0.0, jackson-core=0.0, jackson-databind=0.0, jackson-dataformat-xml=0.0, jackson-datatype-jsr310=0.0, azure-core=1.25.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot

However when I look at dependency tree the dependencies are there.

Thank you
Jose

**Comment by joshfree** [comment]
@amishra-dev could you please follow up?

/cc @anuchandy

**Comment by nishanthvasu** [comment]
@devzeze @joshfree I am also facing this issue. Can you please give update on this as soon as possible?

**Comment by izvictor** [comment]
Hello,
Do you have any news about this topic , we are facing the same dilemma? should we still use the Android SDK which seemes not to be maintained ?
Thank you for your answer.
Regards.

**Comment by devzeze** [comment]
Hi @joshfree , @amishra-dev any news regarding this topic?

**Comment by joshfree** [comment]
@jaschrep-msft is the right owner to follow up with on Storage

/cc @vcolin7 @anuchandy

**Comment by jaschrep-msft** [comment]
The library found at https://github.com/Azure/azure-storage-android is relegated to community support and has been for many years at this point.

The library found at https://github.com/Azure/azure-storage-java has been deprecated in favor of the storage libraries found in this Azure SDK for Java repository.

Storage libraries found here do not officially support Android. While there exists an [Azure SDK for Android](https://github.com/Azure/azure-sdk-for-android) repository, it supports very few services, not including Storage. There is currently no timeline on including Storage support for Android.

**Comment by vcolin7** [comment]
@jaschrep-msft is correct, there are currently no officially supported Storage libraries for Android. You can technically use the [Storage libraries for Java](https://learn.microsoft.com/java/api/overview/azure/storage?view=azure-java-stable) on Android API levels [26+ out-of-the-box and 21+ with desugaring enabled](https://projectreactor.io/docs/core/release/reference/#prerequisites) at your own risk as they were not designed to run on Android.

**Comment by vcolin7** [comment]
I spent a bit more time testing out whether it was possible to use the Java Storage library on Android. It turns out you can, but only in API levels 26 and 27, mainly because before level 26 you need to use desugaring for some Java APIs used by Reactor and our libraries and `MethodHandles.invokeExact()` (which we internally use) can only be desugared starting on level 26. On the other hand, the use of some external SDK APIs is restricted by Google starting on Android 28 (Pie), including two APIs we use in our Azure Core libraries:

```
Ljava/lang/invoke/MethodHandles$Lookup;-><init>(Ljava/lang/Class;)V
```

```
Ljava/lang/invoke/LambdaMetafactory;->metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;
```

I must note I ran these tests the same Storage's version as you (`12.14.4`, the latest). You can try to use an earlier version of the library if you want it to work with newer Android versions that don't use the restricted APIs I mentioned (28+). As far as I know, the latest Azure Core version that does not use this is `1.22.0`, which should be paired with `com.azure:azure-core-http-okhttp:1.7.5` and `com.azure:azure-storage-blob:12.14.2` (which isn't too far back from what you're using right now) to ensure everything works as expected.

I will be closing this issue for the time being as it is not really a bug, but feel free to open a feature request on the Android repository for supporting the Storage service, maybe with enough demand support can be added at some point in the future

**Comment by devzeze** [comment]
Feature request created on Android repository.

https://github.com/Azure/azure-sdk-for-android/issues/1272

If others also need the feature please go there and upvote.

https://github.com/Azure/azure-sdk-for-android/issues/1272
