### ISSUE TITLE
Closing ServiceBusReceiverClient does not fully shut down connections

### ISSUE THREAD

**Issue by mlbiam** [Azure/azure-sdk-for-java#28007]
# Description

I'm building a client to peek all messages in a queue.  I go through all the messages, but after calling `close()` there are still several threads running that keep my Java process from existing.  

```
System.out.println("here");

        String conString = "...";

        ServiceBusReceiverClient peekClient = new ServiceBusClientBuilder()
            .connectionString(conString)
            .receiver()
            .queueName("queuename")
            .buildClient();

        ServiceBusReceivedMessage m = null;
        
        while ((m = peekClient.peekMessage()) != null) {
            System.out.println(m.getApplicationProperties());
        }

        peekClient.close();

        System.out.println("done");

       //process continues to hang until i kill Java
```

## Actual Behavior
1.  After calling `close()` the process hangs
2. 

## Expected Behavior
1. Calling `close()` should remove all resources
2.

**Comment by joshfree** [comment]
@ki1729 could you please follow up with @mlbiam?

**Comment by ki1729** [comment]
Sure Josh,
@mlbiam does the process hang indefinitely? 
If it does, please let me know, and I can help wtith debugging it further
If it doesn't, and the process successfully closes after ~60 seconds after calling `close()`, this is expected behavior as the interal scheduler waits to process and close out any pending items before closing out the client. The operation itself is bound by the operation timeout, so `close()` should not hang indefinitely.

**Comment by ki1729** [comment]
@AndyNolpa - I created a bug to track the investigation into the NodeJS issue -> https://github.com/Azure/azure-sdk-for-js/issues/21266
