### ISSUE TITLE
[BUG] Examine Pattern.compile usage in sdk\servicebus

### ISSUE THREAD

**Issue by billwert** [Azure/azure-sdk-for-java#28206]
The following files have an instance of `Pattern.compile()` that should be examined and likely replaced.

- [x] azure-messaging-servicebus\src\main\java\com\azure\messaging\servicebus\implementation\ServiceBusManagementSerializer.java
- [x] azure-messaging-servicebus\src\main\java\com\azure\messaging\servicebus\ServiceBusClientBuilder.java
- [x] microsoft-azure-servicebus\src\main\java\com\microsoft\azure\servicebus\primitives\ConnectionStringBuilder.java
- [x] microsoft-azure-servicebus\src\main\java\com\microsoft\azure\servicebus\SubscriptionClient.java

**Comment by ZejiaJiang** [comment]
I used a tool to test these regex, here is the tools repo: https://github.com/NicolaasWeideman/RegexStaticAnalysis . After testing, they all look good. No need to replace them.

I referred the tools description to introduce this tool in brief：
> the analysis relies on inspecting the underlying NFA of a regex for exponential degree of ambiguity (EDA) and infinite degree of amgibuity (IDA) to determine whether the regex is vulnerable to exponential backtracking, or polynomial backtracking, respectively.

All of the regex don't contain exponential degree of ambiguity or infinite degree of amgibuity, the performance looks good as well.

It seems like that the tool doesn't support group name, in __azure-messaging-servicebus\src\main\java\com\azure\messaging\servicebus\implementation\ServiceBusManagementSerializer.java__ , there is a 
 regex use group name, I use 
```
xmlns:(\\w+)=\"http://schemas/\\.microsoft\\.com/netservices/2010/10/servicebus/connect\"
```
instead of 
```
"xmlns:(?<namespace>\\w+)=\"http://schemas\\.microsoft\\.com/netservices/2010/10/servicebus/connect\""
```
to input to the tools.

cc @conniey @anuchandy
