### ISSUE TITLE
Cosmos - Is there a prescribed way to build a query for 'Not Contains'?

### ISSUE THREAD

**Issue by ghost** [Azure/azure-sdk-for-java#28286]
**Query/Question**
Queries have support for CriteriaType 'Contains' - https://github.com/Azure/azure-sdk-for-java/blob/9873a52e38fa63e9a7c0a70e084420603d2d9fa2/sdk/cosmos/azure-spring-data-cosmos/src/main/java/com/azure/spring/data/cosmos/core/query/CriteriaType.java#L96. 

Is there a prescribed way to build a query for 'Not Contains'? Are there any plans to add it to the api?

***Why is this not a Bug or a feature Request?***
Need clarification before creating a feature request.

**Setup (please complete the following information if applicable):**
 - OS: na
 - IDE: na
 - Library/Libraries: azure-spring-data-cosmos-3.17.0.jar through 
 
   <groupId>com.azure.spring</groupId>
            <artifactId>azure-spring-boot-starter-cosmos</artifactId>
            <version>3.14.0</version>
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by christopinka-vp** [comment]
We ended up just mirroring sdk code for now which works and shows that simply adding it in the enum is all that's needed. If you can let us know if it's something you would like to support we can see if we can do the work for it. Thanks!

**Comment by kushagraThapar** [comment]
@christopinka-vp - Thanks for the investigation, I also believe it would just be adding the enum and making sure we test it out thoroughly. If can support the feature, that would be awesome. We really value contributions :)

**Comment by christopinka-vp** [comment]
@kushagraThapar It does seem like could be a useful feature. Can you confirm that it's wanted and I'll see what we can do to get a pr going for it. 

It spreads out a bit more than I thought a first pass. Looks like spring-data-commons comes into play and of course the spec generator. I'm not seeing tests yet for all the different types. To make sure they fall into the right slots in the switch cases? Can you point me to them if they are there? Not compiling quite yet so can't see coverage. Mono-repo may take a minute for my env to get ahold of. I may have to break out the big guns. : )

I've only given the dev guide in the readme a cursory glance. Are there any tricks to building the project you can think of up front? I'm already running into

Could not find artifact com.azure:azure-cosmos:pom:4.29.0-beta.1 in ossrh (https://oss.sonatype.org/content/repositories/snapshots/)

Any idea on turnaround time if we get it submitted and approved?

**Comment by kushagraThapar** [comment]
@christopinka-vp - yes, it could be a useful feature, and if you need it, definitely worth building. 

Tests are spread out in both unit and integration tests - `CriteriaUnitTest`, `CosmosTemplateIT`, `AbstractQueryGeneratorTest`, and many more. You can basically search the usages of `CriteriaType` object and you can find all the test classes referencing it. 

Regarding building it out, few things you might need to get out of the way are -> 

Build `azure-cosmos` locally and install it in your local repo. Then build `azure-spring-data-cosmos` 

To build, you might need to build some azure tools as well, which is mentioned here - https://github.com/Azure/azure-sdk-for-java/wiki/Building

Instead of building the whole repository, I would recommend just building `azure-cosmos` and `azure-spring-data-cosmos` since you only need those two modules. And then of course `azure-spring-data-cosmos-test` to test your changes. 

Command to build them locally is here -> 

`mvn -e -DskipTests  -Dgpg.skip -Dmaven.javadoc.skip=true -Dcodesnippet.skip=true -Dspotbugs.skip=true -Dcheckstyle.skip=true -Drevapi.skip=true -pl ,com.azure:azure-cosmos -am clean install`

`mvn -e -DskipTests  -Dgpg.skip -Dmaven.javadoc.skip=true -Dcodesnippet.skip=true -Dspotbugs.skip=true -Dcheckstyle.skip=true -Drevapi.skip=true -pl ,com.azure:azure-spring-data-cosmos -am clean install`

Please let me know if you run into any issues. 

Turnaround for releasing the feature is pretty quick. Azure SDKs release every first / second week of the month. So basically if we can get this feature by the end of this month, we can ship it out next month.
