### ISSUE TITLE
[Feature Req] Enable backward compatibility for the release pipelines

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-java#28398]
Release pipelines today can only support releasing libraries using the current version of the main. 

This makes it difficult to hotfix a given SDK release . It also makes bom releases time consuming since we need to retrofit older release tag sources on the latest main sources which results in merge conflicts.

**Comment by JimSuplizio** [comment]
@pallavit
/CC: @hallipr @weshaggard 
The title and description need to be better fleshed out. I don't quite understand what, exactly, you mean by "Enable backward compatibility for the release pipelines" and "can only support releasing libraries using the current version of main". What, specifically, is the specific scenario is that you're trying to flesh out?

**Comment by pallavit** [comment]
When I started with the patching effort I was told that our test and release pipelines are only guaranteed to work with latest sources of engineering infrastructure in main branch of the repo and may not necessarily work on an older snapshot of the branch. I am not 100 pc of the cause but I vaguely remember that we had dependency on things outside our repo (I believe azure-sdk-tools) which would have breaking changes from time to time.

As a result to prepare the patch for a library I have to do the following
1. Use the latest sources of main.
2. Reset the sources of only the library to be released to the last release tag and let the rest of the repo(mostly just eng) snapshot be current.
3. Update its dependencies
4. Make changes to the library sources such that it works with the latest eng snapshot of the main.
5. Trigger the release.

Instead I would like to do the following to release the patch
1. Hard reset the sources of the branch to the last release tag of the library.
2. Update the dependencies 
3. Trigger the release.
    i.e. if a pipeline was green and releasable against a snapshot of branch it should continue to be green and releasable against that snapshot of the branch in future as well.

**Comment by weshaggard** [comment]
While that is always a goal to make builds repeatable from hotfix/release tags it is not 100% possible. We do things like embed versions of tools and things like that to help make the builds repeatable however there are still a number of things that are completely outside of our control. I wouldn't expect the azure-sdk-tools repo to generally be an issue because we embed that into eng/common for the most part. An example of something we cannot control is the agent machine pools. Overtime the machines we are running on get retired and when that happens, we need to update to use a newer machine image. There is basically nothing we can do to make that work on older hotfix branches without changes. As a general rule of thumb, the older the release branch the more likely it will need some sort of update in order to make the branch functional enough to build, test, and release.

If there are specific examples of things that cause issues, we can try to address them if possible, but it is not possible to fix every case.

**Comment by pallavit** [comment]
> I wouldn't expect the azure-sdk-tools repo to generally be an issue because we embed that into eng/common for the most part

I vaguely remember eng\common depended on state outside of our repo.

>  An example of something we cannot control is the agent machine pools. Overtime the machines we are running on get retired and when that happens, we need to update to use a newer machine image.

These will be very one-off though right? And likely be caused in scenarios where the release tag is fairly old. 

> If there are specific examples of things that cause issues, we can try to address them if possible, but it is not possible to fix every case.

I do not have examples because I did not even use this approach. If we think that our own code is backward compatible here and devops limitation is the only blocker, I can move our scripts to doing this. And share examples if and when we run into an issue.

**Comment by JimSuplizio** [comment]
@pallavit, as per our conversation there's not really much to do here. We already try and minimize this but there are some things, like agent machine pools, which could still cause issues, but these are rare and few and far between.
