### ISSUE TITLE
[QUERY/ Feature Req] EventHubConsumerAsyncClient doesnt support checkpoint feature as Sync client does.

### ISSUE THREAD

**Issue by anandsugumaran** [Azure/azure-sdk-for-java#28622]
We are developing a reactive application and using EventHub for our event processing. Currently we are using EventProcessorClient for consuming the messages asynchronously like below.

```
Sinks.Many<CustomMessage> unicastSink; = Sinks.many().unicast().onBackpressureBuffer()
EventProcessorClientBuilder eventProcessorClientBuilder = new EventProcessorClientBuilder()
.connectionString("connStr","ehname")
.consumerGroup(EventHubClientBuilder.DEFAULT_CONSUMER_GROUP_NAME)
.processEvent(PARTITION_PROCESSOR).processError(ERROR_HANDLER)
.checkpointStore(new BlobCheckpointStore(blobContainerAsyncClient));

public Consumer<EventContext> PARTITION_PROCESSOR = eventContext -> {
    PartitionContext partitionContext = eventContext.getPartitionContext();    
    EventData eventData = eventContext.getEventData();    

    System.out.printf("Processing event from partition %s with sequence number %d with body: %s%n",
        partitionContext.getPartitionId(), eventData.getSequenceNumber(), eventData.getBodyAsString());
    
    unicastSink.tryEmitNext(new CustomMessage(eventData.getCorrelationId(), eventData.getBodyAsString()));      
    
    if (eventData.getSequenceNumber() % 10 == 0) {
        eventContext.updateCheckpoint();
    }
};
```
Here in the consumer function, we are emitting the messages to the sink as we consume which is working fine in a normal scenario. But i want to handle the backpressure mechanism. If the consumer(Operator) of these messages are processing slowly, then i have to slow down the consumption of messages from EventHub. How to achieve it ? I see there are reactive consumption in EventHubConsumerAsyncClient but they dont support Checkpoint feature.

**Comment by joshfree** [comment]
Thanks for reaching out to us via this GitHub issue, @anandsugumaran.  @conniey can you please follow up?

/cc @Azure/azsdk-sb-java

**Comment by conniey** [comment]
EventHubConsumerAsyncClient is our lower-level client, we do not support checkpointing because there is no concept of "load-balancing" between multiple instances that EventProcessorClient has.  You would have to manage your own checkpointing locally and results to a persistent storage. Additionally, EventProcessorClient recovers indefinitely when there is an error, EventHubConsumerAsyncClient will attempt to reconnect until the `retryOptions` elapse, after that, you'd have to own the recreation/reconnection of the client.
