### ISSUE TITLE
[BUG] Intermittent timeouts only when using azure-messaging-eventhubs 5.7.0.

### ISSUE THREAD

**Issue by jcruzzz** [Azure/azure-sdk-for-java#28675]
### Library name and version

azure-messaging-eventhubs 5.7.0.

### Describe the bug

We are experiencing intermittent timeouts with the following error message:
 
{727f4db7-4962-4ee9-adaf-75fae98f7818}- { xxx }[TNet:<Azure_Function_Name>PollFunction] [Error
occured in DHLExpressEventProcessor java.lang.IllegalStateException: Timeout on blocking read for 10000000000 NANOSECONDS EventHubHostConnectionConfig{hubName='<EH_entity_name>', hubSasKeyName='xxxx', blobContainer='<blob_name>'}]

We were using azure-messaging-eventhubs 5.7.0. The issue was mitigated with the downgrade of the mentioned library to the version 2.2.0. After the downgrade the issue never happened again so it points out to a library issue.
They are consuming the events from the namespace with a trigger function that writes the events to a blob storage 

References for RootCause:
'Connection aborted' error while trying to send events to Azure Event Hub using java EventHubClient API - Stack Overflow

Kindly noticed that the resources names were omitted, however there is a Microsoft Support Ticket opened, so we can share the resources names offline.

[DHLExpressEventProcessor.txt](https://github.com/Azure/azure-sdk-for-net/files/8633613/DHLExpressEventProcessor.txt)

### Expected behavior

We should be able to read the sent payload from the EventHub.

### Actual behavior

While trying to read event payloads from the  EventHub we are receiving the below mentioned error:
              
              [Error occured in DHLExpressEventProcessor java.lang.IllegalStateException: Timeout on blocking read for 10000000000 NANOSECONDS EventHubHostConnectionConfig{hubName='<EH entity>', hubSasKeyName='xxxx', blobContainer='<blob_container name>'}]

              Due to which we are not able to read any event from the payload.

### Reproduction Steps

1.	Send events to Azure EventHub namespace
2.	Consume EventHub events using an azure function

### Environment

1.	EH Namespace
2.	Function App: 
3.	Hub
4.	BlobContainer

**Comment by joshfree** [comment]
Hi @jcruzzz thank you for reaching out to us via this GitHub issue.  @conniey @Azure/azsdk-sb-java can you please follow up?

**Comment by jcruzzz** [comment]
Hi @joshfree and @conniey , do we have any feedback?

**Comment by jcruzzz** [comment]
@joshfree  and @conniey is there anything we can do here?

**Comment by conniey** [comment]
Hey, apologies for the delayed response here. 

I am looking at your issue... The [referenced StackOverflow issue](https://stackoverflow.com/questions/40905400/connection-aborted-error-while-trying-to-send-events-to-azure-event-hub-using) leverages the old library and is producing events.

1. Do you have a call stack for this exception message? It doesn't correspond to the code we have in the library, so it would help to understand where this exception is being thrown from, whether it is reading checkpoints, persisting them, etc.
2. Does this happen in our latest release, 5.12.1? Since 5.7.0, we've done many reliability fixes, etc.
3. Do you have any logs 5 minutes before/after this exception message?
    - see https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/TROUBLESHOOTING.md for information about logs.
4. What is the configuration SKU of your storage account?
