### ISSUE TITLE
[QUERY] Multitenancy Spring Data Cosmos

### ISSUE THREAD

**Issue by StrongSteve** [Azure/azure-sdk-for-java#29337]
**Query/Question**
How does the azure cosmos spring data SDK support building a multi tenant application?

***Why is this not a Bug or a feature Request?***
Not sure yet if it is a bug or a feature request or if we are missing some pieces of information.

**Setup (please complete the following information if applicable):**
Following the best practices defined by Microsoft regarding multi tenancy available at [Multitenant Cosmos](https://docs.microsoft.com/en-us/azure/architecture/guide/multitenant/service/cosmos-db) we realised multitenancy by defining one database per tenant, each one having the same containers.

Something like

data
  - database_1
      - dataContainer
  - database_2
      - dataContainer

Now at the moment I see no way on how to use the spring data cosmos SDK for implementing a simple query application for this use case.
In the end it boils down to setting the correct database name before executing a query (e.g. database_1, database_2, ...) which is not easily possible using the current state of the SDK.

Basically lets focus on the sync case
There is one implementation of `CosmosOperations `- `CosmosTemplate`.
Queries, Inserts, ... are executed over the CosmosTemplate (over some abstractions like CosmosRepos and so on)
BUT
`CosmosTemplate `has the database name defined as a final (not overwriteable) string and is used on every call with a pattern like
`
cosmosAsyncClient.getDatabase(this.databaseName).getContainer(containerName).doSomething()
`

At the moment one approach could be to use several CosmosTemplates - one for each tenant - which differ from each other only in regards to the database name.

_Shouldn't support for such a multi tenant scenario be part of the SDK?_

Furthermore the approaches documented in [Spring Data Cosmos](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/cosmos/azure-spring-data-cosmos) - MultiDatabase handling and one account multiple database - do not really fit such a multi tenant scenario as they are all based on the assumption of having separat repositories and so on. This is not suitable here as the repos, data model and so on are the same just the database differs depending on the tenant.

In case I am not overseeing something I can also share our approach for solving this issue in order to bring it to a pull request.

**Comment by StrongSteve** [comment]
Any updates? 🙃

**Comment by kushagraThapar** [comment]
@StrongSteve  as you mentioned, current implementation of spring data cosmos supports multiple database using multiple cosmos templates and different repositories. That is the only way to connect to multiple databases which you can find here - https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/cosmos/azure-spring-data-cosmos#multi-database-configuration

Also, this example can help you out with a complete end to end sample implementation - https://github.com/kushagraThapar/azure-spring-data-cosmos-demo

With multi-tenancy, however, I think the best way to go would be to use separate CosmosTemplates - so as to make sure each one of them uses different database - at the same time limiting your repositories, since you have those as common across different tenants. 

Another solution is to use Azure Cosmos Java SDK (on which spring data cosmos SDK is based upon). Because of limitations in spring data cosmos, supporting multi-tenancy will have to come out of the box.

**Comment by TheovanKraay** [comment]
Adding a comment here as we've made some updates to the Spring Data Client Library since the last answer was posted. Take a look at [this ](https://devblogs.microsoft.com/cosmosdb/building-multi-tenant-java-apps-using-spring-data-and-azure-cosmos-db/) blog. It shows how to make your Spring Data Repository reference and/or create different databases or containers in Azure Cosmos DB for each tenant - no need to have a separate app instance for each tenant.

**Comment by StrongSteve** [comment]
Just read it on linkedin. Amazing! Really appreciate it being part of the sdk now!
