### ISSUE TITLE
[FEATURE REQ] Clarify Spring Cloud Azure Properties

### ISSUE THREAD

**Issue by stliu** [Azure/azure-sdk-for-java#29578]
Some of Spring Cloud Azure properties are too general to understand what real value they expect.

for example, the `spring.cloud.azure.storage.blob.endpoint` property says `Endpoint for Azure Storage service` from [this page](https://microsoft.github.io/spring-cloud-azure/current/reference/html/appendix.html)

but which one is accepted or all of them are valid?

* https://{accountName}.blob.core.windows.net/{containerName}/{blobName}
* https://{accountName}.blob.core.windows.net/{containerName}
* https://{accountName}.blob.core.windows.net/

can I use `DefaultEndpointsProtocol=https;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=https://127.0.0.1:10000/devstoreaccount1;
` as the `endpoint` value? AFAIK, `BlobClientBuilder.endpoint()` accepts that.

if I use `https://{accountName}.blob.core.windows.net` as `endpoint` value, do I still have to provide `spring.cloud.azure.storage.blob.account-name`?

as you can see, there are way to vague and lead to configuration mistake.

this is from [Azure SDK BlobClientBuilder Javadoc](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobClientBuilder.java#L56)

>  <li>the endpoint through {@code .endpoint()}, including the container name and blob name, in the format of
> {@code https://{accountName}.blob.core.windows.net/{containerName}/{blobName}}.

**Comment by saragluna** [comment]
The same problem exists for all endpoint properties, like for Key Vault. Should users provide `some.vault.azure.net` or `https://some.vault.azure.net/`, we should clarify the expected values.

**Comment by stliu** [comment]
### principal

* clear and no confusion, avoid ambiguity
* align with Azure SDK ( Doc and code , javadoc )

### steps

- [ ] Common / Global properties
- [ ] AAD
- [ ] KeyVault
- [ ] Storage
- [ ] Event Hubs
- [ ] Service Bus
- [ ] App Configuration
- [ ] Cosmos

**Comment by Netyyyy** [comment]
After preliminary investigation and sorting out, the following problems can be found to be improved:

1. Endpoint or resourceId not clear：

   1. Description not correct

      | spring.cloud.azure.profile.environment.data-lake-endpoint-resource-id | The  Data Lake endpoint. |
      | ------------------------------------------------------------ | ------------------------ |

   2. Endpoint actually point to resourceId

      | spring.cloud.azure.profile.environment.azure-log-analytics-endpoint | The  Azure Log Analytics endpoint. | =azureLogAnalyticsResourceId?  Sample: "https://api.loganalytics.io/" |
      | ------------------------------------------------------------ | ---------------------------------- | ------------------------------------------------------------ |

 2. Format endpoint:

    provide a format for all URLs, such as: 

    ```
    https://{accountName}.blob.core.windows.net/{containerName}/{blobName}
    ```

 3. Align with SDK description:

    | spring.cloud.azure.client.amqp.transport-type | Transport  type for AMQP-based client. | All  TransportType switches available for AMQP protocol. |
    | --------------------------------------------- | -------------------------------------- | -------------------------------------------------------- |

 4. No instance:

    provide instance for some properties, such as:

    | spring.cloud.azure.client.amqp.transport-type | Transport  type for AMQP-based client. | [AMQP,AMQP_WEB_SOCKETS ] |
    | --------------------------------------------- | -------------------------------------- | ------------------------ |

    | spring.cloud.azure.profile.environment.key-vault-dns-suffix | The  Key Vault DNS suffix. | For instance, '.vault.azure.net' |
    | ----------------------------------------------------------- | -------------------------- | -------------------------------- |

**Comment by Netyyyy** [comment]
## Common / Global properties

Property | Current Description | Problem | Proposed Description
-- | -- | -- | --
spring.cloud.azure.client-id | Client ID to use when performing service principal authentication with Azure. This is a legacy property. |   |  
spring.cloud.azure.client-secret | Client secret to use when performing service principal authentication with Azure. This is a legacy property. |   |  
spring.cloud.azure.client.amqp.transport-type | Transport type for AMQP-based client. | Doesn't know what/how to configure | Transport type for AMQP-based client. Supported types are: AMQP, AMQP_WEB_SOCKETS.
spring.cloud.azure.client.application-id | Represents current application and is used for telemetry/monitoring purposes. |   |  
spring.cloud.azure.client.http.connect-timeout | Amount of time the request attempts to connect to the remote host and the connection is resolved. | Doesn't know the unit | Amount of time(Duration) the request attempts to connect to the remote host and the connection is resolved.
spring.cloud.azure.client.http.connection-idle-timeout | Amount of time before an idle connection. | Doesn't know the unit | Amount of time(Duration) before an idle connection.
spring.cloud.azure.client.http.headers | List of headers applied to each request sent with client. | Doesn't know what/how to configure | List of headers applied to each request sent with client. For instance, '"myCustomHeader", "myStaticValue"'.
spring.cloud.azure.client.http.headers[0].name | The name of the header. |   |  
spring.cloud.azure.client.http.headers[0].values | List of values of the header. |   |  
spring.cloud.azure.client.http.logging.allowed-header-names | Comma-delimited list of allowlist headers that should be logged. | Doesn't know what/how to configure | Comma-delimited list of allowlist headers that should be logged. For instance, '"x-ms-request-id", "x-ms-client-request-id"'.
spring.cloud.azure.client.http.logging.allowed-query-param-names | Comma-delimited list of allowlist query parameters. | Doesn't know what/how to configure | Comma-delimited list of allowlist query parameters. For instance, '"api-version"'.
spring.cloud.azure.client.http.logging.level | The level of detail to log on HTTP messages. | Doesn't know what/how to configure | The level of detail to log on HTTP messages. Supported types are: NONE, BASIC, HEADERS, BODY, BODY_AND_HEADERS.
spring.cloud.azure.client.http.logging.pretty-print-body | Whether to pretty print the message bodies. |   |  
spring.cloud.azure.client.http.maximum-connection-pool-size | Maximum connection pool size used by the underlying HTTP client. |   |  
spring.cloud.azure.client.http.read-timeout | Amount of time used when reading the server response. | Doesn't know the unit | Amount of time(Duration) used when reading the server response.
spring.cloud.azure.client.http.response-timeout | Amount of time used when waiting for a server to reply. | Doesn't know the unit | Amount of time(Duration) used when waiting for a server to reply.
spring.cloud.azure.client.http.write-timeout | Amount of time each request being sent over the wire. | Doesn't know the unit | Amount of time(Duration) each request being sent over the wire.
spring.cloud.azure.credential.client-certificate-password | Password of the certificate file. |   |  
spring.cloud.azure.credential.client-certificate-path | Path of a PEM certificate file to use when performing service principal authentication with Azure. |   |  
spring.cloud.azure.credential.client-id | Client ID to use when performing service principal authentication with Azure. |   |  
spring.cloud.azure.credential.client-secret | Client secret to use when performing service principal authentication with Azure. |   |  
spring.cloud.azure.credential.managed-identity-enabled | Whether to enable managed identity to authenticate with Azure. If true and the client-id is set, will use the client ID as user assigned managed identity client ID. The default value is false. |   |  
spring.cloud.azure.credential.password | Password to use when performing username/password authentication with Azure. |   |  
spring.cloud.azure.credential.username | Username to use when performing username/password authentication with Azure. |   |  
spring.cloud.azure.message-converter.isolated-object-mapper | Whether to use an isolated object mapper to serialize/deserialize messages in EventHubsMessageConverter/ServiceBusMessageConverter/StorageQueueMessageConverter. The default value is true. |   |  
spring.cloud.azure.profile.cloud-type | Name of the Azure cloud to connect to. | Doesn't know what/how to configure | Name of the Azure cloud to connect to. Supported types are: AZURE, AZURE_CHINA, AZURE_GERMANY, AZURE_US_GOVERNMENT, OTHER.
spring.cloud.azure.profile.subscription-id | Subscription ID to use when connecting to Azure resources. |   |  
spring.cloud.azure.profile.tenant-id | Tenant ID for Azure resources. |   |  
spring.cloud.azure.proxy.amqp.authentication-type | Authentication type used against the proxy. | Doesn't know what/how to configure | Authentication type used against the proxy. For instance, 'none', 'basic', 'digest'.
spring.cloud.azure.proxy.hostname | The host of the proxy. |   |  
spring.cloud.azure.proxy.http.non-proxy-hosts | A list of hosts or CIDR to not use proxy HTTP/HTTPS connections through. |   |  
spring.cloud.azure.proxy.password | Password used to authenticate with the proxy. |   |  
spring.cloud.azure.proxy.port | The port of the proxy. |   |  
spring.cloud.azure.proxy.type | Type of the proxy. | Doesn't know what/how to configure | Type of the proxy. For instance, 'http', 'socks4', 'socks5'.
spring.cloud.azure.proxy.username | Username used to authenticate with the proxy. |   |  
spring.cloud.azure.retry.amqp.try-timeout | How long to wait until a timeout. | Doesn't know the unit | Amount of time(Duration) to wait until timeout.
spring.cloud.azure.retry.exponential.base-delay | Amount of time to wait between retry attempts. | Doesn't know the unit | Amount of time(Duration) to wait between retry attempts.
spring.cloud.azure.retry.exponential.max-delay | Maximum permissible amount of time between retry attempts. |   |  
spring.cloud.azure.retry.exponential.max-retries | The maximum number of attempts. |   |  
spring.cloud.azure.retry.fixed.delay | Amount of time to wait between retry attempts. | Doesn't know the unit | Amount of time(Duration) to wait between retry attempts.
spring.cloud.azure.retry.fixed.max-retries | The maximum number of attempts. |   |  
spring.cloud.azure.retry.mode | Retry backoff mode. | Doesn't know what/how to configure | The retry backoff mode when retrying. Supported types are: FIXED, EXPONENTIAL.

**Comment by stliu** [comment]
@Netyyyy we probably should not use table due to this poor render on github, let's change to use a bulleted list instead

## Commons

* `spring.cloud.azure.retry.mode`
  * Retry backoff mode.
  * Doesn't know what/how to configure
  * The retry backoff mode when retrying. Supported types are: FIXED, EXPONENTIAL.

the format is:

## {Section}
* `property name`
  * CURRENT DESCRIPTION
  * PROBLEM or N/A
  * NEW DESCRIPTION

**Comment by Netyyyy** [comment]
## Common Properties

- spring.cloud.azure.client-id
  - Client ID to use when performing service principal authentication with Azure. This is a legacy property.
- spring.cloud.azure.client-secret
  - Client secret to use when performing service principal authentication with Azure. This is a legacy property.
- spring.cloud.azure.client.amqp.transport-type
  - Transport type for AMQP-based client.
  - Doesn't know what/how to configure
  - Transport type for AMQP-based client. Supported types are: AMQP, AMQP_WEB_SOCKETS.
- spring.cloud.azure.client.application-id
  - Represents current application and is used for telemetry/monitoring purposes.
- spring.cloud.azure.client.http.connect-timeout
  - Amount of time the request attempts to connect to the remote host and the connection is resolved.
  - Doesn't know the unit
  - Amount of time(Duration) the request attempts to connect to the remote host and the connection is resolved.
- spring.cloud.azure.client.http.connection-idle-timeout
  - Amount of time before an idle connection.
  - Doesn't know the unit
  - Amount of time(Duration) before an idle connection.
- spring.cloud.azure.client.http.headers
  - List of headers applied to each request sent with client.
  -  Doesn't know what/how to configure
  - List of headers applied to each request sent with client. For instance, '"myCustomHeader", "myStaticValue"'.
- spring.cloud.azure.client.http.headers[0].name
  -  The name of the header.
- spring.cloud.azure.client.http.headers[0].values
  -  List of values of the header.
- spring.cloud.azure.client.http.logging.allowed-header-names
  - Comma-delimited list of allowlist headers that should be logged.
  - Doesn't know what/how to configure
  - Comma-delimited list of allowlist headers that should be logged. The default value is `"x-ms-request-id","x-ms-client-request-id","x-ms-return-client-request-id","traceparent","MS-CV","Accept","Cache-Control","Connection","Content-Length","Content-Type","Date","ETag","Expires","If-Match","If-Modified-Since","If-None-Match","If-Unmodified-Since","Last-Modified","Pragma","Request-Id","Retry-After","Server","Transfer-Encoding","User-Agent","WWW-Authenticate"`.
- spring.cloud.azure.client.http.logging.allowed-query-param-names
  - Comma-delimited list of allowlist query parameters.
  - Doesn't know what/how to configure
  - Comma-delimited list of allowlist query parameters. The default value is `"api-version"`.
- spring.cloud.azure.client.http.logging.level
  - The level of detail to log on HTTP messages.
  - Doesn't know what/how to configure
  - The level of detail to log on HTTP messages. Supported types are: NONE, BASIC, HEADERS, BODY, BODY_AND_HEADERS. The default value is `NONE`.
- spring.cloud.azure.client.http.logging.pretty-print-body
  - Whether to pretty print the message bodies.
  - Doesn't know the default value
  - Whether to pretty print the message bodies. The default value is `false`.
- spring.cloud.azure.client.http.maximum-connection-pool-size
  - Maximum connection pool size used by the underlying HTTP client.
- spring.cloud.azure.client.http.read-timeout
  - Amount of time used when reading the server response.
  - Doesn't know the unit
  - Amount of time(Duration) used when reading the server response.
- spring.cloud.azure.client.http.response-timeout
  - Amount of time used when waiting for a server to reply.
  - Doesn't know the unit
  - Amount of time(Duration) used when waiting for a server to reply.
- spring.cloud.azure.client.http.write-timeout
  - Amount of time each request being sent over the wire.
  - Doesn't know the unit
  - Amount of time(Duration) each request being sent over the wire.
- spring.cloud.azure.credential.client-certificate-password
  - Password of the certificate file.
- spring.cloud.azure.credential.client-certificate-path
  - Path of a PEM certificate file to use when performing service principal authentication with Azure.
- spring.cloud.azure.credential.client-id
  - Client ID to use when performing service principal authentication with Azure.
- spring.cloud.azure.credential.client-secret
  - Client secret to use when performing service principal authentication with Azure.
- spring.cloud.azure.credential.managed-identity-enabled
  - Whether to enable managed identity to authenticate with Azure. If true and the client-id is set, will use the client ID as user assigned managed identity client ID. The default value is `false`.
- spring.cloud.azure.credential.password
  - Password to use when performing username/password authentication with Azure.
- spring.cloud.azure.credential.username
  - Username to use when performing username/password authentication with Azure.
- spring.cloud.azure.message-converter.isolated-object-mapper
  - Whether to use an isolated object mapper to serialize/deserialize messages in `EventHubsMessageConverter/ServiceBusMessageConverter/StorageQueueMessageConverter`. The default value is `true`.
- spring.cloud.azure.profile.cloud-type
  - Name of the Azure cloud to connect to.
  - Doesn't know what/how to configure
  - Name of the Azure cloud to connect to. Supported types are: AZURE, AZURE_CHINA, AZURE_GERMANY, AZURE_US_GOVERNMENT, OTHER. The default value is `AZURE`. 
- spring.cloud.azure.profile.subscription-id
  - Subscription ID to use when connecting to Azure resources.
- spring.cloud.azure.profile.tenant-id
  - Tenant ID for Azure resources.
- spring.cloud.azure.proxy.amqp.authentication-type
  - Authentication type used against the proxy.
  - Doesn't know what/how to configure
  - Authentication type used against the proxy. For instance, 'none', 'basic', 'digest'. The default value is `'none'`.
- spring.cloud.azure.proxy.hostname
  - The host of the proxy.
- spring.cloud.azure.proxy.http.non-proxy-hosts
  - A list of hosts or CIDR to not use proxy HTTP/HTTPS connections through.
- spring.cloud.azure.proxy.password
  - Password used to authenticate with the proxy.
- spring.cloud.azure.proxy.port
  - The port of the proxy.
- spring.cloud.azure.proxy.type
  - Type of the proxy.
  - Doesn't know what/how to configure
  - Type of the proxy. For instance of http, 'http', 'socks4', 'socks5'. For instance of amqp, 'http', 'socks'.
- spring.cloud.azure.proxy.username
  - Username used to authenticate with the proxy.
- spring.cloud.azure.retry.amqp.try-timeout
  - How long to wait until a timeout.
  - Doesn't know the unit
  - Amount of time(Duration) to wait until timeout.
- spring.cloud.azure.retry.exponential.base-delay
  - Amount of time to wait between retry attempts.
  - Doesn't know the unit
  - Amount of time(Duration) to wait between retry attempts.
- spring.cloud.azure.retry.exponential.max-delay
  - Maximum permissible amount of time between retry attempts.
- spring.cloud.azure.retry.exponential.max-retries
  - The maximum number of attempts.
- spring.cloud.azure.retry.fixed.delay
  - Amount of time to wait between retry attempts.
  - Doesn't know the unit
  - Amount of time(Duration) to wait between retry attempts.
- spring.cloud.azure.retry.fixed.max-retries
  - The maximum number of attempts.
- spring.cloud.azure.retry.mode
  - Retry backoff mode.
  - Doesn't know what/how to configure
  - The retry backoff mode when retrying. Supported types are: FIXED, EXPONENTIAL.

**Comment by Netyyyy** [comment]
## Azure AD properties
- spring.cloud.azure.active-directory.app-id-uri
  - App ID URI which might be used in the "aud" claim of an id_token.
  - Doesn't know the format
  - App ID URI which might be used in the "aud" claim of an id_token. For instance, 'api://{applicationId}'.
  
- spring.cloud.azure.active-directory.application-type
  - Type of the Azure AD application.
  - Doesn't know what/how to configure
  - Type of the Azure AD application. Supported types are: WEB_APPLICATION, RESOURCE_SERVER, RESOURCE_SERVER_WITH_OBO, WEB_APPLICATION_AND_RESOURCE_SERVER. The value can be inferred by dependencies, only 'web_application_and_resource_server' must be configured manually.

- spring.cloud.azure.active-directory.authenticate-additional-parameters
  - Add additional parameters to the Authorization URL.
  - Doesn't know what/how to configure
  - Add additional parameters to the Authorization URL. For instance, 'spring.cloud.azure.active-directory.authenticate-additional-parameters.prompt = login'.

- spring.cloud.azure.active-directory.authorization-clients
  - The OAuth2 authorization clients.
  
- spring.cloud.azure.active-directory.credential.client-certificate-password
  - Password of the certificate file.
- spring.cloud.azure.active-directory.credential.client-certificate-path
  - Path of a PFX or P12 certificate file to use when performing service principal authentication with Azure.
- spring.cloud.azure.active-directory.credential.client-id
  - Client ID to use when performing service principal authentication with Azure.
- spring.cloud.azure.active-directory.credential.client-secret
  - Client secret to use when performing service principal authentication with Azure.
- spring.cloud.azure.active-directory.enabled
  - Whether to enable Azure Active Directory related auto-configuration. The default value is `false`.
- spring.cloud.azure.active-directory.jwk-set-cache-lifespan
  - The lifespan of the cached JWK set before it expires, default is 5 minutes. The default value is `5m`.
- Duplicate content
  - The lifespan(duration) of the cached JWK set before it expires. The default value is `5m`.
- spring.cloud.azure.active-directory.jwk-set-cache-refresh-time
  - The refresh time of the cached JWK set before it expires, default is 5 minutes. The default value is `5m`.
  - Duplicate content
  - The refresh time(duration) of the cached JWK set before it expires. The default value is `5m`.
- spring.cloud.azure.active-directory.jwt-connect-timeout
  - Connection Timeout for the JWKSet Remote URL call.
  - Doesn't know the unit
  - Connection Timeout(duration) for the JWKSet Remote URL call. The default value is `500s`.
- spring.cloud.azure.active-directory.jwt-read-timeout
  - Read Timeout for the JWKSet Remote URL call.
  - Doesn't know the unit
  - Read Timeout(duration) for the JWKSet Remote URL call. The default value is `500s`.
- spring.cloud.azure.active-directory.jwt-size-limit
  - Size limit in Bytes of the JWKSet Remote URL call.
  - Default
  - Size limit in Bytes of the JWKSet Remote URL call. The default value is `51200`.
- spring.cloud.azure.active-directory.post-logout-redirect-uri
  - The redirect uri after logout.
  - Doesn't know the format
  - The redirect uri after logout. For instance, 'http://localhost:8080/'.
- spring.cloud.azure.active-directory.profile.environment.active-directory-endpoint
  - Azure Active Directory endpoint. For example: https://login.microsoftonline.com/
- spring.cloud.azure.active-directory.profile.environment.microsoft-graph-endpoint
  - Microsoft Graph endpoint. For example: https://graph.microsoft.com/
- spring.cloud.azure.active-directory.profile.tenant-id
  - Azure Tenant ID.
- spring.cloud.azure.active-directory.redirect-uri-template
  - Redirection Endpoint: Used by the authorization server to return responses containing authorization credentials to the client via the resource owner user-agent. The default value is `{baseUrl}/login/oauth2/code/`.
- spring.cloud.azure.active-directory.resource-server.claim-to-authority-prefix-map
  - Configure which claim will be used to build GrantedAuthority, and prefix of the GrantedAuthority's string value. Default value is: "scp" -> "SCOPE_", "roles" -> "APPROLE_".
  - Align format of default value 
  - Configure which claim will be used to build GrantedAuthority, and prefix of the GrantedAuthority's string value. The default value is `"scp" -> "SCOPE_", "roles" -> "APPROLE_"`.
- spring.cloud.azure.active-directory.resource-server.principal-claim-name
  - Configure which claim in access token be returned in AuthenticatedPrincipal#getName. Default value is "sub".
  - Align format of default value 
  - Configure which claim in access token be returned in AuthenticatedPrincipal#getName. The default value is `"sub"`.
- spring.cloud.azure.active-directory.session-stateless
  - If true activates the stateless auth filter AADAppRoleStatelessAuthenticationFilter. The default is false which activates AADAuthenticationFilter. The default value is `false`.
- spring.cloud.azure.active-directory.user-group.allowed-group-ids
  - The group IDs can be used to construct GrantedAuthority.
- spring.cloud.azure.active-directory.user-group.allowed-group-names
  - The group names can be used to construct GrantedAuthority.
- spring.cloud.azure.active-directory.user-group.use-transitive-members
  - If "true", use "v1.0/me/transitiveMemberOf" to get members. Otherwise, use "v1.0/me/memberOf". The default value is `false`.
  - Not complete
  - Whether to use transitive way to get members. If "true", use "v1.0/me/transitiveMemberOf" to get members. Otherwise, use "v1.0/me/memberOf". The default value is `false`.
- spring.cloud.azure.active-directory.user-name-attribute
  - Decide which claim to be principal's name.

**Comment by Netyyyy** [comment]
## Azure AD B2C properties
- spring.cloud.azure.active-directory.b2c.app-id-uri
  - App ID URI which might be used in the "aud" claim of a token.
  - Doesn't know the format
  - App ID URI which might be used in the "aud" claim of a token. For instance, '[https://{hostname}/{applicationId}](https://%7Bhostname%7D/%7bapplicationId%7d)'.
- spring.cloud.azure.active-directory.b2c.authenticate-additional-parameters
  - Additional parameters for authentication.
  - Doesn't know what/how to configure
  - Additional parameters for authentication. For instance, 'prompt: login'.
- spring.cloud.azure.active-directory.b2c.authorization-clients
  - Specify client configuration.
  - Doesn't know what/how to configure
  - Specify client configuration. For instance, 'authorizationGrantType: client_credentials'.
- spring.cloud.azure.active-directory.b2c.base-uri
  - Azure AD B2C endpoint base URI.
  - Doesn't know the format
  - Azure AD B2C endpoint base uri. The default value is `"/oauth2/authorization"`.
- spring.cloud.azure.active-directory.b2c.credential.client-id
  - Client ID to use when performing service principal authentication with Azure.
- spring.cloud.azure.active-directory.b2c.credential.client-secret
  - Client secret to use when performing service principal authentication with Azure.
- spring.cloud.azure.active-directory.b2c.enabled
  - Whether to enable Azure Active Directory B2C related auto-configuration. The default value is false.
- spring.cloud.azure.active-directory.b2c.jwt-connect-timeout
  - Connection Timeout for the JWKSet Remote URL call.
  - Doesn't know the unit
  - Connection Timeout(duration) for the JWKSet Remote URL call. The default value is `500s`.
- spring.cloud.azure.active-directory.b2c.jwt-read-timeout
  - Read Timeout for the JWKSet Remote URL call.
  - Doesn't know the unit
  - Read Timeout(duration) for the JWKSet Remote URL call. The default value is `500s`.
- spring.cloud.azure.active-directory.b2c.jwt-size-limit
  - Size limit in Bytes of the JWKSet Remote URL call.
  - Default
  - Size limit in Bytes of the JWKSet Remote URL call. The default value is `50*1024`.
- spring.cloud.azure.active-directory.b2c.login-flow
  - Specify the primary sign-in flow key. The default value is sign-up-or-sign-in.
- spring.cloud.azure.active-directory.b2c.logout-success-url
  - Redirect URL after logout. The default value is http://localhost:8080/login.
- spring.cloud.azure.active-directory.b2c.profile.tenant-id
  - Azure Tenant ID.
- spring.cloud.azure.active-directory.b2c.reply-url
  - Reply URL after get authorization code. The default value is {baseUrl}/login/oauth2/code/.
- spring.cloud.azure.active-directory.b2c.user-flows
  - User flows.
  - Doesn't know what/how to configure
  - User flows. For instance, 'sign-up-or-sign-in: B2C_signin_or_signup'.
- spring.cloud.azure.active-directory.b2c.user-name-attribute-name
  - User name attribute name.

**Comment by Netyyyy** [comment]
## App Configuration properties
- spring.cloud.azure.appconfiguration.client.application-id
  - Represents current application and is used for telemetry/monitoring purposes.
- spring.cloud.azure.appconfiguration.connection-string
  - Connection string of the Azure App Configuration instance.
- spring.cloud.azure.appconfiguration.endpoint
  - Endpoint of the Azure App Configuration instance.
  - Doesn't know the format
  - Endpoint of the Azure App Configuration instance. For instance, 'https://{appConfigurationName}.azconfig.io'.
- spring.cloud.azure.appconfiguration.resource.region
  - The region of an Azure resource.
- Doesn't know what/how to configure
  - The region of an Azure resource. For instance, '"eastus"'.
- spring.cloud.azure.appconfiguration.service-version
  - Version of the app configuration service to be used when making request.
  - Doesn't know default value
  - Version of the app configuration service to be used when making request. The default value is `"1.0"`.

**Comment by Netyyyy** [comment]
## KeyVault Properties
- spring.cloud.azure.keyvault.endpoint
  - Azure Key Vault endpoint.
  - Doesn't know the format
  - Azure Key Vault endpoint. For instance, 'https://{your-unique-keyvault-name}.vault.azure.net/'.
- spring.cloud.azure.keyvault.secret.endpoint
  - Azure Key Vault endpoint.
  - Doesn't know the format
  - Azure Key Vault endpoint. For instance, 'https://{your-unique-keyvault-name}.vault.azure.net/'.
- spring.cloud.azure.keyvault.secret.property-sources
  - Azure Key Vault property sources.
  - Doesn't know what/how to configure
  - List of Key Vault property source. For instance, '
   -name:key-vault-property-source-1
    endpoint:${ENDPOINT_1}
    -name:key-vault-property-source-2
     endpoint:${ENDPOINT_2}'
- spring.cloud.azure.keyvault.secret.property-sources[0].case-sensitive
  - Defines the constant for the property that enables/disables case-sensitive keys.
  - Not clear
  - Whether to enable case-sensitive for secret keys. The default value is `false`.
- spring.cloud.azure.keyvault.secret.property-sources[0].endpoint
  - Azure Key Vault endpoint.
  - Doesn't know the format
  - Azure Key Vault endpoint. For instance, 'https://{your-unique-keyvault-name}.vault.azure.net/'.
- spring.cloud.azure.keyvault.secret.property-sources[0].secret-keys
  - The secret keys supported for this property source.
  - Not clear
  - The configured secret keys will be loaded from Azure Key Vaults secret, if configured nothing, then load all the secrets.
- spring.cloud.azure.keyvault.certificate.endpoint
  - Azure Key Vault endpoint.
  - Doesn't know the format
  - Azure Key Vault endpoint. For instance, 'https://{your-unique-keyvault-name}.vault.azure.net/'.

**Comment by Netyyyy** [comment]
## Storage Properties
- spring.cloud.azure.storage.endpoint
  - Endpoint for Azure Storage service.
  - Doesn't know the format
  - Endpoint for Azure Storage service. For instance, 'https://{storage-account-name}.blob.storage.azure.net' for blob or 'https://{storage-account-name}.file.storage.azure.net' for file share or 'https://{storage-account-name}.queue.storage.azure.net' for queue.
- spring.cloud.azure.storage.retry.try-timeout
  - Amount of time to wait until a timeout.
  - Doesn't know the unit
  - Amount of time(Duration) to wait until a timeout.
- spring.cloud.azure.storage.blob.customer-provided-key
  - Customer provided key used to encrypt blob contents on the server.
  - Not clear
  - Customer-provided encryption key(base64 encoded string) used to encrypt blob contents on the server. See Microsoft doc about Customer-provided Keys for more details: https://learn.microsoft.com/azure/storage/blobs/encryption-customer-provided-keys
- spring.cloud.azure.storage.blob.encryption-scope
  - Encryption scope used to encrypt blob contents on the server.
  - Not clear
  - Specifies the name of the encryption scope to use to encrypt the data provided in the request. If not specified, encryption is performed with the default account encryption scope. See Microsoft doc about Encryption Scope for more details: https://learn.microsoft.com/azure/storage/blobs/encryption-scope-overview
- spring.cloud.azure.storage.blob.endpoint
  - Endpoint for Azure Storage service.
  - Doesn't know the format
  - Endpoint for Azure Storage service. For instance, 'https://{storage-account-name}.blob.storage.azure.net' for blob or 'https://{storage-account-name}.file.storage.azure.net' for file share or 'https://{storage-account-name}.queue.storage.azure.net' for queue.
- spring.cloud.azure.storage.fileshare.endpoint
  - Endpoint for Azure Storage service.
  - Doesn't know the format
  - Endpoint for Azure Storage service. For instance, 'https://{storage-account-name}.blob.storage.azure.net' for blob or 'https://{storage-account-name}.file.storage.azure.net' for file share or 'https://{storage-account-name}.queue.storage.azure.net' for queue.
- spring.cloud.azure.storage.fileshare.retry.secondary-host
  - Secondary Storage account to retry requests against.
  - Doesn't know the format
  - Secondary Storage account to retry requests against if the primary region becomes unavailable. For instance, 'https://{storage-account-name}-secondary.file.storage.azure.net'.
- spring.cloud.azure.storage.queue.endpoint
  - Endpoint for Azure Storage service.
  - Doesn't know the format
  - Endpoint for Azure Storage service. For instance, 'https://{storage-account-name}.queue.storage.azure.net'.
- spring.cloud.azure.storage.queue.message-encoding
  - How queue message body is represented in HTTP requests and responses.
  - Doesn't know what to configure
  - How queue message body is represented in HTTP requests and responses. All Supported types are: NONE, BASE64.
