### ISSUE TITLE
[QUERY] Spring cloud stream azure service bus amqp over websocket ?

### ISSUE THREAD

**Issue by numirov** [Azure/azure-sdk-for-java#29657]
**Query/Question**
Does spring cloud stream service bus support amqp over websocket? I tried setting it like this:

```properties
spring.cloud.azure.servicebus.consumer.client.transport-type=amqp_web_sockets
spring.cloud.stream.servicebus.bindings.consume-in-0.consumer.namespace=sb-namespace
spring.cloud.stream.servicebus.bindings.consume-in-0.consumer.domain-name=servicebus.windows.net
spring.cloud.stream.servicebus.bindings.consume-in-0.consumer.entity-name=queue_name
spring.cloud.stream.servicebus.bindings.consume-in-0.consumer.entity-type=queue
spring.cloud.stream.servicebus.bindings.consume-in-0.consumer.auto-complete=false
```
But still getting 

```console
com.azure.core.amqp.exception.AmqpException: org.apache.qpid.proton.engine.TransportException: connection aborted, errorContext[NAMESPACE: sb-namespace. ERROR CONTEXT: N/A]
	at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85) ~[azure-core-amqp-2.5.0.jar:2.5.0]
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.notifyErrorContext(ConnectionHandler.java:332) [azure-core-amqp-2.5.0.jar:2.5.0]
	at com.azure.core.amqp.implementation.handler.ConnectionHandler.onTransportError(ConnectionHandler.java:235) ~[azure-core-amqp-2.5.0.jar:2.5.0]
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191) ~[proton-j-0.33.8.jar:na]
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.33.8.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) ~[proton-j-0.33.8.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) ~[proton-j-0.33.8.jar:na]
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91) ~[azure-core-amqp-2.5.0.jar:2.5.0]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.4.17.jar:3.4.17]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.4.17.jar:3.4.17]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

And I debugged through the service bus builders/factories and they are indeed using simple amqp and not websocket one. 

I also tried this without luck:

```properties
spring.cloud.azure.client.amqp.transport-type=amqp_web_sockets
```

***Why is this not a Bug or a feature Request?***
Not sure if I am missing some property config or it is indeed a bug

**Setup (please complete the following information if applicable):**
 - OS: Macos
 - IDE: Intellij
 - Library/Libraries: Java 17 with spring boot 2.6.7 and spring cloud azure 4.2.0

```xml
        <dependency>
            <groupId>com.azure.spring</groupId>
            <artifactId>spring-cloud-azure-stream-binder-servicebus</artifactId>
            <version>${azure.version}</version>
        </dependency>
```

and 

```xml
            <dependency>
                <groupId>com.azure.spring</groupId>
                <artifactId>spring-cloud-azure-dependencies</artifactId>
                <version>${azure.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and check off the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by yiliuTo** [comment]
@numirov thanks for reaching us.
The property `spring.cloud.azure.servicebus.consumer.client.transport-type` is only used for library of `com.azure.spring:spring-cloud-azure-starter-servicebus` which provides autoconfiguration for Service Bus Java SDK clients. 

To set the transport-type for Spring Cloud Stream Service Bus Binders, you need to configure for the binding level, with properties like
```properties
spring.cloud.stream.servicebus.bindings.<binding-name>.consumer.client.transport-type=amqp_web_sockets
```
Besides, as you mentioned there is also a common level property `spring.cloud.azure.client.amqp.transport-type`, it should take effects. However, due to this common property has lower priority than the above binding property, and the default value for all levels of transport-type property is `amqp`, thus to configure `spring.cloud.azure.client.amqp.transport-type` cannot take effects.

Therefore, you can configure the transport-type with the property of 
```properties
spring.cloud.stream.servicebus.bindings.consume-in-0.consumer.client.transport-type=amqp_web_sockets
```

**Comment by numirov** [comment]
thanks @yiliuTo , it is working fine with above config

**Comment by rmolcr** [comment]
thanks @yiliuTo, working here also.

I've been looking into the [documentation for servicebus binder](https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#consumer-properties), but I could't find any reference to this property.
Is it documented anywhere?

Thanks in advance

**Comment by yiliuTo** [comment]
Hi @rmolcr , the property of `spring.cloud.stream.servicebus.bindings.<binding-name>.consumer.client.transport-type` is not documented  in the binder's reference doc directly since that property is not defined in the [ServiceBusConsumerProperties](https://github.com/Azure/azure-sdk-for-java/blob/b620b3ff2e28dde4d64458a199361efbeb50daf8/sdk/spring/spring-cloud-azure-stream-binder-servicebus-core/src/main/java/com/azure/spring/cloud/stream/binder/servicebus/core/properties/ServiceBusConsumerProperties.java#L11) class but in its [super class](https://github.com/Azure/azure-sdk-for-java/blob/250c73d024880a82076807ec0ae7e398856605fc/sdk/spring/spring-cloud-azure-core/src/main/java/com/azure/spring/cloud/core/properties/client/AmqpClientProperties.java#L12).  So we introduce it [here](https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#advanced-consumer-configuration-2), which means all the [global properties](https://microsoft.github.io/spring-cloud-azure/current/reference/html/appendix.html#global_proeprties) can be configured in the binding level.

Besides, one improvement for the service bus binder is that, to configure the transport-type for service bus binder, we don't require the configuration in the binding level now. Which means you can choose any of the three properties with the ascending priority.

```properties
spring.cloud.azure.client.amqp.transport-type
spring.cloud.azure.servicebus.client.transport-type
spring.cloud.stream.servicebus.bindings.<binding-name>.consumer.client.transport-type
```
You can try it with our latest version.

**Comment by yiliuTo** [comment]
Thanks @rmolcr , would you like to share which version you are using?

**Comment by rmolcr** [comment]
> Thanks @rmolcr , would you like to share which version you are using?

Again, thanks @yiliuTo for guiding me to that point. I was messing with my dependencies and was not resolving to the required version. Now I managed to make it work!

Regards

**Comment by saragluna** [comment]
@rmolcr could you help point out which version works for you?

**Comment by rmolcr** [comment]
> @rmolcr could you help point out which version works for you?

i ended up using version 4.5.0, and kept applying the configuration at the binding level because we found more problems while trying upgrade other dependencies of our application

**Comment by yiliuTo** [comment]
Hi @rmolcr,
for the compatibility with Spring Boot and Spring Cloud of this Service Bus binder, you can refer to [our changelog](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/CHANGELOG.md). And assuming you are using Spring Boot 2.x, then the latest version is [4.5.0](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/CHANGELOG.md#450-2022-12-06), I forgot to mention the concrete version number in my earlier comment which may mislead you to use our 6.x or 5.x.

Besides, another way may help to deal with the version compatibility is to leverage our bom [com.azure.spring:spring-cloud-azure-dependencies](https://mvnrepository.com/artifact/com.azure.spring/spring-cloud-azure-dependencies) for dependency management.

Hope these could help you, and let me know if you need additional assistance.
