### ISSUE TITLE
[FEATURE REQ]Long running Receiver and a sample/documentation with details about its use.

### ISSUE THREAD

**Issue by madossan01** [Azure/azure-sdk-for-java#29766]
**Is your feature request related to a problem? Please describe.**
We implemented a ServiceBusSessionReceiverClient to continuously listen to messages arriving from a Service Bus topic and for that we used the acceptNextSession() method. 
However, this method only listens for a single session, and it stops looking for other sessions. If we do not close the client, it stays on a loop renewing its lock, if we close the client then it stops looking for sessions overall. 
So, we added the acceptNextSession() to a while(true) and we are able to continuously listen for new messages with sessions, even though this is not an elegant solution.

**Describe the solution you'd like**
We kindly request a long running Receiver and a sample/documentation with details about the use. 

**Describe alternatives you've considered**
Please see the description above.

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Description Added
- [x ] Expected solution specified

**Comment by joshfree** [comment]
Hi @madossan01 thank you for posting this GitHub issue. @ki1729 could you please take a look?

**Comment by ki1729** [comment]
@madossan01 The way receiver clients are designed are to be associated with a particular session. The recommended way to receive messages from multiple sessions is to create as many clients as the number of sessions and receive messages on all of them. Session-enabled messaging entity giving ordering gaurantees which is why we have a single client associated with each session.
If on the other hand you want a long running receiver, which is not session enabled, can I recommend taking a look at our ServiceBusProcessorSample located here - https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ServiceBusProcessorPeekLockReceiveSample.java.
