### ISSUE TITLE
[BUG] AadPropertiesConfiguration missing client-secret value if it is provided from ENV or CLI

### ISSUE THREAD

**Issue by vgarmash** [Azure/azure-sdk-for-java#29910]
**Describe the bug**
All examples for Spring boot and Azure SDK at https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure or https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.3.0/aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/aad-resource-server-obo use YAML config files and the client secret is written in the file. Some files are using explicit reference to the environment variable like following: `client-secret: ${AZURE_CLIENT_SECRET}`.

Although Spring Boot has standard way to override properties: via CLI or Environment. So according the [documentation ](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.typesafe-configuration-properties.relaxed-binding) it should be possible to override any configuration property by setting the external CLI parameter or the ENV variable. So it should be possible to set the CLI as following: `-Dspring.cloud.azure.active-directory.credential.client-secret=<my secret>` or ENV variable `SPRING_CLOUD_AZURE_ACTIVE_DIRECTORY_CREDENTIAL_CLIENT_SECRET=<my secret>` and the value should be propagated into the configuration.

Although it is not the case if the YAML file simply don't have the `client-secret` and the value is provided vial CLI or ENV. It is not delivered to the AadPropertiesConfiguration 

***Exception or Stack Trace***
AadPropertiesConfiguration #credential-clientSecret is null.

**To Reproduce**
Steps to reproduce the behavior: take any existing Azure AAD example, remove the client-secret and set `SPRING_CLOUD_AZURE_ACTIVE_DIRECTORY_CREDENTIAL_CLIENT_SECRET=<my secret>` instead.

**Expected behavior**
The client-secret should not be null if it not provided in the YAML but the  `-Dspring.cloud.azure.active-directory.credential.client-secret=<my secret>` or ENV variable `SPRING_CLOUD_AZURE_ACTIVE_DIRECTORY_CREDENTIAL_CLIENT_SECRET=<my secret>`  is set.

**Setup (please complete the following information):**
 - OS: Windows
 - Library/Libraries: azure-core=1.29.1
 - Java version: 11 
 - App Server/Environment: Spring Boot
 - Frameworks: Spring Boot

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by backwind1233** [comment]
@vgarmash Thanks for reaching out, @chenrujun will follow up this issue.

**Comment by chenrujun** [comment]
Hi, @vgarmash 

I tested it and found CLI(JVM parameter) works well. Here are the steps:

1. Open [aad-resource-server-obo](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.3.0/aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/aad-resource-server-obo) , delete the `client-secret` in `application.yml`
![image](https://user-images.githubusercontent.com/13167207/178422473-1f850ee3-9244-4cee-abe0-bd2e7995d635.png)

2. Set breakpoint in [AadPropertiesConfiguration.java#L55](https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure_4.3.0/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/configuration/AadPropertiesConfiguration.java#L55)
![image](https://user-images.githubusercontent.com/13167207/178422696-5e7c55d7-1369-424b-82b8-16b78cfe0b9f.png)


3. Set breakpoint in [AadResourceServerConfiguration.java#L53](https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure_4.3.0/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/configuration/AadResourceServerConfiguration.java#L53)
![image](https://user-images.githubusercontent.com/13167207/178422787-d13086fc-368e-4e84-ab53-4e3c056a5217.png)


4. Add JVM parameter `-Dspring.cloud.azure.active-directory.credential.client-secret=test20220712`. for [aad-resource-server-obo](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.3.0/aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/aad-resource-server-obo) .
![image](https://user-images.githubusercontent.com/13167207/178422988-270baf16-74fb-42f3-ae2a-b68171cfec19.png)
![image](https://user-images.githubusercontent.com/13167207/178422251-1debd55a-7cbf-4ab7-8ccd-52e7bd2812cc.png)

5. Debug [aad-resource-server-obo](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.3.0/aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/aad-resource-server-obo). Check the values in above 2 breakpoints.

5.1. `client-secret` is null in [AadPropertiesConfiguration.java#L55](https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure_4.3.0/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/configuration/AadPropertiesConfiguration.java#L55)

![image](https://user-images.githubusercontent.com/13167207/178423335-7d1ef7d3-0665-404a-8bda-74b4d279c324.png)

5.2. `client-secret` is `test20220712` in [AadResourceServerConfiguration.java#L53](https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure_4.3.0/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/configuration/AadResourceServerConfiguration.java#L53)
![image](https://user-images.githubusercontent.com/13167207/178423487-2fc53cf5-8012-4977-bb8b-15042d80b70b.png)


I guess you think CLI(JVM parameter) doesn't take effect because you check the value in [AadPropertiesConfiguration.java#L55](https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure_4.3.0/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/configuration/AadPropertiesConfiguration.java#L55). Actually, the binding process is after [AadPropertiesConfiguration.java#L55](https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure_4.3.0/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/configuration/AadPropertiesConfiguration.java#L55). So, the set value `test20220712` cannot been seen in [AadPropertiesConfiguration.java#L55](https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure_4.3.0/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/configuration/AadPropertiesConfiguration.java#L55). but it can be seen in [AadResourceServerConfiguration.java#L53](https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure_4.3.0/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/configuration/AadResourceServerConfiguration.java#L53).

**Comment by vgarmash** [comment]
I my case I was configuring MS Graph authorized client in service principal mode (client credential flow). I set the configuration the following way:

![image](https://user-images.githubusercontent.com/1226001/178441036-b309608e-7df4-431b-8ae5-e9ec8fa98c66.png)

The expectation is to to get the authorized graph client into the factory method:
```
public GraphServiceClient getGraphServiceClient(OAuth2AuthorizedClient graph) {

            ILogger logger = new DefaultLogger();
            logger.setLoggingLevel(LoggerLevel.DEBUG);

            return GraphServiceClient.builder()
                    .authenticationProvider(new GraphAuthenticationProvider(graph))
                    .logger(logger)
                    .buildClient();
        }
```
Code samples can be found here: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure?tabs=maven

Usually the annotation is used to get the authorized client:
```
public class Demo {
    @GetMapping("/graph")
    @ResponseBody
    public String graph(
    @RegisteredOAuth2AuthorizedClient("graph") OAuth2AuthorizedClient graphClient) {
        // toJsonString() is just a demo.
        // oAuth2AuthorizedClient contains access_token. We can use this access_token to access resource server.
        return toJsonString(graphClient);
    }
}
```

Manual variant of this code described here: https://docs.microsoft.com/en-us/graph/tutorials/java?tabs=aad&tutorial-step=8.


The problem is that the `@RegisteredOAuth2AuthorizedClient("graph")` returns the client with empty client-secret and as the result the call to MS Graph API fails with error 401: invalid token.

With debugger I traced it to the place where the client is being created: `com.azure.spring.cloud.core.implementation.credential.resolver.AzureTokenCredentialResolver#resolveTokenCredential`, line 53: https://github.com/Azure/azure-sdk-for-java/blob/f0f26ddf88219c78548137fa0c4e3f89b7fe3097/sdk/spring/spring-cloud-azure-core/src/main/java/com/azure/spring/cloud/core/implementation/credential/resolver/AzureTokenCredentialResolver.java#L53

the `StringUtils.hasText(properties.getClientSecret())` returns false. I started following the code and found the place https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure_4.3.0/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/configuration/AadPropertiesConfiguration.java#L55 where the properties should be set.

Seems like to support client credential flow the properties initialization should be implemented in Spring Boot style to support external properties from the very beginning.

**Comment by chenrujun** [comment]
@vgarmash 

```
The expectation is to to get the authorized graph client into the factory method:
public GraphServiceClient getGraphServiceClient(OAuth2AuthorizedClient graph) {

            ILogger logger = new DefaultLogger();
            logger.setLoggingLevel(LoggerLevel.DEBUG);

            return GraphServiceClient.builder()
                    .authenticationProvider(new GraphAuthenticationProvider(graph))
                    .logger(logger)
                    .buildClient();
        }

Code samples can be found here: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure?tabs=maven
```

1. I think you pasted the wrong link here. The right link should be https://docs.microsoft.com/en-us/graph/tutorials/java?tabs=aad&tutorial-step=8.
2. I'm not sure whether `GraphAuthenticationProvider(graph)` is a right way to use `GraphServiceClient`. Because `OAuth2AuthorizedClient ` is belong to spring-security framework, but `GraphServiceClient` not belong to spring-security framework. 


```
Usually the annotation is used to get the authorized client:

public class Demo {
    @GetMapping("/graph")
    @ResponseBody
    public String graph(
    @RegisteredOAuth2AuthorizedClient("graph") OAuth2AuthorizedClient graphClient) {
        // toJsonString() is just a demo.
        // oAuth2AuthorizedClient contains access_token. We can use this access_token to access resource server.
        return toJsonString(graphClient);
    }
}
Manual variant of this code described here: https://docs.microsoft.com/en-us/graph/tutorials/java?tabs=aad&tutorial-step=8.
```
1. I think you pasted the wrong link, the right one should be https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure?tabs=maven.

```
As you can see it is critical to get the client secret value set, otherwise the code will not work properly and the API client will not be initialized.
The problem is that the @RegisteredOAuth2AuthorizedClient("graph") returns the client with empty client-secret and as the result the call to MS Graph API fails with error 401: invalid token.
```

Could you please add a breakpoint in this line? And check the value in `OAuth2AuthorizedClient graphClient`. 

1. In [OAuth2AuthorizedClient](https://github.com/spring-projects/spring-security/blob/5.7.2/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/OAuth2AuthorizedClient.java#L52), there is an [OAuth2AccessToken](https://github.com/spring-projects/spring-security/blob/5.7.2/oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/OAuth2AccessToken.java).
2. [OAuth2AccessToken](https://github.com/spring-projects/spring-security/blob/5.7.2/oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/OAuth2AccessToken.java) extends [AbstractOAuth2Token](https://github.com/spring-projects/spring-security/blob/c40f65f5a20ec9a34ebc2320eb9520dabbc51622/oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/AbstractOAuth2Token.java#L35). And [AbstractOAuth2Token](https://github.com/spring-projects/spring-security/blob/c40f65f5a20ec9a34ebc2320eb9520dabbc51622/oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/AbstractOAuth2Token.java#L35) has a property `tokenValue`. The `tokenValue` is the accessToken that can be used to access graph.
3. If the accessToken` is not null, you can use https://jwt.ms/ to analyze the accessToken. For more information about Azure AD access token, please refer to https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens

```
With debugger I traced it to the place where the client is being created: com.azure.spring.cloud.core.implementation.credential.resolver.AzureTokenCredentialResolver#resolveTokenCredential, line 53:
```

Actually, the `OAuth2AuthorizedClient graph` is not created in `AzureTokenCredentialResolver`. `OAuth2AuthorizedClient graph` is constructed by spring-security framework.


```
 I started following the code and found the place https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure_4.3.0/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/configuration/AadPropertiesConfiguration.java#L55 where the properties should be set.
```

As I explained in my last comment. If you set client-secret by `-Dspring.cloud.azure.active-directory.credential.client-secret=test20220712`, in `AadPropertiesConfiguration.java#L55`, the client-secret is null, the property binding will happed after this method, which means when use the properties, the `AadAuthenticationProperties#getClientSecret` will not return null.

```
Maybe it would work properly if the AadAuthenticationProperties would have the @ConfigurationProperties annotation on it instead of being InitializingBean?
```
[AadPropertiesConfiguration](https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure_4.3.0/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/configuration/AadPropertiesConfiguration.java#L41) is already a `@ConfigurationProperties`/
![image](https://user-images.githubusercontent.com/13167207/178666782-9300c21f-07a2-435b-8299-e01aebb4addb.png)


### Next steps I asked you to do

1. Please debug your code and check the value in `OAuth2AuthorizedClient graphClient` (graphClient.accessToken.tokenValue). If the value is not null, it means your application can get access token successfully. You can use the access token to access graph. `GraphServiceClient` is not the only way to access graph.
2. If `graphClient.accessToken.tokenValue` is null, please provide the sample that can reproduce the problem. I'll investigate the sample and give you feedback.

**Comment by vgarmash** [comment]
I see that you admitting that the initialization for those properties is delayed to the later time and in most cases it is OK. Although in my case I am not using JWT but I am trying to use "client_credential" flow, which is describes here [AadPropertiesConfiguration](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure?tabs=maven#client-credential-flow) as you correctly suggested. I offered another link just to show you in the nutshell what would be happening inside the code: it is strongly dependent on presence of the client-secret and won't work without it. The tutorial you are referring to is not showing full code for the "client_credential" flow and it even fail with that "scope" value. In testing the library would reject any scopes except "https://graph.microsoft.com/.default". 

It will take some time to get you working sample. If you can wait for a month or more, I provide it. The code sample will do the following: 
1. Start the application as a Spring Boot service without UI.
2. Load list of users form the Active Directory every 5 minutes on schedule and print them to the log.

**Comment by chenrujun** [comment]
> I see that you admitting that the initialization for those properties is delayed to the later time

When the bean (AadAuthenticationProperties) is used, it's field should be ready to use. It should not be null if it configured.

> I offered another link just to show you in the nutshell what would be happening inside the code: it is strongly dependent on presence of the client-secret and won't work without it. 

Do you mean this?
![image](https://user-images.githubusercontent.com/13167207/178865938-86a42861-8312-470b-9cc3-ae8740f618fa.png)

It's not related to `client_credential` flow. 

You can add a breakpoint in [ClientCredentialsOAuth2AuthorizedClientProvider](https://github.com/spring-projects/spring-security/blob/5.7.2/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/ClientCredentialsOAuth2AuthorizedClientProvider.java#L67) to check whether the client-secret is set there.
![image](https://user-images.githubusercontent.com/13167207/178866816-09585304-8331-4df3-aeca-d9edad6b97c5.png)

Could you please debug your application and share the screenshot here?

> In testing the library would reject any scopes except "https://graph.microsoft.com/.default".

For client-credential flow, it can only be `xxx/.default`. Refs: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow#first-case-access-token-request-with-a-shared-secret

![image](https://user-images.githubusercontent.com/13167207/178867096-f661040e-3acd-4dc8-b2ab-1d3d6a3909d8.png)

> If you can wait for a month or more, I provide it. 

Not necessary to spent so much time to create a sample. Let's continue discuss, Let's try to solve the problem without a sample.

**Comment by chenrujun** [comment]
Hi, @vgarmash 
If you are using ENV variable, you should use `SPRING_CLOUD_AZURE_ACTIVEDIRECTORY_CREDENTIAL_CLIENTSECRET` instead of `SPRING_CLOUD_AZURE_ACTIVE_DIRECTORY_CREDENTIAL_CLIENT_SECRET`.


Refs: https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.typesafe-configuration-properties.relaxed-binding
![image](https://user-images.githubusercontent.com/13167207/178934443-8b17d33b-4bb5-4cf1-8cb8-e0ca8f8e2c5c.png)

**Comment by vgarmash** [comment]
Hi, @chenrujun . Thank you for your patience. I set a breakpoint in [ClientCredentialsOAuth2AuthorizedClientProvider](https://github.com/spring-projects/spring-security/blob/5.7.2/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/ClientCredentialsOAuth2AuthorizedClientProvider.java#L67)

and today both tests - with CLI and ENV variable worked properly! Even with my env variable name. I am not sure what changed but now it works as it should and the client-secret is propagated to the Graph client and my call are successful.

I am closing the issue.
