### ISSUE TITLE
Event Hubs Client is not processing messages which were sent during a period when the client was not running.

### ISSUE THREAD

**Issue by dusmar** [Azure/azure-sdk-for-java#30109]
**Describe the bug**
Having simple event hub client in java (only 1 partition)
If I run client first and then send messages, it works as expected. However client is not processing messages which were sent to Event Hub during a period when client was not running.

**To Reproduce**
If I stop client, then send messages to event hub, then I start client, messages previously sent are not processed at all. Messages sent after are processed. 

If I stop client, then I delete checkpoint data in Azure Blob Storage, then I start client, existing messages in Event Hub are not processed. Messages sent after are processed. 

***Code Snippet***
```
Client

public static void main(String[] args) throws Exception {
        // Create a blob container client that you use later to build an event processor client to receive and process events
        BlobContainerAsyncClient blobContainerAsyncClient = new BlobContainerClientBuilder()
                .connectionString(storageConnectionString)
                .containerName(storageContainerName)
                .buildAsyncClient();

        // Create a builder object that you will use later to build an event processor client to receive and process events and errors.
        EventProcessorClientBuilder eventProcessorClientBuilder = new EventProcessorClientBuilder()
                .connectionString(connectionString, eventHubName)
                .consumerGroup("$default")
                .processEvent(PARTITION_PROCESSOR)
                .processError(ERROR_HANDLER)//.checkpointStore(new SampleCheckpointStore());
                .checkpointStore(new BlobCheckpointStore(blobContainerAsyncClient));

        // Use the builder object to create an event processor client
        EventProcessorClient eventProcessorClient = eventProcessorClientBuilder.buildEventProcessorClient();

        System.out.println("Starting event processor");
        eventProcessorClient.start();

        System.out.println("Press enter to stop.");
        System.in.read();

        System.out.println("Stopping event processor");
        eventProcessorClient.stop();
        System.out.println("Event processor stopped.");

        System.out.println("Exiting process");
}
```
**Expected behavior**
All messages are processed by client 

**Setup (please complete the following information):**
 - OS: Windows
 - IDE:  IntelliJ
 - Library/Libraries:   azure-messaging-eventhubs 5.12.2
                                 azure-messaging-eventhubs-checkpointstore-blob 1.13.0
 - Java version: [e.g. 11 Open JDK Redhat]

**Comment by joshfree** [comment]
@conniey could you follow up on @dusmar's GitHub issue?

**Comment by conniey** [comment]
To make sure I understand,

**Scenario 1**
This scenario works:
1. Run Client.
2. Run Producer and publish messages (A, B, C).
3. Client receives messages (A, B, C).

**Scenario 2**
This does not:
1. Stop Client.
2. Run producer and publish messages (D, E, F).
3. Start Client.
4. Client does not receive (D, E, F)

Questions:
* For **Scenario 2** where does the Client begin receiving messages? Does it receive only future messages?
* What does your processEvent(PARTITION_PROCESSOR) callback look like?

> If I stop client, then I delete checkpoint data in Azure Blob Storage, then I start client, existing messages in Event Hub are not processed. Messages sent after are processed.

This is expected behaviour. If you look at the docs for [EventProcessorClientBuilder.initialPartitionEventPosition](https://docs.microsoft.com/en-us/java/api/com.azure.messaging.eventhubs.eventprocessorclientbuilder.initialpartitioneventposition?view=azure-java-stable), we mention that "If there is no checkpoint in [CheckpointStore](https://docs.microsoft.com/en-us/java/api/com.azure.messaging.eventhubs.checkpointstore?view=azure-java-stable) and there is no entry in this map, the processing of the partition will start from latest() position."  You can override this behaviour by passing in a map of positions via this method.
