### ISSUE TITLE
[BUG] Issues with springCloudAzureCredentialTaskExecutor in Spring Boot after upgrading SDK from v4.0.0 to v4.3.0

### ISSUE THREAD

**Issue by dbelyaev** [Azure/azure-sdk-for-java#30134]
Hei,

Mine REST-API project which is using **Spring Boot** (`v2.7.1`) and **spring-cloud-azure-starter-active-directory** (`v4.0.0`) started failing with a message after I bumped from version `v4.0.0` to `v4.3.0`:

> No qualifying bean of type 'org.spring framework.core.task.TaskExecutor' available: expected single matching bean but found 2: applicationTaskExecutor,springCloudAzureCredentialTaskExecutor

Looks like a bean from Cloud Azure SDK (`springCloudAzureCredentialTaskExecutor`) and autoconfigured bean from Spring Boot framework (`applicationTaskExecutor`) are conflicting with each other due to they implementing the same type.

Any suggestions on how to fix this problem?

NOTE: 
I am not instantiating `applicationTaskExecutor` bean manually, it is done via autoconfiguration by the Spring Boot framework itself (https://docs.spring.io/spring-boot/docs/2.7.1/reference/htmlsingle/#features.task-execution-and-scheduling).

**Comment by dbelyaev** [comment]
As a workaround I have added my own configuration to instantiate the bean of `TaskExecutor` type "manually" (disabling auto-configuration of this bean by Spring Boot routines) and adding `@Primary` annotations (link: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/Primary.html) so it will be chosen by default from those two beans existing in the application context (`taskExecutor` and `springCloudAzureCredentialTaskExecutor`).

Example of this configuration:

```
package com.my.api.configuration;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Primary;
import org.springframework.core.task.TaskExecutor;
import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor;

@Configuration
public class TaskExecutorConfig {

    @Bean
    @Primary
    public TaskExecutor taskExecutor() {
        return new ThreadPoolTaskExecutor();
    }

}
```

**Comment by moarychan** [comment]
Hi @dbelyaev ,  thanks for reaching out!

The Spring Boot will take the named bean `applicationTaskExecutor`, the bean `springCloudAzureCredentialTaskExecutor` is added and used for Spring Cloud Azure credential thread since the Spring Cloud Azure 4.3.0, We let bean `springCloudAzureCredentialTaskExecutor` be created later than `applicationTaskExecutor` to avoid this Spring Boot finding multiple `TaskExecutor` beans. 

I can't reproduce your scenario. I used Spring Boot 2.6.10 + spring-cloud-azure-starter-active-directory 4.0.0, it works fine; 
then upgrade to Spring Boot 2.7.1 and spring-cloud-azure-starter-active-directory 4.3.0, it also works fine. Could you please provide your pom and yml files? better to provide your minimal project for reproducing this issue.
