### ISSUE TITLE
[QUERY] How to fix 403 error when Azure AD redirects after a successful authentication to my Spring Boot App?

### ISSUE THREAD

**Issue by bergmp** [Azure/azure-sdk-for-java#30378]
**Query/Question**
How to fix 403 error when Azure AD redirects after a successful authentication to my Spring Boot App?
I had to disable CSRF on Spring Security to fix this. Please, see the code below.
However, my app is going to production, and I would like to deploy it with CSRF enabled.

```
@Configuration
public class SecurityConfiguration extends AadWebSecurityConfigurerAdapter {


    @Override
    protected void configure(HttpSecurity http) throws Exception {
        super.configure(http);
        http.csrf().disable().authorizeRequests().antMatchers("/**").permitAll();

```

***Why is this not a Bug or a feature Request?***
It is a question in order to explain how to fix some scenario.

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - IDE: IntelliJ
 - Library/Libraries: com.azure.spring:spring-cloud-azure-starter-active-directory:4.3.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by joshfree** [comment]
Hi @bergmp thanks for reaching out to us via this GitHub issue.  @yiliuTo could you help route @bergmp's question?

**Comment by yiliuTo** [comment]
@chenrujun could you help to take a look?

**Comment by chenrujun** [comment]
Hi, @bergmp 

Thanks for reaching out.
I can't reproduce the problem.
Could you please create a new GitHub repository that contains a minimal project which can reproduce the problem?

**Comment by bergmp** [comment]
I will try to give you more details about my question.

I using OpendID to authenticate a user at AAD.
The first request is the one generated by Azure AD SDK to get the id_token
The second request is the callback called by AAD
![Figura1](https://user-images.githubusercontent.com/68135117/186516425-813ec80d-029c-462f-b245-0b7a7d110863.png)

It is a POST. When I disable CSRF on my app that uses Spring Security, it works and doesn't give 403, but when CSRF is enabled I receive 403 as shown below
![Figura2](https://user-images.githubusercontent.com/68135117/186516423-5d52915b-ba5f-45cc-a5f7-70bb4b92c93e.png)

**Comment by chenrujun** [comment]
Hi, @bergmp 

Thanks for the detailed description.

Here is the document about Azure AD OAuth 2.0 authorization code flow: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow

> The first request is the one generated by Azure AD SDK to get the id_token

Actually, the request is sent by browser (Edge or Chrome). Here are the detailed steps:

1. Chrome want to access your app's end point, like `http://localhost:3001/foo`
2. Your app is protected by Spring Security framework (by extending `AadWebSecurityConfigurerAdapter` ). The access to `http://localhost:3001/foo` will be redirected to Azure AD authorize endpoint: `https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize?`.
3. Then the Azure AD display the login page.
4. After login successfully, the Azure AD will redirect to `http://localhost:3001/auth2/authorization/azure?code=...`. Until now, everything works well.
5. Here is the problem. I don't know where the request to `http://localhost:3001/SvlCentralizator?provider=azuread` comes from. Do you mean the endpoint you request in step is `http://localhost:3001/SvlCentralizator?provider=azuread` instead of `http://localhost:3001/foo`?

Could you please create a project to reproduce this problem? I think I can give you suggestion if I can reproduce the problem in my localhost.

**Comment by bergmp** [comment]
Hi @chenrujun,

Sorry, now I am sending the complete url for step 2:
`https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize?response_type=id_token&client_id={clientid}&scope=openid%20profile%20offline_access&state=TaueFvRE2hHVVTHlnyasdfg%3D&redirect_uri=http://localhost:3001/sso/SvlCentralizador?provedor%3Dazuread&nonce=D8k0O02YSUSfasdfasfsadfasfa&response_mode=form_post`

5. The request comes from Microsoft in the redirect_uri

I will try to create a project to reproduce the problem, but it is a corporate app with many layers that makes things a bit difficult.

**Comment by chenrujun** [comment]
@bergmp 

> I am using response_mode=form_post.

Why did you do like this? and how did you achieve that? Seems the 403 is caused by `response_mode=form_post`.

> redirect_uri=http://localhost:3001/sso/SvlCentralizador

In normal case, the redirect endpoint is `http://localhost:8080/login/oauth2/code/`, and `http://localhost:8080/login/oauth2/code/` is handled by spring-security framework. Seems `http://localhost:3001/sso/SvlCentralizador` is a self-defined endpoint. Is it implemented by yourself?


> However, I also don't get id_token

If you want to get id_ token, you can get id_token after user login successfully. 

In auth code flow, there are 2 steps:
1. Request an authorization code (together with id_token in hybrid flow)
2. Redeem a code for an access token

Refs: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow

Seems you want to get id_token after step 1. Actually, to finish the whole flow, I suggest you get the id_token after step 2.


> Shouldn't AAD call a POST to my redirect_uri setting the XSRF-TOKEN in the request header?

Now I'm not sure about this. First let's confirm one thing: Is `response_mode=form_post` necessary in your application?

**Comment by bergmp** [comment]
> @bergmp
> 
> > I am using response_mode=form_post.
> 
> Why did you do like this? and how did you achieve that? Seems the 403 is caused by `response_mode=form_post`.
> 
response_mode=query -> It doesn't work with OIDC.
response_mode=fragment -> It doesn't pass the id_token to the server. It comes in the URL with #id_token=....

Please, see the doc from Microsoft:
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc
"Specifies the method that should be used to send the resulting authorization code back to your app. Can be form_post or fragment. For web applications, we recommend using response_mode=form_post, to ensure the most secure transfer of tokens to your application."

> > redirect_uri=http://localhost:3001/sso/SvlCentralizador
> 
> In normal case, the redirect endpoint is `http://localhost:8080/login/oauth2/code/`, and `http://localhost:8080/login/oauth2/code/` is handled by spring-security framework. Seems `http://localhost:3001/sso/SvlCentralizador` is a self-defined endpoint. Is it implemented by yourself?
> 

Yes, that's right and It will get the id_token.

> > However, I also don't get id_token
> 
> If you want to get id_ token, you can get id_token after user login successfully.
> 
> In auth code flow, there are 2 steps:
> 
> 1. Request an authorization code (together with id_token in hybrid flow)
> 2. Redeem a code for an access token
> 
> Refs: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow
> 
> Seems you want to get id_token after step 1. Actually, to finish the whole flow, I suggest you get the id_token after step 2.
> 

I see, but id_token already comes from the first step (after a user login succesfully)

> > Shouldn't AAD call a POST to my redirect_uri setting the XSRF-TOKEN in the request header?
> 
> Now I'm not sure about this. First let's confirm one thing: Is `response_mode=form_post` necessary in your application?

Yes, It seems to be the only way to get id_token in a web application
When I use response_mode=fragment, AAD redirects like this: http://localhost:3001/sso/SvlCentralizador?provedor=azuread#id_token=1232323Gd6TlRFelp&state=loremsfsaf&session_state=234234234
However, all the information after # is not sent to server. So, in SvlCentralizador I can't get the id_token, state and session_state.

**Comment by chenrujun** [comment]
@bergmp 

> response_mode=query -> It doesn't work with OIDC.
> response_mode=fragment -> It doesn't pass the id_token to the server. It comes in the URL with #id_token=....
> 
> Please, see the doc from Microsoft:
> https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc
> "Specifies the method that should be used to send the resulting authorization code back to your app. Can be form_post or fragment. For web applications, we recommend using response_mode=form_post, to ensure the most secure transfer of tokens to > your application."

You are right. `spring-cloud-azure-starter-active-directory` (based on `spring-security` framework) implements `oidc` together with `auth code flow`, which is called `hybrid flow`. Refs: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-id-token-as-well-or-hybrid-flow `response_mode` can't be `query` if `response_type` contains `id_token`.


> Yes, that's right and It will get the id_token.

Why did you want to handle the redirect url by yourself? In normal case, this request will be handled by `OAuth2LoginAuthenticationFilter`. `OAuth2LoginAuthenticationFilter` will do necessary works.
![image](https://user-images.githubusercontent.com/13167207/187113024-75b43d95-a4e1-41b5-9493-94d46bcf0b88.png)


> I see, but id_token already comes from the first step (after a user login succesfully)

Yes, but the request should be handled by `OAuth2LoginAuthenticationFilter` in `spring-security` framework, not handled by us(developer who is using `spring-security` framework).

> However, all the information after # is not sent to server. So, in SvlCentralizador I can't get the id_token, state and session_state.

Is there any special reason that you need to handle this request by yourself? If there is no special reason, I suggest you accept the default behaver: Use `OAuth2LoginAuthenticationFilter` to handle the request. If you just want to get id_token, you can get id_token from [DefaultOidcUser](https://github.com/spring-projects/spring-security/blob/5.7.3/oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/oidc/user/DefaultOidcUser.java#L45)

**Comment by bergmp** [comment]
@chenrujun 

Could you please guide me how to use DefaultOidcUser?
My scenario is just one http request (one step) to login and then I need to get the id_token

**Comment by chenrujun** [comment]
Hi, @bergmp , here is the sample:

https://github.com/chenrujun/azure-sdk-for-java-issue-30378/blob/de174a7ff646e4609743795606f7695a19b0438e/src/main/java/chenrujun/azure/sdk/issue/DemoController.java#L15-L17
