### ISSUE TITLE
Facing issue while launching Spring boot App with Azure Key vault Configuration

### ISSUE THREAD

**Issue by Rakeshghatage** [Azure/azure-sdk-for-java#30628]
**Query/Question**
Facing issue while launching Spring boot app from STS getting below exception.
1.Verified key vault properties they look fine.
2.Pom is updated and all certificate have been updated using key store command.

```
02:16:17.076 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Failed to configure KeyVault property source
	at com.azure.spring.keyvault.KeyVaultEnvironmentPostProcessorHelper.addKeyVaultPropertySource(KeyVaultEnvironmentPostProcessorHelper.java:113) ~[azure-spring-boot-3.11.0.jar:3.11.0]
	at com.azure.spring.keyvault.KeyVaultEnvironmentPostProcessor.postProcessEnvironment(KeyVaultEnvironmentPostProcessor.java:51) ~[azure-spring-boot-3.11.0.jar:3.11.0]
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:203) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:191) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
```

attached full log trace .
any help would be appreciable. 
[SpringbootStarter_Exception.txt](https://github.com/Azure/azure-sdk-for-java/files/9415834/SpringbootStarter_Exception.txt)

**Comment by chenrujun** [comment]
Hi, @Rakeshghatage 

Thanks for reaching out. I can't reproduce the problem you described in the issue description.

`azure-spring-boot-starter-keyvault-secrets:3.11` is out of life. Refs: [Spring-Versions-Mapping](https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping#spring-cloud-azure-support-status). Could you please use `spring-cloud-azure-starter-keyvault-secret:4.3.0` instead? Here are some useful links:
  1. [4.3.0 Reference doc](https://microsoft.github.io/spring-cloud-azure/4.3.0/reference/html/index.html#secret-management)
  2. [4.3.0 Sample](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.3.0/keyvault/spring-cloud-azure-starter-keyvault-secrets/property-source)

If the problem still exists, please create a GitHub repo to put a sample project that can reproduce the problem. I can to root cause analyze if I can reproduce the problem in my localhost.

**Comment by chenrujun** [comment]
@Rakeshghatage 

Thank you for your response.

I have some questions:

1. Do you mean Azure's root certificate is `caadmin-netskope.cer`? How did you download it? I didn't get the information from this page: https://docs.microsoft.com/en-us/azure/security/fundamentals/azure-ca-details
2. Is `AVD` short for your application's name?

**Comment by Rakeshghatage** [comment]
@chenrujun 

1) I am not able to attach the screen shot of certificate, but here are the steps which I followed.
  * Below link shows Steps and Details.
    https://www.esri.com/arcgis-blog/products/bus-analyst/field-mobility/learn-how-to-download-a-ssl-certificate-for-a- 
     secured-portal/
  * I went to azure portal and downloaded the certificate from Details, it download for *.portal.azure.com.
  * But then I went to certificate path and selected root certificate {caadmin-netskope.com} imported it and installed in JDK.
  * This way I was able to fix the issue.
   
2)AVD-> Azure Virtual Desktop

Please let me know if any details required.

**Comment by chenrujun** [comment]
@Rakeshghatage 

I got it. Thank you for your information.
