### ISSUE TITLE
[QUERY] How to provide session token to queryChangeFeed Java API

### ISSUE THREAD

**Issue by jgray-toshibagcs** [Azure/azure-sdk-for-java#30652]
I am developing a Spring MVC REST service that uses the Cosmos change feed pull model to provide changes to web clients that have occurred since the last client request.  I would like to support running the service on multiple nodes using session consistency as described in https://docs.microsoft.com/en-us/azure/cosmos-db/sql/how-to-manage-consistency?tabs=portal%2Cdotnetv2%2Capi-async#utilize-session-tokens, but I cannot seem to find how to provide the session token to the queryChangeFeed call.  Is the session token not appropriate to queryChangeFeed or is this missing from the API?  I am currently using azure-cosmos 4.32.1 but I have looked in 4.35.0 and didn't see a way to pass the session token to queryChangeFeed in 4.35.0 either.  Apologies if I'm missing something obvious.

**Comment by yiliuTo** [comment]
Hi @kushagraThapar and @TheovanKraay, could you help to look into this issue?

**Comment by TheovanKraay** [comment]
@jgray-toshibagcs you are using [change feed pull model](https://learn.microsoft.com/azure/cosmos-db/nosql/change-feed-pull-model?tabs=java) which requires you to manage state and parallelization across partitions. Have you considered using [change feed processor](https://learn.microsoft.com/azure/cosmos-db/nosql/change-feed-processor?tabs=dotnet)? This allows you to deploy multiple delegates on multiple machines, and parallelization across partitions is handled internally and transparently using a shared lease container. Regardless of which model you use, the challenge to be solved in processing change feed data is not sharing a sessions across multiple nodes - that is not typically required to processes the data in parallel for the use cases in which change feed is used. With that said, if you think this is needed in your case, please do elaborate on your use case, so that we can understand if there is really a feature gap.

**Comment by TheovanKraay** [comment]
Closing due to age and no response to last comment.
