### ISSUE TITLE
[QUERY] Azure-cosmos recommended version 

### ISSUE THREAD

**Issue by esciullo** [Azure/azure-sdk-for-java#30661]
**Query/Question**
In azure-cosmos changelog you recommend to use version 4.31.0 and above (https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos/CHANGELOG.md#4310-2022-06-08).

Why do you recommend this ?
What features or bugfixes justify this?

Thanks

**Comment by kushagraThapar** [comment]
@esciullo - there have been several improvements and critical bug fixes in the Java SDK which are all listed in the changelog below this specific version like memory leak fixes, and jackson dependency updates. 
On top of that, azure-cosmos depends on azure-core and azure-core-http-netty modules for reactor and netty dependencies. Those also have critical fixes in the older versions, and that's why recommend this version. 
If you want to get more details, I would recommend looking at release notes for azure-core, and azure-core-http-netty for 3rd party library critical fixes.
