### ISSUE TITLE
Go through all SQL Server passwordless migration guide/quickstart/tutorial to make sure by following them can work

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#30831]
Since most of the passwordless docs are ready, we should follow instructions of each doc to make sure all of them can work correctly. The docs included:

- [x] #30343 
  PR: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3511
- [x] #30342 
  PR: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3511
- [x] Tutorial: deploy spring database application to Azure Spring Apps
  PR: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3511
- [x] #30350 
  PR: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3590

**Comment by Netyyyy** [comment]
fixed in:
- https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3660
- https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3653
- https://github.com/saragluna/azure-dev-docs-pr/pull/8
- https://github.com/saragluna/azure-dev-docs-pr/pull/7
- https://github.com/saragluna/azure-dev-docs-pr/pull/6
- https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3617
