### ISSUE TITLE
[FEATURE REQ] Add support for sending data to loganalytics via log-analytics client 

### ISSUE THREAD

**Issue by aniketshrimal** [Azure/azure-sdk-for-java#31047]
**Is your feature request related to a problem? Please describe.**

- Currently [LogAnalyticsDataClient](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/loganalytics/microsoft-azure-loganalytics/src/main/java/com/microsoft/azure/loganalytics/LogAnalyticsDataClient.java) only has functionality to query the data from logAnalytics and does not let us send the data. 
- This is currently achievable via REST APIs but it would be better if we have the functionality in azure-sdk itself.  

**Describe the solution you'd like**

- The request here is to add support for sending the data via log-analytics client.

**Describe alternatives you've considered**

- Using rest API (https://learn.microsoft.com/en-us/azure/azure-monitor/logs/data-collector-api)

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by joshfree** [comment]
@ki1729 could you please follow up with @aniketshrimal?

/cc @scottaddie @srnagar

**Comment by scottaddie** [comment]
@aniketshrimal Because this package is deprecated, we'll no longer add features to it. It's been replaced by the [Azure Monitor Query library](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/monitor/azure-monitor-query).

To support the use case of sending logs to Log Analytics, we're developing the [Azure Monitor Ingestion library](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/monitor/azure-monitor-ingestion). Please try the latest beta release, and let me know if it meets your needs. We're targeting November for the GA release.

**Comment by ciufudean** [comment]
This is the [javadoc](https://learn.microsoft.com/en-us/java/api/com.microsoft.azure.loganalytics.loganalyticsdataclient?view=azure-java-stable). I cannot see it as deprecated.
