### ISSUE TITLE
[QUERY] Specific and detailed information for Service Bus connection management

### ISSUE THREAD

**Issue by epomatti** [Azure/azure-sdk-for-java#31331]
**Query/Question**
How exactly should we manage Service Bus client connections, and can we have details added to the documentation?

I will have hundreds and possibly thousands of concurrent requests writing to Service Bus. How should I share connetions in a way that optimizes performance and resource management, without risk to integrity?

Should we always call `.close()` in the client after a "send" operation? I noticed by the logs that when doing this it seems that the whole connection gets recreated and it takes a long time to complete, sometimes close to 2 seconds.

When I leave a client without closing it the speed is much faster, however I get that are opened clients sharing a connection. Is this a bad practice?

```
# of open clients with shared connection: 13391
```

What is thread safe? What isn't thread safe? Can I share a client instance within for my application?

```java
@Bean
@Scope(value = "singleton")
public ServiceBusSenderClient getClientBuilder() {
  return new ServiceBusClientBuilder()
      .connectionString(connectionString).sender()
      .queueName(ORDERS_QUEUE)
      .buildClient();
}
```

What does "done" means? Like, "done" in a user request sense? Or, when shutting down the application process?

```java
// When you are done using the sender, dispose of it.
sender.close();
```

I was reading the connection section in the [documentation](https://azuresdkdocs.blob.core.windows.net/$web/java/azure-messaging-servicebus/7.11.0/index.html) however it is not clear how to optimally manage connections.

> **Sharing of connection between clients**
> 
> The creation of physical connection to Service Bus requires resources. An application should share the connection between clients which can be achieved by sharing the top level builder as shown below.

```java
// Create shared builder.
ServiceBusClientBuilder sharedConnectionBuilder = new ServiceBusClientBuilder()
    .connectionString("<< CONNECTION STRING FOR THE SERVICE BUS NAMESPACE >>");
// Create receiver and sender which will share the connection.
ServiceBusReceiverClient receiver = sharedConnectionBuilder
    .receiver()
    .queueName("<< QUEUE NAME >>")
    .buildClient();
ServiceBusSenderClient sender = sharedConnectionBuilder
    .sender()
    .queueName("<< QUEUE NAME >>")
    .buildClient();
```

What is a "dedicated connection"? I couldn't find to work with it in the documentation.

![image](https://user-images.githubusercontent.com/6530769/194730727-2991ae95-eb93-479d-8497-3509cf44ed95.png)

***Why is this not a Bug or a feature Request?***
To provide detailed information about high-performance connection management.

**Setup (please complete the following information if applicable):**
 - OS: Any
 - IDE: Any
 - Library/Libraries: com.azure:azure-messaging-servicebus:7.11.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@liukun-msft could you please take a look at this issue filed by @epomatti?

**Comment by liukun-msft** [comment]
@joshfree Sure, I am checking all these questions and will reply.

**Comment by liukun-msft** [comment]
Hi @epomatti, I think your main question is when to create and close a sender. When we create a sender client, it will maintain a connection with the service bus service, so that we can send message over that connection. Depends on different using scenario, here is my suggestion: 

- If you send messages frequently over a long period of time (which seems like your scenario), you can create a sender client as a singleton instance and close the sender when the application is shutting down.

- If you send only a small number of messages over a long period of time, you can just create the sender when you need to send a message and then close the sender. Hence, we can save the resource to maintain the connection.

Below are some answers for your questions:

> _How exactly should we manage Service Bus client connections, and can we have details added to the documentation?_

The connections are underlying maintained by clients itself. Basically, you don't need manage client connections from your ends. The only thing you need to consider is whether you want to use one shared connection or separate connections when you have several clients. 

Right, we need to add more documents for about connections and clients. 

> _Should we always call.close() in the client after a "send" operation?_

No. if you still need to send messages, you don't need to close the client after one send operation. You can call send message multiple times on the same client. But if you don't need this sender client (maybe all messages are sent or you want to send with a new sender), you have to close the old sender client to release the resource.

From the logs (open clients with shared connection: 13391), it looks like you created a lot of clients, but didn't close them when you didn't need them anymore. This is not a correct usage.

>_Can I share a client instance within for my application?_

Yes, you can use a share a client instance. 

>_What does "done" means? Like, "done" in a user request sense? Or, when shutting down the application process?_

"done" means you don't need this sender to send message anymore. For your case, I think is when shutting down the application process.

> _What is a "dedicated connection"?_

Here "dedicated connection" is to differentiate from "shared connection".  It means that connection is only owned by one client.

Here is an example:

Case 1 (use shared connections):
- Sender client use a shared connection A
- Receiver client use a shared connection A

if we close sender client, the connection A won't be close as it still be use by receiver client. Only when both sender and receiver clients are closed, connection A will be closed.

Case 2 (not using shared connections):
- Sender client use dedicated connection A
- Receiver client use dedicated connection B

If we close sender client, then the connection A will be closed. If we close receiver client, the connection B will be closed. 

And again, the closure of connection is detected by client itself. You don't need to manage that. If you are using one application and client number is small, I suggest you can use a share connection. But if you want to increase more performance, you can choose to use dedicated connection. So, whether to use shared connection depends on your real scenario.

**Comment by liukun-msft** [comment]
Hi @epomatti  

Oh, I don't mean the closure of client is automatic detected. You still need to explicitly close client before you shut down your application.  

The connection and client are two different concepts, and what I want to say is the connection is managed by client. As log shows, when you close the client (`ServiceBusReceiverAsyncClient`), because no other clients are using that connection, the connection (`ReactorConnection`) is also closed.

For `java.lang.AutoCloseable`, it can allow you to use try-with-resources way to create the client.

And if you don't explicitly `close()` client and shutdown your application, the service bus service can detect client is inactive for some time and release related resources (connection, message locks). Consider the detection have some delay, it is better to use `close()` when you shutdown your application.

**Comment by liukun-msft** [comment]
Hi @epomatti 

Right, the connection is built only when you need to send/receive messages. 

Currently there is no API for user to eagerly start connection without send/receive message. One reason I can think is because a connection will be force-closed if it is inactive for 5 minutes (no messages send/receive), even you eagerly start the connection, it could be closed if you don't send a message during that time. 

Do you have any business requirement for this (maybe you need less time delay for sending the first message)? I can take your question to discuss inside our team. 

Can you also talk more about the purpose of using "healthcheck" queue, you want to send message every 5s to keep connection open?

**Comment by epomatti** [comment]
In my client's particular use case, they have key-accounts which will send 1 weekly request, but this request will contain hundreds of thousands of documents, generating some millions of events, and the SLA for this will be under 30 minutes. The key-accounts application environments are dedicated and so will be the queues, and it should be preferably "warm" to stay within he 30 minutes range. We're exploring Container Apps as the application layer and a SQL Database Serverless. Due to this and other requirements such as transactions and possibly sessions, Service Bus might be an option (as opposed to Storage Queues). The Service Bus namespace would be shared with other applications so price would be justifiable.

Also, I guess it just feels natural to have some way of 1) Optionally having a way to hot test a connection when the application starts up 2) Keeping a connection ready and healthy to start working (something like a `SELECT 1` database pool query).

> Can you also talk more about the purpose of using "healthcheck" queue, you want to send message every 5s to keep connection open?

I wanted to make sure the application is healthy on startup, and connections warmed-up to do some work.

> ... a connection will be force-closed if it is inactive for 5 minutes (no messages send/receive), even you eagerly start the connection, it could be closed if you don't send a message during that time.

Perhaps this behavior could be allowed to be configurable by developers using the SDK from the outside.

In any case this was very informative, it would be nice to have added technical documentation in the official docs for a quick reference of the available configuration options, terminologies and behaviors.

**Comment by liukun-msft** [comment]
Thanks @epomatti! Let me bring this requirement to our team discussion and get back to you.

**Comment by liukun-msft** [comment]
Hi @epomatti, I have some updates for your requirements:

For sender sync/async clients, the `createBatchMessage()` API can establish a connection without sending any messages to the service bus. The method is used when you want to send batch messages, you can firstly know the max size of messages in one batch that transport allows.

As a workaround, you can firstly call `createBatchMessage()` when you want to start up the connection. And if you want to keep the connection active and have a send link ready in place, you can call this method at least every 10 minutes. (Since if there are no messages to be sent within 10 minutes, the send link will be force-detached, and if there is no active link for 5 minutes, then the connection will be forced-closed).  

The link and connection timeout are set on service end, so we need to contact service team for the reason why they pick the fixed value.  But the reason for setting timeout is release resources for unused endpoints. For your case, if you know the exactly sending time, I think you can schedule to call `createBatchMessage()` to startup connection and if you keep sending messages for 30 minutes, the connection can be active during this time.

**Comment by epomatti** [comment]
@liukun-msft I appreciate the details very much and will look into the workaround.

As for the definitive behavior, what should be done about:
- A dedicated health check API derived from the empty `createBatchMessage()`
- Allowing for custom control of timeout and other connection pool behaviors.

Should I open a separate issue for those?

**Comment by liukun-msft** [comment]
Hi @epomatti 
For dedicated health check, after discussion, we decided not to implement this additional API as `createBatchMessage()` cover the same functionality.  
For the custom control of timeout, I am still waiting the response from service team.
