### ISSUE TITLE
Enhance our passwordless docs according to go-through comments 

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#31346]
### Context

Since lots of comments were left by the go-through issue: https://github.com/Azure/azure-sdk-for-java/issues/30800

### Goal
We need to do:
- [ ] Categorize and organize all comments
- [ ] Schedule a meeting to discuss whether and how to modify

**Comment by Netyyyy** [comment]
After discussion, we divided those comments into three parts: fix now, will fix in the future, need to confirm.
### the below comments I will fix now:
1. `credentialS` -> `credentials` in quickstart
![image](https://user-images.githubusercontent.com/92105726/200265386-b89fcf83-b633-4020-8511-6029793ce5dd.png)
2. `after` -> `Since`,  `4.4.0` -> `spring-cloud-azure-dependencies:4.4.0` in migration guide
![image](https://user-images.githubusercontent.com/92105726/200274583-5a45e834-ca9f-41ad-b1a0-3af0e4fda17b.png)
3. (Migration.5) `in the application`-> `in the application code`
4. (Migration.6)Azure Managed Identity and Role Based Access Control (RBAC) are not Azure services. -> such as via Azure Managed Identity, Delete `and … RBAC`
5. (Migration.36)Better to uniform the word: create / enable / assign. -> assign
6. (Quickstart.1)Add link to Azure Active Directory (Azure AD) authentication and Shared Access Signatures (SAS) authentication.
- Azure Active Directory (Azure AD) authentication 
https://docs.microsoft.com/en-us/azure/event-hubs/authenticate-application or 
https://docs.microsoft.com/en-us/azure/event-hubs/authenticate-managed-identity?tabs=latest 
- Shared Access Signatures (SAS) authentication 
https://docs.microsoft.com/en-us/azure/event-hubs/authenticate-shared-access-signature   
7. (Migration.7)To make less confusing, add link to DefaultAzureCredential when it first appears in this document.
- https://learn.microsoft.com/en-us/java/api/overview/azure/Identity-readme?view=azure-java-stable#defaultazurecredential 
8. (Migration.26) Change the order of login method. Put Cli and PowerShell together. 

### the below comments will be fixed in the future:
1. (Quickstart.4)Add links.
2. (Migration.9)The content of Introducing passwordless connections is different from page to page,suggest writing this content in a standalone page, then add link to the page in other pages.
3. (Migration.12,13)To make it less confusing, it's better to provide the project before migraion, and the project after migration.Rujun create the before code: https://github.com/Azure/azure-sdk-for-java/issues/30800#issuecomment-1250725728 
4. (Migration.16)Use constant value instead of raw string.
5. (Migration.23) Deleted properties should be written in the migration guide.
6. (Migration.28)There should be a tab named Intellij.
7. (Migration.29)The login process it possible to change. It's better to add link to tell reader how to login instead of demonstrate login step by step.
8. (Migration.31)Tell customer what should be deleted .Spring Cloud Stream Binder Kafka.
9. (Migration.33,37)Change the order of host environment. Service Connector depends on other host environments. Should not appear at first.
10. (Migration.34)It's better to add link to another page instead of adding steps (screenshots) by ourselves. Because the steps (including the portal page) may change in the future.
11. (Migration.35)Enable managed identity by portal has 5 tabs, but by cli has 6 tabs 
12. (Migration.21) Current guide only contains add contents, is it necessary to delete something? Because this guide assume customer is using Shared Access Signature (SAS) before migrate. Answer: need to change property's value, delete some property key.
13.  (Migration.38)Can not find Azure Spring Apps in Event Hubs role assign page.
14. (Migration.39)Organize content in this style

**Comment by Netyyyy** [comment]
### And the following needs to confirm. 
Please help to confirm, @yiliuTo :
1. (Quickstart.8)Delete unnecessary description;same description in migration guide
2. (Quickstart.7)Delete implementation detail in the quick start guide. Move it to reference doc if necessary.
3. (Migration.20)Mixed spring-kafka and spring-boot. Property like spring.kafka.bootstrap-servers is only useful for spring-boot application. But spring-kafka can be used without spring-boot.
4. (Migration.22)Delete properties that is not caused by migration. For example: spring.kafka.bootstrap-servers already exists before migration. In my understanding, migration guide should only tell reader what should be changed.
5. (Migration.24,25,30)WARN log, has been fixed?
6. (Migration.27)Is visual studio supported? And VisualStudioCodeCredential will be removed. Ref:https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/CHANGELOG.md#170-beta1-2022-09-20

**Comment by yiliuTo** [comment]
> (Quickstart.8)Delete unnecessary description;same description in migration guide
Confirmed, we can delete that.

> (Quickstart.7)Delete implementation detail in the quick start guide. Move it to reference doc if necessary.
Confirmed, we can delete that.

> (Migration.20)Mixed spring-kafka and spring-boot. Property like spring.kafka.bootstrap-servers is only useful for spring-boot application. But spring-kafka can be used without spring-boot.
Confirmed, we change the tab name from `Spring Kafka` to `Spring Kafka (Spring Boot Application)`.

> (Migration.22)Delete properties that is not caused by migration. For example: spring.kafka.bootstrap-servers already exists before migration. In my understanding, migration guide should only tell reader what should be changed.
Confirmed, has been updated before.

> (Migration.24,25,30)WARN log, has been fixed?
Under process.

> (Migration.27)Is visual studio supported? And VisualStudioCodeCredential will be removed. Ref:https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/CHANGELOG.md#170-beta1-2022-09-20
Need to confirm.

**Comment by hui1110** [comment]
### the below comments will be fixed in the future:
1. (Quickstart.4)Add links.
2. (Migration.9)The content of Introducing passwordless connections is different from page to page,suggest writing this content in a standalone page, then add link to the page in other pages.
3. (Migration.12,13)To make it less confusing, it's better to provide the project before migraion, and the project after migration.Rujun create the before code: https://github.com/Azure/azure-sdk-for-java/issues/30800#issuecomment-1250725728 
4. (Migration.16)Use constant value instead of raw string.
5. (Migration.23) Deleted properties should be written in the migration guide.
6. (Migration.28)There should be a tab named Intellij.
7. (Migration.29)The login process it possible to change. It's better to add link to tell reader how to login instead of demonstrate login step by step.
8. (Migration.31)Tell customer what should be deleted .Spring Cloud Stream Binder Kafka.
9. (Migration.33,37)Change the order of host environment. Service Connector depends on other host environments. Should not appear at first.
10. (Migration.34)It's better to add link to another page instead of adding steps (screenshots) by ourselves. Because the steps (including the portal page) may change in the future.
11. (Migration.35)Enable managed identity by portal has 5 tabs, but by cli has 6 tabs 
12. (Migration.21) Current guide only contains add contents, is it necessary to delete something? Because this guide assume customer is using Shared Access Signature (SAS) before migrate. Answer: need to change property's value, delete some property key.
13.  (Migration.38)Can not find Azure Spring Apps in Event Hubs role assign page.
14. (Migration.39)Organize content in this style

**Comment by hui1110** [comment]
Created PR: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3848

**Comment by hui1110** [comment]
Unfixed comments will be tracked with this issue: https://github.com/Azure/azure-sdk-for-java/issues/32185

**Comment by chenrujun** [comment]
Closing this issue because all remaining tasks are tracked by this issue: https://github.com/Azure/azure-sdk-for-java/issues/32185
