### ISSUE TITLE
[FEATURE REQ] Replace the deprecated API RSAKey.Builder#x509CertThumbprint for Spring Cloud Azure

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#31571]
**Is your feature request related to a problem? Please describe.**
RSAKey.Builder#x509CertThumbprint is currently used in Spring Cloud Azure's `com.azure.spring.cloud.autoconfigure.aad.implementation.oauth2.AadOAuth2ClientAuthenticationJwkResolver` that obtaining a `com.nimbusds.jose.jwk.JWK` in *nimbus-jose-jwt*.
But this API has been deprecated since 2017-04-08 version `4.35` due to `security measures`, release notes as below:

![image](https://user-images.githubusercontent.com/19926623/203879813-1750d262-2d3b-4620-8bd8-9ea294adf291.png)

see more from this commit https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/e4d758f756a1a0bbfa693e56cf093d3cc3e73a4e 

The deprecated APIs usage should be upgraded, when enabling the compilation failure, this may affect the downstream application compilation.

**Describe the solution you'd like**
Make a replacement for the API `RSAKey.Builder#x509CertThumbprint` and keep the Azure AD features unchanged.

**Describe alternatives you've considered**
N/A

**Additional context**
This change needs to update in both Spring Cloud Azure 4.x and 6.x versions. This not only needs the *nimbus-jose-jwt* to provide a replacement for `RSAKey.Builder#x509CertThumbprint`, but also the Azure AD can recognize the new header to work together.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by stliu** [comment]
this issue lacks key information and is hard to understand.

* What is this API?
* When it is deprecated?
* Where is it used in Spring Cloud Azure?

 I'd expect something like this:

`RSAKey.Builder#x509CertThumbprint` is currently used in Spring Cloud Azure's _xxx_ that doing _yyy_.
But this API has been deprecated since _{some date time }_ due to {some kind of reason}, here is the detailed information about this deprecation _{maybe a link to the issue that deprecated this one or release note has relvlent info}_.
