### ISSUE TITLE
MSI token cache not work as expected with millions reqeusts to the IMDS

### ISSUE THREAD

**Issue by wejian** [Azure/azure-sdk-for-java#31932]
Customer statement below: 
We are using azure service bus java sdk: com.microsoft.azure:azure-servicebus:3.6.6 and recently enabled user managed identity in our azure spring apps to connect and read/write messages to service bus. we noticed that in 24 hours, the sdk makes more than 1 million calls to the IMDS service to get token and this results in slow performance of message consumption and causes issues in our application due to the slowness.

Below is how we create the client to service bus.
Code:
var tokenProvider = TokenProvider.createManagedIdentityTokenProvider();
var clientSettings = new ClientSettings(tokenProvider);
return MessagingFactory.createFromNamespaceName(
        serviceBusNamespace,
        clientSettings);

The connection is established once during startup but we see that when we use managed identity, the sdk makes a lot of calls to the internal IMDS service of the compute which results in throttling and slows down the overall processing of messaged.

We do not do management operations like getEntity, deleteEntity etc from our application. The application only reads and writes messages to service bus, nothing else.

We have about 16 spring apps and we are using managed identity for various other azure resource which do not seem to have a problem, nor make so many calls to the backend IMDS. We are using it for  azure keyvault, storage blob, we insert and query millions of rows daily in to the database and are using managed identity everywhere without any issues.

Only for service bus, we see so many calls to the backend IMDS. From what we know, tokens returned by the IMDS are valid for 24 hours, so why does the sdk even make so many calls to IMDS ? we don’t see a similar behavior with a high number of calls to IMDS  in other sdks like storage-blob or mssql-jdbc for example.

**Comment by joshfree** [comment]
@billwert could you follow up on this issue reported by @wejian?

**Comment by billwert** [comment]
@wejian Hello! Can you share some information about what version of the Identity library you are using?

**Comment by billwert** [comment]
The `com.microsoft.azure:azure-servicebus` library is a deprecated version. The first step here is to migrate to the new package, [`com.azure.azure-messaging-servicebus`](https://search.maven.org/artifact/com.azure/azure-messaging-servicebus). There is a [migration guide](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/migration-guide.md) available.

**Comment by anuchandy** [comment]
But I had a quick look at the Track1 Service Bus library; I think the issue is - Track1 Service Bus Library is not sharing the MSI Credential object; instead, it creates a new MSI Credential object each time it needs to get the token. Because of this, the cache is not being used. This is likely the case, but I would let the owners of Track1 Service Bus Library have a look and confirm.

Here is the code [reference ](https://github.com/Azure/azure-sdk-for-java/blob/b44bcf798b25ed38e924fa0953dd7150e0bf59ee/sdk/servicebus/microsoft-azure-servicebus/src/main/java/com/microsoft/azure/servicebus/security/ManagedIdentityTokenProvider.java#L31) showing the recreation of the Credential object per token retrieval in Track1 Service Bus

If you look at the Track1 Event Hubs, it shares the Credential Object, here is the [reference ](https://github.com/Azure/azure-sdk-for-java/blob/b44bcf798b25ed38e924fa0953dd7150e0bf59ee/sdk/eventhubs/microsoft-azure-eventhubs/src/main/java/com/microsoft/azure/eventhubs/ManagedIdentityTokenProvider.java#L16).

**Comment by yvgopal** [comment]
Resolved and released in SDK version 3.6.7.
