### ISSUE TITLE
[BUG]IndexingPolicy is getting overwritten

### ISSUE THREAD

**Issue by loudywen** [Azure/azure-sdk-for-java#31949]
hi my issue is kind of same as this issue https://github.com/Azure/azure-sdk-for-java/issues/20330

I am using
```
      <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-spring-data-cosmos</artifactId>
            <version>3.29.1</version>
        </dependency>
```

I setup the the index policy from the azure portal, once the indexing process is done, I am able to make a Order by query. But after sometime then my index policy changed back to the default.

This is how I initial the cosmos client
```
     @Primary
     @Bean
     public CosmosClientBuilder myCosmosBuilder() {
          CosmosClientBuilder cosmosClientBuilder = new CosmosClientBuilder();
          cosmosClientBuilder.key("key");
          cosmosClientBuilder.endpoint("url"));
          cosmosClientBuilder.consistencyLevel(ConsistencyLevel.BOUNDED_STALENESS);
          cosmosClientBuilder.directMode(new DirectConnectionConfig(), new GatewayConnectionConfig());
          cosmosClientBuilder.preferredRegions(Arrays.asList("region"));
          return cosmosClientBuilder;
     }
```

This is my model

```
@Container
@Data
@EqualsAndHashCode(callSuper = true)
@JsonPropertyOrder(alphabetic = true)
@NoArgsConstructor
public class Dummy {
     
     @Schema(hidden = true)
     @JsonIgnore
     private String    id;
     
     @Schema(hidden = true)
     @PartitionKey
     private String    partitionId;

```

**Comment by kushagraThapar** [comment]
@trande4884  please take a look at this.

**Comment by trande4884** [comment]
@loudywen so you have no @CosmosIndexingPolicy() defined on the container, but you have set it via the portal. Per the linked issue it would seem that in that case the indexing policy would be reset to the default, which is the expected behavior. From a comment on the linked issues: "If the annotation is not used, then the code assumes the default index policy should apply.".

@kushagraThapar I see you made some updates in the linked issue, but there is little description as to the goal of those updates. Were these updates to adjust this expected behavior at all? Do these changes make it so that if the indexing policy has been defined via the portal, and @CosmosIndexingPolicy() annotation is not added then what was defined via the portal will be kept?

**Comment by loudywen** [comment]
@trande4884 I think the expected behavior should be `if the indexing policy has been defined via the portal, and @CosmosIndexingPolicy() annotation is not added then what was defined via the portal will be kept` and `if CosmosIndexingPolicy() annotation is added then use it`

**Comment by kushagraThapar** [comment]
@trande4884 I added check for the case where indexingPolicy is not specified at all and we don't override the portal's defined policy with a new policy. 
@loudywen your expectation is correct. Putting it in simple terms, if the annotation is specified, it will be used as new policy, otherwise indexing policy won't be updated. 
Do you know when and how the policy is getting reset? Did you debug the application and saw the policy getting updated through spring data cosmos SDK ?

**Comment by loudywen** [comment]
@kushagraThapar  @trande4884  our current deployed application uses version 3.7.0. and in my local dev environment, I am using 3.29.1. Do you guys think 3.7.0 has this fix `I added check for the case where indexingPolicy is not specified at all and we don't override the portal's defined policy with a new policy`?


I have not started any debugging yet.  So I am not sure whether the overwrite is triggered from our deployed application or in my local dev environment.

**Comment by kushagraThapar** [comment]
@loudywen this bug was fixed in 3.8.0 as I see from the changelog - https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-spring-data-cosmos/CHANGELOG.md#380-2021-06-11

I would highly recommend to update to the latest version and test this in an isolated environment. That will really help with the investigation of this issue, thanks!

**Comment by trande4884** [comment]
I agree with Kushagra, I have been testing this over the last few days but so far I have been unable to reproduce the behavior. If the latest version does not resolve the issue any additional details that could help me reproduce the issue would be great!

**Comment by loudywen** [comment]
@kushagraThapar @trande4884  sure guys, let me do some test on another environment and will get back to u

**Comment by loudywen** [comment]
@trande4884  we will start testing this issue on our alpha environment, will keep you post

**Comment by loudywen** [comment]
@trande4884 looks like after upgrading to the latest version this issue no longer happens. thx, I will close this issue.
