### ISSUE TITLE
[FEATURE REQ] Enable JPMS for Spring Cloud Azure JDBC starters

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#31970]
**Is your feature request related to a problem? Please describe.**
The first beta release for `spring-cloud-azure-starter-jdbc-*` has been out. We should enable JPMS (add automatic module name) before we GA these libraries.

Related to https://github.com/Azure/azure-sdk-for-java/issues/31140. 
**Describe the solution you'd like**
Enable JPMS (add automatic module name). 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by Netyyyy** [comment]
Since the automatic module name for `spring-cloud-azure-starter-jdbc-*` has already been added, only need to test it.

And the test result is that adding or removing these modules `com.azure.spring.cloud.starter.jdbc.mysql` and `com.azure.spring.cloud.starter.jdbc.postgresql` are both OK, because we won't directly use their codes.
