### ISSUE TITLE
[FEATURE REQ] Track telemetry of requests make from Spring Lib through Azure Identity

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#32146]
## Context

Azure Identity now supports customize UserAgent since 1.7.1

see
 * #32095 
 * #32071
 

With this new feature, Spring Cloud Azure should measure adoption from an authentication perspective.

## Goal

Spring Cloud Azure libraries using azure identity should have its own UserAgent customized following on the Spring Cloud Azure Guidelines

And answer this question: 

* how many customers are using Spring Cloud Azure to perform authentication through Azure Identity.
* Percentage of spring over java sdk.

## Status

currently blocked by #32356

**Comment by backwind1233** [comment]
[azure-identity:1.7.1 ](https://repo1.maven.org/maven2/com/azure/azure-identity/1.7.1/) has released on 2022-11-18.

**Comment by stliu** [comment]
Goal:

Track  telemtry of requests make from Spring Lib through Azure Identity.

Sub Goal:

1. Azure Identity now supports customize UserAgent since 1.7.1, all spring cloud azure libraries using azure idenityt should have it s own UserAgent customized following on the Spring Cloud Azure Guidelines 
2. Collect this kind of data and show it in our own BI system.

**Comment by stliu** [comment]
@saragluna please plan this as the highest priority in our next sprint, and this targets to Spring Cloud Azure not passwordless only.

**Comment by saragluna** [comment]
Blocked by https://github.com/Azure/azure-sdk-for-java/issues/32356.

**Comment by saragluna** [comment]
PoC https://github.com/Azure/azure-sdk-for-java/pull/33212
