### ISSUE TITLE
[FEATURE REQ] Spring Cloud Azure 5.0 migration support

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#32178]
### Context
Spring Cloud Azure migration doc for 5.0 only covered the manual upgrades, there are no migration tools to assist to upgrade to Spring Cloud Azure 5.0. When customers upgrade to Spring Cloud Azure 5.0, if it can save time and reduce errors to improve user experience, it is valuable to provide customers.

### Goal
This issue will target to provide a tool to support migration to Spring Cloud Azure 5.0, the tool usage will be a part of the migration guide for 5.0.

**Comment by moarychan** [comment]
Updated to the major version `5`, see more from [Spring Cloud Azure 5.0 Release](https://github.com/Azure/azure-sdk-for-java/issues/31895).

**Comment by anbusampath** [comment]
Since Spring Cloud Azure 6.0.0-beta.4 renamed to Spring Cloud Azure 5, can we remove the beta releases from maven central. Everytime when we look for what is the new version of Spring Cloud Azure, version 6 is marked as new in https://mvnrepository.com/artifact/com.azure.spring/spring-cloud-azure-autoconfigure  which is confusing the users.

https://github.com/Azure/azure-sdk-for-java/issues/31895 
https://github.com/Azure/azure-sdk-for-java/issues/31938
<img width="967" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/1268973/28f488ba-5edc-48ad-b827-36e4729c7066">

**Comment by moarychan** [comment]
Hi @anbusampath , so sorry, this issue does happen, as far as I know we don't seem to be able to delete it, it's out of our control.
