### ISSUE TITLE
[FEATURE REQ] Deprecate the implementations from WebSecurityConfigurerAdapter

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#32279]
### Context
Since the `WebSecurityConfigurerAdapter ` has been deprecated, then the below class should be updated to provide a new configurer for HTTP security,
https://github.com/Azure/azure-sdk-for-java/blob/2c884a44845ad3d6b4b755bd80ceaf1e87a3fe01/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/AadWebSecurityConfigurerAdapter.java#L38

https://github.com/Azure/azure-sdk-for-java/blob/2c884a44845ad3d6b4b755bd80ceaf1e87a3fe01/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/AadResourceServerWebSecurityConfigurerAdapter.java#L22

We should refer to the new configuer from `feature/spring-boot-3` branch, 

https://github.com/Azure/azure-sdk-for-java/blob/a77e4b3982041991b5ca467ee574eb7e8d7ebe11/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/AadResourceServerHttpSecurityConfigurer.java#L24

https://github.com/Azure/azure-sdk-for-java/blob/a77e4b3982041991b5ca467ee574eb7e8d7ebe11/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/AadWebApplicationHttpSecurityConfigurer.java#L37

### Goal
- Marked the AadXXAdapter as deprecated APIs.
- Provide the new way based on `AbstractHttpConfigurer` for Azure AD autoconfigure.

**Comment by samhanes-fs** [comment]
While this is being worked on, would it be possible to add an `@ConditionalOnMissingBean` condition for `org.springframework.security.web.SecurityFilterChain` to the `DefaultAadResourceServerWebSecurityConfigurerAdapter` bean in `AadResourceServerConfiguration` so that projects using the starter can adopt Spring's recommendations?

Without that condition, attempting to use a `SecurityFilterChain` causes a bunch of Spring container wiring errors because many of the Spring Security beans are being created twice.

**Comment by Netyyyy** [comment]
Hi @samhanes-fs , the condition updated in the two PRs above.
