### ISSUE TITLE
Is azure-identity-providers-jdbc-postgresql 1.0.0 GA released?

### ISSUE THREAD

**Issue by prafsoni** [Azure/azure-sdk-for-java#32359]
**Query/Question**
Is azure-identity-providers-jdbc-postgresql 1.0.0 GA released? If so, do we know when it will be available on maven central? 
The reason I ask is when I look at the [CHANGELOG.md](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/jdbc/azure-identity-providers-jdbc-postgresql/CHANGELOG.md#100-2022-11-11) It dates 1.0.0 GA 2022-11-11. But unable to resolve it via maven and when I checked [here](https://mvnrepository.com/artifact/com.azure/azure-identity-providers-jdbc-postgresql) `1.0.0-beta.1` is shown as the latest version

**Comment by backwind1233** [comment]
Hi @prafsoni, thanks for reaching out.

There is a procedure called API review before we GA our libraries.
At first we were going to do our API review procedure on **main** branch, which need a concrete date to pass our pipelines.
since we still have many discussions, so we checked a new release branch [release/jdbc/1.0.0](https://github.com/Azure/azure-sdk-for-java/tree/release/jdbc/1.0.0) working on this, but forgot to update the [changelog](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/jdbc/azure-identity-providers-jdbc-postgresql/CHANGELOG.md#100-2022-11-11) on main branch.

I will update the [CHANGELOG.md](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/jdbc/azure-identity-providers-jdbc-postgresql/CHANGELOG.md) and update the status here.

**Comment by prafsoni** [comment]
@backwind1233  Thanks for the update. It sounds like this will not be released anything soon. Is there any timeline (roughly) for when the libraries will GA?
Also, in the interim what would be the recommended solution/workaround?

**Comment by backwind1233** [comment]
@prafsoni  We are preparing and working for the release, we target to GA our library during our next Sprint(12.5~1.6).

> Also, in the interim what would be the recommended solution/workaround?

What do you know by this? We beta released our libaries, 

- [spring-cloud-azure-starter-jdbc-mysql/4.5.0-beta.1](https://mvnrepository.com/artifact/com.azure.spring/spring-cloud-azure-starter-jdbc-mysql/4.5.0-beta.1)
- [azure-identity-providers-jdbc-mysql/1.0.0-beta.1](https://mvnrepository.com/artifact/com.azure/azure-identity-providers-jdbc-mysql/1.0.0-beta.1)

You can find more docs here.
[use-passwordless-connections](https://learn.microsoft.com/en-us/azure/developer/intro/passwordless-overview#use-passwordless-connections)

Is that a workaround for you?

**Comment by prafsoni** [comment]
Thanks, @backwind1233  I already tested with beta.1 jars and things were working. However, my question was mainly about alternatives to beta jars since didn't want to use them in production. 
Anyways I see https://github.com/Azure/azure-sdk-for-java/releases/tag/azure-identity-extensions_1.0.0 is released a few hours ago. 
Also, will there be an azure-sdk-bom release that will include azure-identity-extensions?

**Comment by backwind1233** [comment]
Hi @prafsoni:

> Anyways I see [azure-identity-extensions_1.0.0 (release)](https://github.com/Azure/azure-sdk-for-java/releases/tag/azure-identity-extensions_1.0.0) is released a few hours ago.

Yes, we moved azure-identity-providers-core, azure-identity-providers-jdbc-mysql, azure-identity-providers-jdbc-postgresql into one module: azure-identity-extensions. So [azure-identity-extensions_1.0.0](https://github.com/Azure/azure-sdk-for-java/releases/tag/azure-identity-extensions_1.0.0) will be the GA version.

**Comment by saragluna** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/32504 will add the `azure-identity-extensions` to `azure-sdk-bom`. So the artifact will be managed by the BOM in the next release. 

Closing this issue now.
