### ISSUE TITLE
mgmt, review and guideline on overall thread count

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#32369]
We likely have thread pool from azure-identity, HttpClient, and Reactor. We'd like a break down on how many on each, and whether it can be configured.

This likely worth a doc https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/resourcemanager/docs

The case in focus would be
- 1 HttpClient
- 1 TokenCredential impl
- 5000 Azure clients

Baseline is idle.
Another case would be system working, similar to https://github.com/Azure/azure-sdk-for-java/issues/31999#issuecomment-1309961334

Possible verification be JFR.

**Comment by XiaofeiCao** [comment]
Thread pool usage: https://github.com/XiaofeiCao/azure-client-example/blob/main/THREAD_USAGE_INFO.MD

Guide on thread pool and connection pool configuration: https://gist.github.com/XiaofeiCao/f7590441fd116aa87ac1dd39be19ce29

**Comment by weidongxu-microsoft** [comment]
Could you also write the way to change the pool size (I assume you have it for identity and netty, but not for Reactor yet)?

Also what is the CompilerThread?

---

When you think you are ready, loop in Alan for review as well.

I would expect it to be in repo doc.

**Comment by XiaofeiCao** [comment]
Reactor pool size is a little bit tricky because it's totally dependent on how users use the Flux or Mono that we return to them. By default, our provided Flux or Mono operates on http event loop threads. I can provide an example to hop over dedicated threads by using reactor Schedulers and ways to control Scheduler thread size.

CompilerThread comes from JIT compilers in JVM, with C1 client compiler and C2 server compiler, and their threads correspondingly. Their size can be controlled by providing java args `-XX:CICompilerCount=N`.

**Comment by weidongxu-microsoft** [comment]
Let's assume user uses the sync method, and hence not explicitly control the Reactor stream via e.g. `subscripedOn`

**Comment by XiaofeiCao** [comment]
PR created: https://github.com/Azure/azure-sdk-for-java/pull/32585

**Comment by XiaofeiCao** [comment]
close by https://github.com/Azure/azure-sdk-for-java/pull/32585
