### ISSUE TITLE
[BUG] Form Recognizer business card SDK is not working on Android

### ISSUE THREAD

**Issue by duytuan001** [Azure/azure-sdk-for-java#32441]
**Describe the bug**
The Form Recognizer Business Card SDK is not working on Android.

***Exception or Stack Trace***
No response.

**To Reproduce**
- JDK 11
- Android SDK 31
- Kotlin
- com.android.tools.build:gradle:7.2.2
- com.azure:azure-ai-formrecognizer:4.0.2

***Code Snippet***
```java
DocumentAnalysisAsyncClient client = new DocumentAnalysisClientBuilder()
    .credential(new AzureKeyCredential(key))
    .endpoint(endpoint)
    .buildAsyncClient();

String businessCardUrl = "https://raw.githubusercontent.com/Azure/azure-sdk-for-java/main/sdk/formrecognizer"
    + "/azure-ai-formrecognizer/src/samples/resources/sample-forms/businessCards/businessCard.jpg";

PollerFlux<OperationResult, AnalyzeResult> analyzeBusinessCardPoller =
    client.beginAnalyzeDocumentFromUrl("prebuilt-businessCard", businessCardUrl,
        new AnalyzeDocumentOptions().setPages(Arrays.asList("1")).setLocale("en-US"));

Mono<AnalyzeResult> businessCardPageResultsMono = analyzeBusinessCardPoller
    .last()
    .flatMap(pollResponse -> {
        if (LongRunningOperationStatus.SUCCESSFULLY_COMPLETED.equals(pollResponse.getStatus())) { 
            Log.d("XXX", "Polling completed successfully");

            return pollResponse.getFinalResult();
        } else {
            Log.d("XXX", "Polling completed unsuccessfully with status:" + pollResponse.getStatus());

            return Mono.error(new RuntimeException(
                "Polling completed unsuccessfully with status:" + pollResponse.getStatus()));
        }
    });

businessCardPageResultsMono.subscribe(businessCardPageResults -> {
    for (int i = 0; i < businessCardPageResults.getDocuments().size(); i++) {
        Log.d("XXX", "--------Analyzing business card --------");
    }
});
```

**Expected behavior**
It returns a response.

**Comment by joshfree** [comment]
@samvaity please take a look.  /cc @vcolin7

**Comment by vcolin7** [comment]
Hi @duytuan001,

Libraries from the Azure SDK for Java do not officially support Android. While there exists an [Azure SDK for Android](https://github.com/Azure/azure-sdk-for-android) repository, it supports very few services, not including Form Recognizer. There is currently no timeline for including Form Recognizer support for Android.

Having said that, you can technically use the Form Recognizer library for Java on certain Android API levels at your own risk as they were not designed to run on Android; also due to the fact that Reactor (one of our core dependencies) can only run on Android API level [26+ out of the box and 21+ with desugaring enabled](https://projectreactor.io/docs/core/release/reference/#prerequisites).

I spent some time testing where Form Recognizer can run out of the box and found that you can only use it as is on Android API levels 26 and 27, mainly because before level 26 you need to use desugaring for some Java APIs used by Reactor and our libraries and `MethodHandles.invokeExact()` (which we internally use) can only be desugared starting on level 26. On the other hand, the use of some external SDK APIs is restricted by Google starting on Android 28 (Pie), including two APIs we use in our Azure Core libraries:

```
Ljava/lang/invoke/MethodHandles$Lookup;-><init>(Ljava/lang/Class;)V
```
```
Ljava/lang/invoke/LambdaMetafactory;->metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;
```

I will be closing this issue for the time being as it is not really a bug.

Feel free to open a feature request on the Android repository for supporting the Form Recognizer service, maybe with enough demand support can be added at some point in the future.

**Comment by vcolin7** [comment]
I must note I ran these tests using Form Recognizer's latest version (`4.0.2`). You can try to use an earlier version of the library if you want it to work with newer Android versions that don't use the restricted APIs I mentioned (28+). As far as I know, the latest Azure Core version that does not use this is `1.22.0`, which should be paired with `com.azure:azure-core-http-okhttp:1.7.5` and `com.azure:azure-ai-formrecognizer:3.1.6` to ensure everything works as expected. However, this means you would be using an older version of FormRecognizer and would be missing out on the new features added on version `4.0.0`.
