### ISSUE TITLE
Consume from Eventhub at a constant speed 

### ISSUE THREAD

**Issue by Chaitragandha** [Azure/azure-sdk-for-java#32633]
**Is your feature request related to a problem? Please describe.**
During peak hours the event hub used receives sudden huge traffic which ultimately overwhelms the downstream components of the consumer service.
Eg. If my microservice(System A) is consuming events from an event hub and after doing some business logic and processing it is forwarding those events to some other system by its calling the REST API(System B). When I receive a sudden surge of events on System A from the event hub, there is a possibility that System B is not able to handle the load.

**Describe the solution you'd like**
As I can not control producer end of eventhub as well as System B's capability of handling events, I want System A to consume events from Eventhub at constant speed. This will let me put a constant tps load on the downstream components. Even if I consume in BATCH I am not achieving this as it is only max size based and not size + time based.
So request you to update ALL consumer client builders' declarations where we can mention how many events per second or minute it will receive.
eg.
```
EventHubConsumerAsyncClient consumer = new EventHubClientBuilder()
    .connectionString("<< CONNECTION STRING FOR SPECIFIC EVENT HUB INSTANCE >>")
    .batchPerSec(<< NO OF EVENTS PER SEC >>)
    .consumerGroup(EventHubClientBuilder.DEFAULT_CONSUMER_GROUP_NAME)
    .buildAsyncConsumerClient();
```

Also need to update the [spring-cloud-azure-stream-binder-eventhubs](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub) accordingly

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by yiliuTo** [comment]
Hi @Azure/azsdk-sb-java , could you help to take a look of @Chaitragandha 's feature request? This issue is migrating from https://github.com/MicrosoftDocs/azure-dev-docs/issues/977.

@Chaitragandha  is using the library of `spring-cloud-azure-stream-binder-eventhubs` and wants to consume messages at a constant speed, e.g., 5 events per second from each partition. The  `spring-cloud-azure-stream-binder-eventhubs` actually leverages the [EventProcessorClient](https://github.com/Azure/azure-sdk-for-java/blob/5bdf09aceac5e4cce4c6def23b0214d7cf3644e6/sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventProcessorClient.java#L41) and wraps its `processEventBatch` and `processEvent` APIs with both parameters of `maxWaitTime` and `maxBatchSize`.

So far `EventProcessorClient` doesn't provide the function of specifying both time and size for a batch as they way how @Chaitragandha described, would you consider this feature request? Or would there be any other workaround?

**Comment by Chaitragandha** [comment]
Hi 
Please let me know what inputs are required from my side?
I think what @yiliuTo has described is enough.

**Comment by conniey** [comment]
Hey,

I'm sorry for the delay.  We looked at your request, and when designing EventProcessorClient, we had high throughput in mind.  One option is to add some delay in your processEvents handler to throttle throughput.  (We do not continue to request additional events while processing user code.). Another option is to use the EventHubConsumerAsyncClient, it supports backpressure, so you can limit the rate at which you receive events and manually control the requests upstream.  A sample of that is: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventhubs/azure-messaging-eventhubs/src/samples/java/com/azure/messaging/eventhubs/EventHubPartitionConsumerWithBackpressure.java#L47.
