### ISSUE TITLE
[QUERY] Azure Blob SDK exception handling

### ISSUE THREAD

**Issue by zhtang-li** [Azure/azure-sdk-for-java#32666]
**Query/Question**
The question is about exception handling and i couldn't find any official information regarding this topic (something similar to speech sdk best practices)

1. Generally speaking, for any blob/container/client operations, e.g. append, download, exists, etc., should we expect any other runtime exception other than BlobStorageException?
2. should we expect BlobStorageException for every method calls from the sdk? when generally should we expect exceptions that could happen?

***Why is this not a Bug or a feature Request?***
It is not a bug, but I do think a clearer documentation could help for future readers.

**Setup (please complete the following information if applicable):**
N/A
com.azure:azure-storage-blob:12.20.1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by joshfree** [comment]
@jaschrep-msft could you please follow up with @zhtang-li on this github issue

**Comment by ibrahimrabab** [comment]
Hi @zhtang-li ,

Thanks for reaching out! 
1. Essentially the BlobStorageException is thrown whenever the service returns any response code that was not expected. For example, BlobContainerClient.create() method expects to return a response code 201 upon success. If any other response code was returned (such as response code 409 if container already exists), then a BlobStorageException would be thrown. 

For example, here:
[https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/implementation/ContainersImpl.java#L93](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/implementation/ContainersImpl.java#L93)
you can see that we expect response code 201 from the service upon completion. If there is any other response code returned, BlobStorageException is thrown. 

2. BlobStorageException will not be thrown for every exception. There will be cases where RuntimeException (or any other exceptions) are thrown due to other reasons. For example, here:
[https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobContainerClient.java#L255](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobContainerClient.java#L255)
We've specified in the docs that a RuntimeException will be thrown if the timeout duration completes before a response is returned. 

Let me know if this answers your question, and if you have any additional questions!

**Comment by zhtang-li** [comment]
@ibrahimrabab thank you for the detailed explanations and examples. It is very helpful.
Correct me if my understanding is wrong: for blob operations (append, exist, download, etc.), since essentially they are just HTTP calls, BlobStorageException should be expected if the response code is not expected plus other runtime exceptions for other cases, e.g. timeout. 
therefore, in practice, it is always recommended to try and catch the BlobStorageException and other runtime exceptions in the case of failures.

**Comment by ibrahimrabab** [comment]
@zhtang-li 
Yes, for blob operations, BlobStorageException should be expected if the response code is not the expected value. If you run into any other exceptions such as RuntimeException, those won't be related to the service response, those will occur due to other reasons (usually the javadocs for each method will list what exception will be thrown based on the situation). 

Yes, you can definitely wrap the BlobStorageException in a try catch clause to catch any service-related failures.

**Comment by ibrahimrabab** [comment]
If this answers your question, I will be closing this issue now. But please feel free to reach out with any additional questions! :)

**Comment by zhtang-li** [comment]
thank you
