### ISSUE TITLE
[BUG] Spring boot 3.0.0 spring.factories has been removed

### ISSUE THREAD

**Issue by ivan909020** [Azure/azure-sdk-for-java#32679]
**Describe the bug**
Spring Boot 3.0.0 "spring.factories" has been removed. The automatic import of autoconfigurations is broken.

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/spring-cloud-azure-autoconfigure/src/main/resources/META-INF/spring.factories

**To Reproduce**
Run the app with Spring Boot 3.0.0 and autoconfiguration will not work. Only explicit import using @ImportAutoConfiguration is working.

**Expected behavior**
The app will run without explicit @ImportAutoConfiguration({ list of autoconfiguration classes }).

**Comment by moarychan** [comment]
Hi @ivan909020  thanks for reaching out!

The autoconfiguration registration has been changed since Spring Boot 3, you can find this change in the branch `feature/spring-boot-3` https://github.com/Azure/azure-sdk-for-java/blob/feature/spring-boot-3/sdk/spring/spring-cloud-azure-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports. We have released the latest version [6.0.0-beta.4](https://mvnrepository.com/artifact/com.azure.spring/spring-cloud-azure-dependencies/6.0.0-beta.4) for Spring Boot 3.0.0-RC2 and Spring Cloud 2022.0.0-RC2, you are welcome to have a try!
