### ISSUE TITLE
[BUG]After GlobalThroughputControlConfig enable getting error " The control container must have partition key equal to /groupId"

### ISSUE THREAD

**Issue by brijeshsinghNuance** [Azure/azure-sdk-for-java#32791]
**Describe the bug**
GlobalThroughputControlConfig enabling is not working

***Exception or Stack Trace***
error.type":"java.lang.IllegalArgumentException","error.message":"The control container must have partition key equal to /groupId","error.stack_trace":"java.lang.IllegalArgumentException: The control container must have partition key equal to /groupId\n\tat com.azure.cosmos.implementation.throughputControl.controller.group.global.ThroughputControlContainerManager.lambda$validateControlContainer$12(ThroughputControlContainerManager.java:213)\n\tSuppressed: The stacktrace has been enhanced by Reactor, refer to additional information below: \nError has been observed at the following site

**Comment by FabianMeiswinkel** [comment]
This is expected behavior (but I ack that docs should be improved). It is described here: https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/throughput-control-spark#how-does-throughput-control-work

the PK of the container used for throughput control metadata needs to have "/groupId" set as partition key - and TTL needs to be enabled (On (no default)) - https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/how-to-time-to-live?tabs=dotnet-sdk-v3
