### ISSUE TITLE
Do we have stable released version jar for azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar library

### ISSUE THREAD

**Issue by ThirupathiMogulla** [Azure/azure-sdk-for-java#33027]
**Query/Question**
do we have a stable released version jar for beta jar "azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar".

***Why is this not a Bug or a feature Request?***
we are using Kafka Producer and Kafka Consumer to send and read the messages to and from azure event hubs.
as part of this we are serializing the messages using KafkaAvroSerializer and KafkaAvroDeserializer. when we wanted to use the stable version of jar instead of beta version "azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar" we didnt find in Maven repo so we have used beta jars "azure-data-schemaregistry-apacheavro-1.0.0-beta.11.jar" and "azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar". 
Explained the issue in details in attached document "2301130030001331.docx".
please let me know the stable released version jars for these jars.
samples used for our project:
https://github.com/Azure/azure-schema-registry-for-kafka/tree/master/java/avro/samples/kafka-producer
https://github.com/Azure/azure-schema-registry-for-kafka/tree/master/java/avro/samples/kafka-consumer 

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - IDE: eclipse
 - Library/Libraries: azure-core-1.33.0, azure-data-schemaregistry-1.1.1, azure-identity-1.5.4, kafka-clients-3.3.1, azure-data-schemaregistry-apacheavro-1.0.0-beta.11.jar and azure-schemaregistry-kafka-avro-1.0.0-beta.7.jar.
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- Query Added
- Setup information Added

**Comment by ThirupathiMogulla** [comment]
explained the issue in detail in the attached document.
[2301130030001331.docx](https://github.com/Azure/azure-sdk-for-java/files/10435561/2301130030001331.docx)

**Comment by joshfree** [comment]
@conniey @srnagar please take a look

**Comment by conniey** [comment]
@hmlam Do you know about this package? We've never worked on this.

**Comment by jitendriya-dash-cg** [comment]
Hi Team,

Are there any tentative timelines to fix this issue  ? 

Will these beta libraries be later published to a stable release and supported or, are there any plans to drop support for these libraries and declare them as deprecated ?

We need to understand these details asap to plan for our ongoing project using Java SDK libraries with MS Azure Event Hub.

Thanks a lot in advance for your feedback and support.

Rgs,

Jiten

**Comment by nickghardwick** [comment]
The service has kept this package in beta using the older beta SDK library to retain backwards compatibility with regards to how the reference to the schema stored in the registered was used. However, we are ready to move past this and send out a generally available version of the azure-schemaregistry-kafka-avro package. This should be complete by early next week.

**Comment by jitendriya-dash-cg** [comment]
Thanks Nick for an update on this topic which is helpful for us as we are already near to the User Acceptance Testing phase of our project by using the documented processes of Serialization / De-serialization using KafkaAvroSerializer / KafkaAvroDeserializer with the available beta libraries. We wanted to have this clarification asap that, will the same libraries be supported and promoted to a stable GA release in future so that we can continue using the same library for the time being.

Also would you also be adding / fixing the necessary missing classes / methods to "azure-data-schemaregistry-apacheavro-1.1.1.jar" (similar to  "azure-data-schemaregistry-apacheavro-1.0.0-beta.11.jar") to make it compatible with the "azure-schemaregistry-kafka-avro" for the KafkaAvroSerializer / KafkaAvroDeserializer API to work the same way as the combination of the beta libraries (as highlighted in the attached document) ?

Thanks a lot in advance for your feedback into this topic.

Rgs,

Jiten

**Comment by nickghardwick** [comment]
The updates to `azure-schemaregistry-for-kafka` the latest versions of both `azure-data-schemaregistry` and `azure-data-schemaregistry-apacheavro` packages are under review and should be checked in later this week barring any unforeseen setbacks.

**Comment by Tyngstast** [comment]
@nickghardwick awesome work! When do you think you could get `azure-schemaregistry-kafka-avro:1.1.0-beta.1` published to https://mvnrepository.com/? I'm sort of blocked by a bug in `1.0.0-beta.9` and need the new version where my issue is solved.

**Comment by jitendriya-dash-cg** [comment]
Hi Nick / Team,

Is there any update on releasing the stable jar for these 2 libraries, with the support of KafkaAvroSerializer / KafkaAvroDeserializer ?

We are kind of blocked at the moment and awaiting for the stable released libraries to proceed further in our implementation project.

Thanks a lot in advance for keeping us updated on the same.

Rgs,

Jiten

**Comment by nickghardwick** [comment]
The new library will go into our release process today; best case scenario it will be available in a couple of days depending on how soon it reaches the Maven repository, but I will update this discussion when it is fully released.

**Comment by jitendriya-dash-cg** [comment]
Thanks Nick. In the case that, the jars get released today, can you please share the jars offline to us rather than waiting for the maven repository for them to get published ? In that case we can fast track the validation of the libraries and proceed with the implementations on our side.

**Comment by nickghardwick** [comment]
New library is now available on Maven
https://central.sonatype.com/artifact/com.microsoft.azure/azure-schemaregistry-kafka-avro/1.1.0-beta.1

**Comment by jitendriya-dash-cg** [comment]
Thanks Nick for the update. As the name still contains beta, just wanted to check if this is going to be the final version or are there any further changes expected in the final versions that will be released in future ?

Also we are now validating the same at our end to understand if it works fine without any changes on our side.

**Comment by nickghardwick** [comment]
We are still working with the SDK teams to finalize the timeline of a non-beta version of the Java package, but it looks like the release is scheduled to be completed around mid-April. Just for reference, the reason why this package is still in beta is because this library relies on a shared package that supports beta features, which means we have to call this package beta as well. As far as Avro support goes, all of that functionality is in GA, just the package dependencies are not all out of beta. Will continue to update this issue with more info as I receive it.

**Comment by LoCortes** [comment]
Good morning,
please @nickghardwick could you confirm the mid-April schedule is still on plan?
Thank you!

**Comment by jitendriya-dash-cg** [comment]
Hi Nick / Team, is there an update on this activity and are the libraries already released from Beta as planned ? 

Thanks a lot in advance for your quick feedback and support.

Rgs,

Jiten

**Comment by nickghardwick** [comment]
Because the Schema Registry Client from the SDK team that this package relies on is still in beta, we are continuing to designate this package as beta as well. However, as was previously stated, all implantations regarding the use of Avro schemas are in GA, meaning [this package](https://mvnrepository.com/artifact/com.microsoft.azure/azure-schemaregistry-kafka-avro) can be treated as a GA release for the Avro serialization and deserialization it is used for.

**Comment by jitendriya-dash-cg** [comment]
Hi Nick,
Thanks for your response. We are getting some setbacks from our customers because of the beta release of the libraries and its usage even though they are because of some other dependent libraries being in Beta phase. Do you know when is the planned date for those dependent libraries to be released first, so that the Avro serialization / de-serialization packages can be released as well ?

Thanks a lot in advance for all your feedback and support.

Rgs,

Jiten

**Comment by nickghardwick** [comment]
After some discussion, we were able to move the dependencies to stable releases while still providing GA support for Avro scenarios. This is not reflected in the latest stable release of this package, which can be found here: https://central.sonatype.com/artifact/com.microsoft.azure/azure-schemaregistry-kafka-avro/1.1.1
