### ISSUE TITLE
Link to external API from generated JavaDoc

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#3303]
This is a low-priority issue. Presently, our generated JavaDoc is not as user-friendly as it can be, as it does not link to external JavaDoc sites for relevant API. For example, [KeyVaultClientBase](https://azuresdkartifacts.blob.core.windows.net/azure-sdk-for-java/staging/apidocs/com/microsoft/azure/keyvault/KeyVaultClientBase.html) has methods specified that have return types of `rx.Observable<BackupCertificateResult>`, where `BackupCertificateResult` links to our API, but `rx.Observable` does not link to, e.g. http://reactivex.io/RxJava/javadoc/index.html?rx/Observable.html

JavaDoc / Maven [supports external links](http://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html#links) (with more [documentation here](https://maven.apache.org/plugins/maven-javadoc-plugin/examples/links-configuration.html)) - you can see documentation on how to do it. We should integrate this into our Maven build so that our external links are properly handled. We should link to at least the following API doc sites:

 * https://docs.oracle.com/javase/8/docs/api/
 * https://projectreactor.io/docs/core/release/api/
 * https://netty.io/4.1/api/
 * http://reactivex.io/RxJava/javadoc/

**Comment by srnagar** [comment]
Fixed in PR https://github.com/Azure/azure-sdk-for-java/pull/3858

**Comment by srnagar** [comment]
Due to another issue #3874 , the fix for this issue had to be rolled back. The latest version of `maven-javadoc-plugin` (3.1.0) doesn't generate aggregate javadocs correctly - [see stackoverflow] (https://stackoverflow.com/questions/56571385/maven-javadoc-plugin-3-1-0-not-generating-aggregate-javadocs) and jira [599](https://issues.apache.org/jira/browse/MJAVADOC-599) and [608](https://issues.apache.org/jira/browse/MJAVADOC-608)

So, we had to rollback to 3.0.1 version of this plugin for now - #3893

**Comment by srnagar** [comment]
Fixed in #5181
