### ISSUE TITLE
Spark-Cosmos Connector custom query does not return valid columns when result is empty

### ISSUE THREAD

**Issue by danzafar** [Azure/azure-sdk-for-java#33085]
Please see this unexpected behavior:

```
val CosmosRXs = spark.read
  .format("cosmos.oltp")
  .options(SparkCosmosConfig + ("spark.cosmos.read.customQuery" -> "SELECT c.id, c.partition_id FROM c where c.id = 'thisDefDontExist'") )
  .load()

CosmosRXs.collect()
```
results in:
```
Array[org.apache.spark.sql.Row] = Array()
```

But really it should return an empty dataframe with those two columns in the schema.

**Comment by kushagraThapar** [comment]
@FabianMeiswinkel  please take a look at this, thanks!

**Comment by TheovanKraay** [comment]
review for next semester planning.

**Comment by kushagraThapar** [comment]
@xinlian12 can you please take a look at this, thanks!

**Comment by FabianMeiswinkel** [comment]
This is expected behavior - schema inference works based off of the documents being returned. In case of possibility that the customQuery does not return any records, the following ways can be used to address it:
- Use a different query for schema inferrence (to get a sample set of documents) - config "spark.cosmos.read.inferSchema.query" (for example SELECT TOP 1 c.id, c.partition_id FROM c ) - https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3_2-12/docs/configuration-reference.md#schema-inference-config can be used.  
- User a manual schema by passing in the StructType to be used - spark.read.format("cosmos.oltp").schema(myCustomStructType)
