### ISSUE TITLE
Why is there a difference in the azure-sdk-bom version in maven central and github repo

### ISSUE THREAD

**Issue by tralians94** [Azure/azure-sdk-for-java#33149]
**Query/Question**
In maven central, azure-sdk-bom is at version 1.2.8 but in github this is still at 1.2.7. How does this work ? 

Maven central link : https://mvnrepository.com/artifact/com.azure/azure-sdk-bom/1.2.8
Github link: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/boms/azure-sdk-bom/pom.xml#L5

It´s confusing why maven has a newer version when github is still at 1.2.7. We are using 1.2.8 currently and expecting 1.2.9 with all the latest dependency updates in azure libraries but noticed that github is still at 1.2.7 so would it mean that next version would be 1.2.8. Wouldn´t that conflict with the existing version of 1.2.8 in maven central. Could someone please elaborate how this is supposed to work ?

It would also be nice to know when the next bom update would be released. We are looking for getting the latest azure identity dependency version (1.7.3) in the bom. Would it possible to give an estimate on when this would be available ? Currently we override azure identity version which causes dependency convergence which we would like to get rid off.

***Why is this not a Bug or a feature Request?***
This looks like it could be a bug in the way versioning was handled but I am not sure of the history on what happened here. This is more of a query since its more relevant to know when the newest version of azure bom would be released which should solve all the issues

**Comment by alzimmermsft** [comment]
Thank you for reporting this @tralians94, it looks like we never updated the version there after releasing version `1.2.8`. @vcolin7 could you make sure the version gets updated?

**Comment by tralians94** [comment]
Thank you for the update @alzimmermsft . Do you know when version 1.2.9 is planned to be released?  I was expecting something this month since its a monthly release cycle. Currently we use azure identity version 1.7.3 which is not yet available in bom and we would like to have it taken from the bom to avoid dependency convergence issues

**Comment by alzimmermsft** [comment]
@vcolin7 would know better when the next release will be, but it should be within the next few days. We're still waiting for a few of the libraries included in the BOM to be updated to the latest versions of Azure Core and the other common dependencies.

**Comment by vcolin7** [comment]
@tralians94 like @alzimmermsft said, the BOM releases usually a bit after the 20th of every month, we are actually working on releasing version `1.2.9` and the process should be done by early tomorrow. As for the version mismatch with `main`, it looks like I forgot to merge the changes from our release branch from last time, thanks for bringing that to my attention.

So, to answer the question in the title, the versions are different because we handle the release from a separate branch and forgot to merge the changes from the latest release onto `main` this time around.

I will be closing this issue for the time being but will let you know once the BOM is available here @tralians94 :)

**Comment by vcolin7** [comment]
[The latest version](https://repo1.maven.org/maven2/com/azure/azure-sdk-bom/1.2.9/) of the Azure SDK BOM has been released @tralians94 :)
