### ISSUE TITLE
How to specify sessionId when using SCS servicebus-binder

### ISSUE THREAD

**Issue by rodrigolopes** [Azure/azure-sdk-for-java#33214]
I'm using spring-cloud-azure-stream-binder-servicebus version 5.0.0 with spring-boot 3.0.1 and spring cloud 2022.0.1

I have a consumer where session-enabled=true and I want it to consume messages only from one specific sessionId. 
Is there a way to accomplish that, without consuming the message and then not complete the message if the sessionId is not the expected?

**Comment by fangjian0423** [comment]
@yiliuTo could you pls help to handle this issue?

**Comment by rodrigolopes** [comment]
Hi @yiliuTo , thank you for your response.
My situation is the following: I have 2 applications consuming from the same queue. Each application should consume messages that have a specific sessionId, so, messages shouldn't be discarded. Every message HAS a sesionId.
I know that ideally I should use a topic with different subscriptions; but I don't have influence to change the infrastructure. 

So, I'd like to have something similar to ```ServiceBusSessionReceiverAsyncClient.acceptSession("sessionId")```, but using SCS binder

**Comment by yiliuTo** [comment]
Hi @rodrigolopes , thanks for the detailed explanation. And for your situation, I am afraid that the SCS service bus binder cannot satisfy. 

This is due to that the SCS binder uses `ServiceBusProcessorClient`. It is designed to receive messages from a certain number of sessions, but cannot be used to specify which session(s) to receive from, referring [here](https://github.com/Azure/azure-sdk-for-java/blob/408ff0ff5e2f483b74ee59a20dc268d76fc14816/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusClientBuilder.java#L995). And the above solution may cause a dead-lock for the session lock when you are using in a multiple-application situation, even though it can be further configured to not discard messages.

**Comment by rodrigolopes** [comment]
Thank you again @yiliuTo 
I will re-think my solution.
