### ISSUE TITLE
formatting layout

### ISSUE THREAD

**Issue by survivant** [Azure/azure-sdk-for-java#33269]
the formatting is not correct

<img width="761" alt="image" src="https://user-images.githubusercontent.com/191879/216056708-641957bf-e7a1-4a9d-974d-1a034fadc387.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 05c6db3d-e908-f0bb-c259-501b8fd5921c
* Version Independent ID: 1758e42e-e833-492b-19d6-b2cff9f32293
* Content: [Azure SDK Maven Build Tool](https://learn.microsoft.com/en-us/java/api/overview/azure/sdk-build-tool-readme?view=azure-java-preview)
* Content Source: [docs-ref-services/preview/sdk-build-tool-readme.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/preview/sdk-build-tool-readme.md)
* Service: **tools**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @joshfree
* Microsoft Alias: **jfree**

**Comment by alzimmermsft** [comment]
Thank you for reporting this @survivant.

@srnagar @JonathanGiles the formatting of the README table appears no different than other README tables used in other SDKs, so I'm not sure why this one renders incorrectly in Docs.

**Comment by JonathanGiles** [comment]
Thanks for the report @survivant. I'm not sure why this page exists - the proper location for this content is [here](https://learn.microsoft.com/en-us/azure/developer/java/sdk/get-started-maven#use-the-azure-sdk-for-java-build-tool). We should look into getting this page removed - I'll try to chase this up.

**Comment by danieljurek** [comment]
A couple things to change here: 

* I'll delete the markdown files from the docs repo and set up a redirect so that future visits to that URL land in the correct place. 
* @srnagar @jonathangiles, please review the artifacts in [`ci.yml` for `sdk/tools`](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/tools/ci.yml) and ensure that `skipPublishDocMs: true` and `skipPublishDocGithubIo: true` are added for artifacts that do not need to be published in this way. There may be other artifacts in the Java SDK repo that need to have these added as well.

**Comment by danieljurek** [comment]
PR to remove from our docs and redirect to correct location: https://github.com/Azure/azure-docs-sdk-java/pull/2405

**Comment by srnagar** [comment]
@danieljurek I'll create a PR to get skip publishing these docs.

**Comment by srnagar** [comment]
@danieljurek - Here's the PR to skip publishing docs - https://github.com/Azure/azure-sdk-for-java/pull/33374

**Comment by JonathanGiles** [comment]
Thanks @danieljurek and @srnagar - I will now mark this issue resolved.
