### ISSUE TITLE
Azure Cosmos Emulator - Can i use spark3 connector for mongo db api or sql api

### ISSUE THREAD

**Issue by WillianMattosRibeiro** [Azure/azure-sdk-for-java#33317]
Tried to read data with the connector from docker container with a cosmos db emulator whitout success. Is it possible?

![image](https://user-images.githubusercontent.com/17055626/216627685-f82a6dbb-cbda-4af5-b48d-bfb1295f1774.png)

**Comment by TheovanKraay** [comment]
First, this connector will only work for core NoSQL (SQL API). Also, in order to connect to emulator with any Java based connector, you would need to export certificates, did you do this already? https://learn.microsoft.com/en-us/azure/cosmos-db/local-emulator-export-ssl-certificates. If already done, please post comment with more information about the error.

**Comment by TheovanKraay** [comment]
I mentioned the docs above. The section to use certificate with java apps is here: https://learn.microsoft.com/en-us/azure/cosmos-db/local-emulator-export-ssl-certificates#use-the-certificate-with-java-apps. This would be required for Spark Connector because it depends on Java SDK. You are right that we do not have any documentation specifically on local docker setup with Spark and emulator, but all of the instructions would be the same, apart from exporting certs, and of course installing the Spark connector in your local Spark environment.

**Comment by WillianMattosRibeiro** [comment]
I’ve tried this way:

pyspark --packages com.azure.cosmos.spark:azure-cosmos-spark_3-2_2-12:4.15.0 --driver-java-options "-Djavax.net.ssl.trustStore=certificados/key.crt -Djavax.net.ssl.trustStorePassword='C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=='"

from pyspark.sql.functions import lit
cosmosEndpoint = "https://localhost:8081/"
cosmosMasterKey = "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="
cosmosDatabaseName = "SampleDB"
cosmosContainerName = "Persons"

cfg = {
    "spark.cosmos.accountEndpoint": cosmosEndpoint,
    "spark.cosmos.accountKey": cosmosMasterKey,
    "spark.cosmos.database": cosmosDatabaseName,
    "spark.cosmos.container": cosmosContainerName,
}

spark.conf.set("spark.sql.catalog.cosmosCatalog", "com.azure.cosmos.spark.CosmosCatalog")
spark.conf.set(
    "spark.sql.catalog.cosmosCatalog.spark.cosmos.accountEndpoint", cosmosEndpoint)
spark.conf.set(
    "spark.sql.catalog.cosmosCatalog.spark.cosmos.accountKey", cosmosMasterKey)

query = "select * from cosmosCatalog.{}.{};".format(
    cosmosDatabaseName, cosmosContainerName)

df_people = spark.sql(query)
df_people.show()

But got this error:

***@***.***

am i doing something wrong or the conector just dont have suport for this type of connection? Can you send me a sample?


De: Theo van Kraay ***@***.***>
Enviada em: segunda-feira, 6 de fevereiro de 2023 15:49
Para: Azure/azure-sdk-for-java ***@***.***>
Cc: WillianMattosRibeiro ***@***.***>; Author ***@***.***>
Assunto: Re: [Azure/azure-sdk-for-java] Azure Cosmos Emulator - Can i use spark3 connector for mongo db api or sql api (Issue #33317)


I mentioned the docs above. The section to use certificate with java apps is here: https://learn.microsoft.com/en-us/azure/cosmos-db/local-emulator-export-ssl-certificates#use-the-certificate-with-java-apps. This would be required for Spark Connector because it depends on Java SDK. You are right that we do not have any documentation specifically on local docker setup with Spark and emulator, but all of the instructions would be the same, apart from exporting certs, and of course installing the Spark connector in your local Spark environment.

**Comment by TheovanKraay** [comment]
No error given above and guidance already given. Closing due to age of issue. If this is critical please open a support case.
