### ISSUE TITLE
[FEATURE REQ] Improve Cadl SDK automation from spec repo

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#33346]
Relates to https://github.com/Azure/azure-sdk-for-java/issues/33263

1. Add common Cadl dependencies to [eng/emitter-package.json](https://github.com/Azure/azure-sdk-for-java/blob/main/eng/emitter-package.json) (in addition to cadl-java), ref to the changes in [PR](https://github.com/Azure/azure-sdk-for-java/pull/33325) for the list and version of common dependencies
2. When running the automation, directly copy `eng/emitter-package.json` to working directory, as `package.json`
3. In script, after copy, call `npm install` to install the dependencies in `package.json`

Step (1) is also helpful for automation/script from SDK repo, as most Cadl source depends on `cadl-autorest`, which is not in dependencies of `cadl-java`. Without these dependencies, `cadl compile` will fail (similar to Java when code uses a package but POM doesn't specify it).

Step (2), the `package.json`, root or not, from spec repo is never used. Is this expected?

@haolingdong-msft @srnagar

**Comment by haolingdong-msft** [comment]
I guess 'the package.json, root or not, from spec repo is never used.' is expected. Micheal's [doc](https://github.com/Azure/azure-sdk-tools/blob/main/doc/common/Cadl-Project-Scripts.md#emitter-packagejson
) also mentioned that:
_emitter-package.json replaces the package.json checked into the spec repo and allows each language to fix the version of their emitter to be the same for all packages in their repo._

I also prefer we use our emitter-package.json.  Because service team's package.json contains more dependencies then we need, and they may also have private dependencies that we don't have permission to install. ADP's package.json is an example, they have private dependencies.
