### ISSUE TITLE
[FEATURE REQ] Allow to define consistencyLevel on azure-cosmos-spark

### ISSUE THREAD

**Issue by mangonc** [Azure/azure-sdk-for-java#33420]
The azure-cosmos-spark lib doesn't allow us to define the consistency level on client side.

We can only disactivate Eventual consistency and we are forced to use default Account consistency level on server side.
spark.cosmos.read.forceEventualConsistency=false 

The following lib for example allow us to define the consistency level:
https://github.com/Azure/azure-cosmosdb-spark

Will it be possible to provide the following option instead of "forceEventualConsistency":
spark.cosmos.read.consistencyLevel=[Eventual | Session | ... | Strong]

**Comment by FabianMeiswinkel** [comment]
The consistency level of write operations is always decided based on the account consistency level. For reads/queries the consistency level can be reduced - Spark by default will use eventual simply because most batch job running in Spark would not need stronger consistency - but it is possible to fallback as you described above to the stronger account consistency level.
Can you explain in which scenario you would prefer another consistency level setting than eventual or the one of the account. The only possible combination I see would be on a strong/bounded staleness account to reduce consistency for reads/queries to Session - but that effectively is the same as eventual in Spark anyway because each Spark worker would have its own SessionContainer.

**Comment by TheovanKraay** [comment]
Closing dues to age, and reason for existing configuration options has been explained, and there are no other configuration options that could be added that would give practical benefit when used in Spark.
