### ISSUE TITLE
CVE-2022-40152 - High vulnerability issue with jackson-dataformat-xml

### ISSUE THREAD

**Issue by ianwilk20** [Azure/azure-sdk-for-java#33546]
**Query/Question**
Your project contains a package with a high vulnerability according to NIST's national vulnerability database. Please update com.fasterxml.jackson.dataformat:jackson-dataformat-xml to the latest version ([2.14.2](https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-xml/2.14.2))

***Why is this not a Bug or a feature Request?***
It's not a bug because your project still functions properly. It's not a feature request because it is a vulnerability in your code.
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by ianwilk20** [comment]
Hello @alzimmermsft,

That's correct, `woodstox-core` has vulnerabilities in versions <6.4.0. 

From my understanding, the latest `azure-core` maven package version is 1.36.0. The latest same `azure-core` version uses `jackson-dataformat-xml` 2.13.4, which uses `woodstox-core` 6.3.1. By updating the package `azure-core` uses for `jackson-dataformat-xml` from 2.13.4 to 2.14.2, `woodstox-core` will be updated to 6.4.0 as well. Please let me know if there's something I've missed in my understanding of this as it is my first time reporting vulnerabilities/package updates.

**Comment by alzimmermsft** [comment]
Yeah, that's true that `jackson-dataformat-xml` uses `woodstox-core` `6.3.1` which is affected by this CVE but we've added an explicit dependency on `6.4.0`, which has been in-place since `azure-core` `1.34.0`.

https://mvnrepository.com/artifact/com.azure/azure-core/1.34.0

We're currently holding off on updating to Jackson 2.14.x but I see that `jackson-dataformat-xml` `2.13.5` has a dependency on `woodstox-core` `6.4.0`, so I'll update to that version and remove the dependency on `woodstox-core`.

**Comment by ianwilk20** [comment]
Thank you, @alzimmermsft!
