### ISSUE TITLE
spark.cosmos.partitioning.feedRangeFilter values

### ISSUE THREAD

**Issue by roadruuner** [Azure/azure-sdk-for-java#33584]
Using libraryDependencies += "com.azure.cosmos.spark" % "azure-cosmos-spark_3-1_2-12" % "4.16.0"

Given I have partition ids /id = test123, testabc, xyx
I need to call individually based on partition ids to reduce RU's.

What should feed_range_filter be set to.
example I have come across.
df = (
        spark.readStream.format("cosmos.oltp.changeFeed")
        .option("spark.cosmos.accountEndpoint", db_uri)
        .option("spark.cosmos.accountKey", db_key)
        .option("spark.cosmos.database", "DbName")
        .option("spark.cosmos.container", "Container")
        .option("spark.cosmos.partitioning.feedRangeFilter", feed_range_filter)
        .option("spark.cosmos.read.inferSchema.enabled", False)
        .load()
    )
   Thanks

**Comment by FabianMeiswinkel** [comment]
See how to get the feedRangeFilter here: https://github.com/Azure/azure-sdk-for-java/blob/bc5ee7545bd1ee7d1202d840ce5a6f554232ede3/sdk/cosmos/azure-cosmos-spark_3_2-12/src/test/scala/com/azure/cosmos/spark/SparkE2EChangeFeedITest.scala#L354-L373

This doc also shows how to get the Partition Key definition programmatically (instead of the hard-coding in the unit test above)
https://github.com/Azure/azure-sdk-for-java/blob/bc5ee7545bd1ee7d1202d840ce5a6f554232ede3/sdk/cosmos/azure-cosmos-spark_3_2-12/src/test/scala/com/azure/cosmos/spark/SparkE2EChangeFeedITest.scala#L354-L373

**Comment by roadruuner** [comment]
Thanks for the response.

Given I have partition ids /id = test123, testabc, xyz, etc
What value do I assign to lastId for below call.
 val dummyDf = spark.sql(s"SELECT GetFeedRangeForPartitionKey('$pkDefinition', '$lastId')") 
If I set lastId = 'test123', I only get the single record for 'test123'.

Thanks
