### ISSUE TITLE
[BUG] Azure spring boot java SDK for key-vault will return http 401 code then return http 200 code

### ISSUE THREAD

**Issue by yansyunchen** [Azure/azure-sdk-for-java#34259]
Using the below SDK but will see the http 401 code response then a http 200 code response. The request is successful in the end and can get the key-vault value back but it's a little weird to see this symptom:
**SDK :**
![image](https://user-images.githubusercontent.com/15064864/228707465-5918f4e9-1b32-4074-ab42-e25936b815c3.png)

**Log in the application insight:**
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/15064864/228707403-50c2c936-b463-4891-b65f-d9f8afae4303.png">

**Ask:**
I did some research and found a similar issue on the GitHub page (https://github.com/Azure/azure-sdk-for-java/issues/18270), but not see the solution in the end and the issue is still open. Any suggestion would be helpful, thanks.

**Comment by nagarajA124** [comment]
Hi Team,

Could you please expedite this request asap as we are in production and client is asking for an update daily

Thanks,
Naga

**Comment by chenrujun** [comment]
Hi, @yansyunchen , @nagarajA124 
Thanks for reaching out.

1. I didn't reproduce the problem yet. Here is my guessing: 
    - 1.1. In the first time, the java SDK try to access Key Vault endpoint. But failed. The response code (401) means the client is not authorized.
    - 1.2. In the second time, the java SDK authenticate by some method like client-id and client-secret. This time it can access successfully. (Response code is 200). 
2. Which authenticate method are you using? `client-id and client-secret` or `managed-identity` ?
3. Since the app can get the value successfully at the end, why you still think it's urgent to solve this problem?

**Comment by nagarajA124** [comment]
TCS Confidential

Hi Team,

Please find my inline comments below.

Thanks,
Naga

Thanks,
Nagaraja Kumar B
Senior Enterprise Architect
Tata Consultancy Services
Phone: +1 847-867-8144
Mailto : ***@***.******@***.***>
***@***.***        ***@***.***

**Comment by chenrujun** [comment]
Hi, @nagarajA124 
Could you please share the exception logs?

**Comment by nagarajA124** [comment]
TCS Confidential

Hi Akash,

Please share the Keyvalut exception logs.

Thanks,
Naga

Thanks,
Nagaraja Kumar B
Senior Enterprise Architect
Tata Consultancy Services
Phone: +1 847-867-8144
Mailto : ***@***.******@***.***>
***@***.***        ***@***.***

**Comment by nagarajA124** [comment]
TCS Confidential

Hi Team,

Here is the information which we find out in AppInsights.

Using the below SDK but will see the http 401 code response then a http 200 code response. The request is successful in the end and can get the key-vault value back but it's a little weird to see this symptom:
SDK :
[image]<https://user-images.githubusercontent.com/15064864/228707465-5918f4e9-1b32-4074-ab42-e25936b815c3.png>
Log in the application insight:
[image]<https://user-images.githubusercontent.com/15064864/228707403-50c2c936-b463-4891-b65f-d9f8afae4303.png>


Thanks,
Nagaraja Kumar B
Senior Enterprise Architect
Tata Consultancy Services
Phone: +1 847-867-8144
Mailto : ***@***.******@***.***>
***@***.***        ***@***.***


From: NAGARAJA KUMAR BODDU
Sent: Wednesday, April 5, 2023 9:46 PM
To: Akash Sahoo ***@***.***>
Cc: Mention ***@***.***>; Azure/azure-sdk-for-java ***@***.***>; Azure/azure-sdk-for-java ***@***.***>
Subject: RE: [Azure/azure-sdk-for-java] [BUG] Azure spring boot java SDK for key-vault will return http 401 code then return http 200 code (Issue #34259)

Hi Akash,

Please share the Keyvalut exception logs.

Thanks,
Naga

Thanks,
Nagaraja Kumar B
Senior Enterprise Architect
Tata Consultancy Services
Phone: +1 847-867-8144
Mailto : ***@***.******@***.***>
***@***.***        ***@***.***

**Comment by chenrujun** [comment]
Hi, @yansyunchen , @nagarajA124 .
I'll try to reproduce this problem and give you feedback.

**Comment by backwind1233** [comment]
Hi @nagarajA124 
We have received your submission and will take it into consideration. We appreciate your input and will review this matter as soon as possible.
Please feel free to provide any additional information or context that you think may be helpful. We'll keep you updated on the progress of our review.
Thank you for your contribution to improving our project.

**Comment by nagarajA124** [comment]
Hello @Rujun ***@***.***> please provide an update as this issue looks stagnate for a long time now. Customer only needs to know if this is expected behavior and what would be the workaround.

Thank you,
Carolina

Carolina Guenther

Customer Success Account Manager
Office: (980) 776-1384
Manufacturing EOU | Charlotte, NC
***@***.******@***.***>


[Microsoft Logo]


From: NAGARAJA KUMAR BODDU ***@***.***>
Sent: Tuesday, April 11, 2023 9:32 PM
To: Azure/azure-sdk-for-java ***@***.***>; Azure/azure-sdk-for-java ***@***.***>
Cc: Mention ***@***.***>; Akash Sahoo ***@***.***>; Carolina Guenther ***@***.***>
Subject: [EXTERNAL] RE: [Azure/azure-sdk-for-java] [BUG] Azure spring boot java SDK for key-vault will return http 401 code then return http 200 code (Issue #34259)


TCS Confidential

Hi Team,

Do you have any updates? If yes, please let me know.

Thanks,
Naga

Thanks,
Nagaraja Kumar B
Senior Enterprise Architect
Tata Consultancy Services
Phone: +1 847-867-8144
Mailto : ***@***.******@***.***>
***@***.***        ***@***.***

**Comment by moarychan** [comment]
Update:
I can not reproduce this case. the 401 status is not the expected behavior.  @yansyunchen , could you try to upgrade to other versions or the latest version 4.7.0?

**Comment by nagarajA124** [comment]
TCS Confidential

Hi Team,

Thanks for the update.

We will check and update you soon whether its fine or not.

Thanks,
Naga

Thanks,
Nagaraja Kumar B
Senior Enterprise Architect
Tata Consultancy Services
Phone: +1 847-867-8144
Mailto : ***@***.******@***.***>
***@***.***        ***@***.***

**Comment by nagarajA124** [comment]
TCS Confidential

Hi Team,

Here is the update

We are using :

<dependency>
<groupId>com.azure.spring</groupId>
<artifactId>azure-spring-boot-starter-keyvault-secrets</artifactId>
<version>3.9.0</version>
</dependency>


and this SDK does not have a 4.7.0 version
***@***.***


We even tried a few other SDKs, and others are not working.(not detecting secrets)
***@***.***

We also tried the SDK that had 4.7.0.(not detecting secrets)
***@***.***



Thanks,
Nagaraja Kumar B
Senior Enterprise Architect
Tata Consultancy Services
Phone: +1 847-867-8144
Mailto : ***@***.******@***.***>
***@***.***        ***@***.***


From: NAGARAJA KUMAR BODDU
Sent: Friday, April 21, 2023 8:54 AM
To: 'Azure/azure-sdk-for-java' ***@***.***>; Azure/azure-sdk-for-java ***@***.***>
Cc: Mention ***@***.***>; Carolina Guenther ***@***.***>; Akash Sahoo ***@***.***>
Subject: RE: [Azure/azure-sdk-for-java] [BUG] Azure spring boot java SDK for key-vault will return http 401 code then return http 200 code (Issue #34259)

Hi Team,

Thanks for the update.

We will check and update you soon whether its fine or not.

Thanks,
Naga

Thanks,
Nagaraja Kumar B
Senior Enterprise Architect
Tata Consultancy Services
Phone: +1 847-867-8144
Mailto : ***@***.******@***.***>
***@***.***        ***@***.***

**Comment by moarychan** [comment]
Hi @nagarajA124 , the artifact id has been changed to [spring-cloud-azure-starter-keyvault](https://mvnrepository.com/artifact/com.azure.spring/spring-cloud-azure-starter-keyvault/4.7.0) since 4.0, please see the [guide](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault) for details. Thanks!

**Comment by nagarajA124** [comment]
Hi, @Carolina ***@***.***>.
Sorry for late response. I'm OOF since 2023-04-12 to 2023-07-02. For any further request about Spring Cloud Azure<http://aka.ms/spring-cloud-azure>, please send email to @Spring Cloud Azure ***@***.***>.


Regards
Rujun Chen
Developer of Spring Cloud Azure<http://aka.ms/spring-cloud-azure>
Location: Shanghai, China
Time Zone: UTC + 8

From: Carolina Guenther ***@***.***>
Sent: Friday, April 21, 2023 1:42 AM
To: NAGARAJA KUMAR BODDU ***@***.***>; Azure/azure-sdk-for-java ***@***.***>; Azure/azure-sdk-for-java ***@***.***>; Rujun Chen ***@***.***>; Josh Free ***@***.***>
Cc: Mention ***@***.***>; Akash Sahoo ***@***.***>
Subject: RE: [Azure/azure-sdk-for-java] [BUG] Azure spring boot java SDK for key-vault will return http 401 code then return http 200 code (Issue #34259)

Hello @Rujun ***@***.***> please provide an update as this issue looks stagnate for a long time now. Customer only needs to know if this is expected behavior and what would be the workaround.

Thank you,
Carolina

Carolina Guenther

Customer Success Account Manager
Office: (980) 776-1384
Manufacturing EOU | Charlotte, NC
***@***.******@***.***>


[Microsoft Logo]


From: NAGARAJA KUMAR BODDU ***@***.******@***.***>>
Sent: Tuesday, April 11, 2023 9:32 PM
To: Azure/azure-sdk-for-java ***@***.******@***.***>>; Azure/azure-sdk-for-java ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>; Akash Sahoo ***@***.******@***.***>>; Carolina Guenther ***@***.******@***.***>>
Subject: [EXTERNAL] RE: [Azure/azure-sdk-for-java] [BUG] Azure spring boot java SDK for key-vault will return http 401 code then return http 200 code (Issue #34259)


TCS Confidential

Hi Team,

Do you have any updates? If yes, please let me know.

Thanks,
Naga

Thanks,
Nagaraja Kumar B
Senior Enterprise Architect
Tata Consultancy Services
Phone: +1 847-867-8144
Mailto : ***@***.******@***.***>
***@***.***        ***@***.***

**Comment by moarychan** [comment]
This behavior is expected, please ignore the first 401 exception, see more from [Key Vault request and response Authentication](https://learn.microsoft.com/en-us/azure/key-vault/general/authentication-requests-and-responses#authentication), similar issues you can check https://github.com/Azure/azure-sdk-for-net/issues/4924
