### ISSUE TITLE
BlobClient doesn't expose a setExpiry() method

### ISSUE THREAD

**Issue by msamsonse** [Azure/azure-sdk-for-java#34674]
Our current requirements are to set a TTL on a blob and then have it automatically be deleted from the storage container.  While I was reviewing the azure-storage-blob  source code, I discovered the BlobsImpl.setExpiryAsync(containerName, blob, expiryOptions, timeout, requestId, expiresOn) method is already implemented. 

This method (or similar method) is not currently available on the BlobClient class.
Would it be possible to add a BlobClient.setExpiry() method that would eventually call into BlobsImpl.setExpiryAsync() ?

**Comment by ibrahimrabab** [comment]
Hi @msamsonse 
Looks like setExpiry() was never implemented for BlobClient and BlobAsyncClient even though it exists in the implementation class. I will work on getting this in soon. Thanks for bringing this up!

**Comment by ibrahimrabab** [comment]
Hi @msamsonse 
Following up on this. I did some further investigation and looks like in the documentation, it's specified that setting expiry time is only available on HNS accounts,
https://learn.microsoft.com/en-us/rest/api/storageservices/set-blob-expiry?tabs=azure-ad

You can do this using [DataLakeFileClient.scheduleDeletion()](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-file-datalake/src/main/java/com/azure/storage/file/datalake/DataLakeFileClient.java#L1511)

That's why we do not have a public API for setting expiry on the BlobClient, since it's only applicable for HNS accounts. You can use DataLakeFileClient, docs mention some remarks [here](https://learn.microsoft.com/en-us/rest/api/storageservices/set-blob-expiry?tabs=azure-ad#remarks)

Please let us know if this answers your question, apologies for the confusion.

**Comment by msamsonse** [comment]
Yes that answers my question.  Thanks for the quick response.
