### ISSUE TITLE
The ServiceBusProcessorClient stop waiting for message from Service Bus after stopping the client [FEATURE REQ]

### ISSUE THREAD

**Issue by prokoks121** [Azure/azure-sdk-for-java#34894]
I constantly need to create certain logic that will interrupt listening from the service bus because some external service is not working. And this is very quickly done by calling the `stop()` method. The problem arises if we do not have a single message on the Service Bus and we call the `stop()' method, the library will continue to wait for a new message and when a new message arrives on the Service Bus we will read it even though we said that we want to stop listening. The real problem arises if we have more workers (maxWorkerCounter), for example, let's say we have 4 workers, and our max delivery count on Service Bus is 3, that message will end up on DeadLetter. Why?
1. We have 4 workers and the max delivery count is 3
2. 1 message arrives on the Service Bus
3. The first worker will take that message and try to perform certain business logic and for some reason it fails, it sends an abandon message and we call the stop() method.
4. The message now has delivery 1. Although we said stop(), the second worker will take the message and do everything the same as the first, then the delivery increases to 2, the same thing happens for the third worker and the message ends on DeadLetter.

Why is this happening?
The current implementation of ServiceBusProcessorClient contains a variable isRunning that represents a Boolean value and when we call the stop() method, it sets the value to false by itself.
On the other hand, there is an implementation of the method `public void onNext(ServiceBusMessageContext serviceBusMessageContext)` in which messages from Service Bus are requested and which only at the end of the method checks the value of the isRunning field and, depending on the value, requests a new message or stops working.

It is necessary to create a logic that, when calling the stop() method, will terminate all requests for a message to the Service Bus (except for those who have already received the message) or provide a way for the message to be Abandoned without increasing the Delivery count of the same message.

**Comment by prokoks121** [comment]
Is there any progress on this topic? :)

**Comment by conniey** [comment]
Hey @prokoks121 ,
 
Apologies for the delay.  Thanks for reporting this.  We looked into the behaviour of `stop()` and found that the current implementation has issues that would require a bit of overhead to address correctly. We had prototyped a solution that would have an intermediate queue to manage the backpressure from `stop()` but it introduced a lot of complexity and performance concerns; consequently, we did not implement it because the normal use-case of the processor is to run this continuously rather than starting and stopping frequently.
 
To work with your scenario, you may have to increase the delivery count for your messages or manage each of these consumers yourself using ServiceBusReceiverAsyncClient, ServiceBusReceiverClient, ServiceBusSessionReceiverAsyncClient, or ServiceBusSessionReceiverClient.
