### ISSUE TITLE
Track Python exception hierarchy - make changes as necessary

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#3503]
The Python exception hierarchy that we are tracking is changing. We should track its movements and make equivalent changes, after consideration and discussion.

Here is the latest pull request that motivated this issue (and which should be reviewed): https://github.com/Azure/azure-sdk-for-python/pull/5020

**Comment by sima-zhu** [comment]
Leave a comment in python PR. 

Java web application exception: [1](https://docs.oracle.com/javaee/7/api/javax/ws/rs/WebApplicationException.html)

AWS core exception:[ v2](https://github.com/aws/aws-sdk-java-v2/tree/master/core/aws-core/src/main/java/software/amazon/awssdk/awscore/exception)

[v1.11](https://github.com/aws/aws-sdk-java/tree/master/aws-java-sdk-core/src/main/java/com/amazonaws)

**Comment by sima-zhu** [comment]
Conclusion:
1. We agreed the construction of simplifying the exception hierarchy.
2. Current design, all exceptions are using HTTP protocol by default (Except AzureException). Other protocol will name with prefix of protocol name. 
3. Current hierarchy:
```
AzureException (base one)
         - ServiceRequestException. (Error occur when attempt to connect with azure service)
         - ServiceReponseException. (Client failed to understand the response, no status code, connection timeout)
         - HttpResponseException (Http response with status code to understand the error)
                   - DecodeException 
                   - ResourceExistException
                   - ResourceNotFoundException
                   - ClientAuthenticationException
                   - ResourceModifiedException
                   - TooManyRedirectsException
```

**Comment by sima-zhu** [comment]
Justification of changing the following classes:
1. ReadTimeoutException: This one has the same functionality as ServiceResponseException. (Delete to keep hierarchy clean)
2. DecodeException one move to HttpResponseException (Originally under ServiceResponseException). Service response tend to catch exception without status code and the response format not quite right. 
Decode one tend to catch exception with status code, get the right response format which cannot parse or understand by client. 
One thing needs to discuss is what if I got the half of the response (e.g. network issue) with status code of 200. Which exception do I need to throw? Put into [issue ](https://github.com/Azure/azure-sdk-for-java/issues/3591)for further discussion.
3. ServerException deleted (status code of 5XX). It deleted because the client does not need to distinguish different server issue (501 or 503), they can just catch the base one HttpResponseException, and log details if they care. Another reason is it is independent one, so if the client actually needed, it does not take too much efforts to add it in.

**Comment by sima-zhu** [comment]
Code merged in, closed the issue
