### ISSUE TITLE
storage queue: receiveMessages(..).iterableByPage() does not return all queue items

### ISSUE THREAD

**Issue by aappddeevv** [Azure/azure-sdk-for-java#35064]
Unlike the python library where `by_page()` returns an iterable over pages of queue items, neither of the methods `iterableByPage()` nor `streamByPage()` return the full set of queue items when calling `queueClient.receiveMessages(...)`. Only the first page is ever returned so there is no way for the java client to iterate over all queue items using this API directly.

**Comment by aappddeevv** [comment]
Thanks. Bit of head scratcher.

**Comment by ibrahimrabab** [comment]
Hi @aappddeevv 
Thanks for reaching out! Can you clarify which API you are using? `getMessages()` is not part of `QueueClient`, it is part of the implementation class that users do not use. Are you using `receiveMessages()`?

**Comment by aappddeevv** [comment]
Apologies, I have a thin wrapper that I call getMessages, but yes, the `QueueClient.receiveMessages` is what I'm using. I just corrected the title and initial note.

**Comment by ibrahimrabab** [comment]
@aappddeevv 
The by_page iterable functionality for `receiveMessages` is only supported by Python. In Java, when you call `QueueClient.receiveMessages()`, the max number of messages returned is up to 32 messages. So only one page is returned with up to 32 messages, and if you want to receive more than 32, you will need to make the call again to receive another 32. The service by nature only allows dequeuing of up to 32 messages at a time, which is why if your queue has more than 32, it will only return up to 32 for that single PagedIterable object. 

Hope this helps! Let me know if you have any additional questions about this behavior. We do support `iterableByPage()` for other APIs such as `listQueues()`, but `receiveMessages()` does not support `iterableByPage()`.

**Comment by aappddeevv** [comment]
Got it. I'll increase the visibility parameter then just call the same method multiple times so I can access the queue and "see" each set of 32 sequentially with enough timing space.

Thanks!
