### ISSUE TITLE
Dependency on Telemetry is not mentioned

### ISSUE THREAD

**Issue by sijucm** [Azure/azure-sdk-for-java#35079]
When I try this it looks like it needs reference to some Telemetry library. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 009f13e3-83f0-8f58-4be1-ebb785e6a344
* Version Independent ID: 6c845f98-c6a3-d3cd-c0b7-23f6775ef5ad
* Content: [Azure Key Vault Secret client library for Java](https://learn.microsoft.com/en-us/java/api/overview/azure/security-keyvault-secrets-readme?view=azure-java-stable)
* Content Source: [docs-ref-services/latest/security-keyvault-secrets-readme.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/security-keyvault-secrets-readme.md)
* Service: **keyvault**
* GitHub Login: @vcolin7
* Microsoft Alias: **vicolina**

**Comment by vcolin7** [comment]
Hi @sijucm, I'm a little confused as to what you're trying to achieve, but I see the issue points to our "Getting Started" documentation for Key Vault. There is no mandatory telemetry or logging dependency for using our Key Vault libraries (or any library in the Azure SDK for that matter). What you might be seeing is a warning message from SLF4J about not having specified an implementation for logging:

```bash
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

If you see this, it means you will get the default implementation instead of one provided by you that you can customize. This won't impede the functioning of your application or the Key Vault libraries.

If you want to provide an SLF4J implementation and further customize it, you can follow these instructions:
- https://learn.microsoft.com/azure/developer/java/sdk/logging-overview

**Comment by joshfree** [comment]
Closing this old issue which has been replied to by @vcolin7.
