### ISSUE TITLE
[BUG] validation can be ignored by adding values to Map obtained from TableEntity.getProperties()

### ISSUE THREAD

**Issue by taisuke-fujimoto** [Azure/azure-sdk-for-java#35156]
**Describe the bug**
I know validateProperty() is called if I add a value with addProperty() / setProperties().
But it seems that modifying the Map obtained by getProperties() does not call validateProperty().

**To Reproduce**
example code:
```kotlin
// kotlin
val entity = TableEntity("partition", "row")
entity.properties["Timestamp"] = "error"
```

**Expected behavior**
This code should throw IllegalArgumentException.

**Setup (please complete the following information):**
 - Library/Libraries: com.azure:azure-data-tables:12.3.11
 - Java version: 17 

**Additional context**
We are trying to add property to TableEntity using delegate property in kotlin.
So, if possible, please keep "you can change properties of TableEntity by changing getProperties()"
```kotlin
class Adapter(source: MutableMap<String, Any>) {
    var name: String by source
}

Adapter(TableEntity(xxx).properties).apply {
    name = "name"
}
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by jairmyree** [comment]
@taisuke-fujimoto I will follow up on this shortly.

**Comment by jairmyree** [comment]
Hello @taisuke-fujimoto,

Here's the class-level documentation for `TableEntity`:

_"An entity within a table. A TableEntity can be used directly when interacting with the Tables service, with methods on the com.azure.data.tables.TableClient and com.azure.data.tables.TableAsyncClient classes that accept and return TableEntity instances. After creating an instance, call the addProperty(String, Object) or setProperties(Map) methods to add properties to the entity. When retrieving an entity from the service, call the getProperty(String) or getProperties() methods to access the entity's properties."_

Per the documentation, entity properties are meant to be accessed using the following methods:

- `getProperty(String key)`
- `getProperties()`
- `addProperty(String key, Object value)`
- `setProperties(Map<String, Object> properties)`

Accessing and attempting to set properties directly is not supported behavior and therefore there is no expected behavior in this instance. Please utilize the above-mentioned functions to access `TableEntity` properties.

**Comment by taisuke-fujimoto** [comment]
@jairmyree 
Thanks for the answer, understood.

I have one concern.
I think it would be better if `getProperties()` returned a copy of the `properties` that `TableEntity` has, instead of the `properties` itself.
For example:
```java
public Map<String, Object> getProperties() {
    return Collections.unmodifiableMap(properties);
}
```

**Comment by jairmyree** [comment]
@taisuke-fujimoto Thank you for the suggestion, it is much appreciated.
