### ISSUE TITLE
Use of Prefetch count and Maxconcurrent call

### ISSUE THREAD

**Issue by YogeshwarPrajapatiTR** [Azure/azure-sdk-for-java#35352]
I am using ServiceBusProcessorClient for receive message from azure service bus queue in Java-SDK.
For improve performance, I tried Prefetch count and MaxConcurrentCall features , but not sure in what combination and numbers it will more suitable and help to improve performance.
for example give value for prefetch and MaxConcurrent to (10,10) or (5,10) or (10,5)  
Also not found any related documents in microsoft.

**Comment by YogeshwarPrajapatiTR** [comment]
is their and update related to this?

**Comment by anuchandy** [comment]
When applications enable Prefetch, the library internally allocates an in-memory queue and buffer the messages from the service into this queue. One thing to note here is – by design, library won’t do lock renew for the messages in this im-memory queue, so if the messages are not processed fast enough then they can expire while sitting in the buffer. This document describes recommendations around Prefetch https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-prefetch?tabs=dotnet#why-is-prefetch-not-the-default-option

MaxConcurrentCalls controls how many messages your application wants to process in parallel. While not exactly same, you can think of it as Thread-Pool size, as you can imagine, the sizing of the thread pool is very much depending on the workload in the application. In your case, the workload is the message processing time (and anything else you’ve running on the VM). You want to use a Prefetch value such that maximum prefetch value and the lock duration configured on the queue or subscription need to be balanced such that the lock timeout at least exceeds the cumulative expected message processing time for the maximum size of the prefetch buffer, plus one message. At the same time, the lock timeout shouldn't be so long that messages can exceed their maximum time to live when they're accidentally dropped, and so requiring their lock to expire before being redelivered.

For messages that take 30-60 seconds, I’ve seen users using 2 core machines with MaxConcurrentCalls = 10-15, with the Prefetch value matching it. There is no one size that fit all settings here, as application behavior is major driving factor here. 

Hope this helps!
