### ISSUE TITLE
Occurred while refresh Token, Unable to open send and receive link

### ISSUE THREAD

**Issue by YogeshwarPrajapatiTR** [Azure/azure-sdk-for-java#35467]
In my application, got multiple times this errors at receiver application.
how can i fix this issue. that Unable to Open send and receive link.
Library Used : azure-messaging-servicebus 7.8.0
Log :
com.azure.core.util.logging.LoggingEventBuilder.performLogging:Line 365 - {"az.sdk.message":"Error occurred while refreshing token that is not retriable. Not scheduling refresh task. Use ActiveClientTokenManager.authorize() to schedule task again.","exception":"Unable to open send and receive link.","scopes":"amqp://workflow-scalbility.servicebus.windows.net/collaborate_dummy_instance_1244.1686206220529_workflow","audience":"amqp://workflow-scalbility.servicebus.windows.net/collaborate_dummy_instance_1244.1686206220529_workflow"}

**Comment by anuchandy** [comment]
@YogeshwarPrajapatiTR could you update to the latest version? 7.8.0 is almost a year old and updating to the latest will bring all the reliability fixes since then. If it still happens with new version, please share the usage code and 10/+10 minutes of logs (preferably verbose) since the error. https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/TROUBLESHOOTING.md#enable-and-configure-logging
