### ISSUE TITLE
[FEATURE REQ] mgmt, update the convenient API for Application Gateway SSL profile

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#35926]
Current code configures `ApplicationGateway.sslPolicy`.

However service seems moved to `ApplicationGateway.sslProfiles.sslPolicy`. We likely need to update the convenience API impl. And may need to deprecate `WithDisabledSslProtocol`.

Note that the CUSTOM and CUSTOM_V2 type of ApplicationGatewaySslPolicyType requires config of both `cipherSuites` and `minProtocolVersion`.

**Comment by XiaofeiCao** [comment]
`ApplicationGateway.sslProfiles.sslpolicy` is for configuring [listener-specific ssl policies](https://learn.microsoft.com/en-us/azure/application-gateway/application-gateway-configure-listener-specific-ssl-policy), while `ApplicationGateway.sslPolicy` is the applicationGateway-level ssl policy which can be overwritten by listener-specific policies.

Are they deprecating applicationGateway-level policy? I saw they still have sample for it(though v1 has sample too): https://learn.microsoft.com/en-us/azure/application-gateway/application-gateway-configure-ssl-policy-powershell

**Comment by weidongxu-microsoft** [comment]
It is mostly on Portal, that if one try to add SSL policy, it be added to `ApplicationGateway.sslProfiles.sslPolicy`.

Question is from customer, I will forward the email. I didn't really tried whether `ApplicationGateway.sslPolicy` now have or not have effect on the application gateway.

**Comment by XiaofeiCao** [comment]
I created one using our current SDK with `ApplicationGateway.sslPolicy`(slight change to the code so that I can create a custom policy with one cipher suite). 
In Portal the gateway-level ssl policy is under `Listeners` tab, not `SSL Settings`..

![image](https://github.com/Azure/azure-sdk-for-java/assets/92354331/22168db5-bab0-462d-8547-a32027780018)

I doubt that sslPolicies under `SSL Settings` will ever have effect unless it's [associated with a specific listener](https://learn.microsoft.com/en-us/azure/application-gateway/application-gateway-configure-listener-specific-ssl-policy#associate-the-ssl-profile-with-a-listener). 

Though I'm not sure what customer meant by 
> I added TLSV1_0 and TLSV 1_1 as disabled protocols during creation, but still when a new AppGw is created default TLSV1_0 protocol is set. 

but yeah, `WithDisabledSslProtocol` should be deprecated as it no longer works with v2 gateways.

**Comment by weidongxu-microsoft** [comment]
Sounds correct. I will loop in the email, in case they've have update from customer.
