### ISSUE TITLE
Deprecated Azure SDK packages in Maven Central Repository

### ISSUE THREAD

**Issue by mario-guerra** [Azure/azure-sdk-for-java#36140]
**Summary:**
Three Azure SDK packages for Java were discovered in the Maven Central Repository:

- com.azure:azure-keyvault-certificates:4.0.0-preview.4
- com.azure:azure-keyvault-keys:4.0.0-preview.4
- com.azure:azure-keyvault-secrets:4.0.0-preview.4

These packages appear to be part of an initial effort to develop Track 2 libraries but never reached GA. It is unclear whether customers are using these beta packages. They are listed as active in our Java CSV file that is the source of truth for our Azure SDK dashboard.

**Action Items:**
1. Investigate the historical context of these packages.
2. Check with the Java team to better understand their origin.
3. Look into Maven download stats to determine usage.
4. Consider marking these packages as deprecated if they are not in use.

**Comment by joshfree** [comment]
@mario-guerra please note that the only way to mark them deprecated is to ship an update (e.g., a 4.0.0-preview.5) to maven central.

@vcolin7 is the library owner and can share more details with you either here or offline

**Comment by vcolin7** [comment]
I took a look at the code history and found that when we originally added the code for Certs, Keys, and Secrets to our monorepo we did so with the names reported by @mario-guerra for versions `4.0.0-preview.3`, which leads me to believe we shipped them like that at some point in time. We never shipped these libraries as GA with those names though, as we eventually moved onto using the "security" word in the artifact id, as in `azure-security-keyvault-keys`.

@mario-guerra Since these were only made available as previews/betas, do we really want to release a new version deprecating them? Is this something we do for all "abandoned" package names?

**Comment by JonathanGiles** [comment]
I sent the following via email, but I'll include here as well:

I think there might be confusion here. Because of Maven, we can't deprecate a beta release without doing a new release that includes the deprecation information, but that release does not need to be a GA - it can just be the next beta version. 

With that said, I believe we are all in agreement that no one wants to release a GA version of this library using the old artifact ID. We should release a new non-GA version of these libraries, in the same 'wrong' place, so that we can provide the relevant relocation information to anyone who encounters it.

**Comment by mario-guerra** [comment]
https://github.com/Azure/azure-sdk/pull/6516

**Comment by mario-guerra** [comment]
Victor updated the packages in Maven to reflect their deprecated status, I've submitted a PR to reflect that status on our SDK dashboard.
