### ISSUE TITLE
[QUERY] Is it possible to use azure-storage-file-datalake retryOptions to handle a (temporary) UnknownHostException?

### ISSUE THREAD

**Issue by gdubya** [Azure/azure-sdk-for-java#36216]
**Query/Question**
We have an application running in a Kubernetes environment which seems to have an intermittent DNS problem. The application uses the a dataLakeServiceClient to obtain a fileSystemClient which then uses a dataLakeFileClient to create a file in an ADLS Gen2 account. The application uses com.azure.storage.file.datalake.DataLakeFileClient#append(java.io.InputStream, long, long) to append data to the file.

It appears as though the DNS problem causes the append operation to throw a java.net.UnknownHostException. Is it possible to configure a retryPolicy to handle this, given that we are confident that the DNS problem will resolve itself?

***Why is this not a Bug or a feature Request?***
The Azure Storage File Datalake SDK already provides the possibility for configuring retryOptions, but there isn't much documentationr regarding usage or configuration, so this is a question to determine if what I want is possible already.

**Setup**
 - Library/Libraries: [e.g. com.azure:azure-storage-file-datalake:12.14.0 (groupId:artifactId:version)]

**Comment by joshfree** [comment]
HI @gdubya someone from the `Storage` team will follow up with you shortly.

**Comment by ibrahimrabab** [comment]
Hi @gdubya 

Is this still an issue you're seeing? If so, can you go ahead and enable logging to see how many times it is being retried? It could be that the default options on retryOptions is retrying but could be exhausting attempts.

**Comment by gdubya** [comment]
Hi @ibrahimrabab,
I believe the issue is still occurring but I have not been working on it since september. Do you mean to say that the current implementation of the retry mechanism **should** handle an UnknownHostException?

**Comment by gdubya** [comment]
Yes, the problem is still occurring. As far as we can tell there is no retry occurring.

**Comment by ibrahimrabab** [comment]
@gdubya Can you enable logging and provide the logs? By default, the RequestRetryOptions are already handling IOExceptions and will retry. Since UnknownHostException is a subtype of IOException, it is by default being retried. 

One thing could be that all the retries are being exhausted. By default, the retry policy retries 3 times, if the logs contain more than 3 occurrences of the UnknownHostException it might be a good idea to pass in RequestRetryOptions with a different number for retries when constructing the client.
