### ISSUE TITLE
[FEATURE REQ] Azure SDK for Java:  Logging Environment Information

### ISSUE THREAD

**Issue by mattsmall1972** [Azure/azure-sdk-for-java#36248]
**Is your feature request related to a problem? Please describe.**
When an exception is logged using the Azure SDK for Java, it would be preferable to also log the environment where the exception occurs.  For example:  if a Key Vault Client running in an application uploaded to Azure (Web App, Function app, etc) fails to send due to an exception, it logs the exception but not the application name in which it failed. 

```
 catch (IOException ioe) {
            LOGGER.log(WARNING, "Unable to finish the http get request.", ioe);
```

**Describe the solution you'd like**
When running in any Azure environment, an environment variable is accessible to the client code.  This variable could describe the specific service, subscription, name, etc. so that when a log is submitted to Log Analytics, that error is easily found and correlated to that environment.  At this time, multiple environments could be running similar code and report into the same log.  An exception arising from only one application leaves the engineer unable to easily find the troublesome application.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by joshfree** [comment]
@lmolkova could you please follow up with @mattsmall1972

**Comment by lmolkova** [comment]
@mattsmall1972 thank you for reporting this.

Do you use some broader monitoring solution? OpenTelemetry or tool like Azure Application Insights?
Such solutions have extensive means to collect environment information including Azure VMs, Functions, AKS, and many others.
They also provide all the means to debug issues in distributed applications (metrics, distributed traces, and logs).

Since detecting the environment and enriching telemetry with corresponding information is a common feature across monitoring solutions, we on the Azure SDK side, delegate it to such tools.

If you don't use any APM solution, I recommend adding the application name or other information you need manually (by adding extra context based on your environment variables in your logging layout or in the code that forwards logs to Log Analytics).

**Comment by lmolkova** [comment]
Since we're not planning on implementing this feature in Azure SDK, I'm going to close this issue. Feel free to reopen as necessary.
