### ISSUE TITLE
[FEATURE REQ] Expose ResourceType in BlobItemProperties

### ISSUE THREAD

**Issue by electrum** [Azure/azure-sdk-for-java#36349]
When using `BlobContainerClient.listBlobs()` with Gen2 hierarchical namespace, the `Blobs.Blob.Properties` XML structure contains a `ResourceType` property that seems to distinguish between directories and files. Unfortunately, it doesn't seem to be available in the `BlobItemProperties` class (or mapped at all in `BlobItemPropertiesInternal`).

```xml
<EnumerationResults>
  <Blobs>
    <Blob>
      <Name>mydirectory</Name>
      <Properties>
        <ResourceType>directory</ResourceType>
        ...
      </Properties>
    </Blob>
    <Blob>
      <Name>mydirectory/myfile</Name>
      <Properties>
        <ResourceType>file</ResourceType>
        ...
      </Properties>
    </Blob>
```
I'd like to do something like the following:
```java
BlobContainerClient client = ...;
PagedIterable<BlobItem> blobItems = client.listBlobs(new ListBlobsOptions().setPrefix(path), null);
blobItems.stream()
        .filter(item -> item.getProperties().getResourceType().equals("directory"))

**Comment by joshfree** [comment]
Hi @electrum thanks for reaching out via this github issue - someone from the storage team will follow up with you shortly.

**Comment by jaschrep-msft** [comment]
Acknowledging and discussing with team.

**Comment by ibrahimrabab** [comment]
Hi @electrum 
Thanks for reaching out! As for your request, ResourceType of file vs directory only applies to DataLake since hierarchal namespace must be enabled, and HNS is not available for blobs. If you want to use blobs and want to be able to see whether you're using a directory or a file, we recommend you use DataLake with HNS enabled on your storage account.

DataLake builds on top of Blobs and has HNS capabilities (i.e. having a filesystem), so that's why you may see resourceType being populated with either of type directory or file on BlobItemPropertiesInternal, but we do not parse that value for Blobs since Blobs doesn't have HNS capabilities.

For more information, see here:
https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-directory-file-acl-java?tabs=azure-ad

https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-introduction

Let us know if you have more questions!
