### ISSUE TITLE
[BUG] Not able to insert timestamp type data from nanoseconds to milliseconds from Azure databricks to CSOMOS DB

### ISSUE THREAD

**Issue by shwetaagrawal1** [Azure/azure-sdk-for-java#36474]
**Describe the bug**
I am trying to inserting dataframe from azure databricks. While inserting the timestamp type to COSMOS DB, its getting inserted as nanoseconds. But I want to insert in milliseconds, after conversion as well its getting inserted in nanoseconds only.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
Insert dataframe of type timestamp from azurr databrcisk pyspark 3.3 version to COSMOS DB.

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
Data getting insert like this - 1692695953000000 and want to insert like this - 1692695953000

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

Azure databricks cluster 12.1 (includes Apache Spark 3.3.1, Scala 2.12)

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [ ] Setup information Added

**Comment by FabianMeiswinkel** [comment]
This is not a bug - but expected behavior. Cosmos DB stores documents as json - for simplification a default mapping of Spark data-types into a json datatype exists - and for timestamps as you mentioned it uses nanosecond-scale. If you want to use a different scale like milliseconds you can do the data-type conversion in the dataframe before writing it into Cosmos DB - for example by changing the Spark data-type in the dataframe to LONG (and use the millisecond scale) or storing it as a textual representation whatever is needed. Given that the native document format in Cosmos-DB is json - and json has only very limited data types - basically text and "numbers" (which have precision/scale limitations enforced by the json parser library) the Cosmos DB Spark connector can only provide default mappings - there will always be a scenario where the conversion needs to be done in Spark manually before writing into Cosmos DB - luckily Spark makes it very easy and efficient to do these conversions.
