### ISSUE TITLE
[QUERY] ServiceBus FIFO is lost when using prefetch and session

### ISSUE THREAD

**Issue by brunomace** [Azure/azure-sdk-for-java#36478]
### Library name and version

Maven azure-messaging-servicebus 7.13.0

### Query/Question

Hi,

_I've the same query than Azure/azure-sdk-for-net#26618, but this issue is closed with no real answer._

I am using the Service Bus sessions on my producer and consumers to guarantee the FIFO order of the messages.
Now I want to set the `prefetch count` >0 to speed up the delivery of the messages, but I have a strange behavior when a message is rejected.
I want to know if it is intentional or if it is a bug.

I've done some testing where:

- my producer publish 3 messages, with the same session ID
- my consumer reject the message with ID 1 four times before accepting it, and accept messages 2 and 3

The results with prefetch count `0`:

- 	1 -> rejected
- 	1 -> rejected
- 	1 -> rejected
- 	1 -> rejected
- 	1 -> accepted
- 	2
- 	3

**> OK, the messages are consumed in order**

With prefetch count `1`:

- 	1 -> rejected
- 	2
- 	1 -> rejected
- 	3
- 	1 -> rejected
- 	1 -> rejected
- 	1 -> accepted

**> The messages aren't consumed in order, 2 and 3 before 1**

With prefetch count `2`:

- 	1 -> rejected
- 	2
- 	3
- 	1 -> rejected
- 	1 -> rejected
- 	1 -> rejected
- 	1 -> accepted

**> Same, the messages aren't consumed in order, 2 and 3 before 1**

I was expecting to always have the messages delivered in order, even if a message is rejected (until it reach the `max delivery count`).
Why the message 1 isn't redelivered before the others when the prefetch is activated ?

Currently, I must leave the `prefetch count` value to 0 to guarantee the FIFO order.

Thanks

### Environment

Via Spring Cloud Stream

**Comment by anuchandy** [comment]
Hi @brunomace, this behavior is by design. Turning on the Prefetch means application want client to internally allocates a buffer called Prefetch-Buffer. It results in client requesting the broker to return a bulk of messages, those get buffered in the Prefetch-Buffer.

The library invokes Processor-Handler with one message from the Prefetch-Buffer at a time. When an invocation of Processor-Handler returns, the next invocation of Processor-Handler happens with next message from the Prefetch-Buffer. 

As long as the Prefetch-Buffer has messages, they get delivered to the Processor-Handler. When/If the broker "Redeliver" a message while the Processor-Handler is handling a message from the buffer, it also gets enqueued to Prefetch-Buffer, and when the buffer’s current cursor reaches that message, it will be notified to Processor-Handler.

Prefetch is a client-side opt-in feature, the above explained in-memory buffer draining is simply driven by when Processor-Handler returns. A network operation (reject) happened at LATER point has no control over draining of ALREADY buffered in-memory messages.

**Comment by anuchandy** [comment]
This client side ordering  nature is explained in the common documentation [Prefetch messages from Azure Service Bus - Azure Service Bus | Microsoft Learn](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-prefetch?tabs=dotnet#why-is-prefetch-not-the-default-option) in the context of _lock-expiration_

> "…and is again made available for retrieval from the queue. It might cause the message to be fetched into the prefetch buffer and placed at the end…."

The _reject_ case is same as this, we’ll update and clarify it in the doc.

**Comment by brunomace** [comment]
OK, thanks for the explanation.
I will let the prefetch count to 0.

**Comment by anuchandy** [comment]
The MS-Doc is now updated with the Prefetch-Buffer behavior discussed above. https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-prefetch?tabs=dotnet#why-is-prefetch-not-the-default-option
