### ISSUE TITLE
[QUERY] How to receive single message from a session concurrently

### ISSUE THREAD

**Issue by PavanMoturu** [Azure/azure-sdk-for-java#36639]
Hi team,

We have a scenario where we should only receive/process one message per session concurrently.
Like if max concurrent sessions are 10, then I need to keep on receiving one message per session across 10 threads until the application is running and if messages are available.

I can't use ServiceBusSessionProcessorClient as you can't receive one message using processor clients.

I can use ServiceBusSessionReceiverClient and get ServieBusReceiverClient by calling acceptNextSession and use receiveMessages(1) to get only one message, but I would like to use this for concurrent sessions and got stuck on how to use it.
I can't set maxConcurrentSessions on ServiceBusSessionReceiverClient as maxConcurrentSessions method is not public.

It will be much appreciated if someone assist me on how to achieve this.

**Comment by anuchandy** [comment]
Hi Pavan, with an instance of ServiceBusSessionProcessor you should be able to receive from multiple sessions – where messages from each session is delivered one by one, then this pattern replicated concurrently across sessions.

```
Session1    Session2   ......
|               |
Msg_1_1    Msg_2_1
|               |
Msg_1_2    Msg_2_2
|               |
Msg_1_3    Msg_2_3
.               .
.               .
.               .
```

where it's serial execution column wise and concurrent in horizontal direction.

Or did I misunderstand your ask.

**Comment by PavanMoturu** [comment]
Hi Anu,

Our scenarios is to accept message from session and close it without waiting for next message. The reason for this is we have lot of sessions(probably around 10k) with few messages in the session.
From documentation, I can't make more than 5000 concurrent calls to service bus.

**Comment by PavanMoturu** [comment]
Hi Anu,

Can you please look into this?
I tried with ServiceBusProcessorClient but there will be a delay in switching sessions.

**Comment by PavanMoturu** [comment]
I just noticed that I can set sessionIdleTimeOut on ServiceBusSessionProcessorClientBuilder with 7.14.0 version.
I am looking if it solves my scenario or not.

**Comment by anuchandy** [comment]
Hello Pavan, session-idle-timeout should help with rolling to the next session. Otherwise, the solution would be to rollout a model like below – 

```java
Thread {
    Loop {
        accept-session to obtain the client.
        Receive message from the client.
        Close the client.
        Wait For a second or so then loop. 
    }
}  
```

Then replicate this model using multiple threads. I would suggest further grouping these replicates, such that each group will have a _dedicated_ builder that builds the ServieBusReceiverClient . Then each replicate in that group uses this ServieBusReceiverClient to invoke accept-session.


I would keep the number of replicates in one group to 10-20. 

Also given the large number of concurrent sessions, you might want to split the load across multiple pods or machine (this very much depends on your use case and env, I was just sharing thoughts in general)

**Comment by PavanMoturu** [comment]
Closing this issue. Session idle timeout works but in that time message should be completed by your application.
I used ConcurrentExecutor for multiple threads and use servicebussessionreceiverclient for each thread to consume messages.
