### ISSUE TITLE
[Upload to Blob using stream is failing intermittently with Timeout on blocking read for Configured NANOSECONDS]

### ISSUE THREAD

**Issue by ramdevsharma1985** [Azure/azure-sdk-for-java#36691]
**Describe the bug**
We are using Azure java SDK storage APIs to upload using files as well as streams. We are observing that on daily basis some requests are failing with Timeout on blocking read for XX NANOSECONDS. Azure support team is asking for request Id of those requests to investigate but we don't get any request Id or not other helpful message or trace that whether it was stuck or x percent of bytes were transferred.

***Exception or Stack Trace***
Exception stack trace as follows:
java.lang.IllegalStateException: Timeout on blocking read for 1800000000000 NANOSECONDS
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:123) ~[reactor-core-3.4.26.jar!/:3.4.26]
        at reactor.core.publisher.Mono.block(Mono.java:1766) ~[reactor-core-3.4.26.jar!/:3.4.26]
        at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:158) ~[azure-storage-common-12.19.1.jar!/:12.19.1]
        at com.azure.storage.blob.BlobClient.uploadWithResponse(BlobClient.java:337) ~[azure-storage-blob-12.20.1.jar!/:12.20.1]

**To Reproduce**
We are callng blob upload API through out a day roughly 180,000 times which will increase to 2 millions with full production load.
We have facing this issue with roughly 10 to 50 requests that are failing with timeout.
We are running Spring boot jar from 5 different instances of VMSS.

***Code Snippet***
public void downloadStreamWithResponse(InputStream inputStream, Long contentLength, BlobClient blobClient)
			throws AppException {
		
		try{
			BlobParallelUploadOptions options = new BlobParallelUploadOptions(inputStream);
			
			ParallelTransferOptions parallelTransferOptions = null;
			if(adlsConfigSettings.isUseParallelOptions()){
				
				parallelTransferOptions = getParallelTransferOptions();
				options.setParallelTransferOptions(parallelTransferOptions);
			}
			
			if(adlsConfigSettings.isAddProgressListener()){
				
				if(parallelTransferOptions == null){
					parallelTransferOptions = new ParallelTransferOptions();
				}
				parallelTransferOptions.setProgressListener(bytesTransferred -> log.info( " blob: {},  Upload progress: {} bytes sent", blobClient.getBlobName(), bytesTransferred));
				options.setParallelTransferOptions(parallelTransferOptions);
			}
			
			Duration requestTimeOut = getAdlsRequestTimeout(contentLength);
			log.info("requestTimeOut :" + requestTimeOut.getSeconds());
			
			Response<BlockBlobItem> response = blobClient.uploadWithResponse(options, requestTimeOut, Context.NONE);
			
			verifyDownloadResponse(contentLength, blobClient, response);
			
		}catch(IOException ex){
			throw new DirectDownloadFailedException(ErrorCodesEnum.SUB047.name(), ErrorCodesEnum.SUB047.getMsg() + ex.getMessage(), ex);
		}
	}

**Expected behavior**
We are expecting that timeout error should not happen and if still happens we may get for which request Id it happened and percentage of bytes transferred when it happened.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Linux
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-storage-blob:12.20.1
 - Java version: JDK 8
 - App Server/Environment: Spring Boot Jar
 - Frameworks: Spring Boot

**Comment by alzimmermsft** [comment]
Thanks for asking this question @ramdevsharma1985.

What you're likely seeing is the effects of the `requestTimeout` passed into `blobClient.uploadWithResponse(options, requestTimeout, Context.NONE)`. The timeout passed to this API is a timeout for the entirety of the upload, or more broadly any API that takes a timeout it's the timeout for the entire operation. While the timeout is `1800000000000` nanoseconds, depending on network congestion, network speed, and the size of the upload it's possible that 30 minutes isn't long enough.

A potential remedy for this is to remove the timeout or setting it to a longer amount of time. Another option provided by the SDKs is using `HttpClientOptions`'s `writeTimeout`, `responseTimeout`, and `readTimeout`, these timeouts are more granular and effect the HttpClient sending the request where `writeTimeout` will timeout the request if no data is sent over the wire within a certain time frame, `responseTimeout` will timeout if the request finishes sending but a response isn't received within a certain time frame, and `readTimeout` will timeout the response if no data is received from the wire within a certain time frame. All the `HttpClientOptions` timeouts have a default of 1 minute, except `connectTimeout` which is 10 seconds.

Correlating the request ID to the request that timed out if a little more difficult due to how the timeout is applied to the request and when a request ID is generated for the request. Additionally, the upload API may send parallel requests of smaller data to chunk the upload which means there is a one-to-many API to service requests going on here. The first option I can think of is enabling HTTP logging and correlating the API timeouts to the requests that were sent at `timeout time - timeout`, HTTP logging can be enabled following this guide: https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/core/azure-core#enabling-logging

A second option around tracking the request ID is constructing your `BlobClient` with `.policy(new AddHeadersFromContextPolicy())` and on API request passing a `Context` like `new Context(AddHeadersFromContextPolicy.AZURE_REQUEST_HTTP_HEADERS_KEY, new HttpHeaders("x-ms-request-id", someIdentifierYouCreate))`. The downside to this is that is `upload` does chunk the data being uploaded all chunks will have the same `x-ms-request-id`, but it at least gives a way to correlate an `x-ms-request-id` to the client-side timeout.

**Comment by alzimmermsft** [comment]
FYI @ibrahimrabab as this is in Storage

FYI @JonathanGiles @lmolkova @srnagar as this is a pain point in troubleshooting

**Comment by ramdevsharma1985** [comment]
We have checked regarding on this further from our based suggestions. Regarding read and write timeout , we are building HttpClient using NettyAsyncHttpClientBuilder as follows:

```
HttpClient httpClient = null;
if (commonConfigSettings.getProxy()) {
	httpClient = new NettyAsyncHttpClientBuilder().proxy(new ProxyOptions(ProxyOptions.Type.HTTP,
			new InetSocketAddress(commonConfigSettings.getProxyHost(), commonConfigSettings.getProxyPort())))
			.build();
} else {
	httpClient = new NettyAsyncHttpClientBuilder().build();
}
```
This must have default read and write timeout but in our case, we didn't see request getting timeout either on read or on write. Is there anything obvious that we are missing here?

To add more on this-
We have observed this issue for stream data as small as few bytes to GB.
E.g. requests with content length as 171 bytes, 22 bytes. 

To add more context - Our application is running subscriber as endpoint that is called by other application to push files over HTTP request. We have 5 Spring boot JVMs (e.g) running behind Azure Load Balancer and caller is also have N number of Hosts from which requests are coming. Currently we are getting roughly 180K request with varied file sizes which will grow as we add more load.

I will add more details but needs to understand whether any issue with Storage APIs if it is not able to connect to storage and remains hung ?

**Comment by srnagar** [comment]
> FYI @ibrahimrabab as this is in Storage
> 
> FYI @JonathanGiles @lmolkova @srnagar as this is a pain point in troubleshooting

When the client side timeout is triggered (i.e.  the requestTimeout in `blobClient.uploadWithResponse(options, requestTimeout, Context.NONE)`), we should include the last known request id for that operation in the exception message. This will require us to catch the timeout exception and also track the request id added by the `RequestIdPolicy`.

**Comment by ramdevsharma1985** [comment]
HTTP logging  https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/core/azure-core#enabling-logging is logging each request response which cannot be possible to enable in logging to troubleshoot and issue is not reproducible in non-prod environment.

We would like to know if any options that can periodically write progress like every 5 minutes if upload is taking longer or to understand if it is stuck and not doing anything. We also want to fail fast if upload is not happening. What are the option that you can suggest on it.

**Comment by ramdevsharma1985** [comment]
We would also like to know what we must expect in thread dump when upload with stream is happening (assumed that request is  showing us running).

**Comment by alzimmermsft** [comment]
Following up on some of the questions asked @ramdevsharma1985 

> This must have default read and write timeout but in our case, we didn't see request getting timeout either on read or on write. Is there anything obvious that we are missing here?

Based on the code samples, though environment configuration can impact this, there is nothing missing here. This will use the defaults for timing out a connection based on inactivity: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty/NettyAsyncHttpClientBuilder.java#L79

This may be pointing to a case where progress is happening extremely slow due to resource contention.

> We would like to know if any options that can periodically write progress like every 5 minutes if upload is taking longer or to understand if it is stuck and not doing anything. 

This would require a more complex `ProgressListener` to be passed into each upload request that manages how long-ago progress was reported. Something like:

```java
public class TimedProgressListener implements ProgressListner {
    private final long millisBetweenProgressReports;
    private long lastProgressMillis = -1;
    
    public TimedProgressListener(long millisBetweenProgressReports) {
        this.millisBetweenProgressReports = millisBetweenProgressReports;
    }

    @Override
    public void handleProgress(long progress) {
        long currentTimeMillis = System.currentTimeMillis();
        if (lastProgressMillis == -1 || (currentTimeMillis - lastProgressMillis >= millisBetweenProgressReports) {
            reportProgress(progress);
            lastProgressMillis = currentTimeMillis;
        }
    }
}
```

This could also be extended to track what the progress was last time progress was reported and alert if progress hasn't happened or is happening slowly.

> We also want to fail fast if upload is not happening. What are the option that you can suggest on it.

Other than no progress happening at all between timeout periods in the networking layer there isn't anything else available. So, one option could be to reduce how quickly progress needs to happen before timing out. 60 seconds was just a general rule of thumb we used but this could be reduced to fail requests if no progress happens within any given time period and reducing this may help slow progressing requests.
