### ISSUE TITLE
Does ServiceBusReceiverClient peekMessage() has any adverse effect on the Messages present in Queue/Topic(Subscriber) 

### ISSUE THREAD

**Issue by snarlagi** [Azure/azure-sdk-for-java#36788]
**Query/Question**
I'm trying to build the ServiceBusReceiverClient using connection string and trying to perform peekMessage() operation on it.
When I perform peekMessage() method call I don't want to have any adverse affect for customer messages present in Queue or Topic/Subscribers and just want to check if Listen SAS policy is applied on connection string as mentioned in the code snippet.

Please answer below queries as well for better understanding of the peekMessage() and receiveMessage() methods:

1. If I do peekMessage() method calls multiple times does it delete messages/increase deliverycount or any adverse effect happens for messages in Queue/Topic?
2. Does peekMessage() has any effect on the Message on Queue/Topic(Subscriber) DeliveryCount,  or adds any on lock on message ?
3. Can you please clarify what is the difference between peekMessage() and receiveMessages(int maxMessages) methods?
4. When to use peekMessage() and receiveMessages(int maxMessages) methods?
5. Does peekMessage() method has any affect on the messages in either Queue or Topic Subscribers ?

**Code Snippet I'm trying to test**
```
try{
ServiceBusReceiverClient receiverClient = new ServiceBusClientBuilder().connectionString(connectionString).receiver().queueName(azp.getEntityName()).buildClient();

receiverClient.peekMessage();
}catch(Exception e){
}
```

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?
This is only a query and not a bug . The API Functionality is working fine.

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE: Eclipse
 - Library/Libraries: azure-messaging-servicebus-7.8.0.jar and it's dependencies.
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [*] Query Added
- [*] Setup information Added

**Comment by anuchandy** [comment]
Hello @snarlagi

1.	peekMessage() will not increase the delivery count of the message it returns.
2.	peekMessage() will not add a lock to the message.
3.	peekMessage() will give a read-only view of the message so application cannot perform disposition (compete, abandon etc.) on that message. Whereas receiveMessages() will give the same message that application can disposition it. When using receiveMessages() the message will be locked for the configured duration so that another receiveMessages() call won’t receive the same message. If no complete call is made / the lock expires, another receiveMessages() call will later get the same message.
4.	For the common work pattern of – “receive message, business-process, complete or abandon the message to commit success or failure of the business-processing” – use receiveMessages().
There isn’t much you can do with message from peekMessage() other than inspecting its properties.
5.	No

By Default, receiveMessages will pull messages in PEEK_LOCK mode, you can find more info [here ](https://learn.microsoft.com/en-us/azure/service-bus-messaging/message-transfers-locks-settlement#peeklock)

**Comment by anuchandy** [comment]
Provided answers for the queries. Closing
