### ISSUE TITLE
[QUERY]which service can use to query device list information from IoT Hub.

### ISSUE THREAD

**Issue by pratson20** [Azure/azure-sdk-for-java#3680]
Hi, 
We need to get a list of devices from the IoT Hub with details like capabilities and scope. What would be the right service to use from azure java sdk?

Thanks,
Prateek

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

I did a quick search and found the [azure-iot-sdk-java](https://github.com/Azure/azure-iot-sdk-java) repo which may hold the answers for this.  However, I'm unsure, so I'm sending this for Java Client team review instead of moving the issue there.

**Comment by joshfree** [comment]
Hi @pratson20, I believe the correct SDK reference is available at https://github.com/Azure/azure-iot-sdk-java#api-reference.  

/cc @myagley

**Comment by joshfree** [comment]
@pratson20 I'm closing this issue now.  Feel free to comment and reactivate if there are follow on questions or I misunderstood the original question.  Thanks.
