### ISSUE TITLE
EventHub consumer receiving message with empty body and closing the partition connection

### ISSUE THREAD

**Issue by achintmitt** [Azure/azure-sdk-for-java#36860]
Hi Team

We have EventHub instance with three partitions, and a Java consumer reading from all three partitions.

Very frequently, we get these WARN and ERROR msgs:
---------------------------------------------------------------------------------------------------------------------
WARN 1 --- [ctor-executor-1] c.a.m.e.implementation.MessageUtils      : Message does not have a body.
ERROR 1 --- [ctor-executor-1] c.a.m.e.EventHubMessageSerializer        : offset: x-opt-offset should always be in map.

java.lang.IllegalStateException: offset: x-opt-offset should always be in map.
	at com.azure.messaging.eventhubs.EventHubMessageSerializer.deserializeEventData(EventHubMessageSerializer.java:210)
---------------------------------------------------------------------------------------------------------------------

Immediately after that, consumer stops listening from this particular partition where it gets this empty message. However, the consumer keeps running for other two partitions.

I have checked my producer and its not generating any message with empty body.

Please provide suggestions on this issue.

**Comment by anuchandy** [comment]
Hello @achintmitt, 


1.	Could you share the code showing consumer usage, so that we can understand which flavor of consumer and how it is used? 
2.	Are you using the EventHubProducer[Async]Client to send the events or some other client?
3.	Could you share the version of the Event Library used for Receive and Send?
4.	Could you enable VERBOSE log in Consumer and share -15/+15 mins of logs around these two WARN and ERROR log-messages?

\\cc @conniey

**Comment by achintmitt** [comment]
Hi @anuchandy 

Here are some details:

1. Consumer is a Java/SpringBoot application, and uses EventHubConsumerAsyncClient. The library version for consumer is 
     azure-messaging-eventhubs-5.15.2

2. The Consumer code snippet:
EventHubClientBuilder clientBuilder = new EventHubClientBuilder().connectionString(connectionString)
				.transportType(AmqpTransportType.AMQP_WEB_SOCKETS)
				.consumerGroup(EventHubClientBuilder.DEFAULT_CONSUMER_GROUP_NAME);

EventHubConsumerAsyncClient consumer = clientBuilder.buildAsyncConsumerClient();

consumer.receiveFromPartition(PARTITION_1, EventPosition.latest())
				.subscribe(event -> {
					try {
						processEvent1(event.getData().getBodyAsString());
					} catch (Exception e) {
						log.error();
					}

				}, error -> log.error();

consumer.receiveFromPartition(PARTITION_2, EventPosition.latest())
				.subscribe(event -> {
					try {
						processEvent2(event.getData().getBodyAsString());
					} catch (Exception e) {
						log.error();
					}

				}, error -> log.error();

.........similarly for partition 3

I will provide the producer details (non-Java application) and logs shortly in my next message.

Thanks.

**Comment by achintmitt** [comment]
Hi @anuchandy 

Our producer is in Python and they are using below library (azure-eventhub 5.11.4):

from azure.eventhub import EventHubProducerClient, EventData

producer_client = EventHubProducerClient.from_connection_string(CONNECTION_STR,eventhub_name=eventhub_name)

    with producer_client:
            event_data_batch = producer_client.create_batch(partition_id="1")
            event_data = EventData(final_message)
            event_data_batch.add(event_data)
            producer_client.send_batch(event_data_batch)

Finally, regarding verbose logs, today i was not able to reproduce this issue. So, i'm providing the logs from previous issue generation in attached file.
[EventHub_Error.txt](https://github.com/Azure/azure-sdk-for-java/files/12685780/EventHub_Error.txt)

Please let me know if you suspect anything based on all these pieces of info.

**Comment by achintmitt** [comment]
Hi @anuchandy , @conniey 

do you have any update for me on this issue?

Thanks
Achint

**Comment by anuchandy** [comment]
Hi @achintmitt

The client (SDK) log didn’t provide any insight into why the library received such AMQP deliveries. Hopefully capturing AMQP transport frame logs along with client (SDK) log may provide more insight. See [this ](https://learn.microsoft.com/en-us/azure/developer/java/sdk/troubleshooting-messaging-event-hubs-overview#enable-amqp-transport-logging)

But I want to share the "EventHubConsumerAsyncClient" (aka Lower-Level Client) behavior -

1.	The Lower-Level Client will propagate any exception it encountered to the Subscriber. These errors include transient errors such as server-idle timeout, server-busy error, TCP reset or any error (for example, the decode error you encountered).
2.	Once any error occurs, that instance of Lower-Level Client terminates the events streaming. When using Lower-Level Client, it’s application responsibility to listen for the terminal error and to create a new Lower-Level Client to resume receiving. 
3.	It’s application responsibility to track the sequence number of the latest event processed, so that when creating a new Lower-Level Client (e.g., after error), it can be initialized with the latest sequence number to _resume_ the event streaming.

As you can see, since your application, using Lower-Level Client, is not handling terminal error, application will anyway eventually experience stopping of partition event streaming.

Additionally, The Lower-Level Client is stateless - 

1. So, if the host (e.g., VM, AKS Pod etc.) running a Lower-Level Client crash or restart, the application needs to externally store (checkpoint) the sequence number of the latest event processed, so that as part of the host recovery, this sequence number can be fetched from the external source and used to initialize the new Lower-Level Client.
2. If one host is down for a prolonged period (which stops the partition processing), then the Lower-Level Client instances running on other healthy hosts won’t be able to detect that downtime and won't pick up the partition processing.

Due to these, ***we don’t recommend using the Lower-Level Client in Production uses cases. ***

<ins>For production scenarios, the Higher-Level Client, EventHubProcessorClient is recommended</ins>. The EventHubProcessorClient recovers on errors, load balances partition processing (so if one host is down for a period, another healthy host picks up the partition), and can provide persistent checkpointing.  It simplifies the application design, such that apps don’t have to write custom code to handle the previously explained behaviors of Lower-level Client.

We’ve the samples on how to use EventHubsProcessorClient, which can be found [here ](https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-java-get-started-send?tabs=passwordless%2Croles-azure-portal#receive-events). Are you open to use this client type?

(Note: this also means, if the client happens to encounter an unexpected delivery, causing the error you saw, EventHubProcessorClient will recover).

**Comment by anuchandy** [comment]
Necessary recommendations are provided and closing this issue.
