### ISSUE TITLE
I always have periodic issues with connection azure timeout

### ISSUE THREAD

**Issue by WXCMYDEARMELAN** [Azure/azure-sdk-for-java#36933]
For example, connecting to the service every morning is normal, and then there is always a timeout issue in the afternoon

code:
![企业微信截图_16956352024863](https://github.com/Azure/azure-sdk-for-java/assets/125426469/fccee066-bf03-48d1-a9f9-4f36b849eb47)

Exception:
![企业微信截图_16956349834236](https://github.com/Azure/azure-sdk-for-java/assets/125426469/88e45a2a-4131-46cf-b831-04504b890314)

Could you help me .Thank you very much.

**Comment by alzimmermsft** [comment]
Thank you for filing this issue @WXCMYDEARMELAN.

Unfortunately, the code snippet doesn't help too much as the issue is that a connection to the remote host can't be made within 10 seconds and is timing out, so some additional details are needed.

Is the application using a proxy?

Given you mentioned it seems to happen at a similar time every day, does anything change in the hosting environment regularly that could coincide with the timeout? Ex, periodic reset of a service, increase in usage, etc.
