### ISSUE TITLE
[BUG] Azure-OpenTelemetry library is no longer instrumenting spans for Azure Event Hubs binder.

### ISSUE THREAD

**Issue by azizabah** [Azure/azure-sdk-for-java#37038]
**Describe the bug**
OpenTelemetry spans are not being generated by the Azure-OpenTelemetry library for spans related to Azure Event Hubs processing via com.azure.spring:spring-cloud-azure-stream-binder-eventhubs library. However they ARE being generated by the Azure-OpenTelemetry library for spans related to Azure Service Bus processing via com.azure.spring:spring-cloud-azure-stream-binder-servicebus library. This is inside the same service. 

There are spans being generated for the event hub integration but they are being generated by the io.opentelemetry.spring-integration-4.1 per the span's otel.library.name tag. These spans are missing key information such as messaging.destination.name that we were using. 

**To Reproduce**
Build a service that uses the binders and examine the traces being generated via OTEL.

**Expected behavior**
I would expect the spans to continue to be generated like they were before we upgraded to Java 17, Spring Boot 3.1.x, and Azure SDK 5.4.0. 

**Screenshots**

**Setup (please complete the following information):**
 - OS: eclipse-temurin:17-jre-alpine
 - Library/Libraries:
 - com.azure.spring:spring-cloud-azure-stream-binder-eventhubs
 - com.azure.spring:spring-cloud-azure-stream-binder-servicebus
 - com.azure.spring:spring-cloud-azure-dependencies:5.4.0
 - org.springframework.boot:spring-boot-dependencies:3.1.2
 - org.springframework.cloud:spring-cloud-dependencies:2022.0.4

 - Java version: 17
 - App Server/Environment: Tomcat
 - Service is instrumented using OpenTelemetry Java Agent - Version 1.23.0
 - Frameworks: Spring Boot

**Additional context**
We are collecting traces via otel/opentelemetry-collector-contrib:0.82.0 inside of an AKS cluster.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by joshfree** [comment]
@lmolkova @trask could one of you please take a look?

**Comment by lmolkova** [comment]
thank you for reporting this, @azizabah!

I can reproduce the issue whit OpenTelmetry agent 1.23.0 and believe it was fixed in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/8916 in OpenTelmetry agent 1.28.0.

You can update to 1.28 or any newer version of the agent.
Note that we fixes some other minor tracing issues in the EventHubs (e.g. https://github.com/microsoft/ApplicationInsights-Java/issues/3303) and recommend using the latest version 5.16.0 to avoid them.

I will close this issue, feel free to reopen it if updating OTel agent and EventHubs package does not help or if you have any questions.

**Comment by azizabah** [comment]
Thanks @lmolkova . I will give those a shot and re-open if I am not seeing it resolved.
