### ISSUE TITLE
[FEATURE REQ] Authenticating a service principal with a federation token

### ISSUE THREAD

**Issue by nv-sankalpk** [Azure/azure-sdk-for-java#37067]
Authenticating a service principal with a federation token
Azure CLI has a way to authenticate to the service principal using the federation token, but I do not see any ClientFederationTokenBuilder class similar to ClientSecretCredentialBuilder and ClientCertificateCredentialBuilder.
az login --service-principal -u <client_id> -t <tenant_id> --federated-token <identity_Token>

Can you please add the support for authenticating Service Principal using federation in Azure Java SDK.

**Comment by joshfree** [comment]
Thanks for filing this request, @nv-sankalpk.  @g2vinay @billwert could you please take a look as a potential improvement for next semester

**Comment by g2vinay** [comment]
@nv-sankalpk 

Can you describe, the use case you're looking for ?

How do you intend to use ClientFederationTokenCredential ?
What logic does this credential use to get a token and return it ?

**Comment by MrWellington** [comment]
@g2vinay 

I am not the original poster, but I subscribed to updates here out of interest for my own use case. Rather than fetching a token, I believe this request is to allow a token to be passed externally in via the CLI to authenticate, like the `az login` example that @nv-sankalpk provided. Since the token is passed in as input there would not be a need to fetch one.

In my specific case, I would like to configure an Azure DevOps pipeline to use the `jarsigner` utility with the Azure KeyVault JCA to digitally sign JAR files. Instead of copying the client id/secret into pipeline variables, I would like to use the new [workload identity federation](https://devblogs.microsoft.com/devops/workload-identity-federation-for-azure-deployments-is-now-generally-available/) feature to authenticate without storing sensitive credentials.

In my .NET applications I can do this by getting the token from the pipeline and passing as an option to [AzureSignTool](https://github.com/vcsjones/AzureSignTool), but a similar option does not exist here that I can use for the Azure KeyVault JCA.

**Comment by g2vinay** [comment]
@nv-sankalpk and @MrWellington 

The Azure Identity offers, Azure CLI credential which fetches a token on behalf of the logged in user/service principal. 
On your end, if you ensure, you're logged in to the Azure CLI.
Azure CLI credential can be used to fetch the token.

**Comment by g2vinay** [comment]
Let us know, if any API support is still needed for this and above solutions don't work, we can reopen it.
