### ISSUE TITLE
[BUG] OOM because ServiceBusMessageBatch allocates at least 1MB per message

### ISSUE THREAD

**Issue by bartoszpop** [Azure/azure-sdk-for-java#37197]
**Describe the bug**
When sending a message without batching using the async client, it creates an instance of `com.azure.messaging.servicebus.ServiceBusMessageBatch` for each message being sent. This class has a field eventBytes which consumes at least 1 MB (the minimum size you can set in Azure Service Bus). If there is a peak of messages waiting to be sent in the Reactor's queue, it causes OutOfMemoryError, e.g. 1k of messages will allocate 1 GB of memory.

**Code snippet**
See #34426 (change client to `com.azure.messaging.servicebus.ServiceBusSenderAsyncClient`).

**Expected behavior**
Sender client allocates only the necessary amount of memory for each message.

**Screenshots**
![image](https://github.com/Azure/azure-sdk-for-java/assets/10945404/c8ae27e3-3bc5-4bd5-adcc-b0af2d3b3eda)
In the above example there are ~3600 messages pending to be sent and although each message is has no more than 1 KB, it consumes 1 MB which in sum gives ~3.6 GB.

**Setup (please complete the following information):**
 - Library/Libraries: com.azure:azure-messaging-servicebus:7.14.4
 - Java version: 11

**Comment by anuchandy** [comment]
Hello @bartoszpop, let me take a look.

**Comment by anuchandy** [comment]
Hey, we’ll review the current algorithm for Event Hubs and Service Bus and see how to improve experience (allocation) of "Single message" send.

### Application-level solution to control memory for "Single Message" Send

If assigning more JVM memory is not an option then, for the **interim**, to send "Single Message", use the `CreateMessageBatchOptions` based API that allows capping upper bound for the allocation. For example, if / given that most of your messages fall under 1 KB, use that as the upper bound. Adjust this upper bound constant based on the normal messages(s) size range along with a fallback.

```java
private final maxBatchSizeKb = 1; // The size in KB for most of the messages.

void sendMessage(ServiceBusMessage singleMessage) {
    var messageBatch = messageSender.createMessageBatch(new CreateMessageBatchOptions().setMaximumSizeInBytes(this.maxBatchSizeKb * 1024));
    if (messageBatch.tryAddMessage(singleMessage)) {
       // common cases where the message fits in 1 KB.
       messageSender.sendMessages(messageBatch);
    } else {
       // fallback: if message doesn't fall in the common bucket, fallback to sendMessage.
       LOGGER.info("Message with id {} does not fit in common bucket.", message.getMessageId());
       messageSender.sendMessage(singleMessage);
    }
}
```

I understand the above solution may not dynamic enough, but it’ll helps to control memory with some help from the application, so suggesting it if you're really blocked while we review.

Use batch when/if possible.
**Multi-Message Batch Send**: Note that batching "Multiple messages" in a "One batch" will give better performance as it hugely reduces the network calls. E.g., 100 1KB messages in one batch are 1 network call, sending it separately as you’re doing today will be 100 network calls. Also, you will see a better memory pattern with "Multi-Message Batch Send", because, the allocation is scoped to batch, not each message in the Batch, this was an improvment made as part of this [PR](https://github.com/Azure/azure-sdk-for-java/pull/34591), per [this 34426](https://github.com/Azure/azure-sdk-for-java/issues/34426) github issue feedback. Hence use "Multi-Message Batch Send" when possible.

**Comment by bartoszpop** [comment]
Hi @anuchandy, sorry for the delayed response and thank you for your comprehensive answer. We use Apache Camel as our backing technology and because [Camel's ASB component](https://camel.apache.org/components/3.21.x/azure-servicebus-component.html) delegates to `com.azure.messaging.servicebus.ServiceBusSenderAsyncClient#sendIterable` which silently ignores the result of `com.azure.messaging.servicebus.ServiceBusMessageBatch#tryAddMessage`, some messages can be skipped while sending. For this reason we decided to send messages separately. Unfortunately, Camel's API does not allow to set custom `CreateMessageBatchOptions`.

However, after further analysis it looks like we can switch back to batching messages and calculate the size of payload upfront with some margin left (the serialized payload is greater than the actual payload) not to exceed the size limit.

Nevertheless, the above issue with inefficient memory allocation should be addressed. I believe that `com.azure.messaging.servicebus.ServiceBusSenderAsyncClient#sendIterable` should also be fixed to respect the result of `ServiceBusMessageBatch#tryAddMessage` and create a new instance of `ServiceBusMessageBatch` if the list of messages does not fit into a single one.

**Comment by anuchandy** [comment]
Hello @bartoszpop, thanks for getting back. 

We’ve optimized the memory allocation in `ServiceBusMessageBatch`, so that it no longer allocates the `eventBytes`.

This is shipped as beta.5 (which we’ll GA soon)

```xml
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-messaging-servicebus</artifactId>
    <version>7.15.0-beta.5</version>
</dependency>
```

I agree with your finding about `ServiceBusSenderAsyncClient#sendIterable`, which ignores return value of  `tryAddMessage`. Thanks for pointing it out, this we will address that as well.

**Comment by bartoszpop** [comment]
Thanks @anuchandy. I will test and get back to you.

**Comment by anuchandy** [comment]
Hello @bartoszpop, our internal stress testing shows that this memory problem is addressed. The beta is going to GA in few weeks. Closing this. Thanks for reporting it!

**Comment by bartoszpop** [comment]
Hi @anuchandy, I verified and it's working fine. Thank you for your support!

**Comment by anuchandy** [comment]
thanks for the confirmation @bartoszpop
