### ISSUE TITLE
How to configure ClientCertificateCredential to avoid MsalServiceException: AADSTS700023 exception

### ISSUE THREAD

**Issue by y0geshdev** [Azure/azure-sdk-for-java#37274]
**Query/Question**
I am trying to use First party app (FPA) details to access KV in C1 tenant subscription but getting below exception - 
> Caused by: com.microsoft.aad.msal4j.MsalServiceException: AADSTS700023: Client assertion audience claim does not match Realm issuer. Review the documentation at https://docs.microsoft.com/azure/active-directory/develop/active-directory-certificate-credentials .

I tried to refer to the link in the exception but unable to fix a way to configure ClientCertificateCredential correctly.

**Code sample** -
``` java
ClientCertificateCredential clientCertificateCredential = new ClientCertificateCredentialBuilder()
    .tenantId("<FPA_TENANT_ID>")
    .clientId("<FPA_CLIENT_ID>")
    .pemCertificate("<FPA_CERT>")
    .sendCertificateChain(true)
    .additionallyAllowedTenants("*")
    .build();

// create SecretClient using FPA credentials and C1 KV URL
SecretClient client = new SecretClientBuilder()
    .vaultUrl("<C1_KV_URL>")
    .credential(clientCertificateCredential)
    .buildClient();

// Throws `MsalServiceException: AADSTS700023: Client assertion audience claim does not match Realm issuer.`
KeyVaultSecret keyVaultSecret = client.getSecret("<SECRET_NAME>");

``` 

***Why is this not a Bug or a feature Request?***
To me, it looks like more of a configuration that I am not able to figure out than a bug.

**Setup (please complete the following information if applicable):**
 - OS: Windows 11
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-identity:1.8.2
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by g2vinay** [comment]
@y0geshdev 

Thank you for reporting this issue.

Here are the steps you can consider to troubleshoot this issue:

1. Since you're using a First Party App (FPA) in one tenant to access resources (Key Vault) in another tenant (C1), make sure that you have configured cross-tenant access correctly. Azure AD B2B (Business to Business) might need to be set up to allow your FPA to be recognized and authorized in the C1 tenant. This involves adding the external application or service principal as a guest in the C1 tenant.

2. Ensure the application registration (for the FPA) has the necessary permissions to access Key Vault in the C1 tenant. If the FPA is properly registered and permissioned in its home tenant but hasn't been given access or doesn't have the right permissions in the C1 tenant, you'll encounter authorization issues.

3.  Double-check the tenantId and clientId values you're using in your ClientCertificateCredentialBuilder setup. The tenantId should refer to the tenant where the Key Vault resides (C1 tenant), assuming you're trying to access C1's resources. If you're intending to authenticate against the FPA's tenant, ensure that all configurations align with cross-tenant access requirements.

4. The error might also stem from issues with the certificate itself. Ensure that the certificate used (<FPA_CERT>) is correctly uploaded in both tenants (if necessary) and that it matches the one associated with the application registration in Azure AD.

**Comment by g2vinay** [comment]
Closing this, let us know if issue still persists.
