### ISSUE TITLE
Investigate Changes to Context object

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#3746]
The Context object is an immutable link list and is used to pass data through the pipeline during service calls. Its use cases have been expanded to include passing tracing data, with that new case we should determine the expected cases that context will be used.

If that same context is expected to be used for many service calls it might be better to change the data structure to something else otherwise the context linked list could grow fairly large.

**Comment by alzimmermsft** [comment]
Any changes to this object will need to maintain current functionality where the passed context isn't mutated.

**Comment by anuchandy** [comment]
Context is a tree-like structure made of linked-list. When we added context to azure-core, I had a chat with @JeffreyRichter regarding the need for using such an internal data structure to store data. Copy-pasting Jeffrey's comments below, in case it helps to set some *context* for this context work.

-------------

>> Why tree-like structure for Context?
 
**JeffreyRichter**: It’s a lifetime issue. A caller has a "root" context and then "logically" adds a key-value pair and then passes the "new" context to a method. When the method returns, the key-value pair should no longer exist. That is, we don’t want the key-value pair accidentally passed from the original caller to some another method. So, I think the best way to accomplish this semantic it to use a tree data structure where key-value pair nodes also have a reference to their parent node. The "context" is the deepest node at any given point in time. 

Here’s an example: Customer code has added a key-value pair with "api-version" set to "2018-07-27", some pipeline policy looks for this and changes a query parameter to this value before making all I/O requests. Customer passes this context to a client library method that wants to add a key-value pair to the context such as "meta-operation:uploading foo.bin", this should NOT affect the customer’s context because they can continue to use their context for other operations (like downloading a file) and this new "meta-operation:uploading foo.bin" doesn’t make any sense for the download operation. When the download operation is complete, the  "meta-operation:uploading foo.bin" node would just get GC’d.

---------

**Comment by alzimmermsft** [comment]
Given that this has been GA'd there will be no major redesigns to the object, closing issue.
