### ISSUE TITLE
Define if we need `HttpRequestMetadata` is required or if its APIs could be composed soewhere else.

### ISSUE THREAD

**Issue by vcolin7** [Azure/azure-sdk-for-java#38096]

**Comment by alzimmermsft** [comment]
To set some direction on this, I'll raise the question on how much of implementation and SDK authoring we want to hide from the public API.

The initial design of `HttpRequestMetadata` was in the direction of reducing the amount hidden implementation and module-info opens to specific module code we have and reducing magic values getting based around through `Context` which doesn't have type safety. I personally would rather continue down this direction as it allows for more flexibility in SDK authoring (not as much magic or needing to crack open the module system) and should help make debugging simpler as there isn't a magic box of stuff (`Context`) being used.

I'm all for moving the type, changing what information it carries, and where it's used. I think overall it should be used to simplify logic and control flow within core code.

**Comment by alzimmermsft** [comment]
Right now, the question left on `HttpRequestMetadata` isn't its purpose but whether the design needs to change further.

`HttpRequestMetadata` composes information about the request being made such as:

- Whether data should be eagerly read from the network. For example, if the request will be read as JSON to an object, reading the response eagerly could allow for the connection to be closed quicker and any exception during reading the response is handled down near the HTTP layer rather than at the deserialization layer.
- A `ClientLogger` associated with the method making the request. This removes the need for `HttpLoggingPolicy` to manage a cache of loggers associated with methods making calls.
- How many times the request has been retried. Before this was managed by `Context` which is a generic object store, now it doesn't need type checking for being a number and is just a quick property access rather than a linked list search (which is how context works).
