### ISSUE TITLE
Issues while connecting to Cosmos Db in Spark 3.3.0 and Scala 2.12.14 running in Google Cloud Cluster

### ISSUE THREAD

**Issue by vishal-raj-pandita** [Azure/azure-sdk-for-java#38233]
I am currently working on adding data from dataframe to the comos container in existing spark job. I have followed the document
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3_2-12/docs/quick-start.md

The code for connecting to cosmos

val cfg = Map("spark.cosmos.accountEndpoint" -> cosmosEndpoint,
      "spark.cosmos.accountKey" -> cosmosMasterKey,
      "spark.cosmos.database" -> cosmosDatabaseName,
      "spark.cosmos.container" -> cosmosContainerName,
      "spark.cosmos.read.inferSchema.enabled" -> "true"
    )
    spark.conf.set(s"spark.sql.catalog.cosmosCatalog", "com.azure.cosmos.spark.CosmosCatalog")
    spark.conf.set(s"spark.sql.catalog.cosmosCatalog.spark.cosmos.accountEndpoint", cosmosEndpoint)
    spark.conf.set(s"spark.sql.catalog.cosmosCatalog.spark.cosmos.accountKey", cosmosMasterKey)

while executing the below line i am getting error
    val cosmos = spark.read.format("cosmos.oltp")
      .options(cfg)
      .load()

I am getting the error as Exception in thread "main" org.apache.spark.sql.AnalysisException: cosmos.oltp is not a valid Spark SQL Data Source.;

Similarly if i try to execute 
spark.sql(s"CREATE DATABASE IF NOT EXISTS cosmosCatalog.${cosmosDatabaseName};") I am getting error as 
main" org.apache.spark.sql.catalyst.parser.ParseException: 
mismatched input '.' expecting <EOF>(line 1, pos 43)

== SQL ==
CREATE DATABASE IF NOT EXISTS cosmosCatalog.dbname

I am using 
<dependency>
            <groupId>com.azure.cosmos.spark</groupId>
            <artifactId>azure-cosmos-spark_3-3_2-12</artifactId>
            <version>4.21.0</version>
</dependency>

It is getting installed in cluster as well . See the cluster logs below

**The jars for the packages stored in: /root/.ivy2/jars
:: loading settings :: url = jar:file:/usr/lib/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.google.cloud.spark#spark-bigquery-with-dependencies_2.12 added as a dependency
com.azure.cosmos.spark#azure-cosmos-spark_3-3_2-12 added as a dependency**

Can someone help here ?

**Comment by FabianMeiswinkel** [comment]
Spark tries to resolve the DataSource "cosmos.oltp" and is failing. "cosmos.oltp" is an alias defined - Spark uses reflection to find all classes implementing DataSourceRegister to use the alias dictionary. Usually it simply means the connector is not installed - although the logs you showed above indicate otherwise. One way to quickly check is to replace "cosmos.oltp" (the alias) with the full qualified name of the DataSource class "com.azure.cosmos.spark.CosmosItemsDataSource" - this would skip the alias lookup and directly try to instantiate the class in Spark. If that still fails the jar is definitely not on the class path (or the is a dependency confilct preventing it from being loaded) cluster logs would be needed to investigate more.

**Comment by FabianMeiswinkel** [comment]
Customer confirmed offline that the jar was simply missing from the GCP image. After fixing that, it started working.
