### ISSUE TITLE
Encountered a NullPointerException in the code. The error message is as follows: java.lang.NullPointerException: Cannot invoke "com.azure.storage.blob.implementation.models.BlobItemPropertiesInternal.getBlobType()" because "this.internalProperties" is null

### ISSUE THREAD

**Issue by Dsilk1** [Azure/azure-sdk-for-java#38249]
**Describe the bug**
Encountering a NullPointerException during execution due to an attempt to invoke com.azure.storage.blob.implementation.models.BlobItemPropertiesInternal.getBlobType() on a null object (this.internalProperties).

***Exception or Stack Trace***
java.lang.NullPointerException: Cannot invoke "com.azure.storage.blob.implementation.models.BlobItemPropertiesInternal.getBlobType()" because "this.internalProperties" is null
    at BlobItemProperties properties = blobItem.getProperties();
       System.out.println("Blob  type: " + properties.getBlobType());
    // Additional lines from the stack trace...

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

            for (BlobItem blobItem : containerClient.listBlobsByHierarchy("")) {			
			System.out.println("Blob Name: " + blobItem.getName());
			BlobItemProperties properties = blobItem.getProperties();			

			System.out.println("Blob  type: " + properties.getBlobType());
			
		}
**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: 17
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@ibrahimrabab could you please assist?

**Comment by ibrahimrabab** [comment]
Hi @Dsilk1
The reason why you're seeing a NullPointerException when invoking any calls on the BlobProperties is because the BlobItem itself may be a prefix. If it is a prefix, you will not be able to view its properties.  
To avoid this, you can add a check to see if the BlobItem is a prefix,

`for (BlobItem blobItem : containerClient.listBlobsByHierarchy("")) {`			
`		System.out.println("Blob Name: " + blobItem.getName());`
`               if (!blobItem.isPrefix()) {`
`		      BlobItemProperties properties = blobItem.getProperties();`			
`		      System.out.println("Blob  type: " + properties.getBlobType());`
`              }`
		
`	}`

Hope this helps!
