### ISSUE TITLE
[QUERY] Can azure-cosmos support OkHttp, or can azure-netty stop leaving native libraries behind?

### ISSUE THREAD

**Issue by hildo** [Azure/azure-sdk-for-java#38250]
**Query/Question**
I have an application that uses a number of the Azure Java SDK libraries. We noticed some time ago that, but default, the azure libraries uses netty http clients. The issue with this, however, is every time our service starts, the azure netty library (azure-core-http-netty) creates a DLL file in our local filesystem in a tmp folder but does not remove it when the process stops. So our disk was (eventually) filling up.

To avoid this, we followed the [documented practice](https://learn.microsoft.com/en-us/azure/developer/java/sdk/http-client-pipeline) to replace Netty and use OkHttp. And this worked fine.

We have recently updated our sdk for Azure Cosmos to com.azure:azure-cosmos:4.48.0 When we used this library, it is creating the DLL files. However, when we follow the same process the application fails with the exception

Caused by: java.lang.NoClassDefFoundError: reactor/netty/resources/ConnectionProvider
at com.azure.cosmos.implementation.http.HttpClient.createFixed(HttpClient.java:56)
at com.azure.cosmos.implementation.RxDocumentClientImpl.httpClient(RxDocumentClientImpl.java:674)
at com.azure.cosmos.implementation.RxDocumentClientImpl.<init>(RxDocumentClientImpl.java:471)
at com.azure.cosmos.implementation.RxDocumentClientImpl.<init>(RxDocumentClientImpl.java:305)
at com.azure.cosmos.implementation.RxDocumentClientImpl.<init>(RxDocumentClientImpl.java:267)
at com.azure.cosmos.implementation.AsyncDocumentClient$Builder.build(AsyncDocumentClient.java:269)
at com.azure.cosmos.CosmosAsyncClient.<init>(CosmosAsyncClient.java:170)
at com.azure.cosmos.CosmosClientBuilder.buildAsyncClient(CosmosClientBuilder.java:1052)
at com.azure.cosmos.CosmosClient.<init>(CosmosClient.java:38)
at com.azure.cosmos.CosmosClientBuilder.buildClient(CosmosClientBuilder.java:1086)

Is it possible for the azure-cosmos library to follow the patterns of other Azure Java SDK libraries and use a different httpClient?

Alternatively, is it possible to configure the netty http client so that it does not leave dll files behind? If it did not fill up the file system over time, I'd be happy to use netty instead of OkHttp. It looks like it has a dependency on netty-tcnative, and I would like to think that the http client wouldn't need that?

Thanks for any help

***Why is this not a Bug or a feature Request?***
There is a bug here, I just don't know which one (or is it just one?).

When code writes a dll file to a tmp directory when the process starts, it should clean up after itself.  Leaving it behind and filling up a file system over time is a bug to me.  So, one bug is to be able to use azure-core-http-netty in a manner that doesn't leave files behind when the process falls over.

If that is not possible, then a second bug is to ensure that azure-cosmos behaves consistently with other Azure Java SDK modules that allow alternative http clients to be used instead of just Netty.

At the moment, when using azure-cosmos, I have to use netty (which fills up the disk space because it adds a DLL to the file system every time the service starts and doesn't remove it) and I cannot configure it to use an alternative like I can for other Azure Java SDKs

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - Library/Libraries: com.azure:azure-cosmos:4.48.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by hildo** [comment]
Hi.  Is anyone watching this?  It seems like a shortcoming in the library, where it is not consistent with the rest of the Java SDK

**Comment by kushagraThapar** [comment]
@hildo apologies for the late reply. It looks like you are facing 2 issues. One is regarding creation of dll files - which is because of azure-core-http-netty. To clarify, azure-cosmos SDK does not use azure-core-http-netty for the http client, it creates its own client. So if you are just using azure-cosmos, it should not create dll files. 

For the exception that you are seeing, it looks like you have other dependencies which are bringing an older version of reactor-netty, which is causing the runtime dependency conflict. To prevent that, please make sure to use the correct version of reactor-netty which you can find you using maven ui - https://mvnrepository.com/artifact/com.azure/azure-cosmos/4.48.0
If you notice, azure-cosmos 4.48.0 depends on azure-core-http-netty, which further depends on reactor-netty library. You can follow the maven version links to match the 3rd party library versions to avoid version conflicts.

**Comment by hildo** [comment]
Hi.  Thanks for the feedback.  To be clear, we are using azure-cosmos:4.48.0, via a transitive dependency using the azure-sdk-bom (version 1.2.15).  From what I am seeing, azure-cosmos is bringing in the boringssl-static library (which contains the DLL that azure-core-http-netty is writing to the Temp folder and not cleaning up after itself).  To prevent this from happening, I have had to explicitly defined an exclusion so our application doesn't include the tcnative library

```
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-cosmos</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>netty-tcnative-boringssl-static</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

```

I do agree with you that cosmos isn't doing this, but azure's reactor library (upon which azure cosmos depends) is.  But, I disagree that, in this case, another dependency is bringing in this.  That is not what I am seeing (and not what mvn dependency:tree shows me).

There are two issues here, as you say

- If azure libraries write files to the file system, they should clean up after themselves
- azure-cosmos does not support the ability to use alternate http client libraries as per the documented standard and implemented in other azure libraries.  When we faced this in the past, we elected to use the OkHttp client implementation because it did not make a mess of our filesystem.  With azure-cosmos, we no longer have that option.

**Comment by kushagraThapar** [comment]
Thanks for clarification @hildo , however, azure-cosmos gets all the netty dependencies from azure-core-http-netty, even the boringssl - as it is required for optimization on unix based machines.

@alzimmermsft can you please look into azure-core-http-netty on why it is not cleaning up dlls that are written to the temp folder. 

Regarding the other issue of azure-cosmos not supporting other http clients, it is currently not in our backlog, but you can continue using reactor-netty http client that azure-cosmos internally uses without using boring ssl netty library, is that still an issue?

**Comment by hildo** [comment]
Ultimately, I don't really care.  We had been using okHttp because we didn't want our filesystem to fill up over time.  With azure-cosmos, that is no longer an option it seems (again, I am only raising it because other Azure SDKs support that, so I am surprised it's not even in your backlog... it will make azure-cosmos incongruent with other Azure SDKs).

As I mentioned before, we've stopped overriding the HTTP client, but ensured that we don't bring in the dependency that results in filling up the file system.  I am happy for azure-cosmos to use the client it wants to use, I just need it to respect the environment in which it runs (directly or indirectly).  And, being unaware of the contents of azure-core-http-netty, I was not confident that I could just exclude that and include reactor-netty... in case azure-core-http-netty contains additional configurations azure-core needs.

I have a work around, and I think answers for the two questions: 

- someone who looks after azure-core-http-netty will see if there is anything to do there
- no plans to support other http clients

**Comment by kushagraThapar** [comment]
@hildo, I understand your point, however, the reason azure-cosmos doesn't support passing different http clients is because we don't recommend gateway mode or any http-based interaction with Cosmos DB service. Given Java SDK works primarily on DIRECT mode (which is based on TCP protocol), is more efficient (in terms of latency and performance) and cost effective. This is different than other azure SDKs which are mainly http REST API wrappers. That is why we don't promote customers using Gateway mode and using their own http clients.

That being said, I completely agree, that if azure-cosmos is using a library for its implementation, it should make sure the library is not creating memory leaks or anything of that sort. 

I will follow up internally on this boringssl issue with @alzimmermsft and @xinlian12. Will keep you posted, thanks!

**Comment by alzimmermsft** [comment]
Hi @hildo, the DLLs in temp are created by Netty when attempting to load the native code for TcNative, performed by https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/NativeLibraryLoader.java. I just went through a debugging process of this and it seems that when it tries to delete after loading the native dependency it fails because the JVM has the file in use.

<img width="339" alt="image" src="https://github.com/Azure/azure-sdk-for-java/assets/48699787/6e2c59ae-6343-4c22-8fe4-cbe37e0a0143">

When this happens, it looks to try a fallback of `tmpFile.deleteOnExit()` but I'm not sure if the JVM will release the handle on the file before this delete attempt is tried as well.

**Comment by hildo** [comment]
Thanks for all the great information! It looks like the comment expects that the temp file can be deleted, but I expect in Windows environments the handles are held (perhaps it doesn't do this in Linux OS).

![image](https://github.com/Azure/azure-sdk-for-java/assets/1204224/ae86679a-6f67-4c38-8256-f9b641e27502)

I guess it attempts to delete is straight away (and fails) and then attempts to delete it when the JVM completes and fails again.

So, can I ask one more question?  What I have done, as I mentioned before, was to exclude the tcnative dependency.  Because the library is not in the classpath, it doesn't get extracted.  So, I've fixed the immediate problem that way.  So far, it seems to be working fine without the DLL.

Would you be aware of any issues I am introducing by not using the Static DLL with the JVM?

**Comment by alzimmermsft** [comment]
@hildo, from what we've researched in the past, no. Not using the static DLL should work the same as using the static DLL, the only downside to not using the static DLL is TLS/SSL performance is worse without it as it calls through Java code instead of native code.

**Comment by hildo** [comment]
@alzimmermsft thank you for sharing your research.  We can keep an eye on the performance and see if it's something that becomes a problem.  So far, so good, but I'll continue to keep a watch.

Thank you to everyone else (@kushagraThapar ) who took the time to provide this information and help me understand what was happening.
