### ISSUE TITLE
Provide documentation on how to use the Cosmos Java SDK with open telemetry

### ISSUE THREAD

**Issue by CraftyFella** [Azure/azure-sdk-for-java#38354]
**Is your feature request related to a problem? Please describe.**

It's not a feature request it's a "better docs" request. Currently there is limited information on how to setup the azure cosmos client so that it pushes traces and metrics upto an OTEL library. see https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/sdk-observability?tabs=java

There appears to see some settings available e.g. 

```java
        client = CosmosClientBuilder()
...
            .clientTelemetryEnabled(true)
            .clientTelemetryConfig(
                CosmosClientTelemetryConfig()
                    .sendClientTelemetryToService(true)
                    .tracingOptions(
                        TracingOptions()
                            .setEnabled(true)
                    )
```

**Describe the solution you'd like**
I would like an example application I can clone and look at that pushes cosmos azure metrics to an OTEL service like jaeger. 

**Describe alternatives you've considered**
Please don't leave off java when creating docs.

**Additional context**
link above

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by FabianMeiswinkel** [comment]
Hi @CraftyFella - capturing Otel telemetry should work without any code changes when you add an OTel Java-Agent. So, there is not much special to Cosmos DB SDK.

See https://opentelemetry.io/docs/languages/java/automatic/agent-config/ for the OTel docs on how to use a java agent.

That said, there are a few options to tune the experience:
- Metrics - in case you want to disable certain dimensions/tags at the source vs. filtering them out in MicroMeter or when you want to manually specify the MeterRegistry - https://github.com/Azure/azure-sdk-for-java/blob/789fef47a9de372fda4fbbb4185b4e8d179017c0/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/models/CosmosClientTelemetryConfig.java#L143-L175
- The SDK will log further diagnostic details (the diagnostic string previously available for cx to log/trace themselves) based on whether a request failed or when a request took longer than expected. These thresholds can be overridden here - https://github.com/Azure/azure-sdk-for-java/blob/789fef47a9de372fda4fbbb4185b4e8d179017c0/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/models/CosmosClientTelemetryConfig.java#L200-L212
- By default tracing only happens on operation-level - like when you call CosmosAsyncContainer.readItem one trace for the entire operation will be emitted (even when you use strong consistency and behind the scenes two network requests are made) - if the operation takes longer than expected in addition the diagnostics string is traced with all granular info. This is done because when also enabling network traces the traces become significantly more noisy. If you still want to enable network level traces, you can use this API to do opt-in. https://github.com/Azure/azure-sdk-for-java/blob/789fef47a9de372fda4fbbb4185b4e8d179017c0/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/models/CosmosClientTelemetryConfig.java#L387-L395

Last but not least - we are aware that we need to provide better docs for these relatively new features. We are working on it and will add docs in the next few weeks.

**Comment by CraftyFella** [comment]
We don’t use the agent which could explain things. I know the Otel libraries quite well but all the code I looked at has Microsoft versions of everything. E.g. a tracer. Where is the bridge that sets up the Microsoft classes from the otel equivalents? I’m wondering if it requires the global open telemetry object to be setup? If so is there a way to inject that into the library somehow? I’ll take a look at your links tomorrow and thanks for the speedy response
