### ISSUE TITLE
AccessTokenCache questions / feedback

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#38387]
**Differences between AccessToken.getToken and AccessToken.getTokenSync**

In `Mono<AccessToken> getToken` it has a `repeatWhenEmpty` loop to keep resubscribing to the `Mono` until a token is acquired. `AccessToken getTokenSync` doesn't have a loop to keep trying while the return value is null. A quick review of the code shows that it should be possible for null to be returned from `getTokenSync`.

**Logging level when a token is acquired**

`AccessTokenCache` logs an `INFO` level log when a token is acquired. Should look into lowering the verbosity on this as it isn't really useful as information and is more of a verbose level log. 
Tracing can cover observability gap there (records a span when actual request is made along with the status). We can also consider adding cache/token metrics  - there was a customer asking how to record them for .NET identity lib.

**Comment by billwert** [comment]
The log level piece is fixed by #41648.



@alzimmermsft Looking at the code for `retrieveTokenSync`/`retrieveToken', I think the idea here is that in the sync case as we have taken a lock we know we are the only thread manipulating the cache. I don't actually see `retrieveTokenSync` returning a null ever; it'll either refresh or use the cached token, and return that. If it fails it will throw.

**Comment by billwert** [comment]
Logging was resolved in #41648. After analysis I think the `null` concern is addressed.
