### ISSUE TITLE
Spring Cloud Azure version 5.8.0 is not compatible to Spring Boot 3.1.x /  3.0.x

### ISSUE THREAD

**Issue by hayosc** [Azure/azure-sdk-for-java#38531]
**Query**
Please update https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping in "Which Version of Spring Cloud Azure Should I Use". Spring Cloud Azure version 5.8.0 is not compatible to Spring Boot 3.1.x /  3.0.x. 

For 3.1.x use 5.7.0. For 3.0.x. check yourself.

***Why is this not a Bug or a feature Request?***
Because it is about wrong documentation. But it may lead to big trouble.

**Comment by Netyyyy** [comment]
Hi @hayosc , thanks for reaching out. 
Could help provide your incompatible project? I try to use Spring Cloud Azure 5.8.0 with Spring Boot 3.1.2 and 3.0.2, but it works.

**Comment by alexache** [comment]
It doesn't work to me because of the following dependency tree:
Spring Cloud Azure 5.8.0 -> spring-cloud-azure-autoconfigure 5.8.0 -> azure-messaging-servicebus 7.14.7.

This lib in class ServiceBusClientBuilder uses deprecated method Schedulers.elastic() of reactor-core 3.4.34.
reactor-core version in Spring Boot 3.2 is 3.6.X that doesn't have this method at all hence:
java.lang.NoSuchMethodError: reactor.core.scheduler.Schedulers.elastic() on ServiceBusSenderClientBuilder.buildClient

**Comment by Netyyyy** [comment]
Hi @alexache , azure-messaging-servicebus 7.14.7 already replaced `Schedulers.elastic()` and I don't find it in lib, https://github.com/Azure/azure-sdk-for-java/blob/f4b5e64ea6cc01844c3725e916c87bdd4e8248b9/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusClientBuilder.java#L952 
So could help provide your minimal codes?

**Comment by alexache** [comment]
Hi @Netyyyy, you're right. 
Even though I've bumped the version and reloaded cache - IDE was still pointing at 7.8.0 version instead.

**Comment by Netyyyy** [comment]
> Hi @Netyyyy, you're right. Even though I've bumped the version and reloaded cache - IDE was still pointing at 7.8.0 version instead.

That's strange, do you directly use azure-messaging-servicebus or other Service Bus dependencies?
