### ISSUE TITLE
[FEATURE REQ] eng, move SDK automation out of eng/mgmt folder

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#38985]
The script relates to SDK automation was initially only for management-plane. Hence, they are historically under https://github.com/Azure/azure-sdk-for-java/tree/main/eng/mgmt/automation

Now, since it works for both data-plane and management-plane, we need to re-arrange the folders.

This would need to be updated accordingly
https://github.com/Azure/azure-rest-api-specs/blob/main/specificationRepositoryConfiguration.json#L56
```[tasklist]
### SDK Automation impacts
- [x] 1. eng/mgmt/automation/swagger_to_sdk_config.json(init.sh, generate.py, install_instruction.py)
- [x] 2. [azure-rest-api-specs/specificationRepositoryConfiguration.json](https://github.com/Azure/azure-rest-api-specs/blob/main/specificationRepositoryConfiguration.json#L56)(swagger_to_sdk_config.json)
```

```[tasklist]
### CodeGen Impacts
- [x] 1. eng/mgmt/automation/generation.yml(generate.py)
- [x] 2. eng/mgmt/automation/generate_data.yml(generate_data.py)
- [x] 3. [java - client generation - data](https://dev.azure.com/azure-sdk/internal/_build?definitionId=3590&_a=summary)(generate_data.yml)
- [x] 4. [java - lite generation - mgmt](https://dev.azure.com/azure-sdk/internal/_build?definitionId=2238)(generate.yml)
- [x] 5. sdk/resourcemanager/autocent.js(api-specs.yaml)
- [x] 6. [release-automation-devops/LiteRelease.java](https://github.com/weidongxu-microsoft/release-automation-devops/blob/0f2cfa252c7911ce355813bb38337f4594ab0c23/src/main/java/io/weidongxu/util/releaseautomation/LiteRelease.java#L77) (api-specs.yaml)
- [x] 7. eng/codegen_to_sdk_config.json(sdk_init.sh, sdk_generate.py)
```

**Comment by XiaofeiCao** [comment]
Scheduled after mpg generation script support. 
https://github.com/Azure/autorest.java/issues/2518

**Comment by XiaofeiCao** [comment]
@weidongxu-microsoft Do we want to move only SDK Automation related scripts, or all scripts under eng/mgmt?

I've listed both impacts in the issue description. I feel like moving them together(ultimately) since codegen also includes both data-plane and management-plane. 
If we move only SDK automation related code, shell scripts will still refer to generate script in eng/mgmt folder. 
Downside would be, we may need to memorize new generate.py location when generating code locally, e.g. `eng/automation/generate.py` and we almost always use this script to generate management-plane SDKs.

For new script location, I have `eng/automation` in mind.

We could start with SDK automation first, then the entire folder.

**Comment by weidongxu-microsoft** [comment]
I guess we can move them together. Just remove the `mgmt` in the middle likely be good enough.
