### ISSUE TITLE
[QUERY] In azure-spring-data-cosmos latest version How to enable indexMetrics?

### ISSUE THREAD

**Issue by loudywen** [Azure/azure-sdk-for-java#39102]
In azure-spring-data-cosmos latest version How to enable indexMetrics? @kushagraThapar

**Comment by kushagraThapar** [comment]
@loudywen its not implemented yet, but its in our backlog for the upcoming semester.
@TheovanKraay - FYI.

**Comment by loudywen** [comment]
@kushagraThapar thx for the reply. By the way, are there any workaround so that I can set it manually?

**Comment by kushagraThapar** [comment]
@loudywen - IndexMetrics are exposed through a public API in `CosmosQueryRequestOptions` - if possible for you, you can use this API - https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/models/CosmosQueryRequestOptions.java#L448 
however, it will be a bit difficult to use it in spring-data-cosmos, since the options are not exposed in spring-data-cosmos APIs.

**Comment by HeneryHawk** [comment]
I would also be interested in this feature as it gives further insight and analysis possibilities regarding query performance.

**Comment by kushagraThapar** [comment]
@trande4884 / @TheovanKraay this looks like a low hanging fruit, can we deliver it on priority?

**Comment by trande4884** [comment]
Reopening as this isn't done

**Comment by HeneryHawk** [comment]
/unresolve as the MR is not merged yet.
