### ISSUE TITLE
[Configuration] Support immediate reaction to certain properties

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#3934]
The spec states the following:

> DO NOT change behavior based on configuration changes that occur after the client is constructed. Hierarchies of clients inherit parent client configuration unless explicitly changed or overridden. Exceptions to this requirement are as follows:
> 
>  * Log level, which must take effect immediately across the Azure SDK.
>  * Tracing on/off, which must take effect immediately across the Azure SDK.

This suggests to me that we need some way of not holding the log level and tracing settings directly in the configuration map, but rather to have a `Supplier` that will compute them every time, upon request.

**Comment by alzimmermsft** [comment]
This is already done in Configuration is a slightly more roundabout way so that the logging -> check log level -> log configuration was loaded -> check log level doesn't infinite loop. 

Those two configurations are checked each time they are requested. If the value in the environment is that same as the configuration store the log level is returned. If the environment value is different than the configuration store the new value is stored and a message is logged about loading a configuration before the value is returned.
