### ISSUE TITLE
[OpenAI-Assistants] Support Assistant v2 API version

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#39769]
https://platform.openai.com/docs/assistants/whats-new

OpenAI announces they have a new Assistant API version. 
We need to investigate and support it in our SDK as well.

**Comment by jpalvarezl** [comment]
Spec for [Assistants V2 PR](https://github.com/Azure/azure-rest-api-specs/pull/29067) is under revision. 

In order to start work on this feature there are 2 blockers:
- [Assistant V1 streaming spec](https://github.com/Azure/azure-rest-api-specs/pull/28555)
- [Assistant V1 streaming in Java](https://github.com/Azure/azure-sdk-for-java/pull/39733) (this one is also blocked by the item above)
