### ISSUE TITLE
Is it missing partial update function for blob

### ISSUE THREAD

**Issue by quantrpeter** [Azure/azure-sdk-for-java#40291]
Hi All
    Is it missing partial update function for blob ? I want to test the random access to blob, read/write the middle part of blob.
thanks
Peter

**Comment by quantrpeter** [comment]
python sdk has upload_page(), but java seems missing it.

**Comment by quantrpeter** [comment]
If this is a missing feature. Shall we add it? I am from Hong Kong Programming Society, there are two students interested into it.

**Comment by seanmcc-msft** [comment]
This is already supported, please see this article - https://learn.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs

**Comment by ibrahimrabab** [comment]
Hi @quantrpeter 
The upload_page() function in Python is related to Page Blobs, are you asking if there is an equivalent of this method in Java? Because that would be this:

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/PageBlobClient.java#L362

**Comment by quantrpeter** [comment]
thanks you @seanmcc-msft and @ibrahimrabab
