### ISSUE TITLE
[FEATURE REQ] add a LIVE test for azure-resourcemanager-appcomplianceautomation

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#40623]
https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/appcomplianceautomation/azure-resourcemanager-appcomplianceautomation

context, we will be GA it this month, with TypeSpec and azure-json

Please check if we can add a simple LIVE for this service, if it is fine to create their resource.

**Comment by v-hongli1** [comment]
The `appComplianceAutomation` service needs to be used with `Microsoft Partner Center`, because the offer GUID serves as a unique identifier for marketplace offer in `Microsoft Partner Center`, and it's the key to connect the compliance report with marketplace offer(s). So it is recommended that the service does not add any live test cases.

**Comment by weidongxu-microsoft** [comment]
got it, close this
