### ISSUE TITLE
[BUG] azure-core-http-netty 1.15.1 contains wrong netty.version property

### ISSUE THREAD

**Issue by Sukhumi** [Azure/azure-sdk-for-java#40732]
# **Issue description**
Netty utility class is expecting an older version of Netty dependencies in `azure-core-http-netty 1.15.1`.

Check this POM file in the public Maven repo:

[azure-core-http-netty-1.15.1.pom](https://repo1.maven.org/maven2/com/azure/azure-core-http-netty/1.15.1/azure-core-http-netty-1.15.1.pom)

We can see that there are different version numbers of Netty:

- `4.1.108.Final` (the `netty.version` project property)
- `4.1.110.Final` (all individual Netty dependency versions)
Now, compare with the previous version:

[azure-core-http-netty-1.15.0.pom](https://repo1.maven.org/maven2/com/azure/azure-core-http-netty/1.15.0/azure-core-http-netty-1.15.0.pom)

We can see that it only contains a single version number, i.e. 4.1.108.Final.
___
# **Impact**
It is causing the `azure-core-http-netty.properties` file to contain wrong Netty version.

- Expected: `4.1.110.Final`
- Actual: `4.1.108.Final`
This value, if I guess right, is populated with the netty.version Maven property.

See: [azure-core-http-netty.properties (1.15.1)](https://github.com/Azure/azure-sdk-for-java/blob/azure-core-http-netty_1.15.1/sdk/core/azure-core-http-netty/src/main/resources/azure-core-http-netty.properties)
  
___
# **Exception or error**
There is one `INFO` level log:

> NettyUtility - The following is Netty version information that was found on the classpath: 'io.netty:netty-common' version: 4.1.110.Final, 'io.netty:netty-handler' version: 4.1.110.Final, 'io.netty:netty-handler-proxy' version: 4.1.110.Final, 'io.netty:netty-buffer' version: 4.1.110.Final, 'io.netty:netty-codec' version: 4.1.110.Final, 'io.netty:netty-codec-http' version: 4.1.110.Final, 'io.netty:netty-codec-http2' version: 4.1.110.Final, 'io.netty:netty-transport-native-unix-common' version: 4.1.110.Final, 'io.netty:netty-transport-native-epoll' version: 4.1.110.Final, 'io.netty:netty-transport-native-kqueue' version: 4.1.110.Final. The version of azure-core-http-netty being used was built with Netty version 4.1.108.Final and Netty Tcnative version 2.0.65.Final. If your application runs without issue this message can be ignored, otherwise please align the Netty versions used in your application. For more information, see https://aka.ms/azsdk/java/dependency/troubleshoot.
___
Same issue as https://github.com/Azure/azure-sdk-for-java/issues/39583, different netty versions

**Comment by alzimmermsft** [comment]
Thanks @Sukhumi, I've opened a PR which should resolve this and ensure this doesn't happen again in the furue.

**Comment by alzimmermsft** [comment]
Thanks for the call out on that @Sukhumi, I added in additional handling specifically for Netty TcNative.

**Comment by ad-okshaj** [comment]
I am facing same issue in my project. How to resolve? Please share solution / steps to fix.

**Comment by memetoec** [comment]
My env:
OS: Rocky 8.10
Java: Openjdk 17
Jenkins version: 2.462.1

Case: 

I was upgrading from 2.452.2 to 2.462.1, that went fine. I had a warning sying that the docker-build-step had security issues, decides to disable that plugin. After i Disabled that plugin, I got problems with my initial authentication. 
Probably not by disabling the plugin, but Jenkins started to act very slow. 

Found these lines in my logs after finally logging in: 

Aug 14, 2024 9:50:43 AM INFO com.microsoft.jenkins.azuread.AzureSecurityRealm doFinishLogin

Requesting oauth code time = 1722505 ms

Aug 14, 2024 9:50:44 AM INFO com.azure.core.util.logging.ClientLogger info

The following is Netty version information that was found on the classpath: 'io.netty:netty-common' (not found and is required), 'io.netty:netty-handler' (not found and is required), 'io.netty:netty-handler-proxy' (not found and is required), 'io.netty:netty-buffer' (not found and is required), 'io.netty:netty-codec' (not found and is required), 'io.netty:netty-codec-http' (not found and is required), 'io.netty:netty-codec-http2' (not found and is required). The version of azure-core-http-netty being used was built with Netty version 4.1.108.Final and Netty Tcnative version 2.0.65.Final. If your application runs without issue this message can be ignored, otherwise please align the Netty versions used in your application. For more information, see https://aka.ms/azsdk/java/dependency/troubleshoot.

It takes up to 30 minutes to access Jenkins, that's not good. 

I found this issue, and hope I'm on the right track? Does somebody have any clue here?

**Comment by alzimmermsft** [comment]
Hi @ad-okshaj, in a newer version of the `azure-core-http-netty` library the informational message was fixed to just state the versions that were able to be found and which versions the `azure-core-http-netty` library shipped with. There is no longer a statement about changing the Netty versions, and this message is just information for debugging scenarios as Netty may call native code where errors propagate with misleading context making debugging the issue harder. Or, more simply put, we log versions to help out in managed environments to be able to quickly determine whether the issue is a dependency conflict.

Hi @memetoec, I'm not sure this informational message is related to Jenkins being slow. To generate this message all that happens is a few class loader look ups and a META-INF resource check. This information message may just be a misdirection for the actual issue.
