### ISSUE TITLE
[BUG] Path is url-encoded twice when using the DataLakePathClientBuilder

### ISSUE THREAD

**Issue by therealjsie** [Azure/azure-sdk-for-java#41208]
**Describe the bug**

When instantiating a `DataLakeDirectoryClient` using a `DataLakePathClientBuilder`, the `pathName` is url-encoded twice when accessing it through the `directoryUrl` property.

Like this: `foo/bar -> foo%2Fbar -> foo%252Fbar` (see below for a code example)

**To Reproduce**

Run the test provided in the following section with the following dependencies for the new unexpected behavior:

```
    implementation(platform("com.azure:azure-sdk-bom:1.2.25"))
    implementation("com.azure:azure-identity")
    implementation("com.azure:azure-storage-blob")
    implementation("com.azure:azure-storage-file-datalake") (leads to version `12.19.1`)
```

As opposed to using the `azure-sdk-bom` in version `1.2.23`.

```
    implementation(platform("com.azure:azure-sdk-bom:1.2.23"))
    implementation("com.azure:azure-identity")
    implementation("com.azure:azure-storage-blob")
    implementation("com.azure:azure-storage-file-datalake") (leads to version `12.18.4`)
```

***Code Snippet***

```
    @Test
    fun `test`() {
        val pathName = "foo/bar"
        val urlEncodedPathName = Utility.encodeUrlPath(pathName)

        val azureClientCredentials = ClientSecretCredentialBuilder()
            .clientId("clientId")
            .clientSecret("clientSecret")
            .tenantId("tenantId")
            .build()

        val client = DataLakePathClientBuilder()
            .credential(azureClientCredentials)
            .endpoint("https://some-endpoint.blob.core.windows.net")
            .fileSystemName("foobar")
            .pathName(urlEncodedPathName)
            .buildDirectoryClient()

        println("urlEncodedPathName: $urlEncodedPathName")
        println("directoryPath: ${client.directoryPath}")
        println("directoryUrl: ${client.directoryUrl}")
    }
```

**Expected behavior**

What I expect to see (as in the previous version):

```
urlEncodedPathName: foo/bar
directoryPath: foo/bar
directoryUrl: https://some-endpoint.dfs.core.windows.net/foobar/foo%2Fbar
```

What I actually get:

```
urlEncodedPathName: foo/bar
directoryPath: foo%2Fbar
directoryUrl: https://some-endpoint.dfs.core.windows.net/foobar/foo%252Fbar
```

**Setup (please complete the following information):**
 - OS: MacOS, Ubuntu
 - IDE: IntelliJ
 - Library/Libraries: see above in "Reproduce" section
 - Java version: 21

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by therealjsie** [comment]
@ibrahimrabab @ibrandes @seanmcc-msft

It has been a while since I reported this, and I'm wondering if there is a chance to review the issue. Is our assumption or usage wrong, or is this actually a bug?

**Comment by kranstrom** [comment]
Hello, I'm also interested in this one. Providing some additional context as the behavior submitted still exists in the most recent `12.21.0` release of `com.azure/azure-storage-file-datalake`

As noted by @therealjsie , the behavior changed in `12.19.X` 

This simple Clojure example has the same issue:

```
(let [^DataLakeFileClient client (-> (DataLakePathClientBuilder.)
                                     (.endpoint "https://<storage-account>.dfs.core.windows.net/")
                                     (.fileSystemName "<fs-name>")
                                     (.pathName "foo/bar")
                                     (.sasToken "<sas-token>")
                                     (.buildFileClient))]
  (.getFilePath client))
;; => "foo/bar"    ;; version 12.18.4
;;=> "foo%2Fbar"    ;; version 12.19.0 - 12.21.0
```

It also means that when a file is uploaded, it will be written to the root of the file system as `foo%2Fbar` , rather than into the appropriate hierarchy `foo/bar`.

As the submitter, wondering if this is intended or a bug.

Thanks

**Comment by kranstrom** [comment]
Some additional info. The issue was introduced with commit https://github.com/Azure/azure-sdk-for-java/commit/4316086b1d03f324a1f2f93d043021c0c8c50539 created by @ibrahimrabab 

I think the intent of this commit is to pass the path as submitted in essence - supporting characters without encoding. Thus, forcing the user to pass an encoded string if this was desired. It seems the pathName as simply missed from what I can see. I've created the following PR as a result:

https://github.com/Azure/azure-sdk-for-java/pull/42007

**Comment by ibrahimrabab** [comment]
Hi @therealjsie @kranstrom 
thank you for reaching out and pointing out the issue! We've gone ahead and created a PR with the suggested changes to handle the encoded path when instantiating it via DataLakePathClientBuilder. While removing the instances of urlEncode & UrlDecode for blob names and path names, the change got missed for DataLakePathClientBuilder.pathName. PR is [here](https://github.com/Azure/azure-sdk-for-java/pull/42057)

**Comment by kranstrom** [comment]
Thanks @ibrahimrabab
