### ISSUE TITLE
[BUG] com.microsoft.azure.azure-storage-6.1.0.jar certificate incompatible with newer azure jar's certificate.

### ISSUE THREAD

**Issue by ericacy** [Azure/azure-sdk-for-java#4167]
**Describe the bug**
Java security exception when using classes under found in com.microsoft.azure.storage.blob package if both com.microsoft.azure.azure-storage-6.1.0.jar and com.microsoft.azure.azure-storage-blob-11.0.0.jar are loaded for use.

***Exception or Stack Trace***
SecurityException: class "com.microsoft.azure.storage.blob.StorageException"'s signer information does not match signer information of other classes in the same package
java.lang.SecurityException: class "com.microsoft.azure.storage.blob.StorageException"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:898) ~[na:1.8.0_161]
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668) ~[na:1.8.0_161]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:761) ~[na:1.8.0_161]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_161]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_161]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_161]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_161]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_161]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_161]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_161]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_161]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338) ~[na:1.8.0_161]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_161]

**To Reproduce**
If include com.microsoft.azure:azure-storage-blob:11.0.0 and com.microsoft.azure:azure:1.21.0 dependency. Transitively, this will bring in com.microsoft.azure.azure-storage-6.1.0.jar due to com.microsoft.azure:azure:1.21.0. Utilize any code inside com/microsoft/azure/storage/blob/ of com.microsoft.azure.azure-storage-6.1.0.jar such as com/microsoft/azure/storage/blob/SharedAccessBlobPermissions. In the same runtime, load blob classes in com.microsoft.azure:azure-storage-blob.jar such as com/microsoft/azure/storage/blob/StorageException.

Java class loader will throw an exception.

**Expected behavior**
com.microsoft.azure.azure-storage-6.1.0.jar to be signed with same certificate as rest of the azure libary jars.

**Additional context**
This is java's class loader comments:
 * @throws  SecurityException
     *          If an attempt is made to add this class to a package that
     *          contains classes that were signed by a different set of
     *          certificates than this class, or if <tt>name</tt> begins with
     *          "<tt>java.</tt>".

**Comment by ericacy** [comment]
Could it be the the com.microsoft.azure.azure-storage-6.1.0.jar certificate is expired?
When I run jarsigner on that jar, I get:
[entry was signed on 11/1/17 5:34 PM]
      X.509, CN=Microsoft Corporation, OU=Digital ID Class 3, O=Microsoft Corporation, L=Redmond, ST=Washington, C=US
      [certificate is valid from 3/10/16 12:00 AM to 4/9/19 11:59 PM]
      X.509, CN=VeriSign Class 3 Code Signing 2010 CA, OU=Terms of use at https://www.verisign.com/rpa (c)10, OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
      [certificate is valid from 2/8/10 12:00 AM to 2/7/20 11:59 PM]
      X.509, CN=VeriSign Class 3 Public Primary Certification Authority - G5, OU="(c) 2006 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
      [certificate is valid from 11/8/06 12:00 AM to 7/16/36 11:59 PM]

**Comment by kurtzeborn** [comment]
Thanks for opening this issue!  I'm working with @mozehgir to get this routed quickly for you.

**Comment by rickle-msft** [comment]
Hi, @ericacy. Thank you for opening this issue and we are sorry for the inconvenience. It is true that a certificate was rotated some time in the last few months, which has caused some difficulties. If you are committed to using v8 and v11 side-by-side, I'd request that you try pinning a newer version of the old architecture (like v8.3.0) in your pom. This should have been signed with the same certificate as v11.

That said, we actually would recommend that you pause development on v11. For a variety of reasons that I can explain if you are interested, we are recommending that customers either begin working with the preview of v12, which is similar to v11 with both some cosmetic and networking fixes (though the api surface is still changing) or that they stay entirely on v8. Working with the preview of v12 will also resolve this class loader error because v12 and v8 actually use different package names (com.azure vs. com.microsoft.azure).

Please let us know if you have further questions, concerns, or difficulties and we will be happy to assist you.

**Comment by zhusijia26** [comment]
Since answer provided, I will close this case. Please reopen is there are more questions.
