### ISSUE TITLE
New CosmosClient(s) created every 5 minutes?

### ISSUE THREAD

**Issue by igrigorov** [Azure/azure-sdk-for-java#41912]
**Query/Question**
We are seeing the following logs in our application, repeating X times every 5 minutes:

`com.azure.cosmos.implementation.RxDocumentClientImpl INFO cosmos-parallel-1 Getting database account endpoint from .....`

Investigating the log, we found [this issue](https://github.com/Azure/azure-sdk-for-java/issues/29528), where the symptoms are the same and the recommendation is:

> We recommend you implement CosmosClient/CosmosAsyncClientas as a singleton, and share the instance across your threads. Not only will this reduce the frequency or occurrence of this message, it will also help you reduce memory related problems, and improve performance on the client-side

Is there a misuse of Cosmos clients in the Azure Spring Data Cosmos implementation or there is something else which requires the 5-minute connection "polling"?

Additional info: after setting the option `spring.cloud.azure.cosmos.connection-sharing-across-clients-enabled: true`, it *seems* that the log occurrences have been reduced to X/2 per 5'

***Why is this not a Bug or a feature Request?***
It is possible that the new connection creation is by design, and not a bug

**Setup (please complete the following information if applicable):**
 - OS: Azure Spring Apps deployment
 - IDE: N/A
 - Library/Libraries: com.azure.spring:spring-cloud-azure-starter-data-cosmos
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by kushagraThapar** [comment]
@igrigorov - It is not creating new Cosmos Clients every 5 minutes. This log is coming from a background thread which runs as part of the Cosmos Java SDK which gets the database account metadata every 5 mins. There is whatsoever no issue at all with this log and is expected :)

The issue you referenced is where we provided the extra clarification of creating a single Cosmos Client per your application. 

I will close this issue since this is working as expected and there is no bug.
