### ISSUE TITLE
Supporting Tracing Contexts

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#4211]
There exists a need to support tracing in the Azure client libraries for Java. The existing proof of concept implementation is based on users providing their tracing context information via an explicit `Context` object that can be passed into service client methods, such that they are sent through the HTTP pipeline as appropriate (being transformed by a tracing-impl specific http policy). 

For **sync** API, there does not appear to be a better way other than having the `Context` object be an explicit argument into the API, that is:

```java
public Response<Setting> getSetting(int foo, Context context) { .. }
```

For **async** API, we could choose to use the Project Reactor subscriber context to accept these tracing details, rather than support an explicit `Context` argument. This has the benefit of there being one less argument for users to contend with, e.g:

```java
public class ContextFlowTest {

    public static void main(String[] args) {
        ContextFlowTest test = new ContextFlowTest();

        String result = test
            .clientLibraryAPI("Hello, ")
            .subscriberContext(ctx -> ctx.put("TRACER_IMPL", "OPEN_CENSUS"))
            .block();

        System.out.println(result);
    }

    public Mono<String> clientLibraryAPI(String prefix) {
        // convert subscriberContext coming into this method into a Context
        Context context = ...;
        return serviceCall(prefix, context);
    }

    private Mono<String> serviceCall(String prefix, Context context) {
        ...
    }
}
```

**Question One:** Do we have explicit `Context` arguments into our async API, or do we use the subscriber context to receive arguments? Is it better for API consistency, or API brevity?

If the subscriber context approach is used, we should write azure-core utility code to transform the provided subscriber context into an azure-core `Context`, before sending that through the service interface API. I have prototyped this in #3734.

**Question Two:** As we design our APIs, where often we have a min / max overload pattern, if not many overloads, do we have `Context` be a core argument on all overloads, or is Context only present on the max overload? What if we introduce the "`T` with `Response<T>` 'overload'" pattern of having most methods returning just `T` - do we have a `T` overload that accepts `Context`, or is `Context` only an argument on the `Response<T>` 'overload'?

**Comment by rickle-msft** [comment]
Question One: I lean towards using the subscriber context on async apis. I think in this case it's more a case of being idiomatic to the paradigm than enforcing arbitrary consistency. Even though they are in the same package, the async methods have their own expected behavior and customs, and it wouldn't be quite right to try to force async to conform to sync. 

Question Two: I'm not too familiar with what exactly we're doing in the way of tracing, but I'd sort of default to having Context be available only on the max overload for Response<T> and then we can add other overloads later as necessary. If we think tracing will be super common, though, we can have more overloads exposing it.

**Comment by joshfree** [comment]
Closing as tracing has since been implemented and shipped in the August and September client library previews.
