### ISSUE TITLE
Cosmos ChangeFeed date range for no sql api

### ISSUE THREAD

**Issue by PratapKumarChowdary** [Azure/azure-sdk-for-java#42146]
**Query/Question**
I'm working with Azure Cosmos DB NoSQL API and need to reprocess changes from the Change Feed within a specified date range or between two continuation tokens using the Java SDK.

Based on the documentation, I didn't find a direct option to filter changes by a date range. My use case requires retrieving changes that occurred between specific timestamps or by providing two continuation tokens.

Is there any way to implement this functionality using the Java SDK, or is there an alternative approach to achieve this? Any guidance or suggestions would be appreciated.

But as per Azure docs lsn will be tagged to multiple updated items, I know we can use setStartTime what about endTime(If possible I need documents which got updated to future date) or Can i implement in a way comparing b/w two continuationToken

**Comment by PratapKumarChowdary** [comment]
@kushagraThapar @pjohari-ms @TheovanKraay Any update on this, Could you please reply me on priority

**Comment by TheovanKraay** [comment]
@PratapKumarChowdary there's no direct way to filter the Change Feed by an end time or between two timestamps. But, you can combine setStartTime with continuation tokens to approximate this functionality, using either document timestamps or captured tokens to define your range. For example, using tokens, you could:

1. Get the start continuation token: You could either store the token or use setStartTime to define the starting point.
2. Fetch and store the continuation token: When the change feed reaches the time when you want to stop, store the continuation token.
3. Resume from the first token and stop at the second.

**Comment by PratapKumarChowdary** [comment]
@TheovanKraay Thanks for you reply, I've few last questions. Please answer

1. So you want me to store token when i reach endTime<=_ts(document), But how can i get current Token programmatically using java sdk can you please give me clue on this.
2. But some documents might got updated and moved to future date, what about those documents, Can't i get documents which got updated to future date in current changeFeedProcessorTask..?

**Comment by PratapKumarChowdary** [comment]
@kushagraThapar @pjohari-ms @TheovanKraay  We had some priority please answer as soon as possible

**Comment by TheovanKraay** [comment]
@PratapKumarChowdary - I am going to close this issue, because as I said, there is no direct way to filter the Change Feed by an end time or between two timestamps. So, your query has been answered. If you want to make a feature request, please raise a separate issue and tag it as feature request. But if you need this functionality quickly, you will need to build the business yourself as such a feature will not be built quickly.

With that said, I will try to close with a hint. If I understand correctly, your requirement is:

1. Start reading the Change Feed from a specified start date.
2. Stop reading based on a condition related to a date field within the documents themselves (i.e. not based on the Change Feed's LSN or continuation token). You need documents whose timestamps (or relevant date field in doc) fall within a desired time window.
3. Handle cases where documents may have been updated to reflect future dates but are still being processed in the current change feed batch/window.

Is that correct? 

The specifics of points 2 and 3 are not really clear to me, but you probably need something like below (using pull model and assuming an async container - this untested - please test it yourself and adjust it as you see fit). 

Also, if you have not seen them, take a look at [samples](https://github.com/Azure-Samples/azure-cosmos-java-sql-api-samples/tree/main/src/main/java/com/azure/cosmos/examples) repo which includes samples for pull model and change feed processor. 

```java
// Create options to start reading from a specific date
OffsetDateTime startTime = OffsetDateTime.parse("2024-09-01T00:00:00Z");  // Your start date
CosmosChangeFeedRequestOptions options = CosmosChangeFeedRequestOptions
        .createForProcessingFromPointInTime(startTime.toInstant(), FeedRange.forFullRange());

// Query the change feed asynchronously
container.queryChangeFeed(options, JsonNode.class).byPage()
        .subscribe(feedResponse -> {
            for (JsonNode change : feedResponse.getResults()) {
                // Assuming the document has a field named "updatedDate" (you need to adjust based on your schema)
                OffsetDateTime documentDate = OffsetDateTime.parse(change.get("updatedDate").asText());

                // Define the end date you want to stop at
                OffsetDateTime endDate = OffsetDateTime.parse("2024-10-01T00:00:00Z");

                // Check if the document falls within your desired time range
                if (documentDate.isBefore(endDate)) {
                    System.out.println("Processing document within date range: " + change.toString());
                    // Process the document
                } else {
                    // The document has been updated to a future date (beyond your end date)
                    System.out.println("Future dated document: " + change.toString());
                    // You can either:
                    // 1. Store it for future processing
                    // 2. Ignore it, based on your business logic
                }
            }

            // Get the continuation token to resume later if needed
            String continuationToken = feedResponse.getContinuationToken();
            System.out.println("Continuation Token: " + continuationToken);
        });
```
