### ISSUE TITLE
Example for downloading Asset files

### ISSUE THREAD

**Issue by anweiss** [Azure/azure-sdk-for-java#443]
Is there an example for downloading files contained within an asset? The `WritableBlobContainerContract` seems to define the mechanism by which assets can be created within an AMS account, but there doesn't seem to be one in the SDK for readable. If I create a `LocatorInfo` object based on the asset I'm trying to download, is there a way I can use this to get the URI of the asset and subsequently download it?

**Comment by novaterata** [comment]
@anweiss I found this issue because I was following the example you linked and could not figure out how to download an asset file. I think this issue should be re-opened because I can't for the life of me find an example of downloading a file using Java. The C# example uses a client that doesn't exist in the Java library.
