### ISSUE TITLE
permission denied(public key) when trying to ssh to vm

### ISSUE THREAD

**Issue by florakarniav** [Azure/azure-sdk-for-java#445]
Hello, 

I have created a virtual machine using this sdk. While I can normally ssh to virtual machines created by hand, the ones created by code using this sdk aren't accessible via ssh (permission denied(public key) error). Of course, I have created and uploaded a .cer and use the corresponing .jks for configuration in my code.
I would really appreciate some help, thank you in advance.

**Comment by bradygaster** [comment]
Thanks for the issue submission, @florakarniav - do you have a repro project or scenario? The team would like to have more information on the problem via a repro so we could resolve. With the information in the issue currently we don't have enough to troubleshoot or repro.

**Comment by RibeiroAna** [comment]
Hi @bradygaster 
I think I have a similar issue, I don't know if it is related with this issue or if I am doing something stupid. When I create a Linux VM by hand, it have a ssh endpoint as a pre-configured stuff. When I try to create a VM using this API, I can't in at all (even doing many tries) create a VM with a SSH endpoint, please, take a look at my code (speacially the method createRoleList) to see if I am doing something wrong (because I am trying to set the SSH EndPoint, but I am not having success), or if things are related: https://github.com/fogbow/fogbow-manager/blob/Azure/src/main/java/org/fogbowcloud/manager/core/plugins/compute/azure/AzureComputePlugin.java

**Comment by bradygaster** [comment]
I'll investigate with @devigned and he'll probably get back to you (or someone from the team).

**Comment by RibeiroAna** [comment]
Great, my problem of creating a SSH endpoint was solved by creating a new configuration set for the endpoint (the code I linked is updated, now there is a new method named createSSHConfiguration). But now I am sure I am having the same issue as  @florakarniav, I hope to hear from you soon.

**Comment by RibeiroAna** [comment]
The issue for me was solved, my problem was because of the vm image was not so friendly with cloud-init (I was using ubuntu 12.04), then I changed the image and everything worked well, now the plugin is about to begin the deployment. Thank you for your time and attention.

**Comment by jianghaolu** [comment]
No action to take. Please reopen if necessary.
