### ISSUE TITLE
Remove Netty API from our API

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#4555]
Our public APIs shouldn't contain any references to the Netty API and any current reference should be removed.

- [x] Remove the Netty whitelist in our custom Checkstyle
- [x] Remove all Netty API from public API
- [x] Performance tests of HTTP client before / after extraction of Netty (to compare ByteBuf with ByteBuffer)
- [x] Determine whitelisting for the Checkstyle rule where necessary (but try to limit this as much as possible)
- [x] Update Java spec to [disallow Netty API from public APIs](https://azuresdkspecs.z5.web.core.windows.net/JavaSpec.html#java-allowed-dependencies)
- [x] Extend the client library builder APIs to take an `httpClient` argument.

If the Android SDKs and Java SDKs will be sharing code this is even more important as Netty doesn't exist in Android

**Comment by joshfree** [comment]
@jianghaolu can you own driving this after your Preview 2 Identity and Storage feature work is completed?

**Comment by JonathanGiles** [comment]
A follow-up to the work I started in #4572 would be to remove the `proxy`, `wiretap`, and `port` API from `HttpClient`. These can then be introduced on a future `NettyHttpClientBuilder` class. Eventually we will add API to the builders for each of our client library so that people can specify an `HttpClient` so that they may customise as appropriate their client.

Going a step further along this path, we need to reconcile if our `HttpClient` interface needs to be changed such that a sync client can more easily fit into this design, or if a sync client would just wrap the response in a Mono.

**Comment by JonathanGiles** [comment]
Fixed by merging #4572, but leaving this issue open because there are still a few unchecked requirements in the initial description.
