### ISSUE TITLE
Increase unit test coverage

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#4951]
Some client libraries need to add unit tests. The coverage is low for some modules.
https://azuresdkartifacts.blob.core.windows.net/azure-sdk-for-java/test-coverage/index.html

**Comment by JonathanGiles** [comment]
@alzimmermsft Can you check why storage-blobs is so low? It looks like it is included in the /eng/jacoco-test-coverage project, but something must be configured incorrectly. Maybe related to Groovy/Spock tests?
@g2vinay Same goes for identity - I see lots of tests, but I don't see them registering in the report.

**Comment by alzimmermsft** [comment]
@JonathanGiles I suspect this is due to blobs not having playback records for unit tests so they can only be ran in live mode. Running the live tests shows that the coverage is almost inline with other libraries (and I think most that is missing is autogen models).
![Blob Test Coverage High Level](https://user-images.githubusercontent.com/48699787/62962279-78809880-bdb3-11e9-84cf-68f8a9088068.PNG)
![Blob Test Coverage Line Level](https://user-images.githubusercontent.com/48699787/62962280-79192f00-bdb3-11e9-825e-249d4e9b1102.PNG)

**Comment by g2vinay** [comment]
> @g2vinay Same goes for identity - I see lots of tests, but I don't see them registering in the report.
@JonathanGiles , The issue with Identity is that its using Power Mock to run its tests and Power Mock doesn't work well with Jacoco with on the fly instrumentation.
One possible solution is to add offline instrumentation in jacoc plugin config in Identity pom.
I'll add that and open a PR with the fix, assuming it works.

**Comment by alzimmermsft** [comment]
@joshfree Do we want to continue leaving this issue open? It's fairly vague and I'm wondering if we could break this down into more targeted issues.

**Comment by alzimmermsft** [comment]
Issue split into targeted issues for each module, see the following:

#6473 
#6474 
#6475 
#6476 
#6477 
#6478 
#6479 
#6480 
#6481 
#6482 
#6483 
#6484 
#6485
