### ISSUE TITLE
Switch to JUnit version 5 for unit tests in azure-core

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#4955]
Migrate to JUnit 5. Jonathan has a draft PR that can be used as starting point.
https://github.com/Azure/azure-sdk-for-java/pull/4483

**Comment by mclay** [comment]
hi @JonathanGiles, could you pls explain briefly what's left to be done here so i can finish it - pls. assign me this task

**Comment by JonathanGiles** [comment]
@mclay This is a relatively big task. For all `/sdk/<service>/azure-*` libraries, we remove junit 4 and replace it with junit 5. This will require some changes to the tests in some places as the JUnit 4 and JUnit 5 APIs differ somewhat. This could be decomposed into a number of sub-tasks, e.g. firstly focusing on `/sdk/core/azure-core` and the other core modules. Separate PRs could then be developed for Key Vault, Storage, etc. Because we only focus on the 'next-gen' client libraries, we only care about modules which begin with `azure-`.

If you're keen to take this on, we would love to accept your pull requests! I've assigned the issue to you.

**Comment by joshfree** [comment]
@mclay just a quick note that this issue doesn't apply to /sdk/storage as storage is using groovy tests and not JUnit

**Comment by JonathanGiles** [comment]
@mclay Let me know if you plan to pick this up and work on it, otherwise I'll reassign to myself or someone else so that we may begin to make this move. Thanks!

**Comment by mclay** [comment]
Hi @JonathanGiles i am on it and provide the first Bits of it until the End of this Week

**Comment by JonathanGiles** [comment]
Excellent news! Thanks for the update.
