### ISSUE TITLE
Azure Java SDK v12 is not downloading a file asynchronously

### ISSUE THREAD

**Issue by mgingios** [Azure/azure-sdk-for-java#5071]
**Describe the bug**
I am writing a quick proof-of-concept for downloading images from Azure Blob Storage using the Java 12 Azure Storage SDK. The following code works properly when I convert it to synchronous. However, despite the subscribe() at the bottom of the code, I only see the subscription message when I run this reactive method. The success and error handlers are not firing.  I've debugged and reviewed this code a lot, and cannot move forward, so I suspect that there may be a bug.

Thank you for your time and help.

***Exception or Stack Trace***
No exceptions are thrown.

**To Reproduce**
Insert proper values for the variables at the top of the method and run it.  You will the see subscription handler fire and print a message on your console, but the other handlers never fire nor provide any errors or feedback... Just silence.

***Code Snippet***
```
private fun azureReactorDownload() {

    var startTime = 0L
    var accountName = "abcd"
    var key = "09sd0908sd08f0s&&6^%"
    var endpoint = "https://${accountName}.blob.core.windows.net/$accountName
    var containerName = "mycontainer"
    var blobName = "animage.jpg"

    // Get the Blob Service client, so we can use it to access blobs, containers, etc.
    BlobServiceClientBuilder()
        // Container URL
        .endpoint(endpoint)
        .credential(
            SharedKeyCredential(
                accountName,
                key
            )
        )
        .buildAsyncClient()

        // Get the container client so we can work with our container and its blobs.
        .getContainerAsyncClient(containerName)

        // Get the block blob client so we can access individual blobs and include the path
        // within the container as part of the filename.
        .getBlockBlobAsyncClient(blobName)

        // Initiate the download of the desired blob.
        .download()
        .map { response ->
            // Drill down to the ByteBuffer.
            response.value()
        }
        .doOnSubscribe {
            println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Subscription arrived.")
            startTime = System.currentTimeMillis()
        }
        .doOnSuccess { data ->
            data.map { byteBuffer ->
                println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> READY TO WRITE TO THE FILE")
                byteBuffer.writeToFile("/tmp/azrxblobdownload.jpg")
                val elapsedTime = System.currentTimeMillis() - startTime
                println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Finished downloading blob in $elapsedTime ms.")
            }
        }
        .doOnError {
            println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Failed to download blob: ${it.localizedMessage}")
        }

        .subscribe()
}

fun ByteBuffer.writeToFile(path: String) {
    val fc = FileOutputStream(path).channel
    fc.write(this)
    fc.close()
}
```

**Expected behavior**
I expected to download a blob that exists in our Azure Blob Storage container.  Originally, I wrote a synchronous method that is the mirror image of this one, and it worked properly.  I am using the same values for the variables, so I don't know what is going on.

**Screenshots**
None required; No error messages, exceptions, or feedback, other than a successful subscription.

**Setup (please complete the following information):**
 - OS: Ubuntu 18.10, 64 bit
 - IDE : IntelliJ Ultimate 2019.2
 - Version of the Library used: com.azure:azure-storage-blob:12.0.0-preview.2

**Additional context**
I've attached my build.gradle.kts file.  I can provide a sample project, if necessary.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

[build.gradle.kts.txt](https://github.com/Azure/azure-sdk-for-java/files/3523767/build.gradle.kts.txt)

**Comment by anuchandy** [comment]
@mgingios by looking at the code, I guess issue can be due to the map operator used inside doOnSuccess, this never get subscribed hence never emit.

Could you try replacing the first map operator with flatmap then removing second map operator? 

The code will look like:

```java
        // Initiate the download of the desired blob.
        .download()
        .flatmap { response ->
            // Drill down to the ByteBuffer.
            response.value()
        }
        .doOnSubscribe {
            println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Subscription arrived.")
            startTime = System.currentTimeMillis()
        }
        .doOnSuccess { byteBuffer ->
                println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> READY TO WRITE TO THE FILE")
                byteBuffer.writeToFile("/tmp/azrxblobdownload.jpg")
                val elapsedTime = System.currentTimeMillis() - startTime
                println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Finished downloading blob in $elapsedTime ms.")
        }
        .doOnError {
            println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Failed to download blob: ${it.localizedMessage}")
        }

        .subscribe()
```

If this doesn't work then I will let dev working on storage module to dive deep.

**Comment by mgingios** [comment]
Hi Andy,

Thank you for taking a look at this issue so quickly.  I've made the simple changes, but, alas, I get code that won't build.  I've attached an image showing the changes and the error message.  I've also attached a zip file with a sample project that may be helpful.

Thanks, again,
Mike
![ErrorAfterMakingChanges](https://user-images.githubusercontent.com/51250312/63416201-dca6ec00-c3b3-11e9-8d2e-262f8f4aae30.png)
[storageperformance.zip](https://github.com/Azure/azure-sdk-for-java/files/3524324/storageperformance.zip)

**Comment by anuchandy** [comment]
@mgingios thanks for sharing the code. 

I see, return type of `download()` is `Mono<Response<Flux<ByteBuffer>>>`. `flatMapMany` operator has to be applied to extract `Flux<ByteBuffer>` from this mono. When we subscribe to such an extracted `Flux<ByteBuffer>`, the `doOnNext` can be called multiple times, each time with a chunk of the blob. This means, we will need necessary logic to append these chunks to same file.

```java
.getBlockBlobAsyncClient(blobName)
// Initiate the download of the desired blob.
.download()

.flatMapMany { response ->
    // Response<Flux<ByteBuffer>> to Flux<ByteBuffer>
    response.value()
}
.doOnSubscribe {
    println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Subscription arrived.")
    startTime = System.currentTimeMillis()
}
.doOnNext {
    // TODO:
    // doOnNext can be invoked by upstream multiple times, each call deliver a chunk of the blob in ByteBuffer,
    // hence the logic here should be to append the chunk to same file.
}
.doOnError {
    println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Failed to download blob: ${it.localizedMessage}")
}
.subscribe()
```

Tracking position of file cursor for append would be bit harder. SDK has a convince method that does this hard work - `downloadToFile(filePath)`. Implementation uses asynchronous file channel. Alternatively you could use this instead of dealing with append logic yourself? Here is the sample [usage](https://github.com/Azure/azure-sdk-for-java/blob/8935711b4ffb2621cbe5bbf8203f37d97a4083fb/sdk/storage/azure-storage-blob/src/samples/java/com/azure/storage/blob/BlobAsyncClientJavaDocCodeSnippets.java#L112).

**Comment by mgingios** [comment]
Wow! I totally didn't think about flatMapMany!  I will try both options, today.  Thank you very much for investigating this question and providing such a great response.  I've learned from it and I am sure that it will help others, too!

**Comment by anuchandy** [comment]
@mgingios - sure, thank you for using SDK and sharing clean repro description and code.

Please don't hesitate to reach out to us if you have any feedback on SDK usability.

**Comment by mgingios** [comment]
Thank you!  By the way, to answer your question about why I was using download rather than downloadToFile...  I will use download so I can get a stream from the blob and flow it through our distributed app. :)

**Comment by mgingios** [comment]
Arggg...  So, I had some time to review the code change and, unfortunately, I am stuck...  The subscribe only fires the doOnSubscribe when I use a .subscribe().  When I comment out the subscribe and use a .blockLast(), everything works.  So, I've focused on trying to debug why the subscribe is not working, and I have no clue. :(  I know that Azure is finding the blob and sending data with the .blockLast(), so something is not triggering the download with the subscribe.  I'd appreciate any ideas... I've run out of them! :)

```
        //.blockLast()
        // The code works and displays the following on the console:
        // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> CHUNK 1 FROM BLOB ARRIVED...
        // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Finished downloading 2 chunks of data for the blob in 1526 ms.

        // With subscribe, only the doOnSubscribe is firing and printing the following on the console.
        // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Subscription arrived.
        .subscribe()
```


Here is the latest version of the code:
```
private fun azureReactorDownloadMS() {

    var startTime = 0L

    val chunkCounter = AtomicInteger(0)

    // Get the Blob Service client, so we can use it to access blobs, containers, etc.
    val aa = BlobServiceClientBuilder()
        // Container URL
        .endpoint(kEndpoint)
        .credential(
            SharedKeyCredential(
                kAccountName,
                kAccountKey
            )
        )
        .buildAsyncClient()

        // Get the container client so we can work with our container and its blobs.
        .getContainerAsyncClient(kContainerName)

        // Get the block blob client so we can access individual blobs and include the path
        // within the container as part of the filename.
        .getBlockBlobAsyncClient(kBlobName)
        .download()
        // Response<Flux<ByteBuffer>> to Flux<ByteBuffer>
        .flatMapMany { response ->
            response.value()
        }
        .doOnSubscribe {
            println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Subscription arrived.")
            startTime = System.currentTimeMillis()
        }
        .doOnNext { byteBuffer ->
            println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> CHUNK ${chunkCounter.incrementAndGet()} FROM BLOB ARRIVED...")
        }
        .doOnComplete {
            val elapsedTime = System.currentTimeMillis() - startTime
            println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Finished downloading ${chunkCounter.incrementAndGet()} chunks of data for the blob in $elapsedTime ms.")
        }
        .doOnError {
            println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Failed to download blob: ${it.localizedMessage}")
        }

        //.blockLast()
        // The code works and displays the following on the console:
        // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> CHUNK 1 FROM BLOB ARRIVED...
        // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Finished downloading 2 chunks of data for the blob in 1526 ms.

        // With subscribe, only the doOnSubscribe is firing and printing the following on the console.
        // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Subscription arrived.
        .subscribe()
}
```

**Comment by anuchandy** [comment]
@mgingios thanks for explaining your use case.

The behavior you’re seeing is due to the "asynchronous" nature of the Single<?> returned by the `download()` method. This is expected actually.

The `subscribe()` call subscribe to the Single<?> in "Main Thread" and the lambda we provided in the `doOnSubscribe` gets called from the same “Main thread”.

The lambda we registered via `doOnNext` to receive ByteBuf chunks will get invoked from "IO Thread".

What is happening here is - the main thread is exiting before Flux<ByteBuf> complete the emission in different "IO Thread"s or even before it get a chance to emit.

As a test - If we put Thread.sleep(5000) after `subscribe()` [to delay the main thread termination by 5 sec] and print the thread id from `doOnSubscribe` and `doOnNext`, you can see result like:

```
doOnSubscribe: main
doOnNext: reactor-http-nio-1
```

When we call `blockingLast()`, it does subscription and wait for Flux<ByteBuf> emission to complete.

At first glance these kind of blocking call can be confusing and give us a feeling that things are not asynchronous. 

The real power reactive programming is -  the flexibility it provide that enable us to combine multiple reactive instances (Flux/Single instances) using operators like merge. Such a merge result in a new Flux instance which when blocked result in distributing work associated with all reactive instances into different threads. The framework takes care of scheduling, load balancing and ensure there is no race condition, in a way save us from challenges associated with manual multi-threading.

**Comment by mgingios** [comment]
Awesome explanation, Andy!  I think that I need to spend some time stepping into the azure sdk code so I can learn more about some of these nuances.  Have a great weekend, and thank you for your help.
