### ISSUE TITLE
Research Merging listBlobsFlat and listBlobsHierarchy

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#5076]
These APIs have a lot of overlap and it may be easier to merge them into a single set of listBlobs that supports both listing types and has ample Javadocs to explain the functionality.

**Comment by JonathanGiles** [comment]
Yeah - I believe we could (and should) reduce this to perhaps two methods (rather than the current four). I believe the 'flat' and 'hierarchy' require the luxury of having a storage client library engineer standing next to you to properly understand it, and that we might be exporting implementation details that can be smoothed over with a simpler API (without losing any functionality).

**Comment by alzimmermsft** [comment]
Based on discussions with @rickle-msft these APIs will continue as is. They have been this way for multiple iterations and haven't received strong customer feedback about their implementation.
