### ISSUE TITLE
[Event Hubs] Change partition identifier type to int

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#5153]
The current track two implementation follows the pattern of using strings as the partition identifiers. In conversation with the Event Hubs service team, they confirmed that they had historically used a string in order to have flexibility with the implementation. Going forward, were willing to make a strong guarantee that the identifiers would be numeric and in the range of [0 .. Total Number of Partitions - 1].

In order to provide the best experience, the track two library should alter its representation of the partition identifier to shift to an integer-based value.

See https://github.com/Azure/azure-sdk-for-net/issues/7417

**Comment by ramya-rao-a** [comment]
Follow up tasks required:
- The result from `getProperties()` should contain partition count instead of the partition Ids
- The method `getPartitionIds()` no longer needed as users can start from 0 till n-1 on their own
- All samples & Readme to be updated that use `getPartitionIds()`

**Comment by ramya-rao-a** [comment]
As per feedback from the API review, removal of getPartitionIds() results in new users trying to find a way to fetch the partition id from the client, keeping it with it returning numbers from 0 to n-1 feels silly. Since the service team is not intending to change the API for `runtimeinfo` and will continue to return partition ids as strings, the decision is to continue treating them as strings
