### ISSUE TITLE
Export surefire-reports during test runs

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#5441]
When tests are executed in maven, the test output is dumped in: `${basedir}/target/surefire-reports`.

We should export these logs as artifacts when tests fail, to make diagnosing test failures easier. (Currently, we look at the console log output, but those often do not show the entire stacktrace or what was printed to console when the test was running.

Combining this with setting AZURE_LOG_LEVEL to informational, would help.

**Comment by JimSuplizio** [comment]
/CC @conniey 
After some investigation, it turns out that the TEST-* log files do contain the information. The problem was more about where to find it. The pipelines Test runs all have a Publish Test Results step and the last line of the logging for that step contains the link to the run. Ex.
Published Test Run : https://dev.azure.com/azure-sdk/internal/_TestManagement/Runs?runId=7107240&_a=runCharts.
The test logs can be found there or downloaded in a zip to be manipulated locally.
