### ISSUE TITLE
Add Simpler Data Methods

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#5514]
"I feel like Flux<ByteBuffer> is an advanced use case, in the already-advanced async world. I wonder if there should be additional API here that takes either ByteBuffer directly, or simply an OutputStream similar to the sync case."

Look into adding `OutputStream` methods that correspond to the `Flux<ByteBuffer>` methods in the async clients. Update the sync methods to pass through their OutputStream to the async method.

**Comment by rickle-msft** [comment]
I don't know if I agree with this. This requires the SDK doing some internal buffering and memory allocations and seems like it will be really easy for customers to incur perf costs that they aren't anticipating. If someone is already working in async, I frankly think it's unlikely that they are going to be using classic streams as the paradigms are different. 

@JonathanGiles @alzimmermsft @vhvb1989

**Comment by JonathanGiles** [comment]
I would encourage you to take 15 minutes to write a short application that is async and downloads something from blob storage. The API can be quite intimidating. I'm not suggesting a particular change, but I want to make sure we are not requiring PhDs in reactive programming to perform the core tasks - otherwise we will be judged poorly.

**Comment by rickle-msft** [comment]
Whatever has or hasn't been suggested, there's already a PR out to add these methods that I'd like to hold off on merging until this has been resolved. 

I've written this code several times for samples, tests, and troubleshooting. Downloading is calling client.download() and then reactive operations as necessary, so I'm not sure where the complexity/intimidation is coming from. The difficulties I've experienced when writing this code are all due to trying convert between sync and async workflows that makes getting data in and out of Fluxes cumbersome, but if someone is opting into the async apis, they should have an application that ready to handle async operations and shouldn't require all that extra work. They should be prepared to produce and handle Fluxes naturally. 

Adding in operations to work with input/outputstream will pollute the api surface, blur the lines between async and sync operations, will add hidden perf costs, and make it harder for customers to pick which option suits them best. If we keep them separate, it's clear that if they are using streams, they are working in a sync context, and if they are using fluxes, they are in an async context.

**Comment by JonathanGiles** [comment]
For the download method specifically, their return type is `Mono<Flux<ByteBuffer>>`. For the max overload of download, the return type is `Mono<Response<Flux<ByteBuffer>>`. My concern is that users will look at this and wonder how to productively work with these return types.

**Comment by rickle-msft** [comment]
Quick point of clarification, the OP says "additional API here that takes either ByteBuffer directly, or simply an OutputStream." Emphasis on "takes". Are we talking about return types or parameters? 

Your most recent comment suggests return type, so I'll go with that for now... I'm not sure how much better Mono<Response<OutputStream>>> really is given what I shared above about blurring lines between sync and async, though I admit Mono<Response<Flux<ByteBuffer>>> isn't pretty. Can we do something similar to reactornetty's ByteBufFlux and have a ResponseMono? Then we get down to ResponseMono<Flux<ByteBuffer>> and we'd also simplify other overloads to be like ResponseMono<BlobItem> instead of Mono<Response<BlobItem>>.

**Comment by conniey** [comment]
In my opinion, the `download()` return value (ie. `Mono<Flux<ByteBuffer>>`) isn't intuitive.  When you tell the BlobAsyncClient you want to download a set of items, I expect it to return a stream of bytes for me to do whatever with. 

Instead it returns a Mono that could either complete with an error, nothing, or a stream of bytes that I then have to unwrap to consume.  The same set of scenarios can be accomplished with: `Flux<ByteBuffer>`.

Working with this API during the storage scavenger hunt was cumbersome because I had to use a .flatMap to toss out the Mono before being able to consume the byte buffer.

## With `Mono<Flux<ByteBuffer>>`
```java
private static Mono<Void> handleDownload(Mono<Flux<ByteBuffer>> contents) {
    return contents
            .flatMap(buffer -> buffer.reduce(ByteBuffer.allocate(0), App::concat))
            .map(concatenate -> {
                final CharBuffer decode = StandardCharsets.UTF_8.decode(concatenate);
                System.out.printf("Item: %s%n%n", decode);
                return decode;
            }).then();
}
```

## With `Flux<ByteBuffer>>`
```java
private static Mono<Void> handleDownload(Flux<ByteBuffer> contents) {
    return contents
            .reduce(ByteBuffer.allocate(0), App::concat)
            .map(concatenate -> {
                final CharBuffer decode = StandardCharsets.UTF_8.decode(concatenate);
                System.out.printf("Item: %s%n%n", decode);
                return decode;
            }).then();
}
```

**Comment by rickle-msft** [comment]
Suggesting getting rid of the Mono feels like a bit of a different discussion than what Jonathan proposed, but I think the idea is that the Mono signals a network call which may or may not be successful and also maybe because it's more consistent with other apis. That said, I'm not sure I see a huge reason why we can't do the flatMap in the sdk. It's hard to imagine a scenario when a customer wouldn't want to do the flatmap, and behavior shouldn't really be affected I don't think.

**Comment by JonathanGiles** [comment]
I agree. I've always had strange looks given to me whenever this API has come up. I would like to see the Mono part of it removed - it seems much more intuitive for end users.

**Comment by JonathanGiles** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/5613 has been created for the Mono<Flux<ByteBuffer>> issue.

**Comment by rickle-msft** [comment]
@anuchandy also commented in a different group (and I hope he doesn't mind me sharing here): " I thought in general async should be done through reactor types (flux/mono). The InputStream has no async IO methods in it t(e.g. read(byte[]) is blocking). To read from a file/socket asynchronously usually we use AsycnhronousChannel."

**Comment by vhvb1989** [comment]
@JonathanGiles , can we close this as not to be implemented?  After all that's been said here?

**Comment by vhvb1989** [comment]
Closing this for now.
