### ISSUE TITLE
[API Review] Auto-gen layer queue

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-java#5671]
- [x] CorsRule `getMaxAgeInSeconds()` why not milliseconds and return long

- [x] Should these classes (e.g. [EqueuedMessage](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-queue/src/main/java/com/azure/storage/queue/models/EnqueuedMessage.java)) be made immutable? Remove setter and final member data.

- [x] Rename Logging to LogData?

- [x] isIncludeAPIs() in Metrics return boolean instead of Boolean

- [x] `setName` in QueueItem rename to `setQueueName`

- [x] QueueMessage class is not used anywhere, so moved to implementation.

- [x] `getMaxResults()` in QueueItem return int instead of Integer?

- [x] Extract StorageException to common module.

- [x] `setLogging` in StorageServiceProperties whether can make it clear to differentiate from client-side logging.

- [x] The necessity of `StorageServiceStats` as it only has one property field in class.

Reference:  https://apiview.azurewebsites.net/Assemblies/Review/2cefcabd89fe4b008f29c7300ba1c3c2

**Comment by rickle-msft** [comment]
- Because the value is in seconds. So why would we report it in miliseconds?
- These are generated types. We'd love to have them immutable but were told that the generator can't determine when types are supposed to be immutable. 
- This is called Logging because that's the xml value the service accepts. I understand the confusion with client side logging, but I also don't think LogData is accurate. Maybe something like ServerLoggingConfigurations
- I think this can be a boolean. If metrics are enabled, it's a required parameter, so that should be ok.
- I'm fine with setName to be setQueueName. I think there's maybe a risk of "stuttering", but if Jonathan thinks it's more clear, then ok.
- I'm seeing QueueMessage is used in QueueAsyncClient (478 and 696(
- I believe this actually applies to QueueSegmentOptions, but it should be an Integer. It's optional. 
- Left a comment inline about merging the StorageException types, but basically there are generator limits to this. 
- This seems like it should be in line with whatever we decide for 3.
- This is the return value for getServiceStats, and this reflects how the service structures this data. Presumably if they created an object here, they are leaving space for future additions and we should do the same.

**Comment by sima-zhu** [comment]
*Regarding: Should these classes (e.g. EqueuedMessage) be made immutable? Remove setter and final member data.*

The `EnqueuedMessage` model is used by post [request](https://github.com/Azure/azure-rest-api-specs/blob/cd1d536ec32f6413d9f660e3fe5c4d62ea6cb3f9/specification/storage/data-plane/Microsoft.QueueStorage/preview/2018-03-28/queue.json#L868).

**Comment by sima-zhu** [comment]
*Regarding: isIncludeAPIs() in Metrics return boolean instead of Boolean*

Rick mentioned "I think this can be a boolean. If metrics are enabled, it's a required parameter, so that should be ok.", what if metrics is disabled (i.e. Metrics::enabled == false), is Metrics::includeAPIs set in this case as well?

- If yes, then need to update [swagger](https://github.com/Azure/azure-rest-api-specs/blob/cd1d536ec32f6413d9f660e3fe5c4d62ea6cb3f9/specification/storage/data-plane/Microsoft.QueueStorage/preview/2018-03-28/queue.json#L1337) required section to include the includeAPI property.

- If no, it will stay as boxed Boolean.

**Comment by sima-zhu** [comment]
*Regarding:'m fine with setName to be setQueueName. I think there's maybe a risk of "stuttering", but if Jonathan thinks it's more clear, then ok.*

Over wire service requires the property to be named “name”, but in SDKs we can rename to `QueueName` by applying [x-ms-client-name](https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md#x-ms-client-name) attribute in [QueueItem](https://github.com/Azure/azure-rest-api-specs/blob/cd1d536ec32f6413d9f660e3fe5c4d62ea6cb3f9/specification/storage/data-plane/Microsoft.QueueStorage/preview/2018-03-28/queue.json#L1365) model. This will get reflected for all languages.

**Comment by sima-zhu** [comment]
*Regarding: I'm seeing QueueMessage is used in QueueAsyncClient (478 and 696)* 

They are not used by clients but internally. That's why Jonathan asked to move to implementation folder. 

*Regarding: QueueMessage class is not used anywhere, so moved to implementation.*

**Comment by sima-zhu** [comment]
*Regarding: getMaxResults() in QueueItem return int instead of Integer?*

As Rick has mentioned above, it is optional property from service perspective. So we cannot actually present it as an primitive integer in our SDK.

**Comment by sima-zhu** [comment]
*Regarding: Extract StorageException to common module.*

The reason `StorageException` exists in each package is - it transitively depends on `StorageErrorCode` type which is specific to each service. So it is better to leave as it is unless service decided to merge error code.

**Comment by sima-zhu** [comment]
*Regarding: setLogging in StorageServiceProperties whether can make it clear to differentiate from client-side logging.`

This will be implicitly addressed once we decide on [this](https://github.com/Azure/azure-sdk-for-java/issues/5671#issuecomment-540710246).

**Comment by sima-zhu** [comment]
*Regarding: CorsRule getMaxAgeInSeconds() why not milliseconds and return long*

and 

*Regarding: The necessity of StorageServiceStats as it only has one property field in class.*

Refers Rick's response, there are no action item for SDK.

**Comment by anuchandy** [comment]
All work items are addressed, issue can be closed.
