### ISSUE TITLE
[BUG] Potential Security vulnerability in Service Bus SDK version 3.1.1

### ISSUE THREAD

**Issue by yvgopal** [Azure/azure-sdk-for-java#5801]
**Describe the bug**
Azure Service Bus SDK version 3.1.1 takes an indirect dependency on OkHttp version 3.1.2, which has a security vulnerability.
Here is the actual issue reported by the customer
https://github.com/Azure/azure-service-bus-java/issues/384

**Expected behavior**
Could you change azure-client-authentication library dependency version so it does depend on  a later version of OkHttp?

**Screenshots**
![image](https://user-images.githubusercontent.com/13388125/66690186-4d93b300-ec43-11e9-8947-13bd8e71af97.png)

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by maggiepint** [comment]
@kurtzeborn @weshaggard @joshfree Is this being looked at?

**Comment by aupadhye** [comment]
Hi, 
Do we know if this ticket is being worked on? This security fix is on high priority on our side and we are waiting for it. Please provide us the ETA.
Thanks
Amol

**Comment by hemanttanwar** [comment]
I have investigated the CVE-2018-20200 and links you specified and followed up with the okHttp discussion. I agree with their reasoning that this isn't a valid issue.  Additionally, the Other Azure SDK Libraries supports Java 7, and upgrading to a newer OkHttp forces users to upgrade to Java 8+ .
 
OK Http Stand on this: This vulnerability requires to inject code in JVM process and replace .class file.  And argument is if some one get into a JVM, what is stopping them to replace any other .class file. 
There should be more strong gates to protect access to JVM. 
 
Upgrading OK Http in Identity: This is not an option because version OKHttp “3.13.0” onwards,  jdk requirement is Java8+ .     
Detail link here   https://square.github.io/okhttp/changelog_3x
  
We are currently working on a new major release of the Service Bus SDK which does require Java 8 and uses the latest versions of Netty or okHttp (user configurable).  

I will update this thread when a public preview of the next release of Service Bus is available.

In interim if you decide upgrade to latest version of OKHttp, you can use maven dependency management to exclude OkHttp which comes with service bus . Here is an example
<dependencies>
  <dependency>
     <groupId>com.microsoft.azure</groupId>
     <artifactId>azure-servicebus</artifactId>
     <version>3.1.3</version>
     <exclusions>
       <exclusion>
         <groupId>com.squareup.okhttp3</groupId>
         <artifactId>okhttp</artifactId>
       </exclusion>
       <exclusion>
         <groupId>com.squareup.okhttp3</groupId>
         <artifactId>okhttp-urlconnection</artifactId>
       </exclusion>
     </exclusions>
   </dependency>
       <dependency>
         <groupId>com.squareup.okhttp3</groupId>
         <artifactId>okhttp</artifactId>
         <version>4.2.2</version>
      </dependency>
</dependencies>

Here is related link on maven dependency exclusion https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html#
 
@aupadhye  Based on above explanation, I am closing this issue. If you have further question , you can contact us in this issue or reopen it.
