### ISSUE TITLE
Support exponential backoff retry policy 

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#5840]
RetryPolicy in azure-core only supports fixed delay retries. This RetryPolicy should also support retries with exponential backoff. 

There's a similar implementation in core-amqp - 
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/ExponentialRetryPolicy.java

**Comment by mrm9084** [comment]
@srnagar Is this a duplicate of https://github.com/Azure/azure-sdk-for-java/issues/3241? The App Configuration Service team is interested in this.

**Comment by anuchandy** [comment]
@srnagar agree, its good to have various retry policies in azure-core. 

Looking at the .net azure-core, it seems there is only support for [exponential retry](https://github.com/Azure/azure-sdk-for-net/blob/7d587e0c8bf8cf7d86c34b8b6e9990861700dd81/sdk/core/Azure.Core/src/Pipeline/Internal/RetryPolicy.cs#L181). Not sure offering from other languages. We might want to consider consistent support across languages.

The current retryPolicies in amqp-core seems very specific to amqp protocol so I guess it needs to stay there since retry policies in azure-core is http pipeline policy based.

///cc @JonathanGiles

**Comment by srnagar** [comment]
@anuchandy .NET has both [Fixed and Exponential](https://github.com/Azure/azure-sdk-for-net/blob/7d587e0c8bf8cf7d86c34b8b6e9990861700dd81/sdk/core/Azure.Core/src/RetryMode.cs) retry modes.

Yes, amqp-core's exponential backoff implementation is specific to amqp protocol, so we will have to have a separate implementation for http pipeline.

**Comment by srnagar** [comment]
@mrm9084 yeah, looks like this is a duplicate of #3241 

I will close this ticket and we'll use #3241 to track this task.
