### ISSUE TITLE
[QUERY]can anyone tell me how to use BlobAsyncClient?

### ISSUE THREAD

**Issue by SHIELD7** [Azure/azure-sdk-for-java#5851]

**Comment by rickle-msft** [comment]
Hi, @SHIELD7. We would be happy to help you in your investigation of the async client. Can you please share more about what exactly you're having trouble with? Are you having trouble using Reactor, with some Storage concepts, or navigating the SDK?

**Comment by SHIELD7** [comment]
> Hi, @SHIELD7. We would be happy to help you in your investigation of the async client. Can you please share more about what exactly you're having trouble with? Are you having trouble using Reactor, with some Storage concepts, or navigating the SDK?

I am trying to upload a file to my azure blob I use code like  example, but it doesn't do any thing,
I am new to this, thanks.

```
        blobAsyncClient.uploadFromFile(file.getPath()).doOnError(throwable -> System.out.println("upload error:"+throwable.getMessage()))
                .subscribe(completion -> System.out.println("success"));
```

**Comment by rickle-msft** [comment]
subscribe() is an asynchronous call, so your program execution will continue past that line even if the operation hasn't been completed. The print statements will be triggered at some point in the future when the operation completes. If this is the only code in your application/test, what's happening is you fire off this operation, then your program continues and completes before the operation completes, so you never see the result and there's a good chance you never finish uploading. If you want to observe this operation completing, you should add something blocking like System.in.readLine() at the end of your application to ensure it stays alive until the operation completes. 

For the record, if you want to get used to Storage and the SDK before adding in async operations and dealing with those concepts, you can use the sync clients, which look pretty much the same but won't have these pitfalls. Then, when you're comfortable with those two things, you can switch over to async if you decide that's the right approach for you.

**Comment by SHIELD7** [comment]
> subscribe() is an asynchronous call, so your program execution will continue past that line even if the operation hasn't been completed. The print statements will be triggered at some point in the future when the operation completes. If this is the only code in your application/test, what's happening is you fire off this operation, then your program continues and completes before the operation completes, so you never see the result and there's a good chance you never finish uploading. If you want to observe this operation completing, you should add something blocking like System.in.readLine() at the end of your application to ensure it stays alive until the operation completes.
> 
> For the record, if you want to get used to Storage and the SDK before adding in async operations and dealing with those concepts, you can use the sync clients, which look pretty much the same but won't have these pitfalls. Then, when you're comfortable with those two things, you can switch over to async if you decide that's the right approach for you.

**Comment by SHIELD7** [comment]
> subscribe() is an asynchronous call, so your program execution will continue past that line even if the operation hasn't been completed. The print statements will be triggered at some point in the future when the operation completes. If this is the only code in your application/test, what's happening is you fire off this operation, then your program continues and completes before the operation completes, so you never see the result and there's a good chance you never finish uploading. If you want to observe this operation completing, you should add something blocking like System.in.readLine() at the end of your application to ensure it stays alive until the operation completes.
> 
> For the record, if you want to get used to Storage and the SDK before adding in async operations and dealing with those concepts, you can use the sync clients, which look pretty much the same but won't have these pitfalls. Then, when you're comfortable with those two things, you can switch over to async if you decide that's the right approach for you.

I am trying upload multiple file in the same time by using async , so I do not want my code blocked. can you tell me how can I do that? thinks

**Comment by rickle-msft** [comment]
There are plenty of ways you could do it, but one suggestion is:

```
List<String> filenames; // populate list with files to upload
BlobAsyncClient bac; // Use a builder to initialize
Flux.fromIterable(filenames)
    .flatMap(fileName -> bac.uploadFromFile(fileName))
    .subscribe();
```

From there, you can add some bells and whistles to print the fileName when it is done uploading or whatever you want. Just ensure your program doesn't exit before the operations complete.

**Comment by SHIELD7** [comment]
> There are plenty of ways you could do it, but one suggestion is:
> 
> ```
> List<String> filenames; // populate list with files to upload
> BlobAsyncClient bac; // Use a builder to initialize
> Flux.fromIterable(filenames)
>     .flatMap(fileName -> bac.uploadFromFile(fileName))
>     .subscribe();
> ```
> 
> From there, you can add some bells and whistles to print the fileName when it is done uploading or whatever you want. Just ensure your program doesn't exit before the operations complete.

thanks

**Comment by VIJAY-SUBRAMANIAM** [comment]
Hi,

API failed to call subscribe() method on completion of file upload. I tested with a very small text file with one word. File successfully uploaded to Azure storage, but completion message not printed.
subscribe() is an asynchronous call, So add blocking call like Thread.sleep() or System.in.Read() to keep the application alive until the operation completes. 

blobAsyncClient.uploadFromFile(sampleFile.toPath().toString(), true)
                .doOnError(throwable -> System.err.printf("Failed to upload from file %s%n", throwable.getMessage()))
                .subscribe(success -> System.out.printf("Upload file succeeded"));
                
System.in.read()                
                
version v12 (12.3.0) and Java 11 Corretto

Is anyone noticed a similar issue?

Vijay--

**Comment by rickle-msft** [comment]
@VIJAY-SUBRAMANIAM Your callback method will actually never get called as you have defined it. Let me explain: First, the customer (you) calls the subscribe method when you want to trigger the operation. The SDK will never call subscribe on your operations in the async paradigm. What you pass into the subscribe method is a number of callbacks. They are, in order, onNext, onError, and onComplete callbacks. The single value overload you have called accepts an onNext method that allows you to process emissions from the Mono or Flux. That's why you have to specify a consumer and hence your lambda accepts the parameter you have called `success`. However, the uploadFromFile method returns a `Mono<Void>` which is used to indicate that the Mono returns 0 elements (this is standard in Reactor). It either completes or fails. Hence, your method that consumes items will never be called. If you want an action triggered upon successful upload, you should instead pass an onComplete callback via the `doOnComplete` method similar to how you've specified an `onError` callback.

**Comment by VIJAY-SUBRAMANIAM** [comment]
I didn't find a doOnComplete method but there is a doOnSuccess method.   with that success method, My program didn't even upload file to blob storage nor any error?  Is anything wrong here?

blobAsyncClient.uploadFromFile(sampleFile.toPath().toString(), true)
                            .doOnError(throwable -> System.err.printf("Failed to upload from file %s%n", throwable.getMessage()))
                            .doOnSuccess(success -> System.out.printf("Upload file succeeded"));

I'll also take a closer look to functional interfaces & async paradigm

**Comment by rickle-msft** [comment]
My apologies. I got the name of the method wrong (I was thinking of a different reactive framework). You are correct that doOnSuccess is what you're looking for.

You're missing a final call to subscribe. The empty overload should work for you here. You were combining two steps by passing your callbacks to subscribe earlier--setting the call backs and then subscribing. Setting these event notification callbacks is optional, but a reactive stream must always be subscribed to before it does any work. 

Don't worry, this is a very common mistake when people first encounter Reactor, and it's easy to forget even after you've been doing it a while, but it becomes easier to recognize. If you haven't already encountered it, I would strongly recommend reading through the [Reactor guide](https://projectreactor.io/docs/core/release/reference/). It does a really great job of pointing out these stumbling blocks and getting you started. It's also very easy to read.

**Comment by VIJAY-SUBRAMANIAM** [comment]
Thanks.   I'll read through the Reactor guide.

Callback works fine after subscribing().

          blobAsyncClient.uploadFromFile(sampleFile.toPath().toString(), true)
                            .doOnError(throwable -> System.err.printf("Failed to upload from file %s%n", throwable.getMessage()))
                            .doOnSuccess(success -> System.out.printf("Upload file succeeded"))
                            .subscribe();

**Comment by saralpa** [comment]
Hi, I am facing same issue with listBlob and beginCopy method. Since I am also using async client, **the spring boot application runs and completes but I dont get any value in listBlob from container.** 

I am using 12.0.6 version of java sdk.  I don't want to add System.readline or Thread.Sleep. Does any other way can help me? 
Also just adding onSuccess or OnCompletion callbacks resolve my problem? I dont want to use sync clients, because I want to copy multiple files at a time, so dont want to block these operations.
What can be the best way to do these async operations? 
Also, just in case I add Thread.Sleep() , how much time I should add in sleep paramters. How will I know that how much time I need to keep my application running?

**Comment by rickle-msft** [comment]
Hi, @saralpa. I think there's a couple things going on here. 

First is that you may not need an async client for what you are describing. If you use the `beginCopy` api, it will be an asynchronous copy even using the sync client apis. This is because the service method itself is async, so you can start multiple copies sequentially and they will all be running on the service concurrently. You can use the returned `Poller` to block on the copy completion at whatever point you choose. However, if you want even the requests starting the copies to be async and parallelized, you will need the async client as you mentioned.

Adding onSuccess or onCompletion will not solve your problem. Those allow you to specify actions to take at certain points in the process, but they are not guaranteed to run if your application terminates before the operation succeeds/completes.

System.readline and Thread.Sleep are easy ways to keep an application from exiting prematurely, but they are not necessarily the only way. If you have your main code running in a while(true) loop that only exits when certain conditions are met, that can work as well. But you do need to introduce some blocking way to keep your main method from terminating before these operations complete. 

You'll really have to experiment for your environment on timing. It depends a lot on your network conditions, honestly. And if you are using the beginCopy api, while you will get a pretty quick response indicating that the copy has started, the service only guarantees that it will complete within two weeks, so you could be waiting a while...
