### ISSUE TITLE
[QUERY] [V12][Storage] replacement for generateSAS on blobClient

### ISSUE THREAD

**Issue by alexander-riss** [Azure/azure-sdk-for-java#5852]
**Query/Question**
In the preview4 version of the V12 storage api, the blobClient.generateSAS(...) method was removed. The documentation is not clear how this should be replaced.
BlobServiceSasSignatureValues seems to have a generateSAS method - but requires credentials to be passed in. The beauty of the old API, was that these were hidden from the user when just using the blobClient, which allowed a clear separation of credential setup and actual use of the API. (e.g. injecting the fully configured client into a service which has no credential access).

Or am i missing something ?

***Why is this not a Bug or a feature Request?***
This was changed between preview.2 and preview.4

**Setup (please complete the following information if applicable):**
Example code in preview.2:
final String signature = blob.generateSAS(expiryTime, BlobSasPermission.parse(permissions)); 
 
**Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by rickle-msft** [comment]
@alexander-riss You're not missing anything. We did remove SAS stuff in preview 4 because we are making an effort to standardize SAS support across languages, the first step of which was to strip it down. We will definitely be adding back more convenient ways of working with SAS in preview 5. @conniey Is working on this effort and can offer more details when she has settled on a design. We apologize for the inconvenience during preview 4 and will be happy to help you work with SAS in the meantime. Alternatively, if SAS is a big part of your workflow, you can stay on the preview version that suits you best.

**Comment by alzimmermsft** [comment]
@conniey Could you take this on with your other SAS changes?

**Comment by SHIELD7** [comment]
> @alexander-riss You're not missing anything. We did remove SAS stuff in preview 4 because we are making an effort to standardize SAS support across languages, the first step of which was to strip it down. We will definitely be adding back more convenient ways of working with SAS in preview 5. @conniey Is working on this effort and can offer more details when she has settled on a design. We apologize for the inconvenience during preview 4 and will be happy to help you work with SAS in the meantime. Alternatively, if SAS is a big part of your workflow, you can stay on the preview version that suits you best.

When will the preview 5 be released?

**Comment by rickle-msft** [comment]
Preview 5 should be out in the first couple weeks of November. If you need support working with SAS in the meantime to unblock some other work, we will be happy to support you.
