### ISSUE TITLE
Azure Web App: Web hosting plan creation is not working.

### ISSUE THREAD

**Issue by pednekarprajakta** [Azure/azure-sdk-for-java#592]
Azure Web App: Web hosting plan creation is not working. It fails with below exception,

com.microsoft.windowsazure.exception.ServiceException: NotFound: Cannot find WebSpace with name northeuropewebspace.
at com.microsoft.windowsazure.exception.ServiceException.createFromXml(ServiceException.java:206)
at com.microsoft.windowsazure.management.websites.WebHostingPlanOperationsImpl.create(WebHostingPlanOperationsImpl.java:256)
at Test.main(Test.java:33)

I am executing below code,
Configuration configuration = PublishSettingsLoader.createManagementConfiguration(file.getPath(), subscriptionId);
WebSiteManagementClient webAppManagementClient = WebSiteManagementService.create(configuration);
WebHostingPlanCreateParameters appServicePlanParams = new WebHostingPlanCreateParameters();
appServicePlanParams.setName("testserviceplan");
appServicePlanParams.setSKU(SkuOptions.Free);
webAppManagementClient.getWebHostingPlansOperations().create(WebSpaceNames.NORTHEUROPEWEBSPACE, appServicePlanParams);

**Comment by pednekarprajakta** [comment]
This issue is getting reproduced with ASM websites JAR.

For ARM websites JAR, it throws NULL pointer exception but web hosting plan gets created. At least I can view web hosting plan at azure portal.

**Comment by jianghaolu** [comment]
The response from websites team:
for line:
`webAppManagementClient.getWebHostingPlansOperations().create(WebSpaceNames.NORTHEUROPEWEBSPACE, appServicePlanParams);` 
an error will be thrown if "northeuropewebspace" doesn't match any of the webspaces in your subscription. You can list your webspaces by `webAppManagementClient.getWebspaceOperations().list()`.

This code used to work because before ARM was introduced, the Web spaces used to a set of enums to choose from. Since the concept of resource group has been introduced in ARM, in order to have ASM work with ARM, the web space names have "resourcegroupname-" added as a prefix to the location info. A valid web space name could be "a_valid_resouce_group-northeuropewebspace". 

With this being said, the scenario of creating a web hosting plan only works with existing webspaces. If you want to create new web hosting plans in new web spaces, ARM will be the way to go. And there shouldn't be any reason not to use ARM, considering that ARM has all the functionalities in ASM.
