### ISSUE TITLE
[BUG] Jar file in Maven Central for 1.27.1 is acutally a POM

### ISSUE THREAD

**Issue by r-darwish** [Azure/azure-sdk-for-java#6023]
**Describe the bug**
https://repo1.maven.org/maven2/com/microsoft/azure/azure/1.27.1/azure-1.27.1.jar
This file is actually a POM instead of a Jar.

**Comment by joshfree** [comment]
@JimSuplizio is this something you could assist us with?

**Comment by JimSuplizio** [comment]
> @JimSuplizio is this something you could assist us with?

@mitchdenny or @JonathanGiles may be of more help here. I'm unfamiliar with how to manipulate things on Maven. It's odd, I'm looking at the azure-1.27.1.pom file in the link above and there's nothing in the azure-sdk-for-java sources that matches this pom. Further, there are dependencies in that pom that literally don't exist in any pom in our sources as dependencies or otherwise. An example would be azure-mgmt-cdn.

**Comment by weshaggard** [comment]
@ChenTanyi  @yaohaizh I believe this comes from the https://github.com/Azure/azure-libraries-for-java/blob/master/azure/pom.xml which I believe you guys own.

**Comment by yaohaizh** [comment]
@r-darwish, could you help use 1.27.2 instead? There was an issue happened when we published the 1.27.1 version during the build that maven ignored some errors.

**Comment by r-darwish** [comment]
1.27.2 seems okay. Thanks.
