### ISSUE TITLE
implement expressive toString methods for model objects

### ISSUE THREAD

**Issue by herrwieger** [Azure/azure-sdk-for-java#609]
Currently most of the classes in the models packages have no toString method. For logging its essential to get meaningful output from model objects via toString. Although its boring work, adding toString methods would make debugging way more fun and increase the usefulness of the sdk.

**Comment by jianghaolu** [comment]
Hi @herrwieger 

Thanks for your advice. I will park this until the iteration slows down and I get some time to get back to this. After the same time, if you'd like to contribute or have an urgent need, please feel free to make your changes in our template for all models: https://github.com/Azure/autorest/blob/master/AutoRest/Generators/Java/Java/Templates/ModelTemplate.cshtml. Changes in that template will be propagated to all models in the SDK.

**Comment by martinsawicki** [comment]
perhaps this will be part of our JSON serialization work, so on the To Do list for now.

**Comment by martinsawicki** [comment]
@anuchandy just some food for thought perhaps related to the JSon serialization investigation

**Comment by praries880** [comment]
@anuchandy Any updates on this issue?

**Comment by jianghaolu** [comment]
Potential autorest v3 item.

**Comment by jianghaolu** [comment]
Due to the extensive amount of custom serialization we do in the pipeline, there's no simple `toString()` implementation available. A simple `toString()` implementation will be confusing as it will differ from what's sent to the service. I would suggest adding in your watch window `JacksonAdapter.createDefaultSerializerAdapter().serialize(modelObject)`.
