### ISSUE TITLE
Implement method in EventHubConsumerClient to receive from all partitions

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#6236]
Implement method in EventHubConsumerClient to receive from all partitions with two overloads - one with default "earliest" event position and second with a user-provided event position (same position will be used for all partitions).

**Comment by conniey** [comment]
@srnagar Regarding this one, I thought the overloads would be `int` and `Duration` similar to our existing receives.  I didn't know that our receivers could start from new positions... if that's the case, should this also be added into our async consumer since it does not have the capability to start from another partition?

**Comment by conniey** [comment]
Related PR #6258
