### ISSUE TITLE
[BUG] Warnings trying to compile with newest SDK version

### ISSUE THREAD

**Issue by gmndrg** [Azure/azure-sdk-for-java#6330]
**Describe the bug**
We have an application running with azure-servicebus version 2.0. Due to some issues we're experiencing that may be related to the library (huge roundtrip of publishing events to service bus, waiting even if async writing is being performed and delay visible from the client end when AKS cluster resources are working with no stress), we were requested to upgrade to azure-servicebus/3.1.2 instead.
We are running with JDK 11.

When trying to update to the newest version azure-servicebus/3.1.2 we get the following warning. Our current deployment environment won't let us run the app if there is any warning. We need to have a clean compilation in every sense. We are with very tight deadlines, please help.

***Exception or Stack Trace***
Supported source version 'RELEASE_7' from annotation processor 'com.microsoft.azure.management.apigeneration.LangDefinitionProcessor less than -source '11')?

**To Reproduce**
Compile existing code that is working with azure-servicebus/2.0 and try compiling it with azure-servicebus version 3.1.2

***Code Snippet***
We have a solution for AKS that may not be uploaded, however, since this is related to compiling with the new version, any sample from Microsoft for Java to send messages to service bus should give the same: https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-java-how-to-use-queues

Example:
public void run() throws Exception {
	// Create a QueueClient instance and then asynchronously send messages.
	// Close the sender once the send operation is complete.
	QueueClient sendClient = new QueueClient(new ConnectionStringBuilder(ConnectionString, QueueName), ReceiveMode.PEEKLOCK);
	this.sendMessageAsync(sendClient).thenRunAsync(() -> sendClient.closeAsync());

	sendClient.close();
}

    CompletableFuture<Void> sendMessagesAsync(QueueClient sendClient) {
        List<HashMap<String, String>> data =
                GSON.fromJson(
                        "[" +
                                "{'name' = 'Einstein', 'firstName' = 'Albert'}," +
                                "{'name' = 'Heisenberg', 'firstName' = 'Werner'}," +
                                "{'name' = 'Curie', 'firstName' = 'Marie'}," +
                                "{'name' = 'Hawking', 'firstName' = 'Steven'}," +
                                "{'name' = 'Newton', 'firstName' = 'Isaac'}," +
                                "{'name' = 'Bohr', 'firstName' = 'Niels'}," +
                                "{'name' = 'Faraday', 'firstName' = 'Michael'}," +
                                "{'name' = 'Galilei', 'firstName' = 'Galileo'}," +
                                "{'name' = 'Kepler', 'firstName' = 'Johannes'}," +
                                "{'name' = 'Kopernikus', 'firstName' = 'Nikolaus'}" +
                                "]",
                        new TypeToken<List<HashMap<String, String>>>() {}.getType());

        List<CompletableFuture> tasks = new ArrayList<>();
        for (int i = 0; i < data.size(); i++) {
            final String messageId = Integer.toString(i);
            Message message = new Message(GSON.toJson(data.get(i), Map.class).getBytes(UTF_8));
            message.setContentType("application/json");
            message.setLabel("Scientist");
            message.setMessageId(messageId);
            message.setTimeToLive(Duration.ofMinutes(2));
            System.out.printf("\nMessage sending: Id = %s", message.getMessageId());
            tasks.add(
                    sendClient.sendAsync(message).thenRunAsync(() -> {
                        System.out.printf("\n\tMessage acknowledged: Id = %s", message.getMessageId());
                    }));
        }
        return CompletableFuture.allOf(tasks.toArray(new CompletableFuture<?>[tasks.size()]));
    }

**Expected behavior**
To compile with no processor compilation warnings from the management module.

**Screenshots**
![image](https://user-images.githubusercontent.com/46359679/68818655-46e5ca80-064b-11ea-9595-63422102aecd.png)

**Setup (please complete the following information):**
 - OS: Linux
 - Version of the Library used:  azure-servicebus version 3.1.2

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by gmndrg** [comment]
Hi Team, is there any update on this issue? Thank you!

**Comment by yvgopal** [comment]
You can safely ignore the warning.

It is caused by a dependency that processes annotation and generates source compatible with java 7. 
Check the javadoc at https://docs.oracle.com/javase/10/docs/api/index.html?overview-summary.html
Any annotation processor must specify a source version or it defaults to Java 6.
That means every time there is a new java version, that piece of code will generate this warning unless that code is modified to specify the new source version. It is not practical to expect the libraries we depend on to change their source every time there is a new java version. So you should ideally ignore this warning.

The service bus SDK is on Java 8. As long as we are with Java 8, the dependency also will be java 8 or older. So this warning cannot be fixed unless we release an SDK version targeting Java 11 and the dependency also releases a version targeting Java 11.

If your environment doesn't allow deployment with any warning, disable warnings by passing a compiler option. -nowarn or -Xlint:none will hide this warning. If you are using maven to build, pass the compiler options to the plugin following the link https://maven.apache.org/plugins/maven-compiler-plugin/examples/pass-compiler-arguments.html
