### ISSUE TITLE
Support for Customizing RetryStrategy implementations 

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#6363]
The `RetryPolicy` is an asynchronous loop. The factors that control the loop behavior (when to break, time to wait before retry, max number of iterations) are externalized to `RetryStrategy` type. 

The `RetryStrategy` expose `shouldRetry(HttpResponse)` and `calculateRetryDelay(int retryAttempts)` which controls the async retry loop in `RetryPolicy`. 

While `shouldRetry` can use the current `HttpResponse` to dynamically decide whether to retry or not, the `calculateRetryDelay` has only static data available those provided at the time of creating the `Strategy` | `RetryPolicy`. 

It would be nice if `calculateRetryDelay` also has access to `HttpResponse`. This enables users to customize the existing implementations of `RetryStrategy`. 

A use case is - The AzConfig library requires looking a custom header to decide the retry-delay. There could be more cases, where users want to look at other headers (in request/response) to make a decision. 

The proposal is have a default method `RetryStrategy::calculateRetryDelay(HttpResponse httpResponse, int retryAttempts)`, By default is it invokes `calculateRetryDelay(int retryAttempts)` impl of specific `RetryStrategy` implementation.

```java
public interface RetryStrategy {
    …..

    default Duration Duration calculateRetryDelay(HttpResponse httpResponse, int retryAttempts) {
        return calculateRetryDelay(retryAttempts);
    }

    Duration calculateRetryDelay(int retryAttempts);
}

```

AzConfig can override this default impl like:

```java
RetryPolicy DEFAULT_RETRY_POLICY = new RetryPolicy(new ExponentialBackoff() {
    @Override
    public  Duration calculateRetryDelay(HttpResponse httpResponse, int retryAttempts)) {
        String delay = httpResponse.getHeaderValue("retry-after-ms");
        return delay != null ?  Duration.ofMillis(Long.parseLong(delay)) : calculateRetryDelay(retryAttempts);
    }
});
```

The only parameter that `RetryPolicy` takes is `RetryStrategy`. 

This keeps `RetryPolicy` generic while all the decisions are offloaded to `RetryStrategy`.

**Comment by anuchandy** [comment]
Though proposal is generic, we can have specialization of it to solve the issue we discussed here: https://github.com/Azure/azure-sdk-for-java/issues/5945. 

Also if we offload all the controlling factors of async-retry-loop to `RetryStrategy` impl then we can simplify the ctr of `RetryPolicy`, all it take is `RetryStrategy `.


\\\cc @hemanttanwar @JonathanGiles @srnagar @conniey

**Comment by srnagar** [comment]
Yes, the motivation to have a `RetryStrategy` was to make all these things configurable.  Adding a new interface method in `RetryStrategy`  that looks like `calculateRetryDelay(HttpResponse httpResponse, int retryAttempts)` and making it a `default` will be sufficient rather than updating the `RetryPolicy` constructor and introducing a new type `RetryPolicyOptions`.

**Comment by hemanttanwar** [comment]
We had a similar discussion on this https://github.com/Azure/azure-sdk-for-java/issues/6217
Here is another point of view

**Comment by hemanttanwar** [comment]
We had a similar discussion on this https://github.com/Azure/azure-sdk-for-java/issues/6217

Here is another point of view. In above issue : We discussed, to update following with new design
1. HostPolicy
2. RequestIdPolicy
3. May be combine 1. PortPolicy , 2. ProtocolPolicy , 3. HostPolicy into "EndpointPolicy" ? And also handle "Geo fail over "
4. RetryPolicy -> Strategy, response header
5. UserAgentPolicy

Since we were taking wholistic approach and looking at a generic way to provide user to be able to configure these policies. 
Have "one way"  i.e. `XXXPolicyOptions`  to configure all the `Policies`. 

Right now it does feel like `RetryPolicyOptions` is unnecessory if we add one overload
`default Duration Duration calculateRetryDelay(HttpResponse httpResponse, int retryAttempts)` 
 
Here are few alternatives , we can discuss and decide

Alternative 1: 
 Do not use `RetryPolicyOptions`  in RetryPolicy.  Just  add one overload
`default Duration Duration calculateRetryDelay(HttpResponse httpResponse, int retryAttempts)` 

And Continue to use `Options` approach for all other policies.
Like in this PR : https://github.com/Azure/azure-sdk-for-java/pull/6370/files/c0b1fdf8d8b6663335743acae5e67cfbcade7128#diff-0ef7cbb422d0b747a9384531a7cddce5R40
Use `XXXPolicyOptions` approach where it make sense.

Alternative 2: 
Use `XXXPolicyOptions` approach  in above `XXXPolicy`.

**Comment by hemanttanwar** [comment]
Combining Multiple issues to bring discussion at one place 
Moving this discussion on to #6217
