### ISSUE TITLE
TokenCredentials do not validate that the url is using https

### ISSUE THREAD

**Issue by rickle-msft** [Azure/azure-sdk-for-java#6367]
**Describe the bug**
TokenCredentials do not enforce that the connection is using https, which means the BearerToken can be easily intercepted. 

**To Reproduce**
Use TokenCredentials with http and inspect the request in fiddler to see it is plainly visible. 

**Expected behavior**
The TokenCredentialPolicy should fail if it notices the connection is not over https.

**Comment by sima-zhu** [comment]
Taking a look

**Comment by sima-zhu** [comment]
Using EnviromentalCredential to test. 
Here is the error msg when use http, SDK has verified and throw message before sending out to the network.
```
[ForkJoinPool.commonPool-worker-1] ERROR com.microsoft.aad.msal4j.ConfidentialClientApplication - [Correlation ID: f983de5e-fc97-448f-bbd8-35aa86964862] Execution of class com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier failed.
com.microsoft.aad.msal4j.MsalServiceException: The resource principal named http://<blob-name>.blob.core.windows.net was not found in the tenant named <tenant-id>. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: cd9e2e5c-d29f-4411-a394-663185130000
Correlation ID: f983de5e-fc97-448f-bbd8-35aa86964862
Timestamp: 2019-11-20 21:30:41Z
```

**Comment by sima-zhu** [comment]
Tried other 2 creds, UsernamePasswordCredential and InteractiveBrowserCredential. They all throw the similar errors as above. 

When user tries to access Storage through TokenCredential, they need to use azure-identity creds instead of azure-core. 

Azure-identity does some verification over http before the request getting out of the door.

Close the issue. Please feel free to reopen if the issue can reproduce.

Thanks!
