### ISSUE TITLE
Incorrect exception InvalidKeyException thrown in SharedKeyCredentials constructor

### ISSUE THREAD

**Issue by bhavanikalisetty** [Azure/azure-sdk-for-java#6390]
**Describe the bug**
The constructor in SharedKeyCredentials : https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/microsoft-azure-storage-blob/src/main/java/com/microsoft/azure/storage/blob/SharedKeyCredentials.java#L57 never throws the exception *InvalidKeyException *. Instead, it throws IllegalArgumentException when accountKey is ill-formatted. Please update the exception thrown.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
The java doc of Base64 decode explains that only possible exception here is IllegalArgumentException.

***Code Snippet***
public SharedKeyCredentials(String accountName, String accountKey) throws InvalidKeyException {
        this.accountName = accountName;
        this.accountKey = Base64.getDecoder().decode(accountKey);
    }

**Expected behavior**
public SharedKeyCredentials(String accountName, String accountKey) throws IllegalArgumentException {
        this.accountName = accountName;
        this.accountKey = Base64.getDecoder().decode(accountKey);
    }

**Screenshots**

**Setup (please complete the following information):**
 - OS: iOS
 - IDE : eclipse
 - Version of the Library used - 10.3.0, but the latest master also has the same bug.

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by rickle-msft** [comment]
@bhavanakonchada Thank you for reporting this. I notice that you are referring to the microsoft-azure-storage-blob package instead of just the azure-storage-blob package. The package you are mentioning is an older version, and unfortunately we do not plan to release any updates in that code as of right now. We have recently GAed version 12 from azure-storage-blob, which supersedes v10/11 in microsoft-azure-storage-blob. You'll notice that the [constructor](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/StorageSharedKeyCredential.java#L43) for SharedKeyCredential no longer throws an InvalidKeyException. Because IllegalArgumentException is an unchecked exception, it also does not call that out explicitly.

I am going to close this issue as I believe the concern has been addressed, but please feel free to comment/reopen it if you feel further discussion is needed.
