### ISSUE TITLE
[FEATURE REQ] shorten management sdk path

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#6402]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

@mitchdenny 
@JimSuplizio 

Shorten mgmt sdk path

E.g., skip azure-mgmt-{service_name} entirely, resulting:

sdk/operationsmanagement/v2015_11_01_preview/src/main/java/com/microsoft/azure/management/operationsmanagement/v2015_11_01_preview/implementation/ManagementConfigurationsInner.java

or

sdk/operationsmanagement/mgmt-v2015_11_01_preview/src/main/java/com/microsoft/azure/management/operationsmanagement/v2015_11_01_preview/implementation/ManagementConfigurationsInner.java

**Comment by mitchdenny** [comment]
I believe changing the package to be ```mgmt-[version]``` is a good starting point here, in addition to the suggested renamings that I'm listing here (for service directories):

```
recoveryservices.siterecovery -> siterecovery
recoveryservices.backup -> backup
applicationsights -> appinsights
datamigration -> datamig
cognitiveservices -> cogservices
```

**Comment by weidongxu-microsoft** [comment]
@mitchdenny
Do we need someone's approval for renaming services?

**Comment by weshaggard** [comment]
I suspect you will have a hard time trying to find the owners of the various services but if you know who they are then it might be worth pinging them on the PR otherwise I think we have a good reason to rename. 

As for the service folders themselves I personally would like to keep them consistent across the languages repo's unless we have a really strong reason not to so based on that lets see what we come up with:

1) recoveryservices.siterecovery/recoveryservices.backup - [.NET recoveryservices-siterecovery](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/recoveryservices-siterecovery), Python - NA, [JSrecoveryservicessiterecovery](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/recoveryservicessiterecovery) - So we don't have any real consistency here. 
Similar situation for backup. I kind of wonder if we shouldn't just make the folder name "recoveryservices" and put the other packages under it. Python has does that for the other 2 recoveryservices already. If we need to distinguish the folders under then then we could add the siterecovery or backup to the api version folder. 

2) applicationinsights - this is applicationinsights in all languages so I'd suggest we keep it that way.
3) datamigration - this is datamigration in all languages so I'd suggest we keep it that way. 
4) cognitiveservices - this is cognitiveservices  in all languages so I'd suggest we keep it that way. 

Based on my quick investigations the recoveryservices is the only inconsistent one across languages so for now I'd suggest we keep all the others unchanged. I'd also suggest we try to leave the recoveryservices one along for now as well and at some point we can try to align a strategy across the repo's. Even without these service folder renames I think we get down to a max path length of 216 by just renaming to mgmt-version convention. That should be reasonable.

**Comment by mitchdenny** [comment]
Adding @weshaggard and @JonathanGiles for their input, but to be honest I think that having the repo usable on Windows without long path hacks is probably the higher order bit here.

**Comment by mitchdenny** [comment]
Whoops. my view didn't refresh before I saw @weshaggard 's response.

**Comment by weidongxu-microsoft** [comment]
https://github.com/Azure/azure-sdk-for-java/issues/5682
