### ISSUE TITLE
Azure Cosmos 3.3.2 and 3.4.0

### ISSUE THREAD

**Issue by thanhngo219** [Azure/azure-sdk-for-java#6486]
I am confused about the release 3.3.2 and 3.4.0. I wonder if the hot fix in release 3.3.2 was added to 3.4.0. It seems when I upgraded 3.4.0, it starts missing some change items. However, when I restart the app, it starts loading the missing. It never happened before when I use 3.3.2.

In 3.3.2 release notes
```
Cosmos: CFP 3.3.2 hot-fixes (#6212)

* ChangeFeedProcessor; fixes and extra logging related to the creations of the lease documents.
Port consistency policy bug fix from V2 (see https://github.com/Azure/azure-cosmosdb-java/pull/196)
ChangeFeedProcessor: fix a race condition issue where the lease document has been updated while we are trying to write the current state like when check-pointing the continuation token.

* update version
```

**Comment by kushagraThapar** [comment]
@milismsft can you please investigate this issue ?

**Comment by milismsft** [comment]
@thanhngo219 We had to hurry the 3.3.2 and 3.3.3 releases ahead of the main since they were targeted releases to address specific customer issues which they encounter in production. We are in the process to release either a 3.4.1 or a 3.5.0 in the first week of December which will help catch-up with all the other changes that were in the repo.
