### ISSUE TITLE
Live vm return null instanceView sdk 0.9.3

### ISSUE THREAD

**Issue by netwmr01** [Azure/azure-sdk-for-java#653]
ArrayList<VirtualMachine> vms = computeManagementClient.getVirtualMachinesOperations().list("mygroup").getVirtualMachines();
    for(VirtualMachine vm:vms)
    {

      VirtualMachineInstanceView instanceView = vm.getInstanceView(); //instanceView is null
      ArrayList<InstanceViewStatus> statuses = instanceView.getStatuses(); //NullPointerException

**Comment by anuchandy** [comment]
@netwmr01 

By default server will not return the instance view field, so 'VirtualMachineOperations.get' response will not contain this field. 
 
Could you try 'getWithInstanceView' instead of 'get' method? getWithInstanceView passes $expand=instanceView query parameter which cause server to return the additional details.

https://github.com/Azure/azure-sdk-for-java/blob/master/resource-management/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachineOperations.java#L401

**Comment by netwmr01** [comment]
This won't solve our problem directly. list of VMs was return by resourcegroup.
We were trying to avoid calling the bad end for each VM.

However, if the sdk doesn't have this feature, we will work around it.

**Comment by anuchandy** [comment]
@netwmr01 Looking at the Azure compute service spec https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2015-06-15/swagger/compute.json#L1148, it looks like the service does not support specifying expand parameter (for instance view) in list. This means SDK can't support this as well.

So we left with the solution: list VMs and call getWithInstanceView for each of them.

**Comment by jianghaolu** [comment]
this is supported in 1.0.0-beta2. See https://github.com/Azure/azure-sdk-for-java/blob/master/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java#L264.
