### ISSUE TITLE
NetworkGetConfigurationResponse Encoding Issue

### ISSUE THREAD

**Issue by hello-azure** [Azure/azure-sdk-for-java#678]
We we invoke the api "NetworkManagementClient.getNetworksOperations().getConfiguration()", we get error error encoding string which is like as bellow:
锘�?xml version="1.0" encoding="utf-8"?>
<NetworkConfiguration xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration">
  <VirtualNetworkConfiguration>
    <Dns>
      <DnsServers>
        <DnsServer name="contosonetDns" IPAddress="10.10.2.4" />
        <DnsServer name="publicDns" IPAddress="114.114.114.114" />
        <DnsServer name="qq" IPAddress="114.114.114.114" />
      </DnsServers>
    </Dns>
...

Please help check this issue. I'm from China Windows Azure Support team. Any question, send email to feevan@126.com

**Comment by jianghaolu** [comment]
Can you provide your local configuration, like OS language, which IDE are you using, etc? So that we can try reproducing it.

At the same time, you can also experiment modifying [this line](https://github.com/Azure/azure-sdk-for-java/blob/master/service-management/azure-svc-mgmt-network/src/main/java/com/microsoft/windowsazure/management/network/NetworkOperationsImpl.java#L306) to 
```java
result.setConfiguration(IOUtils.toString(responseContent, StandardCharsets.UTF_8));
```

**Comment by jianghaolu** [comment]
Maintaining 0.9 is not on the top of the priority list. Please feel free to send a pull request if you've already come up with a fix.
