### ISSUE TITLE
Certificates consistency fixes

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-java#6790]
- [x] isEnabled is listed as a Boolean in sync beginCreateCertificate but is a boolean in async
- [x] includePending is a Boolean in async listPropertiesOfCertificates but a boolean in sync
- [x] certificateProperties parameter -> properties in updateCertificateProperties
- [x] (not 100% sure) get rid of the createIssuer overload that takes in issuerName and provider
- [ ] Make provider required for the CertificateIssuer model
- [ ] You are the only language that allows users to setProperties of KeyVaultCertificate. Should probably get trid
- [x] You are the only language that has a setter for CertificatePolicy in KeyVaultCertificateWithPolicy. Should probably get rid
- [x] Expose vaultUrl for CertificateProperties
- [x] Need constructor in CertificatePolicy that takes both subject and subjectAlternativeNames
- [x] Get rid of getSubjectName in CertificatePolicy
- [x] Inconsistency since CertificatePolicy constructor takes subject and subjectAlternativeNames, but there is no setSubject and there is setSubjectAlternativeNames
- [x] certificateName parameter -> name in MergeCertificateOptions
- [ ] You require at least firstName, lastName, and email for AdministratorContact. None of these are specifically required, just one out of the four are.
- [ ] Same thing for CertificateContact
- [x] getCreated() and getUpdated() -> getCreatedOn() and getUpdatedOn() in CertificateIssuer
- [x] Bigger discussion, but Java doesn't have cancelCertificateOperation on the client. Having it on the CertificateOperation itself requires a get and update permission. Is this something we're ok with?
- [x] What should you do about potentially not having get permissions in a poller? (will discuss as a team)

**Comment by samvaity** [comment]
- [ ] Make provider required for the CertificateIssuer model 
  - It already is?

- [ ] You are the only language that allows users to setProperties of KeyVaultCertificate. Should probably get rid
  - This is the only way users can update the properties and this way of doing the update is idiomatic in java.

- [ ]  Need constructor in CertificatePolicy that takes both subject and subjectAlternativeNames
  - There already is, along with issuerName. Since issuerName is required?

- [ ] You require at least firstName, lastName, and email for AdministratorContact. None of these are specifically required, just one out of the four are.
 Same thing for CertificateContact
  - Do we know which parameter specifically to be required? Or service throws an exception if this fails?
