### ISSUE TITLE
[QUERY] Does DownloadRetryOptions honour BlobRequestConditions?

### ISSUE THREAD

**Issue by vvellanki** [Azure/azure-sdk-for-java#6864]
**Describe the bug**
One of the BlobRequestConditions we use is: ifUnmodifiedSince. On a retry after a partial download, I don't see the BlobRequestConditions being honoured. Let's say, the async request is to fetch a 1MB chunk of a blob. The request was partly successful since the blob wasn't modified and 512k of the blob is available.

When the retry (for the remaining 512k) hits the server, the blob might have been modified and the request condition no longer true. I dont see this being honoured in the retry logic.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***

Specifically, in downloadHelper, I see the BlobRequestConditions being modified for the retry:
                return new ReliableDownload(response, options, info, updatedInfo ->
                    downloadHelper(new BlobRange(updatedInfo.getOffset(), updatedInfo.getCount()), options,
                        new BlobRequestConditions().setIfMatch(info.getETag()), false, context));

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by rickle-msft** [comment]
@vvellanki The DownloadRetryOptions do honor request conditions but perhaps not in the way you're expecting. The workflow you described is correct--we use the passed conditions on the first download call and then for any subsequent calls, we create new request conditions that target the etag returned from the first call. 

We chose this method because we always want to ensure we are downloading a consistent view of the blob, even if the customer didn't pass in request conditions to begin with. In other words, regardless of whether or not there are conditions for starting the download, we always want to ensure we are downloading a single version of the data. Locking on the etag of the first download attempt has this effect as it will fail if the data is modified and therefore the etag changed in between retries. 

I believe this will satisfy your scenario as it has the same effect even if though a slightly different implementation, but please let me know if you have concerns about this approach or if you are seeing incorrect results due to this behavior.

**Comment by rickle-msft** [comment]
I am going to close this issue as I believe it has been addressed and there has been no customer follow up.

Please feel free to reopen the issue or otherwise continue to engage if you need more support.
