### ISSUE TITLE
Update JUnit dependencies in azure-identity

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#6879]
Currently azure-identity has a dependency on junit 4.13-beta-3. This should move in line with the other client libraries that are configured with the following xml:

```xml
<dependency>
  <groupId>org.junit.jupiter</groupId>
  <artifactId>junit-jupiter-api</artifactId>
  <version>5.4.2</version> <!-- {x-version-update;org.junit.jupiter:junit-jupiter-api;external_dependency} -->
  <scope>test</scope>
</dependency>
<dependency>
  <groupId>org.junit.jupiter</groupId>
  <artifactId>junit-jupiter-engine</artifactId>
  <version>5.4.2</version> <!-- {x-version-update;org.junit.jupiter:junit-jupiter-engine;external_dependency} -->
  <scope>test</scope>
</dependency>
```

This should be copy/pasted in place of the existing JUnit 4 dependency. Additionally, it would be great if PowerMock could be removed, and `mockito-junit-jupiter` introduced instead. A good guide is available [here](https://www.baeldung.com/mockito-junit-5-extension).

**Comment by JonathanGiles** [comment]
Paging @mclay in case this is of interest to you! :-)

**Comment by mclay** [comment]
Thanks @JonathanGiles please assign it to me and let me know the estimated due date.

**Comment by JonathanGiles** [comment]
No time requirements - anything you can contribute is appreciated at any time!

**Comment by JonathanGiles** [comment]
@mclay Were you still interested in helping on this, or should it be reassigned? Thanks!

**Comment by mclay** [comment]
@JonathanGiles if i can't make it the next week you can reassign it thanks for waiting

**Comment by mclay** [comment]
hi @JonathanGiles,

upgrading to junit5 in azure-identity is not possible since powermock does not support junit5 currently - see https://github.com/powermock/powermock/issues/830. Replacing powermock with mockito is not feasible because it does not support constructor mocking (i.e. on the fly bytecode manipulation) which is used multiple time to indirectly (integration) test the various IdentityClient.authenticate* methods via PowerMockito.whenNew(IdentityClient.class).withAnyArguments().thenReturn(identityClient); 

I see the following solutions to move forward

1. stick to junit4 until powemockito issue #830 gets resolved
2. refactor the current TokenCredential and introduce an overloaded constructor which accepts an IdentityClient 
3. refactor the current IdentityClient implementation and extract and unit test the various authenticate* methods directly ..?

**Comment by JonathanGiles** [comment]
@g2vinay What are your thoughts? My preference is to move to JUnit 5.

**Comment by joshfree** [comment]
Related https://github.com/Azure/azure-sdk-for-java/issues/7641

**Comment by jianghaolu** [comment]
We will be able to move to mockito once we remove powermock after #7641.
