### ISSUE TITLE
Ship BOM file to simplify end user dependency management

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-for-java#7280]
This issue is to discuss the creation of a Maven 'BOM' (Bill of Materials) artifact that we ship to Maven Central for consumption by our users. In short, a BOM is a customer-focused Maven POM. It alleviates the need for users to track versions of individual Azure SDK components, allowing them to focus on a bigger picture. They only need to upgrade their BOM version, to upgrade all dependencies that they explicitly import. The BOM includes version numbers for all of our Azure SDK releases, but it does not imply that a user is importing all of these dependencies into their own code.

A BOM is versioned in Maven Central, just like any other release. There are no artifacts shipped as part of the BOM, it is simply a POM file referencing other SDK component releases.

Our Azure Java SDK BOM will be referred to with a groupID of 'com.azure', and an artifactID of 'azure-sdk-bom' (or similar). Users would use this BOM from their own projects with a configuration such as:

```xml
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.azure</groupId>
        <artifactId>azure-sdk-bom</artifactId>
        <version>1.12.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

There are two primary benefits to this:

1. Users no longer need to worry that version X of client Y will work with version A of client B - they will be assured that, as long as they don't specify X or A, that Y and B will be guaranteed to work because the versions will be imported from the BOM, and we will guarantee that all versions listed in a single BOM are known to work together, at least in terms of dependency convergence. Users will also no longer need to worry about tracking the release details of each individual library - they can instead just upgrade the BOM version as appropriate.
2. Because of the requirements that benefit 1. places on us, we will be forced to introduce tooling that enables us to identify and work to resolve any dependency convergence issues. This helps to keep us honest and prevent any dependency drift.

This doesn't come for free though. We now have another artifact that we must maintain, version, and ship. This raises a few obvious questions:

1. What is the motivation for releasing BOM versions? Do we do it on a regular cadence (every 3 or 6 months), or do it more adhoc?
2. What is the versioning strategy for the BOM itself? What motivates a major, minor, or patch increment? Unlike other projects that ship a BOM, there is not a single version number being used across all Azure SDK components. Because of this, we can not simply version our BOM with the same version number as that shared by all SDK components. Therefore, for now we could adopt the versioning strategy of simply incrementing the minor or patch number by one for each BOM release.
3. What is the strategy for including (or excluding) libraries in the BOM that are not yet GA?
4. How does the BOM release timing tie in to the desire to pull all client libraries up to the same azure-core?

I have created a very rough [BOM proof of concept](https://gist.github.com/JonathanGiles/2ba417f03f18486095c42b35beda7f12) (although I don't know that the `x-version-update` tags are appropriate for this file), from which I made improvements to my DependencyChecker tool to be able to analyse the dependencies. This resulted in the [linked report](https://jogiles.z19.web.core.windows.net/azure-sdk-client.html), which may be the first stab at the tooling requirements mentioned above.

The recent motivation for this work has been to requests I've received:

1. Difficulty creating end to end apps because the versions of the client library being used were either out of date or a newer version had not yet been released. This resulted in Jackson dependency conflicts and runtime issues.
2. A request from other Microsoft teams to be able to build their libraries atop the Java client libraries without needing to track individual library versions.

// @joshfree @kurtzeborn @danieljurek @weshaggard @mitchdenny @JimSuplizio @srnagar

**Comment by JimSuplizio** [comment]
If we were going to ship a BOM file we'd have to do it with a pretty regular cadence. We ship monthly so we'd probably have to release one monthly. Part of the problem I see in this that not all teams with stakes in the SDK release on the same cycle, or even letting us know they're going to release. The biggest questions are when do we release and how do we deal with stragglers or one off releases (like maybe a beta release is needed for a customer)?

Also, I'd centralized the [external dependencies](https://github.com/Azure/azure-sdk-for-java/blob/master/eng/versioning/external_dependencies.txt) which went in at the end of November. It seems like we should be able to use the external dependencies file in some way shape or form here but there are [external dependency exceptions](https://github.com/Azure/azure-sdk-for-java/blob/b5f759644d19878aa077b6d3fd544f40dc65029d/eng/versioning/external_dependencies.txt#L151) that would need to get taken care of, at least for the client track libraries. When I have a free moment I'll annotate the file with which dependency exceptions are test since that would be good to know at a glance.

I know that what @danieljurek had run into with the smoke tests which was because we were loading core and the preview cosmos. The problems here are that core was built recently built while the cosmos version was from the end of October in a feature branch before I'd centralized the external dependencies. I mention this because when I'd done the centralization work I'd brought versions forward whenever I was able which is probably part of the reason we'd hit this.

**Comment by mitchdenny** [comment]
Thanks for starting this issue @JonathanGiles. I think you've outlined a good set of issues that we need to work through. We want to make sure that we are prepared to support this in the long term because if consumers use the BOM to pull in our packages they could end up stuck there if we don't service it over the long term.

From a versioning strategy perspective I think we would need to bump major/minor anytime one of the internal packages bumped major/minor. So if storage for example came out with a major update we'd probably need to bump the BOM major too.

One thing that came up during the Spring conversations was using such a BOM to control the dependencies for those packages. If we went that route then we probably wouldn't be moving the spring modules into the various service folders as that would create a kind of circular dependency problem.

**Comment by JonathanGiles** [comment]
Thanks for your thoughts. Here are my thoughts to the comments above.

> If we were going to ship a BOM file we'd have to do it with a pretty regular cadence. We ship monthly so we'd probably have to release one monthly. Part of the problem I see in this that not all teams with stakes in the SDK release on the same cycle, or even letting us know they're going to release. The biggest questions are when do we release and how do we deal with stragglers or one off releases (like maybe a beta release is needed for a customer)?

I think of a BOM as a higher-order offering that isn't bound to the release schedule (or ad hoc whim) of any particular client library. What I mean by this is that we don't necessarily need to say that for each client library release there must be a BOM release. For starters, I don't believe people would want to upgrade their BOM this frequently. Secondly, for the reasons you note, keeping such a fast moving BOM in line will be burdensome. In my mind, having a more regular, BOM-specific release timeline (every X months, for example) gives us a motivating requirement to get all dependencies in line a few times a year, which to me seems a far more reasonable cadence for BOM releases. Having said that, further down I link to the release frequency for other BOMs....and the frequency may surprise you!

>Also, I'd centralized the external dependencies which went in at the end of November. It seems like we should be able to use the external dependencies file in some way shape or form here but there are external dependency exceptions that would need to get taken care of, at least for the client track libraries. When I have a free moment I'll annotate the file with which dependency exceptions are test since that would be good to know at a glance.

The only libraries listed in the BOM should be our own azure-* libraries, rather than a full exhaustive list of all transitive dependencies from these azure-* libraries. I would have liked to have used a versions.txt file, but I wasn't sure it would be compatible with our expectations (namely, we don't necessarily want the BOM to move forward automatically and we need to be certain that everything moves in lockstep). I would imagine this might be one instance where, because of the nature of the offering, it is hand-edited once per release cycle to a known-good set of libraries.

>We want to make sure that we are prepared to support this in the long term because if consumers use the BOM to pull in our packages they could end up stuck there if we don't service it over the long term.

I agree. We need to view the BOM offering as a critical 'library' just as if it were azure-core, azure-identity, or any other client library. The motivation for its release might be different (in my mind, every X months makes the most sense), but the importance of doing this regularly, and having it documented in **all** the relevant places (most readme's, the wiki, docs.microsoft.com, etc) is no less than any other library we offer.

>From a versioning strategy perspective I think we would need to bump major/minor anytime one of the internal packages bumped major/minor. So if storage for example came out with a major update we'd probably need to bump the BOM major too.

I view the BOM as a higher-order offering, and therefore don't necessarily subscribe to the argument that version increments should be equivalent to the version increments of the aggregate libraries, as this could lead to some arbitrary versioning choices of the BOM. I note for example that AWS has 1.11.706 as their current BOM version, suggesting they've had 706 minor patch releases in the current 1.11 release! I also note that they do BOM releases **very** [frequently](https://github.com/aws/aws-sdk-java/commits/master/aws-java-sdk-bom/pom.xml).

>One thing that came up during the Spring conversations was using such a BOM to control the dependencies for those packages. If we went that route then we probably wouldn't be moving the spring modules into the various service folders as that would create a kind of circular dependency problem.

In the case of the Spring modules, I don't think this BOM has much of an impact. Instead of their modules specifying a particular version of, e.g., azure-core, they would simply state a dependency on azure-core, and then their particular version number would be picked up by the BOM. This assumes that they prefer to use this instead of the current versioning strategy that we have (and my advice would be almost certainly for them to remain consistent with our versioning strategy for internal dependencies, and to not use the BOM). I would much rather that they instead offer a BOM for their libraries to their end users instead.

**Comment by mitchdenny** [comment]
> I view the BOM as a higher-order offering, and therefore don't necessarily subscribe to the argument that version increments should be equivalent to the version increments of the aggregate libraries, as this could lead to some arbitrary versioning choices of the BOM. I note for example that AWS has 1.11.706 as their current BOM version, suggesting they've had 706 minor patch releases in the current 1.11 release! I also note that they do BOM releases **very** [frequently](https://github.com/aws/aws-sdk-java/commits/master/aws-java-sdk-bom/pom.xml).

Perhaps a better way of saying what I said earlier was that if one of our client libraries that is included in the BOM introduces a breaking change then we should use the version number to signal that. That should occur, but if it did then it would almost always result in that client library doing a major version bump, and I would expect the BOM to do the same.

Otherwise, from the perspective of a developer consuming the BOM as my way of getting Azure goodness, I don't have anyway of knowing whether this version is going to hurt me, so I might be scared off doing it (bad for us and for them). If that happens then the next project I do, I probably wouldn't depend on the BOM because its hard to reason over the magnitude of version changes.

I don't want to rat hole on it though. I just want to make sure we are considering the versioning rules we'll apply here with a view for how it is going to work in 2-3 years time when we do decide that a client library needs a major refactor.

Triggers for a major version bump might include:

1. Client library getting a major breaking change.
2. Client library being deprecated
3. Others?

Regarding Spring, I think we are in alignment on that one (don't depend on the BOM).

**Comment by srnagar** [comment]
The proposal to have a BOM, the release cadence and maintenance strategy outlined by @JonathanGiles  seems reasonable and simplifies dependency management for users a great deal.

One question I have is if our BOM release cadence is every X months and if a customer identified a bug in a certain library that is fixed in the next release of the respective client library, we may not release a BOM for it immediately. What is our guidance to the user until the next cycle of BOM is released? Do we recommend the user to explicitly specify a version for that particular dependency in the interim?

> Otherwise, from the perspective of a developer consuming the BOM as my way of getting Azure goodness, I don't have anyway of knowing whether this version is going to hurt me, so I might be scared off doing it (bad for us and for them). If that happens then the next project I do, I probably wouldn't depend on the BOM because its hard to reason over the magnitude of version changes.

The only major concern I have is the one that @mitchdenny  noted above. How do we manage major version releases? Breaking change (major version update) to even a single client library listed in BOM will warrant a major version update to the BOM as well. As a user of this BOM, if I am not using the client library that had the breaking change, I still need to update the major version to get the latest versions of other libraries that I really use. This may raise some concerns to the user as to what might break and may discourage them from upgrading. 

This is worth a discussion even though major version changes are less frequent. I can think of a couple of ways to do this (neither of them is great)

- **Documentation**: given that major version updates are less frequent, when a major version of BOM is updated, can clear documentation on what client libraries actually contain breaking change be sufficient? Where should such a document be located for easy discoverability? This will still make users think twice before upgrading to a new major version but hopefully, they'll find the documentation helpful to make an informed decision.

- **Multiple BOMs**: if there's a client library that had a breaking change, then do we release a BOM with a new major version while still continuing to have minor version updates to the previous BOM containing updates to client libraries that don't have breaking changes? This is going to be a maintenance nightmare and not recommended.

Are there any other options that we can consider?

**Comment by JonathanGiles** [comment]
After a few offline discussions let me summarise my current thinking:

1. We should have a versioning strategy of 1.x.y, where 'x' will increment when any of the libraries referenced in the BOM has a major release, and 'y' will increment every time the BOM is released.
2. We should have a release cadence somewhere in the order of every 3-6 months.
3. We should not have multiple versioned BOM releases.
4. When a release of a BOM is coming up, we will need to ascertain which version of each library is included. This may not always be the most recent version as the high order bit will be to include all client libraries in the BOM, and for all libraries they must have a single set of dependencies on azure-core, azure-identity, and transitively down from that. This will help to motivate upgrading client libraries to more recent azure-core's such that they do not hold up the rest of the client libraries from having their latest release included in the BOM.

**Comment by joshfree** [comment]
Thanks @JonathanGiles for kicking this off and coming up with the proposal. I’m supportive of introducing the BOM and shipping one in the next monthly update (when it’s ready) to alleviate customer pain around package dependency version mismatch issues.

**Comment by joshfree** [comment]
Moving to the April milestone as part of closing out old past due milestones

**Comment by alzimmermsft** [comment]
`azure-sdk-bom` was shipped on Friday 4/17, closing this issue.
