### ISSUE TITLE
Support for SimpleTokenCredential

### ISSUE THREAD

**Issue by jianghaolu** [Azure/azure-sdk-for-java#7480]
From https://github.com/Azure/azure-sdk-for-java/issues/6525

Users would like to pass a Bearer token directly.

The functional interface TokenCredential can do this but the customer would prefer not to introduce async Mono into the application code.

**Comment by g2vinay** [comment]
Adding SimpleTokenCredential is an anti pattern as the token will be static and will expire in some time with no logic to refresh it.
We should not offer it as part of Identtiy package to Azure users.
Adding @schaabs to add more details.

**Comment by surajkr** [comment]
I stumbled into this feature request, while struggling to invoke SecretClientBuilder,  on behalf of an  Authenticated User in a Java WebApp.  I think having a SimpleTokenCredential(  BearerTokenCredential) provides convenient API  bridge in Java WebApp, as  IAuthenticationResult  for the user is already available.

Typically in  middleware layer,  expired token  is not necessarily not an issue, since upstream layer would be responsible  for passing in valid token at time of invocation. The target app could simple return 401, if token has expired.

In absence of BearerTokenCredential, I had to resort to making  Key Vault Secrets REST API call with many extra lines of code and then resort to JSON parsing.
