### ISSUE TITLE
Allow return type of PagedFluxBase for @ServiceMethod checkstyle checks

### ISSUE THREAD

**Issue by navalev** [Azure/azure-sdk-for-java#7499]
A client may return PagedFluxBase in a public API. Currnet checkstyle does not allow return types other than PagedFlux for @ServiceMethod(returns = ReturnType.COLLECTION)

Request:
Allow @ServiceMethod(returns = ReturnType.COLLECTION) on public APIs returning PagedFluxBase

**Comment by alzimmermsft** [comment]
@mssfang and @anuchandy we should look into updating this rule for the new collection types that we would expect in our APIs. I don't know the complete logic of the rule but we may want to traverse the inheritance tree since one of the newer guidelines by @JonathanGiles is that we should aim to reduce generics in our APIs by implementing these collection types.

**Comment by alzimmermsft** [comment]
@mssfang Co-signing you as the owner since you've worked the most in this area.

**Comment by srnagar** [comment]
We should also update the checkstyle rule to allow WithResponse methods to return types that extend `Response`.
