### ISSUE TITLE
[QUERY] How to paginate without using maxItemCount?

### ISSUE THREAD

**Issue by f-paulus** [Azure/azure-sdk-for-java#7626]
**Query/Question**
In the documentation [1] it is written:
> The maxItemCount property shouldn't be used just for pagination purpose. It's main usage it to improve the performance of queries by reducing the maximum number of items returned in a single page.

We use pagination in the following way:
When we do a query, we set the `maxItemCount` according to the requested result size. We only take the first feed response in the returned flux. From this, we return the result list and also the continuation-token. With this information, we/the user can get the subsequent pages by doing a second query while using the continuation-token in the request.

But according to the documentation, our technique is wrong. The question is: How to do it correctly?

As a side note: Our query orders the results. Therefore we can not work with an `OFFSET LIMIT` clause for pagination. If we do this and there were new items inserted that would have been part of the first page that was already requested, we would get results on the second page that already were given on the first page. This is no problem when paging using the continuation-token as described above.

[1] https://docs.microsoft.com/de-de/azure/cosmos-db/performance-tips#sdk-usage

**Setup (please complete the following information if applicable):**
 - OS: Linux
 - IDE : IntelliJ
 - Version of the Library used: CosmosDB-SDK v3.5

**Comment by joshfree** [comment]
Thanks for filing the issue @f-paulus.  Someone from the Cosmos SDK team will follow up with you soon.

**Comment by jongio** [comment]
@joshfree - Did you make contact with Cosmos on this?

**Comment by tomekapc** [comment]
I'm facing similar difficulties.

I think I understand why `maxItemCount ` is described that way - it's there to optimize the size of the response and we might face a temptation of increasing the page size above of what's optimal.
But, in my opinion, the back-end shouldn't allow this (it's called `maxItemCount` and not `itemCount` for a reason) and we should't be forced to worry about it at all.

I implemented pagination using a similar approach to the one @f-paulus is describing. I instruct the driver to reduce the size of the page using `maxItemCount` in order to make sure, I don't read too much. It might take another round trip to the server in case when the page I need is larger than a page returned from the server, but that's fine. I work with the continuation token and get all the data I need. I can also read further pages on demand because I keep track of the continuation token.

Initially I was tempted to use `OFFSET LIMIT` here, but.. we don't get the continuation token and as a side effect, every future page query becomes slower and more expensive (I wished we had support for `OFFSET` only, without the `LIMIT`...).

So yeah, +1 here, I'd be interested to hear whether there is a better solution for pagination than just fiddling with the `maxItemCount ` option.

**Comment by tomekapc** [comment]
I'm aware of the fact that we're working on a preview and beta releases.

As of `4.0.1-beta.2` the `FeedOptions::setMaxItemCount` method is no longer public. This change breaks our pagination.

Do you have a suggestion on the best workaround. Our current solution was described above.

**Comment by kushagraThapar** [comment]
@tomekapc  - in 4.0.1-beta.2 -> you have `CosmosPagedFlux` -> which has following APIs: 
`byPage()`
`byPage(continuationToken)`
`byPage(pageSize)`
`byPage(continuationToken, pageSize)`

See this for reference : https://azuresdkdocs.blob.core.windows.net/$web/java/azure-cosmos/4.0.1-beta.2/index.html -> And search for `CosmosPagedFlux` and `CosmosPagedIterable`

Query / Read all / etc. operations now return `CosmosPagedFlux` for async operations and `CosmosPagedIterable` for sync operations. 
Using this, you should be able to achieve what you were doing with `FeedOptions`

**Comment by kushagraThapar** [comment]
@tomekapc  - Refer to these samples for examples on `CosmosPagedFlux` and `CosmosPagedIterable`

**Comment by tomekapc** [comment]
@kushagraThapar thank you for the hint! `CosmosPagedFlux` and `byPage(continuationToken, pageSize)` was exactly was we needed.

You mentioned some examples but it looks like the link is missing. We were able to restore our paging functionality but seeing a few more examples of how to use `CosmosPagedFlux` and `CosmosPagedIterable` correctly would be helpful for the future.

**Comment by kushagraThapar** [comment]
lol, I am sure I pasted it :P 
Here you go - https://github.com/Azure-Samples/azure-cosmos-java-getting-started
This sample project has both sync and async examples.
