### ISSUE TITLE
[BUG] Download blob returns exception

### ISSUE THREAD

**Issue by nadav-lavy-exa** [Azure/azure-sdk-for-java#7627]
**Describe the bug**
When doing  
`blobClient.downloadToFile(tmpFile.toString());`

We occasionally receive a 412 error with message:  
`The condition specified using HTTP conditional header(s) is not met`

***Exception or Stack Trace***

```
BlobStorageException: Status code 412, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>ConditionNotMet</Code><Message>The condition specified using HTTP conditional header(s) is not met.
RequestId:34de4eeb-d01e-0066-263a-d1496d000000
Time:2020-01-22T15:44:59.0296281Z</Message></Error>"
```

**To Reproduce**
Download a blob many times. it just happens occasionally. from this thread is looks like its a race condition caused by a non-atomic acquisition of the blob stream - 
https://stackoverflow.com/a/5098107/409565

***Code Snippet***
`blobClient.downloadToFile(tmpFile.toString());`

**Expected behavior**
No exception

**Screenshots**

**Setup (please complete the following information):**
 - OS: Linux
 - IDE : [e.g. IntelliJ]
 - Version of the Library used: 12.1.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ V] Bug Description Added
- [ V] Repro Steps Added
- [ V] Setup information Added

**Comment by joshfree** [comment]
Thanks for reporting this issue @nadav-lavy-exa.  The Azure Storage SDK team will follow up with you (and the stackoverflow post) soon.

/cc @rickle-msft @alzimmermsft

**Comment by rickle-msft** [comment]
@nadav-lavy-exa We lock on the etag when starting a download because we want to ensure we download a consistent view of the blob. This exception should only occur if there is another process somewhere that modifies the blob in the middle of the download. In that case, this exception is expected and correct and the solution is to either retry your download or to organize your application to avoid overwriting data you are in the middle of downloading (possibly through leases). 

If you are seeing this exception and you believe you are running in an environment where this sort of concurrent modification should not be happening, I would first like to see the Fiddler captures of the download requests (at least one successful one and then the failed one from downloading the same file and actually also the etag from the portal/subsequent get properties call after the failed request) to confirm that the etag and last modified time are indeed not changing between requests.

**Comment by nadav-lavy-exa** [comment]
@rickle-msft our client reads the data in a separate business process than its writer, and we wouldn't want to block them from writing (by acquiring a lease).
I think we'll need to handle these errors are add a retry mechanism

**Comment by gauravdhim1990** [comment]
I am also getting the same error azure event hub while consuming the event and marking for checkpoint

**Comment by rickle-msft** [comment]
@gauravdhim1990 I think it will be more helpful if you open a new issue and describe more details about your environment, code, and error.
