### ISSUE TITLE
Method importCertificate in azure-security-keyvault-certificates:4.0.0 fails with 405

### ISSUE THREAD

**Issue by jokarl** [Azure/azure-sdk-for-java#7682]
Hi,

I'm trying to upload pre-existing certificates to our key vault. I've successfully used the certificate creation flow, so I know I can communicate with the key vault. This seems like an underlying issue.

I have generated a certificate and saved it in a file called `root.pem`. It's formatted as follows to satisfy the requirements of `ImportCertificateOptions`:

```
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
-----BEGIN RSA PRIVATE KEY-----
...
-----END RSA PRIVATE KEY-----
``` 

I call the import method as follows:

```java
// SDK call
client.importCertificate(new ImportCertificateOptions("import", Objects.requireNonNull(Util.fileToByteArray("keys/root.pem"))));

// Util method
public static byte[] fileToByteArray(final String path) {
    try {
        return Files.readAllBytes(Path.of(path));
    } catch (IOException e) {
        e.printStackTrace();
    }
    return null;
}
```

When I call this method, the call fails with:
> com.azure.core.exception.HttpResponseException: Status code 405, "{"error":{"code":"MethodNotAllowed","message":"HTTP POST not allowed"}}"

The call fails in the SDK class `CertificateService`.

# Information
**SDK(s):**
com.azure:azure-security-keyvault-certificates:4.0.0
com.azure:azure-identity:1.0.3

**JDK:** 
openjdk 11.0.5 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-0ubuntu1.1)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Ubuntu-0ubuntu1.1, mixed mode, sharing)

**OS:**
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Pop!_OS 19.10
Release:        19.10
Codename:       eoan

**Comment by joshfree** [comment]
Thanks for reporting this issue @hochas.  @g2vinay can you please investigate and follow up with @hochas?

**Comment by g2vinay** [comment]
@hochas 
Thank you for raising this issue.

I am using the same libraries in a sample app:
com.azure:azure-security-keyvault-certificates:4.0.0
com.azure:azure-identity:1.0.3

But, I am not able to reproduce this error for importCertificate API call.
405 on Http Post means that resource doesn't support POST call, but that's not the case.

It would be helpful, if you could share the following:
1. Dependencies info - (pom file)
2. Ensure Import permission is granted.
3. Authentication code/style used with KV. (exclude any keys/ids).
4. Type of KV used.


Looping in @anuchandy

**Comment by anuchandy** [comment]
Hi @hochas, are you behind any corporate proxy?

**Comment by hochas** [comment]
Thanks for the quick replies. I will answer what I can now and the rest when I'm back at work.

I am using the basic key vault, without HSM support. I have created a principal as per the instructions in the repository. I am authenticating using the same instructions, by populating the required environment variables. I am using the synchronous client. 

No proxy, and I can POST to other APIs we have deployed ourselves in Azure.

I will get back Monday and supply a full dependencies list.

**Comment by hochas** [comment]
Here are all the dependencies I use:
```groovy
implementation platform("io.dropwizard:dropwizard-bom:2.0.0")
implementation "io.dropwizard:dropwizard-core"

implementation "com.azure:azure-security-keyvault-certificates:4.0.0"
implementation "com.azure:azure-identity:1.0.3"

implementation "org.bouncycastle:bcprov-jdk15on:1.64"
implementation "org.bouncycastle:bcpkix-jdk15on:1.64"

testImplementation "org.junit.jupiter:junit-jupiter-api:5.5.1"
testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:5.5.1"
testCompile "org.assertj:assertj-core:3.11.1"
```

**Comment by hochas** [comment]
I have also verified it is not an access issue. I granted the principal every certificate permission there is for the key vault and still the same result.

**Comment by hochas** [comment]
I noticed I did not follow the documentation [as outlined here](https://docs.microsoft.com/en-us/azure/key-vault/certificate-scenarios#formats-of-import-we-support). However, even when private key is formatted according to PKCS#8 standard, I get the same error.

```
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----
```

> Exception in thread "main" com.azure.core.exception.HttpResponseException: Status code 405, "{"error":{"code":"MethodNotAllowed","message":"HTTP POST not allowed"}}"

I took the exact same file and uploaded manually to the key vault through the portal, and it works.

Is it the way I am getting the bytes of the pem file?

**Comment by vcolin7** [comment]
Hi @jokarl, I tried using the library versions you mentioned to reproduce the issue to no avail. If the way you are getting the bytes was the problem, then you would see a message like:
```
Exception in thread "main" com.azure.core.exception.HttpResponseException: Status code 400, "{"error":{"code":"BadParameter","message":"The specified PEM X.509 certificate content is in an unexpected format. Please check if certificate is in valid PEM format."}}"
```

For example, let's say you create a self-signed certificate on Windows using the following command:
```
openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out cert.pem
```
Then, you create a new file that contains both the contents of `key.pem` and `cert.pem` following the correct format as outlined in the [documentation you mentioned](https://docs.microsoft.com/en-us/azure/key-vault/certificates/certificate-scenarios#formats-of-import-we-support).

Everything looks good so far, right? Now we need to get the certificate's contents as a byte array. If we get the exact bytes by using something like `FileUtils.readFileToByteArray()` from Apache's common-io, the `importCertificate()` call will fail with the message shown above, this is because all new lines in Windows' include a carriage return (`\r\n`). As it turns out, it seems Azure Key Vault expects new lines to only use `\n` like UNIX based systems do. One way to get around this problem is to simply read a Windows file's contents line by line, saving that into a string and then converting it to a byte array:

Here's an example of what that code could look like:

```java
StringBuilder contentBuilder = new StringBuilder();

try (Stream<String> stream = Files.lines(Paths.get(path), StandardCharsets.UTF_8)) {
    stream.forEach(s -> contentBuilder.append(s).append("\n"));
}

String fileContents = contentBuilder.toString();
byte[] certificateToImport = fileContents.getBytes();
ImportCertificateOptions config = new ImportCertificateOptions(certificateName, certificateToImport).setEnabled(true);
KeyVaultCertificate importedCertificate = certificateClient.importCertificate(config);
System.out.printf("Received Certificate with name \"%s\" and key id %s", importedCertificate.getName(), importedCertificate.getKeyId());
```

Notice how we add only the newline (`\n`) character after every line is read.

As a final note, if you try to upload the certificate created on Windows by using the Azure Portal you won't have any trouble whatsoever. I assume this is because there is some form of sanitization done by the Portal before sending the contents to the Key Vault Service.

**Comment by vcolin7** [comment]
Please give this code a try and let me know if you encounter any issues :)

**Comment by jokarl** [comment]
Thanks @vcolin7, I'm on vacation right now but I'll see if I can get this to work once I'm back. I do think I have a working upload with a certificate generated

**Comment by AlexGhiondea** [comment]
@jokarl please let us know if you are able to repro this.
