### ISSUE TITLE
[BUG] Support non-IP address based development URLs

### ISSUE THREAD

**Issue by linusnorton** [Azure/azure-sdk-for-java#7909]
**Describe the bug**

Since migrating to version 12 of the SDK it will no longer connect to Azurite in a docker container.

***Exception or Stack Trace***

```
dm-store_1                        | 2020-02-03 13:51:19.946 ERROR 1 --- [nio-8080-exec-2] u.g.h.d.errorhandler.ApiErrorAttributes  : Status code 501, "Path or Http-Method does not match any emulated command.
dm-store_1                        | Possible causes include
dm-store_1                        |   - missing account name path parameter
dm-store_1                        |   - Unsupported Http-Method on resource
dm-store_1                        |   - Unsupported / Not implemented "comp" query parameter on resource"
```

**To Reproduce**

Create a docker compose file with Azurite and try to access it using it's container name.  

For example: https://github.com/hmcts/rpa-em-ccd-orchestrator/blob/master/docker-compose-dependencies.yml#L152-L202

***Code Snippet***

This is the change that causes the problem:

https://github.com/Azure/azure-sdk-for-java/pull/6156/files#diff-c498bc9cb41a9cfda139edbe2bd692c9R105-R110

**Expected behavior**

It should be possible to use Azurite with a non-IP address connection string.

**Screenshots**

N/A

**Setup (please complete the following information):**
 - OS: Ubuntu 18.04
 - IDE : IntelliJ
 - Version of the Library used: 12.3.0

**Additional context**

Relates to #6140

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by JonathanGiles** [comment]
Thanks for using our Azure SDK and reporting this issue. @rickle-msft will take a closer look at this issue and get back to you.

**Comment by rickle-msft** [comment]
@linusnorton From what I understand, we have support for urls of the form `http://account.blob.core.windows.net/container/blob` (no IP and no port) and `http://<ip>:<port>/account/container/blob` (IP and port) but we do not support `http:/account.blob.core.windows.net:port/container/blob` (no IP; port). This last one is what you're trying to use. Is this correct?

**Comment by linusnorton** [comment]
Not quite, I am trying to use `http://azure-storage-emulator-azurite:10000/devstoreaccount1` as part of a docker compose file that uses the Azurite container: https://hub.docker.com/_/microsoft-azure-storage-azurite.

It uses to work with version 8 but stopped when I upgraded to 12.2.0. Using 12.3.0 didn't help either.

**Comment by rickle-msft** [comment]
Thanks for responding. I'm not super familiar with docker and particularly how it's interacting with Azurite, so I appreciate your help in drilling this down. 

What I'm not quite understanding is that `azure-storage-emulator-azurite` isn't a resolvable DNS entry as far as I can tell, so I don't quite know how this endpoint is supposed to work; I don't know how we would know to send the request to your localhost. It looks like [azure-storage-emulator-azurite](https://github.com/hmcts/rpa-em-ccd-orchestrator/blob/master/docker-compose-dependencies.yml#L195) has some other definition that may be affecting how this endpoint is resolved when it's passed into the client? If it's not too much to ask, can you please try to capture the url that is being given to the client builders so I can be more confident in the format?

**Comment by linusnorton** [comment]
It's a feature of docker-compose: each container is given a name that can be used as a DNS entry. 

For example if I create a container:

```
  azure-storage-emulator-azurite:
    image: arafato/azurite
    ports:
      - 10000:10000
    environment:
      executable: "blob"
    volumes:
      - ccd-docker-azure-blob-data:/opt/azurite/folder
```
Then when other containers try to access it they can use the dns `azure-storage-emulator-azurite`

**Comment by rickle-msft** [comment]
Oh interesting. I think I understand now. I think we can fix this by changing our connection string parsing to set the endpoint field directly rather than calling into the method that parses the endpoint and is not recognizing the format (because of the code you linked).  

For future dev reference:
I wouldn't feel comfortable modifying the logic you cited for parsing the endpoint because that method has a slightly different meaning than the endpoint given in connection strings. I think we can trust that whatever the customer sets as their endpoint in the connection string can be placed literally as the client endpoint. This is also what v8 did. By contrast, the method you linked to is supposed to be used to parse a raw endpoint passed by the user that could contain a full blob path and query components we want to break apart. Plus, the form you've given us would make it impossible to determine if the first path element is the container or the account. (The only option we'd really have left is to check for a ':' and a port number, but that seems a little too generic to be safe).
