### ISSUE TITLE
Enable client libraries to opt-out of buffer copying when using azure-core-netty

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#8050]
Due to recently reported [storage data corruption issue](https://github.com/Azure/azure-sdk-for-java/issues/7997), `azure-core-netty` is going to deep copy ByteBuffer to workaround reactor-netty reclaiming ByteBuffer. 

Because the characteristics of Azure services differ drastically, we could provide a settable toggle for client library developers to use to opt-out of the buffer copying. This enables services that care about data correctness over performance to remain opted-in, whilst other services may choose to prefer performance over data correctness, in which case they may opt-out. Client libraries may choose to expose this to end-users, but this would need further investigation. We don't expect this to be heavily used, or encouraged, but it may find a valid use case in time.

In the fullness of time, it would be our desire to push this fix down into reactor-netty itself, and out of the Azure SDK for Java entirely, but we will make that a secondary priority with our first priority to get a fix that works into azure-core itself. Even in the case that this happens, we sense there remains value in retaining the opt-out feature discussed above.

**Comment by rstoyanchev** [comment]
> other services may choose to prefer performance over data correctness

Data correctness doesn't seem like a preference. Are there scenarios where corrupted data could be acceptable? Or do you perhaps mean is that applications might want to turn off deep copying if data is consumed immediately within onNext? In which case it would make sense to turn copying off.

I think the obstacle at the core of this problem is that returning `java.nio.ByteBuffer` eliminates the possibility to take advantage of pooled `ByteBuf`s because the code downstream does not have access to the `retain` and `release` controls.

I don't know if it is feasible, but if you could expose an additional API to consume data as `Flux<ByteBuf>`s, then the applications could opt into working with `ByteBuf`s, which makes perfect in cases where further downstream Netty is involved. This would give an application the ability to retain and pass on pooled direct buffers. In the case of a WebFlux controller those would be written through Netty to the server response.

**Comment by srnagar** [comment]
@rstoyanchev yes, data correctness is not optional. However, as you mentioned, if the data is consumed immediately before returning from `onNext()`, then copying is unnecessary and can improve performance. 

Providing APIs that return `Flux<ByteBuf>` is a good suggestion but we'll have to look into the feasibility of adding this.

**Comment by srnagar** [comment]
Done in https://github.com/Azure/azure-sdk-for-java/pull/8055
