### ISSUE TITLE
Add tests to use OkHTTP 

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#8114]
Most of our client libraries use `azure-core-http-netty` as the Http client by default. So, all our tests run using netty but we should have tests that swap out `azure-core-http-netty` with `azure-core-http-okhttp` and run the tests so we ensure all changes are tested with both http clients.

**Comment by alzimmermsft** [comment]
Should we extend the test framework to handle running permutations at a test suite level where we could plug in Netty or OkHttp for an entire test run?

**Comment by srnagar** [comment]
Customer-reported issue for OkHttp client - https://github.com/Azure/azure-sdk-for-java/issues/8183

**Comment by joshfree** [comment]
@sima-zhu could you assist with this issue please?

**Comment by sima-zhu** [comment]
Looking this

**Comment by sima-zhu** [comment]
Testing over whether OkHttp and Netty populate different request and response in record-json files.

**Comment by sima-zhu** [comment]
Spot check and confirmed from test json and Anu, Okhttp and netty generate the same http request and response.

Current options:
1. Parameterized run on okhttp and netty. Not very ideal since we takes too long to run netty test suite. It will introduce more burden to each build if we setup two test suites.
1. (Optimal) Add new env variable and run different http client on different pipelines, which will not change the overall structure too much. 
For this approach, need to involve eng team, since we do not support different test env sets for service. The assumption is each live test only based on one test env set. @danieljurek  is helping to look into the feasibility.

**Comment by srnagar** [comment]
Fixed in #8679
