### ISSUE TITLE
Fit and finish 

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#8160]
- IndexingParametersExtensions equivalent is missing
- Need to support @search.coverage in AutocompletePagedResponse (it's in the Swagger already)
- Add support for FieldBuilder
- Need to set Accept to application/json;odata.metadata=none in all Documents operations

**Comment by alzimmermsft** [comment]
`@search.coverage` is being added to `AutocompletePagedResponse` in #8303

**Comment by alzimmermsft** [comment]
Setting `application/json;odata.metadata=none` was added in #8772.

**Comment by alzimmermsft** [comment]
Spun off `FieldBuilder` into issue #8903.

**Comment by alzimmermsft** [comment]
@brjohnstmsft would static helpers be sufficient to cover `IndexingParametersExtensions`?

**Comment by brjohnstmsft** [comment]
@alzimmermsft That's a question for @bleroy

**Comment by bleroy** [comment]
I'm sorry, I don't see anything named `IndexingParametersExtensions`. Where's that?

**Comment by alzimmermsft** [comment]
@bleroy It is in the Track 1 SDK for .NET, [IndexingParametersExtensions](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/search/Microsoft.Azure.Search.Service/src/Customizations/Indexers/Models/IndexingParametersExtensions.cs), looking at that class again I realize it is a static helper class and not a partial class as were a few other change requests.

I'm going to spin this off into a new issue so this one can be closed since half the requests are completed and the other two are disparate concepts that should be tracked separately. This is the new issue to add a helper class for `IndexingParameters`, https://github.com/Azure/azure-sdk-for-java/issues/8908.

**Comment by bleroy** [comment]
@alzimmermsft thanks for the clarification, I was missing context on this one. Makes sense.
