### ISSUE TITLE
Move generated code outside api package

### ISSUE THREAD

**Issue by jianghaolu** [Azure/azure-sdk-for-java#839]
Currently, the generated code are living in api package, which is easy for regeneration but we shouldn't bring users confusion for the easiness on our side. 

- [x] Move inner classes from `implementation.api` to `implementation`.
- [x] Move non inner classes out of `implementation`
- [x] Add special license header to flag these as generated files
- [x] Change codegen script to only delete files with the special license header

**Comment by selvasingh** [comment]
Agree this is important.

**Comment by martinsawicki** [comment]
the basic problem is that we're letting some of that auto-gen'd impls bleed through the fluent APIs. Eventually, this problem will need to be resolved more elegantly. the current situation is a pragmatic compromise, otherwise we have many more data-only classes to wrap manually, which may not be the best use of time for beta2

**Comment by jianghaolu** [comment]
Done in beta2.
