### ISSUE TITLE
Storage Exception deserializing logic 

### ISSUE THREAD

**Issue by gapra-msft** [Azure/azure-sdk-for-java#8481]
When an error occurs on a HEAD request, we deserialize to an HttpResponseException instead of a *StorageException. This seems to be due to the fact that HEAD requests do not return a body and the Exception handling logic seems to expect an XML body that describes the error. 

Repro
(Call getProperties on a non-existing file, you can probably use one of the original getProperties tests)
ShareFileClient client = new ShareFileClientBuilder().credential().endpoint().buildFileClient();
client.getProperties();

**Comment by alzimmermsft** [comment]
Finally had a chance to look into this, it actually looks like the Swagger generated layer is missing the `UnexpectedResponseExceptionType` annotation. With that annotation missing the default exception type will default to `HttpResponseException` which is why this method is returning that.

This is the current code for the generated method.

```java
@Head("{shareName}/{filePath}")
@ExpectedResponses({200})
Mono<FilesGetPropertiesResponse>
```

It should be this to match the other generated code.

```java
@Head("{shareName}/{filePath}")
@ExpectedResponses({200})
@UnexpectedResponseExceptionType(ShareStorageException.class)
Mono<FilesGetPropertiesResponse>
```

**Comment by alzimmermsft** [comment]
@gapra-msft Let me know the next time the client is going to be regenerated and we can look into resolving this issue if there is a Swagger transform bug.

**Comment by gapra-msft** [comment]
Closing due to PR being merged to fix it
