### ISSUE TITLE
[Azure Core] RetryPolicy, Missing getter methods of private final properties

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#8504]
Below private final properties variables could have public getter that for any class that extends RetryPolicy can access the value.
```
    private final RetryStrategy retryStrategy;
    private final String retryAfterHeader;
    private final ChronoUnit retryAfterTimeUnit;
```

FYI: @mrm9084

**Comment by mssfang** [comment]
@mrm9084  Can you provide more detail about why these getter is required?

**Comment by mrm9084** [comment]
@mssfang In order to extend RetryPolicy the retryStrategy, retryAfterHeader, and retryAfterTimeUnit need to be accessed to override various methods. But as they are private with no getter that isn't possible. I could create a duplicate copy of the values as I passed them to you, but any changes would diverge and the resulting object would have to instances of each value.

**Comment by mssfang** [comment]
@alzimmermsft  @srnagar 
Is getter implementation possible or there is a better solution.

**Comment by alzimmermsft** [comment]
There isn't a strong reason I can think of to prevent these properties from being accessed, they just shouldn't be able to be set after instantiation of the immutable class.

**Comment by mssfang** [comment]
@srnagar what do u think? I remember your have some ideas about provide these getters is unnecessary.

**Comment by mrm9084** [comment]
@alzimmermsft @mssfang There are 2 feature that we want to add. Fist is that the retry after time should not just take the ms-retry-after value, but take the max value between that and the retryAfterTimeUnit. The second feature we want to add is setting a max retry time for the whole request. i.e. we want the request to last longer than 60s. We can do this by setting a block timeout value, but that will not return the correct error code. We want no more retry requests to happen after the time has past.

**Comment by mrm9084** [comment]
@mssfang @alzimmermsft @srnagar After thinking about this a bit more. What we really need is for the RetryPolicy to be more extensible. If shouldRetry and determineDelayDuration were made protected then I would be able to override them in my code. Then if they also passed the retry strategy into the methods then I would be able to use is.

**Comment by srnagar** [comment]
Discussed this with @mrm9084 over a call.
>Take the max value between ms-retry-after value and duration computed by `calculateRetryDelay()` method in RetryStrategy

To enable this, one option is to extend `calculateRetryDelay()` to include `HttpResponse` as a param but that will be a breaking change. The other option is to make `determineDelayDuration` a protected method which will not be a breaking change.

> Setting a max retry time for the whole request. i.e. we want the request to last longer than 60s. 

To achieve this, adding getters methods or making `shouldRetry` and `determineDelayDuration` may not be sufficient. There is still no information about when the first attempt was made and the total time elapsed since then.
