### ISSUE TITLE
Get rid of raw type usage in Data disk [refer NSGRule]

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-java#884]

**Comment by martinsawicki** [comment]
Subnet has now successfully followed the same pattern as NSG rules - though Subnets have a simpler version of it. (I don't think Subnet needs the *DefineUpdate portion yet, since there is only one property that can be updated it seems: addressSpace). IN any case, yes, I think NSG rule is now a good example to follow .

**Comment by anuchandy** [comment]
@martinsawicki thanks, used NSG as an example to get DataDisk done

**Comment by anuchandy** [comment]
merged
