### ISSUE TITLE
[QUESTION] Difference between BlobProperties and BlobDownloadHeaders

### ISSUE THREAD

**Issue by omarsmak** [Azure/azure-sdk-for-java#8902]
**Query/Question**
Hello guys, 
I have a question which I am bit confused about currently, at `BlobClientBase`, there are methods like `downloadWithResponse` and `downloadToFileWithResponse`, one returns `BlobDownloadResponse` and the other return `BlobProperties`. `BlobDownloadResponse` has `BlobDownloadHeaders` which I guess is similar to `BlobProperties`, may I know what is the difference? 
I wonder why not all methods that related to download blob don't have a unified response, is kinda painful to figure this out. Generally I find the API structure is a bit confusing.

**Comment by rickle-msft** [comment]
Hi, @omarsmak. Thank you for your question. You are correct that `BlobDownloadHeaders` and `BlobProperties` are quite similar. The reason why we return `BlobProperties` from `downloadToFileWithResponse` is because there are some fields on `BlobDownloadHeaders` that don't make sense to return when downloading to a file. For example, because we actually split up the download into a bunch of different download operations in order to parallelize the operation, each `BlobDownloadResponse` will come back with a `Range` header. However, someone calling `downloadToFile` expects the whole file to be downloaded, so returning a range isn't meaningful and may even be misleading if the they think it indicates something less than the entire blob was transferred. For this reason, we found it more appropriate to return `BlobProperties` when downloading to a file, which has all the same relevant information.

Your confusion is understandable as the distinction is subtle and not immediately obvious. There are a few cases like this around the SDK, but we've tried to design things in such a way that, even if distinctions like this one aren't entirely clear in their reasoning, you're guided to the correct solution and behavior simply by using what is available. If you have any further questions about the behavior and choices in the SDK, we're happy to answer those as well.

**Comment by omarsmak** [comment]
Hi @rickle-msft , thank you for the explanation and I get what you mean and I appreciate your time answering my question. You have a valid point about this. However, wouldn't make sense for example to have a base model that represents the common data across different models and then inherent whatever is needed? Now the issue is, I have to implement a wrapper on every different response, although they are almost identical. Moreover, I see some properties with different types, e.g: `lastModified`  in one appears as `OffsetDateTime` and the other one appears as `DateTimeRfc1123 `, hence as result, I may be losing now source of the truth of my data and may cause data deprecation among different entities as result of the redundancy.

**Comment by rickle-msft** [comment]
Another reasonable idea. The reason why we didn't implement it this way is largely to do with code generation. It didn't seem prudent to us to wrap every generated type with a hand written model type, and we can't generate code that inherits from some written type or encode an inheritence hierarchy like this in our spec. 

Can I ask what aspect of your scenario requires you to have a wrapper around `BlobProperties` and `BlobDownloadHeaders`? 

As far as `DateTimeRfc1123`, there should be a `getDateTime()` method on there which returns an `OffsetDateTime` as well as a public constructor which takes an `OffsetDateTime`, so I don't think there should be any loss of precision or anything like that. `DateTimeRfc1123` only affects the `toString()` method.

**Comment by omarsmak** [comment]
I see, yeah I can see the point about the code generation. 
Regarding my scenario, I am writing a camel component for the blob sdk v12 API. I will need to add the headers that can be obtained through `BlobProperties` and `BlobDownloadHeaders`  for every blob operation, e.g: download, upload, delete ..etc, for pageblog, appendblob etc. Because I didn't want to handle every response of the operations separately, I wanted to write a generic function that set the message headers from the response data, e.g: `BlobProperties` ,you just give it the response object and it sets the headers as `Map`. Of course, that would be possible if there was a base model and then handle specific cases later. If I had to implement limited APIs, I can manage that, but since I almost need to cover many of the blob APIs into the component, handling every response would be a bit annoying, I hope you got my idea :)

**Comment by rickle-msft** [comment]
I see. I think if you are trying to build a Map of headers from the response, you should be able to use `response.getHeaders()` instead of `response.getDeserializedHeaders()`. The former will return an instance of `HttpHeaders` that is essentially an `Iterable<HttpHeader>`. You could just iterate over these headers to build the map. Further, all response types do derive from `ResponseBase<>`, so you could write a method that looks something like the following:
```
Map<String, String> extractHeaders(<? extends ResponseBase> response) {
  Map<String, String> headersMap = new HashMap<>;
  for (HttpHeader header : response.getHeaders()) {
    headersMap.put(header.getKey(), header.getValue());
  }
  return headersMap;
}
```

Hopefully I correctly understood your intention?

**Comment by omarsmak** [comment]
Yeah initially I was using this, however the header key has to be mapped to another key (application specific key) , hence the knowledge of the property is essential in order for me to map to header value to the appropriate key

**Comment by rickle-msft** [comment]
I'm not sure I understand completely. When you say "knowledge of the property", you mean the property name? As in one of the properties on the `DownloadResponseHeaders` being `blobType`? And your issue is with the fact that the key for the header is `x-ms-blob-type`, which doesn't match the deserialized property name?

If I'm not correct in my understanding, could you please provide an example of with some desired inputs and outputs to the method you are trying to write so I can have something more concrete to work with? 

For the record, I can't guarantee that there is a clean solution for this particular problem, though I understand your concern regarding writing wrappers for response types. However, I will do my best to try to find a reasonable and effective solution for this scenario.

**Comment by omarsmak** [comment]
Sorry for the confusion, I mean here the property key name. For example the value of key 'x-ms-blob-type' needs to be mapped to 'CamelBlobType' key name in my headers map. 
Is okay, I guess I can find an alternative solution for my use case. Thank you for the help :)

**Comment by rickle-msft** [comment]
I see. Storage is very consistent in using 'x-ms-' as a prefix for storage headers, so you could maybe have some sort of helper to transform storage header names into property names by removing the prefix, splitting on "-", casing appropriately, and joining. I think this should get you the mapping you want.

In any case. I am glad you seem to have options that work for you. I am going to close this issue as I think your concerns have been addressed. Please feel free to reopen or post a new issue if you need further assistance.
