### ISSUE TITLE
Unified Pipeline Nightly Run Failure: Configure GPG passphrase

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-java#8985]
Failure in nightly unified pipeline run publishing to Java dev feed: Configure GPG passphrase

A retry of this job succeeded. Is there more we can do to ensure this succeeds on the first pipeline execution? 

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=288752&view=logs&j=b1e79959-24d8-5aa9-2799-72d40c3e051b&t=616ae03f-d350-5ea1-2948-454bf182d472

```

LoadPercentage : 1


gpg-connect-agent: no running gpg-agent - starting 'D:\a\1\azure-sdk-build-tools\tools\gpg\bin\gpg-agent.exe'
gpg-connect-agent: waiting for the agent to come up ... (5s)
gpg-connect-agent: waiting for the agent to come up ... (4s)
gpg-connect-agent: waiting for the agent to come up ... (3s)
gpg-connect-agent: waiting for the agent to come up ... (2s)
gpg-connect-agent: waiting for the agent to come up ... (1s)
gpg-connect-agent: can't connect to the agent: IPC connect call failed
gpg-connect-agent: error sending standard options: No agent running
gpg-preset-passphrase: can't connect to 'D:\a\1\azure-sdk-build-tools\tools\gpg\home\S.gpg-agent': IPC connect call failed
gpg-preset-passphrase: caching passphrase failed: IPC connect call failed
##[error]PowerShell exited with code '1'.
```

cc @mitchdenny

**Comment by mitchdenny** [comment]
There is a bit of a back story here. When we were originally using "release management" we were using a PowerShell script on the VS2017 hosted image to sign and deploy the Maven packages. When we moved to Unified Pipelines I swapped this out for GPG signing on Linux as part of the overall ESRP signing process.

Because of the work to support Android and a broader set of Maven artifacts in the unified pipelines we moved back to using PowerShell (this time on Windows 2019) to sign packages (via the Maven GPG signing plugin).

I'm thinking that GPG on Windows 2019 might be a bit flakey (its the only thing I can think of because @weshaggard  said that he didn't see these issues in release management ... using the VS2017 hosted image).

I could look at moving this job over to Linux where GPG is a little bit more at home, however one of the reasons I ended up with my approach in the first pass of unified pipelines was because I couldn't find a version of GPG that was compatible with Maven GPG and the distro of Linux we were using.

Living the compat nightmare right now ;)

**Comment by mitchdenny** [comment]
I'm going to swap the image back to Hosted VS2017 for a while and see if that makes the problem go away. If so then it could just be a Windows 2019 compat issue (which we'll then need to figure out what to do about). Perhaps we could update GPG.

**Comment by mitchdenny** [comment]
This change has been merged on the internal build tools repo. We'll see whether it solves the problem.

**Comment by mitchdenny** [comment]
No failures so far. Give it a few more days.

**Comment by mitchdenny** [comment]
All looking good. I created an issue to do some further work around Maven GPG plugin 1.7. 

#10388
