### ISSUE TITLE
[QUERY] azure-keyvault version 1.2.3

### ISSUE THREAD

**Issue by timahenning** [Azure/azure-sdk-for-java#8986]
**Query/Question**
I could not find version 1.2.3 in https://mvnrepository.com/artifact/com.microsoft.azure/azure-keyvault

**Comment by joshfree** [comment]
Hi @timahenning,
You can find the latest information on Azure SDK releases at https://aka.ms/azuresdk and https://azure.github.io/azure-sdk/releases/latest/java.html which includes links to the latest version 4.x  releases of Key Vault.

**Comment by timahenning** [comment]
@joshfree for the quick response.  I think most Java developers using Maven would look in the Maven repo for the most recent version.  Also, they would rely on their development UI intellisense for available versions.  I just happen to be reading the documentation.

**Comment by g2vinay** [comment]
@timahenning 
The latest stable release of KV Track 1 is 1.2.2, that's why you didn't see 1.2.3 in maven repo.

Also, we've shipped next gen KV SDKs, the v4.x azure-security-keyvault-* libraries are the latest supported SDK libraries for KeyVault. We do recommend upgrading to this latest stable, supported release. Packages and more information can be found here:
1. https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-secrets
2. https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/keyvault/azure-security-keyvault-keys/README.md
3. https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/keyvault/azure-security-keyvault-certificates

4.x azure-security-keyvault-libraries are part of our Track 2 SDKs, which are completely redesigned to offer better and friendly user experience to our developers.
It supports pluggable HTTP clients , runs on a re-designed java runtime and offers better performance compared to older Track 1 SDKs.
