### ISSUE TITLE
md5 checksum not checked on server?

### ISSUE THREAD

**Issue by mwan-movideo** [Azure/azure-sdk-for-java#9]
Should the md5 checksum be checked for file upload?

Situation 1:
The blob is being overwritten.
My steps:
1. Get a blob reference
2. calculate the md5 checksum on the original file
3. upload the md5 checksum using upload properties
4. upload another file which is slightly modified than the original file

My modified file is uploaded successfully, and I can download the file from azure cloud and the downloaded file is the modified file.

Situation 2:
The blob is new.
How should I submit a md5 to be checked when the file is uploaded?
1. I can not upload properties before the file upload because blob is not created.
2. If I submit the md5 after the file upload, how can the server know my md5?

**Comment by tomlee** [comment]
I came across the same problem. The single block blob put you suggested doesn't validate MD5 when I use the Java SDK. I set the MD5 with blob.getProperties().setContentMD5(). I have already set setStoreBlobContentMD5 and setUseTransactionalContentMD5 of the BlobRequestOptions object to true and use blob.upload(inpustream, length, null, blobRequestOptions, null) to supply the options.

I believe this is a bug. It's either the MD5 validation is ignored at the server side or the MD5 is not sent to the server when the blob upload request is composed.

I suggest you try it out the code and you'll know it isn't working. Otherwise, please include the code you've tested is working.

**Comment by rdp** [comment]
See also https://stackoverflow.com/a/69319211/32453
