### ISSUE TITLE
Unable to update an existing network security group with a new set of rules

### ISSUE THREAD

**Issue by selvasingh** [Azure/azure-sdk-for-java#935]
-Find the primary interface of current instance
-Take NSG of this interface (no additional fetching through ‘NetworkManagementClient.NetworkSecurityGroups().get(…)’ so no fields beside ‘id’ is set)
-Build list of security rules
-Add this list to NSG via ‘nsg.setSecurityRules(…)’
-Call ‘NetworkManagementClient.NetworkSecurityGroups().createOrUpdate(resGroup, nsgname, nsg)’ to persist these changes (‘nsgname’ was extracted earlier from the ‘id’ field)
 
When you follow this procedure you get an error that the ‘NetworkSecurityGroup.location’ field is not set. Just setting this value resulted in HTTP error 400.  So the next idea is to actually fetch the NSG via ‘NetworkManagementClient.NetworkSecurityGroups().get(…)’ and then continue with the above mentioned steps. Apparently, the validation of the parameters will then also start to validate the field ‘NetworkSecurityGroup.networkInterfaces’ of the fetched NSG which contains all references to network interfaces in this NSG. Since these objects are again not fetched the validation fails again (no field beside of ‘id’ is set)

**Comment by anuchandy** [comment]
Network swagger uses raw resource types to represents resource references instead of using a generic type like other services. Other services uses the generic type `'SubResource { String id }'` to represents these references. For example
in Compute::AvailabilitySet the reference to VMs under it is represented using 'SubResource []'.

Now consider how references are used in network, the NSGs associated to NIC is represented using 'NetworkSecurityGroup[]' not 'SubResource[]', similarly NSGs associated to a subnet is represented using 'NetworkSecurityGroup[]' not 'SubResource[]'. You can see this pattern is followed across all reference type in network object model.

Services (including network) expect only ID to refer a resource, incase of network service when we use raw resource type to represents a reference, all other fields of this specialized types are ignored by the service and it consider only ID.

Forcing consmer to use specialized type to represents references does look that nice, it would be nice if network swagger follow the same pattern as of other services.

Why we have problem:

All Resource types inherit from 'Resource' which looks same across difference service. 
We moved this type to a common place instead of having this type defining per service. Below is how the resource definition looks like for compute, storage, search.

```json
    "Resource": {
      "properties": {
        "id": {
          "readOnly": true,
          "type": "string",
          "description": "Resource Id"
        },
        "name": {
          "readOnly": true,
          "type": "string",
          "description": "Resource name"
        },
        "type": {
          "readOnly": true,
          "type": "string",
          "description": "Resource type"
        },
        "location": {
          "type": "string",
          "description": "Resource location"
        },
	...
      },
      "required": [
        "location"
      ],
      "x-ms-azure-resource": true
    },
```

Note here id IS READONLY, location is REQUIRED.

For network, it looks like below:

```json
    "Resource": {
      "properties": {
        "id": {
          "type": "string",
          "description": "Resource Id"
        },
        "name": {
          "readOnly": true,
          "type": "string",
          "description": "Resource name"
        },
        "type": {
          "readOnly": true,
          "type": "string",
          "description": "Resource type"
        },
        "location": {
          "type": "string",
          "description": "Resource location"
        },
        ...
      },
      "x-ms-azure-resource": true
    },
```

Note here id IS NOT-READONLY, location is OPTIONAL.

This enables network swagger to use raw resource type (that derives from this Resource) to represents the references, since Id is not readonly it will be send to service over wire, we use common Resource type (in which Id is readonly) then id won't get serialized over wire.

@jianghaolu @martinsawicki to share their view

**Comment by jianghaolu** [comment]
Linking the issue in rest-api-specs: https://github.com/Azure/azure-rest-api-specs/issues/382

**Comment by jianghaolu** [comment]
This has been worked around.
