### ISSUE TITLE
[FEATURE REQ] Add parallelism config for uploading/downloading files on ADLS Gen2 Java SDK

### ISSUE THREAD

**Issue by snleee** [Azure/azure-sdk-for-java#9817]
**Is your feature request related to a problem? Please describe.**
While I have done some benchmark for upload/download performance for ADLS Gen2, I found out that the client that I implemented using ADLS Gen2 Azure SDK is much slower than azcopy due to parallelism. (performance from Java SDK was very similar to azcopy with `AZCOPY_CONCURRENCY_VALUE=1`)

For ADLS Gen2, I checked with some POC code that we can improve the performance by adding more parallelism (calling `append() API` with multiple threads & call `flush()` in the end).

Similarly, we can parallelize the read calls using offset on the client side and write the block to a file in the correct place.

However, I think that a lot of people will need this feature and Azure SDK is the right place to solve this problem so that ppl don't have to write the same logic over and over again.

Is there a plan to support this feature?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by rickle-msft** [comment]
@snleee Thank you for creating this issue. In the case of transfers to/from a single blob, both of these features are already built into the SDK. Our `uploadFromFile` method will read from the file at multiple locations at once and issue several `append` calls concurrently. Likewise, `downloadToFile` will do range gets on as many parts of the blob as we are allowed and again write to the local file concurrently. If you need more help finding or using these features, we will be happy to offer more guidance there. 

If you are trying to parallelize transfers of multiple files at once, that is not something the SDK offers, and it is left to each customer to configure and manage this process. This is also the specific use case for azcopy, so we typically recommend azcopy in this scenario.

As a final note, azcopy is typically significantly more performant as a data transfer tool than any of our sdks. It is designed to have much more aggressive performance because it does not have the same constraints as the SDK. If you job involves only bulk transfers, we recommend azcopy. 

Please let us know if you still have questions, concerns, feature requests, and we will be happy to continue this conversation.

**Comment by snleee** [comment]
@rickle-msft Let me try out `uploadFromFile` and `downloadToFile` and check its performance. I think that they are part of Blob Storage SDK API? 

We are using Azure SDK to implement the connector to our system. So, azCopy is not an option here although we will use it for data migration in the future. https://github.com/apache/incubator-pinot/pull/5116

**Comment by jongio** [comment]
@snleee - Can you please provide an update? This is 138 days old.  Thanks, Jon

**Comment by jongio** [comment]
Closing for now. Please reopen if you still experience this issue.  Thanks
