### ISSUE TITLE
"Found circular dependency" error when creating storage account

### ISSUE THREAD

**Issue by lenala** [Azure/azure-sdk-for-java#982]
When trying to create StorageAccount with new resource group and the group name is same as the name of storage account, it fails with following exception:

java.lang.RuntimeException: Found circular dependency
	at com.microsoft.azure.DAGraph.initializeQueue(DAGraph.java:176)
	at com.microsoft.azure.DAGraph.prepare(DAGraph.java:98)
	at com.microsoft.azure.TaskGroupBase.prepare(TaskGroupBase.java:50)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableImpl.create(CreatableImpl.java:88)

**Comment by anuchandy** [comment]
In the DAG we use Indexable::key() as the key of tasks in the graph, to fix the issue first we need to ensure the Indexable ::key() returns unique string instead of name of the resource. I am looking into this issue.

**Comment by martinsawicki** [comment]
I've started to introduce a piece of functionality in LBs for generating the expected resource ID before the resource is created. For now, I only have it limited to LB-related classes, but if we need it elsewhere, I've exposed it in a way that makes it vey easy to make it an abstract base class method. See LoadBalancerImpl#futureResourceId().  Maybe this can help in the key logic?

**Comment by anuchandy** [comment]
Thanks Martin, just looked into it. One requirement for putting an item in the graph is - it need unqiue a key. When we instantiate a resource impl (the one derived from CreatableImpl) we put it self into it's own graph in CreatableImpl::ctr. i.e. each CreatableImpl hold its own graph. As user add dependency  `Creatable`s  via `addCreatableDepedency` then we merge the graphs.

Inside CreatableImpl::ctr we can't call `resourceIdBase()` https://github.com/martinsawicki/azure-sdk-for-java/blob/martin-networking/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/models/implementation/GroupableResourceImpl.java#L52

the reason is resource group is not yet available at that point, an instance of `CreatableImpl` is not yet creatable, user needs to set all required params to have it creatable [the first required param is resourceGroup]

I have a solution in progress, where each CreatableImpl has a uuid that will be used as its key in graph, later point when we want to retrieve the created Resource, we use the Indexable::Key() only but we internally map it to uuid.

**Comment by anuchandy** [comment]
@lenala the fix has been merged, hence closing this.
